README.md
ReadMeがLaravelのままでしたので、wikiのトップページからコネクトCMSの説明文をもってきました。
OKであればマージしてください。
=> doc: ReadMeをコネクトCMSに変更

database/seeds/DefaultUsersTableSeeder.php
弊社以外がConnectCMSを使う想定で、初期ユーザのメールアドレスに弊社のメールアドレスが入ってるのはよくない。
なので空に修正。
これでseederやConnectCMSが動作するのか未テストなので、後でテストしてまたコメントします。
=> mod: 初期ユーザのメールアドレスは空にする

database/seeds/DatabaseSeeder.php, database/seeds/DefaultPluginsTableSeeder.php
https://github.com/opensource-workshop/connect-cms/issues/151
新規インストール時、基本機能のプラグインはONにするseederを作成しました。
動作確認で新規インストールして、プラグインが設置できる事、プラグイン管理で表示されることを確認しました。
問題なければマージしようと思います。
=> add: 新規インストール時、基本機能のプラグインはONにする

app/Plugins/Manage/CodeManage/CodeManage.php, resources/views/plugins/manage/code/code.blade.php
・コード一覧のtype_code2を非表示に変更
マージします。
=> mod: ・コード管理、orderにcodeは含めない。含めるとdisplay_sequenceの並び順とコード一覧の並び順がずれるため

resources/views/plugins/manage/number/number.blade.php
ユーザ管理、ページ管理ともに`<table>`でclass=cc-font-90を使って、フォントサイズを少し小さくしていました。
連番管理も対応した方がよいと思い、プルリクエスト投げます。
OKならマージお願いします。
コード管理は対応済みです。
https://github.com/opensource-workshop/connect-cms/pull/208/files
=> mod:  連番管理、管理画面のテーブル表示はclass=cc-font-90を使うといい感じ

app/Traits/ConnectCommonTrait.php
https://github.com/opensource-workshop/connect-cms/issues/220
この対応で様子見です。
マージします。
Invalid argument supplied for foreach()
「Invalid argument supplied for foreach() …」エラーの対処法
https://kotori-blog.com/php/foreach_error/
=> bugfix: ログイン時、「ログイン状態を維持する」ONで1日たってからブラウザアクセスすると例外が発生するバグに対応

app/Traits/ConnectCommonTrait.php
https://github.com/opensource-workshop/connect-cms/pull/221
上記の修正もれ。別か所でも`$user->user_roles`を使っていたため修正
https://github.com/opensource-workshop/connect-cms/issues/220
=> bugfix: ログイン時、「ログイン状態を維持する」ONで1日たってからブラウザアクセスすると例外が発生するバグに対応2

app/Models/Common/Codes.php, app/Plugins/Manage/CodeManage/CodeManage.php, resources/views/plugins/manage/code/regist.blade.php
mod: 登録・変更処理の共通化
bugfix: 変更画面でキャンセル時、一覧ページを保持できていなかったので対応
マージします。
=> mod: コード管理: created_idを自動登録するためUserable→UserableNohistoryに変更 他2件

app/Models/Common/Buckets.php
Buckets モデルはfillable が未定義だったので、定義しました。
一般プラグインのsaveBuckets()で下記のような実装を行いたいです。
モデルにfillable かguardedが定義されていないと、モデルのfirstOrNew()が利用できないんです。
これをすると、下記のif文かかなくてよくなります。
```php 
if ($request->timetable_id) {
// 更新
$timetables= Timetables::find($request->timetable_id);
} else {
// 登録
$timetables= new Timetables();                    
}
$timetables->bucket_id            = $buckets->id;
$timetables->timetable_name       = $request->timetable_name;
$timetables->school_code          = $request->school_code;
$timetables->save();
```
```php
public function saveBuckets($request, $page_id, $frame_id, $id = null)
{
//（中略）
// バケツの取得 or New
$buckets = Buckets::firstOrNew(['id' => $request->bucket_id]);
$buckets->bucket_name = $request->timetable_name;
$buckets->plugin_name = 'Timetables';
$buckets->save(); …
```
=> add: Buckets モデルにホワイトリストのfillable を追加

resources/views/plugins/user/blogs/default/blogs_list_buckets.blade.php
=> mod: 表示ブログ選択画面、ページ送りとキャンセル・変更ボタンの間に余白を追加

app/Plugins/User/UserPluginBase.php, config/cc_role.php, resources/views/plugins/common/frame_edit_buckets.blade.php
バグ修正のため、マージします。
* bugfix: CC_METHOD_AUTHORITYとCC_METHOD_REQUEST_METHODに、権限設定のeditBucketsRoles、saveBucketsRolesを追加
* bugfix: saveBucketsRoles()で固定記事プラグイン以外は自動でBucketsを作成しないよう見直し
* bugfix: 権限設定は固定記事プラグイン以外はbuckets未選択の場合、権限設定を表示しない
https://github.com/opensource-workshop/connect-cms/issues/233
=> bugfix: CC_METHOD_AUTHORITYとCC_METHOD_REQUEST_METHODに、権限設定のeditBucketsRoles、saveBucketsRolesを追加

app/Plugins/User/UserPluginBase.php
固定記事プラグインの、記事一覧選択画面のソート処理コントロール側を共通化しました。
listBuckets()のここら辺。
https://github.com/opensource-workshop/connect-cms/blob/master/app/Plugins/User/Contents/ContentsPlugin.php#L522-L542
=> add: データ選択画面のソート条件取得メソッドを共通化

app/Plugins/User/UserPluginBase.php, resources/views/plugins/common/frame_edit_buckets.blade.php
権限設定に承認を使うかどうかフラグ`$use_approval`を追加。
承認を使わない場合は、プラグイン側のコントローラでオーバーライトして、`$use_approval = false`をセットする。
相談してからマージする。
```php
/**
* 権限設定変更 画面
*/
public function editBucketsRoles($request, $page_id, $frame_id, $id = null, $use_approval = true)
{
// 承認を使わない設定にして、親クラスの同メソッドを呼ぶ
$use_approval = false;
return parent::editBucketsRoles($request, $page_id, $frame_id, $id, $use_approval);
}
/**
* 権限設定 保存処理
*/
public function saveBucketsRoles($request, $page_id, $frame_id, $id = null, $use_approval = true)
{
// 承認を使わない設定にして、親クラスの同メソッドを呼ぶ
$use_approval = false;
return parent::saveBucketsRoles($request, $page_id, $frame_id, $id, $use_approval);
}
```
=> mod: 権限設定に承認を使うかどうかフラグを追加

app/Userable.php, app/UserableNohistory.php
バグ修正です。
ブログと固定記事は記事削除時、履歴を含めて複数記事をいっぺんに削除するため、コントローラ側でdeleted_id・deleted_nameをupdateしてたので、バグの影響をうけてません。
マージします。
=> bugfix: 論理削除時、deleted_id・deleted_nameがDBに保存されないバグ修正

app/User.php
* bugfix: ログイン時、「ログイン状態を維持する」ONで1日たってからブラウザアクセスすると例外が発生するバグに対応2
https://github.com/opensource-workshop/connect-cms/pull/223
* bugfix: ログイン時、「ログイン状態を維持する」ONで1日たってからブラウザアクセスすると例外が発生するバグに対応
https://github.com/opensource-workshop/connect-cms/pull/221
上記で修正できてなかった。
他にも`$user->user_roles`を使ってる箇所（Buckets.php）があり、そこでarray前提のためエラーになっていた。
Buckets.php
https://github.com/opensource-workshop/connect-cms/blob/cb9c52e5bd30910f3471fac3abea3ea161ce1394/app/Models/Common/Buckets.php#L93
Userモデルでuser_rolesがNULLなら、array()を返すよう修正する。
=> bugfix: ログイン時、「ログイン状態を維持する」ONで1日たってからブラウザアクセスすると例外が発生するバグに対応3

app/Models/Common/Buckets.php, app/User.php
* bugfix: ログイン時、「ログイン状態を維持する」ONで1日たってからブラウザアクセスすると例外が発生するバグに対応3
https://github.com/opensource-workshop/connect-cms/pull/257  ⇒ バグ修正に効果ないためrevert
* bugfix: ログイン時、「ログイン状態を維持する」ONで1日たってからブラウザアクセスすると例外が発生するバグに対応2
https://github.com/opensource-workshop/connect-cms/pull/223
* bugfix: ログイン時、「ログイン状態を維持する」ONで1日たってからブラウザアクセスすると例外が発生するバグに対応
https://github.com/opensource-workshop/connect-cms/pull/221
対応3でバグ修正できてなかった。
対応3は取り消し。
対応4で`$user->user_roles`を使ってる箇所（Buckets.php）を修正する
Buckets.php
https://github.com/opensource-workshop/connect-cms/blob/cb9c52e5bd30910f3471fac3abea3ea161ce1394/app/Models/Common/Buckets.php#L93
=> bugfix: ログイン時、「ログイン状態を維持する」ONで1日たってからブラウザアクセスすると例外が発生するバグに対応4

app/Userable.php, app/UserableNohistory.php
* 未ログインで登録処理を実行した際、Auth::user()がnullでエラーになりました。
* フォームでも未ログイン登録してるのに大丈夫なのは、Userable等使って無く、`created_id` `created_name'等が未定義だったためでした。
不具合修正のプルリクエストのため、マージします。
=> bugfix: 未ログインならUserable等は処理しない。（未ログインで登録する処理、フォーム等に対応）

.gitignore, composer.json, phpcs.xml
https://github.com/opensource-workshop/connect-cms/issues/316
まずはcomposerのdevにphpcs・phpcbfコマンド追加しました。
どのディレクトリをphpcsから除外するかは、phpcs.xmlに記載していて、
まだ見直しする余地があるため、ドラフトとしてpull requestを送ります。
まずはここまで。
LaravelにPHP_CodeSnifferを導入しコーディング規約（PSR）に沿った記述を行う
https://www.ritolab.com/entry/188
=> add: composerのdevにphpcs・phpcbfコマンド追加

composer.lock
https://github.com/opensource-workshop/connect-cms/issues/316
* add: php_codesniffer to composer.lock
php_codesniffer を追加した後に更新された`composer.lock`ファイルをコミット漏れ対応です。
マージします。
=> composerのdevにphpcs・phpcbfコマンド追加 その２

phpcs.xml
https://github.com/opensource-workshop/connect-cms/issues/316
phpcsコマンド一発で下記が同時に出力するように対応しました。
* code:指摘箇所のコードも表示
* 実際の修正の参考に
* summary:コード毎の要約レポート
* どのファイルにエラーが多いか確認
* source:ルール毎の要約レポートを同時に出力するように対応
* phpcsルールの見直し参考に
別々に出力してましたが、下記が同時出力できるようになりました。
[phpcs_after_code.log](https://github.com/opensource-workshop/connect-cms/files/4618961/phpcs_after_code.log)
[phpcs_after_summary.log](https://github.com/opensource-workshop/connect-cms/files/4618960/phpcs_after_summary.log)
[phpcs_after_source.log](https://github.com/opensource-workshop/connect-cms/files/4618959/phpcs_after_source.log)
現在は大量にエラーが出て見ずらいですが、修正が進めば気にならなくなるかと思ってます。
マージします。
=> change: phpcsコマンドでcode:指摘箇所のコードも表示＋ summary:コード毎の要約レポート＋source:ルール毎の要約レポートを同時に出力するように対応

composer.json
エラー内容
>PS C:\sites\connect-cms\htdocs\connect-cms> composer phpcs
\> ./vendor/bin/phpcs --standard=phpcs.xml ./
'.' is not recognized as an internal or external command,
operable program or batch file.
Script ./vendor/bin/phpcs --standard=phpcs.xml ./ handling the phpcs event returned with error code 1
参考
https://blog.msyk.net/?p=923
=> composer.jsonのコマンド修正 phpcs/phpcbf powershell対応

resources/views/plugins/manage/code/code.blade.php, resources/views/plugins/manage/code/display.blade.php, resources/views/plugins/manage/code/edit.blade.php, resources/views/plugins/manage/code/help_message_edit.blade.php
* refactor: コード管理の注釈設定->注釈名に統一
* add: 注釈登録画面に、機能説明文を追加
マージします。
このプルリクの続き　https://github.com/opensource-workshop/connect-cms/pull/333
なし
=> refactor: コード管理の注釈設定->注釈名に統一　他1件

app/Plugins/Manage/CodeManage/CodeManage.php, resources/views/plugins/manage/code/code.blade.php, resources/views/plugins/manage/code/display.blade.php
* refactor: コード管理表示設定、並び順->表示順に統一
* bugfix: コード管理の表示設定、初回登録がされない不具合修正 
* add: 表示設定が未設定だったら、コード一覧に未設定の警告メッセージを表示
マージします。
このプルリクの続き　https://github.com/opensource-workshop/connect-cms/pull/333
なし
```
./vendor/bin/phpcs --standard=phpcs.xml ./app/Plugins/Manage/CodeManage/
./vendor/bin/phpcbf --standard=phpcs.xml ./app/Plugins/Manage/CodeManage/
```
=> refactor: コード管理表示設定、並び順->表示順に統一　他2件

composer.json
* phpcsの色つきは、windows環境だと色が反映されず、余計な文字列が出力されるため、コマンドを分けました。
* また、composer scriptsの説明を追記しました。`composer run-script --list`で表示されます。
マージします。
なし
https://getcomposer.org/doc/articles/scripts.md#writing-custom-commands
composer.jsonのみ修正のため、対象外
=> add: composer phpcs-color command

resources/views/plugins/manage/page/page_form.blade.php, resources/views/plugins/manage/site/site.blade.php
- サイト管理、ページ管理における背景色の設定で何を入力すべきかが明示されていない。  
- プレースホルダを追加
- システム側はカラーコードの入力を期待しているのですが、調べさせるのも不親切なのでカラーピッカー項目を追加（vueで入力値と連動させています）
- 当初は現テキストボックスをそのままカラーパレット化しようと考えましたが、初期表示で該当項目がnullの場合、パレット表示は黒で表示されてしまいます。この場合、本当に黒が設定されているのか未設定なのかが判別不可になります。デフォルト値の設定を検討しましたが、この場合はページ管理の方でページ間の承継機能とバッティングしてしまいます。
- ちなみにカラーパレット自体はIEは動作しない為、IEではピッカー項目は非表示としています。
- 下記はEdge、Firefox、chrome、IEでの対応後イメージです。
なし
https://developer.mozilla.org/ja/docs/Web/HTML/Element/Input/color
=> （サイト管理、ページ管理）カラーパレット追加

composer.json
修正したのは１ファイルなのに、プルリクエストを送る時、phpcs, phpcbfを全ディレクトリチェックするコマンドしかなく、
１ファイルのみチェックしたいんです。
phpcs, phpcbfのチェックパスなしのコマンド、`composer phpcs-any`, `composer phpcbf-any`を追加しました。
マージします。
```
composer phpcs-any -- app/Plugins/Api/Nc2Sso/Nc2Sso.php
```
// ※ composer phpcs-anyの後ろに ` -- `を付けると、任意のオプションを引き渡せます。
https://github.com/opensource-workshop/connect-cms/issues/316
https://github.com/opensource-workshop/connect-cms/wiki/PHP_CodeSniffer
wikiには後ほど、追加コマンドを追記します。
composer.json１ファイルの修正で、チェック対象外ファイルのため、チェック不要です。
=> add: composer phpcs-any, phpcbf-any

app/Plugins/Api/Nc2Sso/Nc2Sso.php
* change: sso, Connect-CMSにユーザ有りの場合、権限チェックしないでログインさせる。
* Connect-CMSにユーザがいて、権限に管理者（ここではサイト管理者）を付けると、SSO時に下記エラー画面が表示され、ログインできませんでした
* ![20200602-085630](https://user-images.githubusercontent.com/2756509/83469467-be315d80-a4ba-11ea-979f-56ef84197c50.jpg)
* NC2とConnect-CMSの権限はそれぞれ独立しているため、SSO後にユーザができて、Connect-CMSの権限を追加する事はありえるため、権限チェックを外しました。
* change: sso, Connect-CMSにユーザ無し時に設定するパスワードは、無効な事が解るように内容変更
* SSO時、Connect-CMS側にユーザがいなければ自動作成しますが、そこで設定するパスワードは無効なもののため、DBを見た時にパスワードが無効である事がわかる内容に修正しました。
なし
なし
=> change: sso, Connect-CMSにユーザ有りの場合、権限チェックしないでログインさせる。他１件

resources/views/plugins/common/wysiwyg.blade.php
wiygwygで画像の回転できるようにするため、tinymce4のimagetoolsプラグインを設定しました。
imagetoolsプラグインは、既にConnect-CMSにありました。
https://github.com/opensource-workshop/connect-cms/tree/master/public/js/tinymce/plugins/imagetools
https://github.com/opensource-workshop/connect-cms/issues/350
https://www.tiny.cloud/docs/plugins/imagetools/
> Warning: This feature requires at least Internet Explorer 10, since it makes use of HTML5 File API.
IE10以上。HTML5 File API.で機能を実現しているようです。
bladeファイルのため、対象外です。
* FireFox OK
* chromeで動作確認しました。
画像の編集ボタンを押すと、トリミングも可能でした。
=> add: wiygwygで画像の回転できるようにする

app/Enums/DatabaseColumnType.php, app/Plugins/User/Databases/DatabasesPlugin.php, resources/views/plugins/user/databases/default/databases_confirm.blade.php, resources/views/plugins/user/databases/default/databases_edit_row.blade.php, resources/views/plugins/user/databases/default/databases_edit_row_detail.blade.php
* 「行グループ」「列グループ」追加に伴い、**機能してない 項目の型「まとめ行」を廃止**します。
* （「まとめ行」は、フォームプラグインを基に作成されたデータベースプラグインの名残で残ってただけ。）
PR
https://github.com/opensource-workshop/connect-cms/pull/377
issue
https://github.com/opensource-workshop/connect-cms/issues/375
なし
=> delete: database plugin, 「行グループ」「列グループ」追加に伴い、機能してない 項目の型「まとめ行」を廃止

resources/views/plugins/user/databases/default/databases_edit.blade.php, resources/views/plugins/user/databases/default/databases_edit_row.blade.php
* bugfix: 【データベース・バグ】設定画面＞項目設定をスマートフォンで見ると入力項目が潰れてるので、min-widthを設定して対応
* change: 項目設定の余白幅を狭くしていたけど、スマートフォン操作で誤タッチの恐れがあるため、もとの余白幅に戻す
https://github.com/opensource-workshop/connect-cms/issues/373
なし
=> bugfix: 【データベース・バグ】設定画面＞項目設定をスマートフォンで見ると入力項目が潰れてるので、min-widthを設定して対応 他1件

resources/views/plugins/user/forms/default/forms_edit.blade.php, resources/views/plugins/user/forms/default/forms_edit_row.blade.php, resources/views/plugins/user/forms/default/forms_edit_row_add.blade.php
【データベース・バグ】設定画面＞項目設定をスマートフォンで見ると入力項目が潰れてる #373
formを参照したところ、直sytleが使われて、min-widthが切られてたため、対応できていた。
formの項目設定画面のファイル構成はこんな感じ。
* forms_edit.blade.php `<table><th>はここで定義`。下記参照
* forms_edit_row.blade.php `<td>はここで定義` 「型」のみ`style="min-width: 140px;"`
* forms_edit_row_add.blade.php `<td>はここで定義` 　「項目名」` style="min-width: 150px;"` 「型」 `style="min-width: 100px;"`
他プラグインで真似する時に、`<th>`タグと`<td>`タグが別々のファイルに別れている関係で、どこに`min-width`が切られているか、気づきずらい形になっていた。
`style="min-width:` を切るなら、ここは、forms_edit.blade.phpの`<th>`タグにまとめる方向が、わかりやすいかと思ったので、
これから修正します。
https://github.com/opensource-workshop/connect-cms/issues/373
なし
=> refactor: フォーム style="min-width: はforms_edit.blade.phpの<th>タグにまとめる

resources/views/plugins/user/databases/default/databases_edit_row_detail.blade.php, resources/views/plugins/user/forms/default/forms_edit_row_detail.blade.php
バグ修正です。
* bugfix: 【データベース・バグ】設定画面＞項目設定＞詳細で、入力エラーになるとラジオボタンの値が保持されない不具合を修正
* refactor: 【フォーム・バグ】設定画面＞項目設定＞詳細で、入力エラーになるとセレクトボックス（キャプションの設定の 文字色）の値が保持されないバグを修正
* refactor: フォーム項目の詳細設定画面, 不要な空白を削除
https://github.com/opensource-workshop/connect-cms/issues/368
なし
=> bugfix: 【データベース・フォーム・バグ】設定画面＞項目設定＞詳細で、入力エラーになるとラジオボタンの値が保持されない不具合を修正

app/Plugins/User/Blogs/BlogsPlugin.php, resources/views/plugins/user/blogs/default/blogs.blade.php, resources/views/plugins/user/blogs/default/blogs_input.blade.php, resources/views/plugins/user/blogs/default/blogs_show.blade.php
追加機能実装です。
ブログで続きを読む機能はよく使われているため。
続きを読むのDBカラムは、既にブログに存在していたため、DBカラム追加はないです。
* ブログ内検索対応, 「続きを読む」を検索対象に含める
* RSSには「続きを読む」を含めない（いままでと同じ）
* ブログ一覧画面と、詳細画面の「続きを読む」表示は同じ（「続きを読む」ボタンを押して、内容を表示する）
* 続きを読む & タグありなら、続きを読むとタグの間に余白追加
https://github.com/opensource-workshop/connect-cms/issues/386
=> add: 【ブログ】続きを読む機能 実装

app/Plugins/User/Databases/DatabasesPlugin.php
https://github.com/opensource-workshop/connect-cms/pull/379
で「まとめ行」のロジックが残っていたので削除
PR
https://github.com/opensource-workshop/connect-cms/pull/379
#377
issue
#375
なし
=> delete: database plugin, 「行グループ」「列グループ」追加に伴い、機能してない 項目の型「まとめ行」を廃止2

app/Plugins/User/Forms/FormsPlugin.php
フォームプラグインに、enumで定義されている`\FormColumnType::group`あり。
直書きの`"group" `を見つけたので見直し
PR
https://github.com/opensource-workshop/connect-cms/pull/388
=> refactor: Form plugin, "group" -> \FormColumnType::groupに見直し

app/Enums/DatabaseColumnType.php, app/Enums/DatabaseSortFlag.php, app/Models/User/Databases/DatabasesFrames.php, config/app.php, resources/views/plugins/user/databases/default/databases_edit_row.blade.php, resources/views/plugins/user/databases/default/databases_edit_view.blade.php, resources/views/plugins/user/databases/default/databases_include_ctrl_head.blade.php, resources/views/plugins/user/databases/menu/databases_edit_view.blade.php, resources/views/plugins/user/databases/single_sheet/databases_include_ctrl_head.blade.php
* ソート用の値がデータベースの型として設定できてしまっていたため、修正します。
* データベースの型は、`DatabaseColumnType`クラスの定数で定義しているので、そこからソート用項目を取り除き、
`App\Enums\DatabaseSortFlag.php`に移動させました。
* また、ソート用項目の定数を使用しておらず、各所で直書きしてたいのを、ソート用項目の定数を利用するように見直しました。
この修正により、`App\Enums\DatabaseSortFlag.php` に新しい定数を追加すると、画面に自動的に反映されるようになりました。
* move: database plugin, DatabaseColumnType::created_asc等は、ソート用項目のため、App\Enums\DatabaseSortFlag.phpに移動
* bugfix: database plugin, 設定＞項目設定の選択肢を表示する行の余白が広かったため、少し狭める. また、列数(cols指定)が他の行より少なかったため修正.
* refactor: database plugin, EnumsBaseを継承して、同じメソッド・同じ処理は削除
* refactor: databases_include_ctrl_head.blade.php, selectedのON・OFFは1行にまとめる。また、インデントの修正
https://github.com/opensource-workshop/connect-cms/issues/395
なし
=> 【データベース・バグ】ソート用の値がデータベースの型として設定できてしまうバグの修正　他3件

app/Enums/DatabaseColumnType.php, app/Plugins/User/Databases/DatabasesPlugin.php, resources/views/plugins/user/databases/default/databases_confirm.blade.php, resources/views/plugins/user/databases/default/databases_include_detail_value.blade.php, resources/views/plugins/user/databases/default/databases_include_value.blade.php, resources/views/plugins/user/databases/default/databases_input.blade.php, resources/views/plugins/user/databases/default/databases_input_link.blade.php
* データベースプラグインに、登録日型・更新日型を追加しました。
* データベースの登録データの登録日・更新日は、`databases_inputs`テーブルに持っていましたので、
登録日型・更新日型は、`databases_inputs`テーブルの`created_at`（登録日）・`updated_at`（更新日）を表示します。
* データベースの登録データテーブル`databases_input_cols`にはデータ登録しません。
* この構成により、データベースプラグインを運用後、後から登録日型・更新日型を設定しても、即時に登録日・更新日を表示する事ができます。
* また、`databases_input_cols`にデータ登録しない・確認画面にも表示しない事から、メール通知の内容に登録日型・更新日型は表示しません。
* add: database plugin, 登録日型・更新日型を追加 
* bugfix: database plugin, まとめ行"group"の削除漏れ対応
* bugfix: database plugin, リンク型を<input type="text">に修正
* bugifx: 'ウィジウィグ' -> 'ウィジウィグ型'に表示修正
* refactor: database plugin, column_typeのfile, image, video, mailが直書きだったため、DatabaseColumnTypeの定数を使うように見直し
https://github.com/opensource-workshop/connect-cms/issues/397
=> 【データベース】登録日型・更新日型を追加 

app/Plugins/User/Databases/DatabasesPlugin.php, resources/views/plugins/user/databases/card/databases_detail.blade.php, resources/views/plugins/user/databases/databases_frame_edit_tab.blade.php, resources/views/plugins/user/databases/default/databases_detail.blade.php, resources/views/plugins/user/databases/default/databases_include_ctrl_head.blade.php, resources/views/plugins/user/databases/list/databases_detail.blade.php, resources/views/plugins/user/databases/menu/databases_detail.blade.php, resources/views/plugins/user/databases/single_sheet/databases_detail.blade.php, resources/views/plugins/user/databases/single_sheet/databases_include_ctrl_head.blade.php, resources/views/plugins/user/databases/table/databases_detail.blade.php, resources/views/plugins/user/databases/table_responsive/databases_detail.blade.php
今まではデータベースプラグインに投稿できるのは、モデレーター以上の権限をもつ人だけでした。
それを見直して、データベース毎に投稿権限の設定できるよう、対応しました。
投稿権限の他に、承認権限もあるのですが、修正が大きくなったため、一旦マージし、
今後承認機能を実装する予定です。
* add: 【データベース】投稿権限の設定追加
* refactor: database plugin, 追加のget/post関数定義・ 追加の権限定義・各画面を投稿権限を参照するように整理・見直し
* refactor: database plugin, 編集画面tabのプラグイン名は $frame->plugin_name を利用するように見直し
https://github.com/opensource-workshop/connect-cms/issues/402
今後この画面に、承認権限も追加する予定です。
=> add: 【データベース】投稿権限の設定追加

resources/views/plugins/user/blogs/default/blogs.blade.php
画像が右寄せになっていると、画像がボタンを回り込むなどの弊害が出ていたので、記事本文を囲んでclearfixした。
上記理由通り。
なし
なし
=> ブログ記事にclearfix設定

app/Plugins/Manage/SiteManage/SiteManage.php, resources/views/core/cms.blade.php, resources/views/plugins/manage/site/site.blade.php
- センターエリア背景画像をランダム表示させたい要件あり
- センターエリア要素に対して任意のclassを設定させる機能を追加
※class設定は複数可能。複数設定時はランダムに１つのclassを適用させる
無し
無し
無し
=> （サイト管理）センターエリア要素に対して任意のclassを複数設定可能にする機能を追加

app/Http/Controllers/Core/DefaultController.php
- Laravelの機能にセッションへフラッシュデータを保存する機能があります。
```
コード例 ※下記のwith()の部分
return redirect("/plugin/rmaps/showResearchers/$page_id/$frame_id#frame-$frame_id")
->with('message', '研究者一覧を更新しました。');
```
- しかしながら、Connectで上記のコードを書くと、Connectのコア側のリクエスト制御処理の為、レスポンスヘッダが一瞬画面に表示されてしまいます。
- Connectのお作法として下記のコードを書けばリダイレクトはされますが、今度はフラッシュデータの保存ができなくなります。
-- 更新画面のformのactionURLに`/redirect/plugin/~~`とredirectである旨のpathを設定
-- 同formのrequest内に`redirect_path`を設定
- Connect的なリダイレクト時にもLaravelの上記機能を使いたい為、コアのリダイレクト処理を改修しました。
なし
https://readouble.com/laravel/5.5/ja/responses.html
無し
=> 共通 Laravelのセッションフラッシュデータ機能を使えるようにする

app/Http/Controllers/Core/DefaultController.php
- Laravelでの手動バリデート時に画面へ戻す為、一般的にリダイレクトも設定しますが、この際、バリデート結果オブジェクトを渡す必要があります。
※withErrors()の部分
- Connect的なリダイレクト設定をした画面では現状、バリデートオブジェクトの受け渡しができない為、コアのリダイレクト機能を改修しました。
- これにより、POST後にGETへ戻すような作りの画面でバリデートが使えるようになります。
- 本対応に先立って、現状のままだとif/elseのネストが入れ子になってしまう為、フラッシュデータ保存のコードをリファクタリングしています。
※with()の部分
無し
https://readouble.com/laravel/5.5/ja/validation.html
無し
=> 共通 Laravelのフラッシュデータにバリデータを追加

app/Plugins/User/Databases/DatabasesPlugin.php
データベースプラグインの行グループ・列グループで最初に2項目追加したら、一つが次の行の左カラムと認識される不具合の修正です。
行グループ・列グループどっちも設定なしは、設定ありのお尻にくっつけるよう見直ししました。
https://github.com/opensource-workshop/connect-cms/issues/483
なし
無し
=> bugfix: database plugin, 行グループ・列グループどっちも設定なしは、設定ありのお尻にくっつけるよう見直し

app/Enums/DatabaseColumnType.php, app/Enums/DatabaseSortFlag.php, app/Models/User/Databases/DatabasesInputs.php, app/Plugins/User/Databases/DatabasesPlugin.php, database/migrations/2020_08_18_131841_add_posted_at_databases_inputs_table.php, resources/views/plugins/user/databases/default/databases_confirm.blade.php, resources/views/plugins/user/databases/default/databases_edit_row_detail.blade.php, resources/views/plugins/user/databases/default/databases_include_detail_value.blade.php, resources/views/plugins/user/databases/default/databases_include_value.blade.php, resources/views/plugins/user/databases/default/databases_input.blade.php, resources/views/plugins/user/databases/default/databases_input_date.blade.php
データベースプラグインに 固定項目で公開日時を追加します。
・固定項目として、入力時必須で「公開日時」を登録させる。初期値は今日日時。
・公開日時(投稿日時)のDBカラム追加時の初期値は、更新日時の値をセット
・「公開日時」の表示するには、「公開日型（表示のみ）」を追加して、任意でデータベースプラグインに設定する形。
・ソート順に「公開日（古い順）」「公開日（新しい順）」を追加
* add: database plugin, 固定項目で公開日時追加
* bugfix: database plugin, フォームプラグインの名残でFormColumnType::dateが使われていたため、DatabaseColumnType::dateに修正
* bugfix: database plugin, キャプション設定に不要な空白と改行が入る不具合修正
* bugfix: database plugin, 日付型入力時のカレンダー表示の年月表示がYYYY年 M月形式になっていなかったため修正, 念のためカレンダーの多言語対応
* bugfix: database plugin, 登録日型・更新日型・公開日型は入力表示しないため、バリデータチェックしない
* bugfix: database plugin, まとめ行削除漏れ対応（まとめ行以外の項目について、バリデータールールをセットの箇所）
https://github.com/opensource-workshop/connect-cms/issues/490
なし
有り
=> add: database plugin, 固定項目で公開日時追加

app/Enums/DatabaseColumnType.php, app/Plugins/User/Databases/DatabasesPlugin.php, app/Rules/CustomVali_DatesYm.php, resources/views/plugins/user/databases/default/databases_confirm.blade.php, resources/views/plugins/user/databases/default/databases_input_dates_ym.blade.php
データベースプラグインに複数年月型（テキスト入力）追加
・複数年月型（テキスト入力）の項目を追加した場合、キャプションが自動設定されます。
・複数年月型（テキスト入力）の項目を更新＆キャプション空の場合、キャプションが自動設定されます。
https://github.com/opensource-workshop/connect-cms/issues/501
なし
無し
=> add: database plugin, 複数年月型（テキスト入力）追加

app/Enums/WhatsnewsTargetPlugin.php, app/Models/User/Databases/DatabasesColumns.php, app/Models/User/Whatsnews/Whatsnews.php, app/Plugins/User/Databases/DatabasesPlugin.php, app/Plugins/User/Whatsnews/WhatsnewsPlugin.php, config/app.php, database/migrations/2020_08_25_104542_add_title_flag_databases_columns_table.php, database/migrations/2020_08_26_113209_update_bucket_name_from_database_name_buckets_table.php, database/migrations/2020_08_26_125952_update_bucket_name_from_whatsnew_name_buckets_table.php, database/migrations/2020_08_26_142624_add_whatsnews_index_to_databases.php, database/migrations/2020_08_26_144809_add_whatsnews_index_to_blogs_and_frames.php, resources/views/plugins/user/databases/default/databases_edit.blade.php, resources/views/plugins/user/databases/default/databases_edit_row.blade.php, resources/views/plugins/user/databases/default/databases_edit_row_detail.blade.php, resources/views/plugins/user/whatsnews/default/whatsnews.blade.php, resources/views/plugins/user/whatsnews/default/whatsnews_edit_whatsnew.blade.php
データベースプラグインの新着対応です。
* 新着表示させるには、新着に表示するタイトルが必要になるため、データベースプラグインの項目に、タイトル表示フラグを追加しました。（データベース毎で１つ、タイトル表示用の項目を設定します）
* 既に他項目でタイトル表示設定済みの場合、自動解除されます。
* タイトル表示未設定のデータベースは、設定画面で注意メッセージを表示します。
* add: whatsnews and database plugin, データベースプラグインの新着対応
* add: whatsnews plugin, 新着対象プラグインのEnum対応
* add: database plugin, 新着に表示するため、DB項目にタイトル指定フラグを追加
* add: database plugin, タイトル指定未設定の場合、設定画面にワーニングメッセージ追加
* add: database plugin, データベースプラグイン関連のテーブルに新着対応のインデックスを追加
* add: blogs plugin, ブログとフレーム関連のテーブルに新着対応のインデックスを追加
* change: whatsnews plugin, 重要な記事（importantカラム）がないプラグインもあるため、重要な記事判定は、結果取得後に行う
* change: whatsnews plugin, 重要な記事判定を、結果取得後に移動したため、件数制限もあわせて結果取得後に行う様見直し
* change: whatsnews plugin, 記事タイトルが空の場合、リンクが表示されなかったので、「(無題)」でリンク表示する
* change: database plugin, …
=> add: whatsnews and database plugin, データベースプラグインの新着対応

app/Enums/CsvCharacterCode.php, app/Plugins/User/Databases/DatabasesPlugin.php, app/Utilities/csv/SjisToUtf8EncodingFilter.php, config/app.php, resources/views/plugins/user/databases/default/databases_edit_database.blade.php, resources/views/plugins/user/databases/default/databases_import.blade.php, resources/views/plugins/user/databases/default/databases_list_buckets.blade.php
【データベースプラグイン】にCSVダウンロード・CVSインポートで文字コードを指定する機能追加 です。
* add: database plugin, CSVダウンロード・CVSインポートで文字コードを指定する機能追加
* bugfix: database plugin, CVSインポート時、全角文字が消える不具合修正
* change: database plugin, DB設定画面のキャンセルボタンに、#frame-XXX アンカー追加
* change: database plugin, インポート画面のキャンセルボタンに、#frame-XXX アンカー追加
* change: database plugin, DB選択画面のキャンセルボタンに、#frame-XXX アンカー追加
https://github.com/opensource-workshop/connect-cms/issues/522
なし
無し
=> 【データベース】CSVダウンロード・CVSインポートで文字コードを指定する機能追加 ＆ CVSインポート時、全角文字が消える不具合修正

app/Plugins/User/Databases/DatabasesPlugin.php, resources/views/plugins/user/databases/default/databases_list_buckets.blade.php
【データベースプラグイン】にCSVインポートに更新機能追加します。
CSVダウンロード・CSVフォーマットにid項目を追加し、idがあれば「更新」、無ければ「登録」します。
id項目の入力チェックは、数値チェック・DB存在チェックをします。
* add: database plugin, CSVインポートに更新機能追加
* add: database plugin, CSVダウンロード、CSVフォーマットにid項目追加
https://github.com/opensource-workshop/connect-cms/issues/527
なし
無し
=> 【データベース】CSVインポートに更新機能追加

app/Plugins/User/Databases/DatabasesPlugin.php, app/Rules/CustomVali_CsvExtensions.php, app/Rules/CustomVali_CsvImage.php, app/Utilities/csv/Csv.php, app/Utilities/zip/UnZip.php, resources/views/plugins/user/databases/default/databases_import.blade.php
機能追加です。
* phpのZipArchive有効時のみ、添付ファイル一括インポート可能
* 添付ファイルありで、登録・更新対応済み
* 添付ファイル一括インポート時の、添付ファイルバリデーション対応済み
* 添付ファイル一括インポート時の添付ファイルは、一度全てUploadsテーブルに`temporary_flag = 1（一時的）`でアップし、その後データ行から呼び出されたら、`temporary_flag = 0（利用）`に更新している。
xxxxxxx.csv
zip内/[database_folder]/[database_file].csv　　　
zip内/[database_folder]/uploads/xxxxx_01.jpg
zip内/[database_folder]/uploads/xxxxx_02.jpg
zip内/[database_folder]/uploads/xxxxx_yyyyyy.pdf
※ windowsでzip圧縮すると、zip内にフォルダが1個作られるため、このフォルダ構成にしました。
※ フォルダ名 `[database_folder]` は任意の名前でOKです。
※ CSVファイル名 `[database_file]`.csv は任意の名前でOKです。含めるCSVファイルは1ファイルのみにしてください。
※ `[database_folder]/uploads/` の `uploads` は固定のフォルダ名です。ここに添付ファイルを入れてください。
"uploads/xxxxx_01.jpg"
"uploads/xxxxx_02.jpg"
"uploads/xxxxx_yyyyyy.pdf"
※ 対象ファイルが無いと入力チェックでエラーになります。
* add: database …
=> add: database plugin, 添付ファイル一括インポート対応

app/Enums/PermissionType.php, app/Enums/ShowType.php, app/Http/Controllers/Core/CookieController.php, app/Plugins/Manage/MessageManage/MessageManage.php, config/app.php, resources/views/layouts/app.blade.php, resources/views/plugins/manage/menus_list.blade.php, resources/views/plugins/manage/message/message.blade.php, resources/views/plugins/manage/message/message_tab.blade.php
- 管理者メニューに「メッセージ管理」として初回確認メッセージの設定機能を追加
https://github.com/opensource-workshop/connect-cms/issues/525
なし
無し
=> 【管理機能】メッセージ管理を追加

app/Plugins/User/Databases/DatabasesPlugin.php, resources/views/plugins/user/databases/default/databases_edit_database.blade.php, resources/views/plugins/user/databases/default/databases_list_buckets.blade.php
機能追加です。
* add: database plugin, 過去のデータベースを使って新たなデータベースを作る機能追加
* change: database plugin, DB選択画面の表示データベース変更ボタンに、#frame-XXX アンカー追加
* change: database plugin, DB作成・DB設定画面の決定ボタンに、#frame-XXX アンカー追加
https://github.com/opensource-workshop/connect-cms/issues/541
なし
無し
=> 【データベース】過去のデータベースを使って新たなデータベースを作る機能追加 

app/Models/User/Forms/Forms.php, app/Plugins/User/Forms/FormsPlugin.php, database/migrations/2020_09_09_202328_add_entry_limit_forms.php, resources/views/plugins/user/forms/default/forms_edit_form.blade.php
機能追加です。
* 登録制限数 設定
入力チェック：数値チェック、0以上入力、任意入力
自動入力値変換：数値入力なら小数点切り捨てて整数に変換。（例）1.9⇒1に変換
※ 未入力か 0 の場合、登録数を制限しません。
* 登録制限数チェック
登録画面、確認画面、登録確定時（送信ボタン押下時）にそれぞれチェック。
制限数オーバーなら登録させない。
* add: form plugin, 登録制限機能追加
* bugfix: form plugin, フォーム設定変更時に入力エラーがあると、フォーム作成画面に遷移する不具合修正
https://github.com/opensource-workshop/connect-cms/issues/543
なし
有り
=> add: form plugin, 登録制限機能追加

app/Enums/DatabaseColumnType.php, app/Enums/DatabaseSortFlag.php, app/Models/User/Databases/DatabasesColumns.php, app/Plugins/User/Databases/DatabasesPlugin.php, database/migrations/2020_09_11_100735_add_display_sequence_databases_inputs.php, resources/views/plugins/user/databases/default/databases_confirm.blade.php, resources/views/plugins/user/databases/default/databases_edit_view.blade.php, resources/views/plugins/user/databases/default/databases_include_detail_value.blade.php, resources/views/plugins/user/databases/default/databases_include_value.blade.php, resources/views/plugins/user/databases/default/databases_input.blade.php, resources/views/plugins/user/linklists/default/edit.blade.php
機能追加です。
* DBカラムに表示順型（表示のみ）追加
* ソート条件に表示順（昇順・降順）追加
* CSVダウンロードに表示順追加
* CSVインポートに表示順対応
* database plugin
* add: database plugin, 表示順追加
* add: database plugin, DBカラムに表示順型（表示のみ）追加
* add: database plugin, ソート条件に表示順（昇順・降順）追加
* add: database plugin, CSVダウンロードに表示順追加
* add: database plugin, CSVインポートに表示順追加
* change: database plugin, 表示設定の決定ボタンに、#frame-XXX アンカー追加
* bugfix: database plugin, CSVのみでインポート時、ファイル型に値があると入力エラーになっていたのを無視するように修正
* link plugin
* change: links plugin, 表示順のヘルプメッセージ修正
https://github.com/opensource-workshop/connect-cms/issues/547
なし
有り
=> 【データベース】表示順追加

app/Plugins/User/Databases/DatabasesPlugin.php, app/Plugins/User/Databases/DatabasesTool.php, app/Plugins/User/Databasesearches/DatabasesearchesPlugin.php, resources/views/plugins/user/databasesearches/default/databasesearches.blade.php
[【データベース】表示設定に絞り込み条件を追加](https://github.com/opensource-workshop/connect-cms/issues/549)に伴う、「データベース検索」 ~~「新着」~~ 対応です。
作業途中のため、ドラフトプルリクエストします。
→ (追記) 対応できましたので、プルリクエストします。また、修正多数になったため、「新着」対応は別のプルリクエストにします。
* add: database serches plugin, 各データベースのフレームの表示設定にある、絞り込み条件に対応
* add: database serches plugin, データベースプラウグイン設定で、権限によって非表示columに対応
* add: database plugin, database serches pluginと共通で使うメソッドをDatabasesToolクラスとして切り出し
* change: databaseserches plugin, 表示項目はbladeでtrimする
* bugfix: database serches plugin, 入力データ1件の項目内で更新日がずれると重複を起こすため、updated_atのgroupBy不要。
https://github.com/opensource-workshop/connect-cms/pull/553
なし
無し
=> 【データベース検索】データベースプラグインの表示設定に絞り込み条件を考慮して、表示しないようにする対応

app/Plugins/User/Databases/DatabasesPlugin.php, app/Plugins/User/Databases/DatabasesTool.php, app/Plugins/User/Databasesearches/DatabasesearchesPlugin.php
[【データベース】表示設定に絞り込み条件を追加](https://github.com/opensource-workshop/connect-cms/issues/549) 対応に伴う 「新着」 対応です。
* add: database plugin, 新着でデータベースの表示設定による絞り込み設定に対応
* add: database plugin, 新着でタイトル指定しても、権限によって非表示columだったらvalue表示しない 
* change: database serches plugin, データベースの新着で使うメソッドの共通化（getDatabasesColumnsAndFilterSearchAll()、getDatabasesFramesSettings(), appendSearchKeywordAndSearchColumnsAllDb()）
* bugfix: database plugin, 設定でタイトル指定のチェックが更新時に外れる不具合修正
https://github.com/opensource-workshop/connect-cms/pull/554
https://github.com/opensource-workshop/connect-cms/pull/553
なし
無し
=> 【データベース】新着、データベースプラグインの表示設定に絞り込み条件を考慮して、表示しないようにする対応

app/Plugins/User/Forms/FormsPlugin.php, resources/views/plugins/user/forms/default/forms_datalist.blade.php
機能追加です。
フォーム選択画面に件数を表示した事で、データが登録されてるか、されていないか不明瞭になったため、
データ保存状態を表示するようにしました。
https://github.com/opensource-workshop/connect-cms/issues/561
なし
無し
=> add: forms plugin, フォーム選択画面にデータ保存状態を表示

app/Plugins/User/Forms/FormsPlugin.php, database/migrations/2020_09_28_110707_add_entry_limit_over_message_to_forms.php, resources/views/plugins/user/forms/default/forms_edit_form.blade.php, resources/views/plugins/user/forms/default/forms_error_messages.blade.php
機能変更です。
詳細は https://github.com/opensource-workshop/connect-cms/issues/573 を参照してください。
* change: 【フォーム】申し込み人数制限オーバー時のメッセージを変更できるように対応
なし
なし
有り
=> change: 【フォーム】申し込み人数制限オーバー時のメッセージを変更できるように対応

resources/views/plugins/user/menus/parentsandchild/menus.blade.php
=> メニューの「親子のみ」テンプレートの修正

app/Models/User/Forms/Forms.php, app/Plugins/User/Forms/FormsPlugin.php, database/migrations/2020_09_28_143806_add_display_control_to_forms.php, resources/views/common/errors_form_line.blade.php, resources/views/plugins/user/forms/default/forms_edit_form.blade.php
機能追加です。
本登録・仮登録どちらでも、初期表示、確認画面、登録時に表示期間チェックを行い、期間外であれば表示しません。
また、フォーム設定画面の設定が増え、エラーが目立たなくなってきたため、共通部品`@include('common.errors_form_line')`で画面上部にエラーがある旨を表示するようにしました。
* add: 【フォーム】申し込みフォーム表示期間の設定（開始～終了）機能追加
* bugfix: core, errors_form_line.blade, エラー無い場合、例外がでるため修正
* add: form, 表示期間FromToでバリデーション追加（FromがToを越えたらエラー）
https://github.com/opensource-workshop/connect-cms/issues/591
なし
有り
=> 【フォーム】申し込みフォーム表示期間の設定（開始～終了）機能追加

app/Models/User/Forms/Forms.php, app/Plugins/User/Forms/FormsPlugin.php, database/migrations/2020_09_28_165505_add_regist_control_to_forms.php, resources/views/plugins/user/forms/default/forms_edit_form.blade.php
機能追加です。
本登録・仮登録どちらでも、初期表示、確認画面、登録時に登録期間チェックを行い、期間外であれば登録できません。
* add: 【フォーム】申し込み可能期間の設定（開始～終了）機能追加
* change: form, 登録制限数オーバーチェックは、indexに飛ばさず、直接エラー画面を表示するように見直し
* change: form, indexの登録制限数オーバーチェックは、エラーなら、すぐにエラー画面を表示するように修正
https://github.com/opensource-workshop/connect-cms/issues/596
なし
有り
=> add: 【フォーム】申し込み可能期間の設定（開始～終了）機能追加

app/Plugins/User/Forms/FormsPlugin.php, resources/views/plugins/user/forms/default/forms_input_checkbox.blade.php, resources/views/plugins/user/forms/default/forms_input_date.blade.php, resources/views/plugins/user/forms/default/forms_input_mail.blade.php, resources/views/plugins/user/forms/default/forms_input_radio.blade.php, resources/views/plugins/user/forms/default/forms_input_select.blade.php, resources/views/plugins/user/forms/default/forms_input_text.blade.php, resources/views/plugins/user/forms/default/forms_input_textarea.blade.php, resources/views/plugins/user/forms/default/forms_input_time.blade.php, resources/views/plugins/user/forms/default/forms_input_time_from_to.blade.php
URLにフォームの項目名のgetパラメータを追加すると、フォームの初期値に値が設定される機能追加です。
http://example.com/plugin/forms/index/2712/9509?日付=2020/09/29&数値=1&メール=xxxx&複数行=zzzz&単一=単１&複数選択=赤,青&リスト=B&時間=11:00&時間FromTo=11:50~12:00#frame-9509
※ 同一名の項目があったら、同じ値が設定されます。
※ 複数選択は、(,)カンマ区切りで複数指定できます。
※ 時間型FromToは、(～又は~)区切りでFromTo指定できます。
※ getパラメータで日付の時の/入力、問題なしです。（上記URLだと`日付=2020/09/29`の部分）
* add: form, getパラメータ指定による初期入力値の設定 https://github.com/opensource-workshop/connect-cms/issues/599
* bugfix: form, 1ページに複数フォームを配置し、1個のフォームで登録を行うと、リクエストが1個目しかなく、他フォームでリクエス https://github.com/opensource-workshop/connect-cms/issues/603
なし
なし
無し
=> 【フォーム】getパラメータ指定による初期入力値の設定 他1件

app/Plugins/User/Searchs/SearchsPlugin.php, resources/views/plugins/manage/code/code.blade.php, resources/views/plugins/user/databases/default/databases_include_ctrl_head.blade.php, resources/views/plugins/user/databases/single_sheet/databases_include_ctrl_head.blade.php, resources/views/plugins/user/knowledges/default/knowledges_include_word_search.blade.php, resources/views/plugins/user/opacs/default/opacs.blade.php, resources/views/plugins/user/searchs/default/searchs_form.blade.php, resources/views/plugins/user/themechangers/default/themechangers.blade.php
アクセシビリティ対応です。
* add: テーマチェンジャー, アクセシビリティ対応（G13:状況の変化を引き起こすフォームのコントロールが変化する前に、何が起こるのかを説明する）
* add: アクセシビリティ対応, 検索ボタン内にフォントアイコン虫眼鏡だけだと、スクリーンリーダーで読み上げられないため、aria-label属性を追加する
* change: search, アクセシビリティ対応, getで検索空で受け取った場合、検索必須であるメッセージを表示する事（G83：入力が完了していない必須項目を特定するために、テキストの説明文を提供していることを確認して下さい）
https://github.com/opensource-workshop/connect-cms/issues/610
https://waic.jp/docs/WCAG-TECHS/G13
https://waic.jp/docs/WCAG-TECHS/G83
スクリーンリーダーNVDA https://www.nvda.jp/
aria-label属性 https://developer.mozilla.org/ja/docs/Web/Accessibility/ARIA/ARIA_Techniques/Using_the_aria-label_attribute 
role="presentation" http://blog.e-riverstyle.com/2011/03/rolepresentationwaiaria.html
無し
=> アクセシビリティ対応（JIS-X 8341-3:2016対応）1

app/Plugins/User/Forms/FormsPlugin.php, resources/views/plugins/user/forms/default/forms_edit_form.blade.php
機能追加です。
* メール件名、本文に[[form_name]]の埋め込みコード追加
* メール件名に[[site_name]]、[[number]]の追加
https://github.com/opensource-workshop/connect-cms/issues/618
なし
無し
=> 【フォーム】メール件名、本文に[[form_name]]の埋め込みコード追加

app/Models/User/Forms/FormsColumns.php, app/Plugins/User/Forms/FormsPlugin.php, database/migrations/2020_10_07_194550_add_placeholder_forms_columns_table.php, resources/views/plugins/user/forms/default/forms_edit_row.blade.php, resources/views/plugins/user/forms/default/forms_edit_row_detail.blade.php, resources/views/plugins/user/forms/default/forms_input_date.blade.php, resources/views/plugins/user/forms/default/forms_input_mail.blade.php, resources/views/plugins/user/forms/default/forms_input_text.blade.php, resources/views/plugins/user/forms/default/forms_input_textarea.blade.php
- 項目毎にプレースホルダーを設定できるように改修
- 対象は1行文字列型、複数行文字列型、メールアドレス型、日付型の４つ
https://github.com/opensource-workshop/connect-cms/issues/215
なし
有り
=> 【フォーム】プレースホルダーの設定機能の追加

app/Plugins/User/Databases/DatabasesPlugin.php, resources/views/plugins/user/databases/default/databases_detail.blade.php, resources/views/plugins/user/databases/table/databases.blade.php, resources/views/plugins/user/databases/table/databases_detail.blade.php
https://github.com/opensource-workshop/connect-cms/pull/626 のバグ修正、詳細画面の対応もれです。
また、tableテンプレートも、一覧・詳細画面対応しました。
* bugfix: データベースのdefault, tableテンプレート, 各項目のcss class指定がきくように対応（入力値のみにclassを反映させる）
* データベース, indexのリファクタリング（bladeで使ってない変数をコメントアウト）
issue
https://github.com/opensource-workshop/connect-cms/issues/625
pull requests
https://github.com/opensource-workshop/connect-cms/pull/626
なし
無し
=> bugfix: データベースのdefault, tableテンプレート, 各項目のcss class指定がきくように対応（入力値のみにclassを反映させる）

app/Plugins/User/Databasesearches/DatabasesearchesPlugin.php
- 掲題の通り。
- 過去の修正でエラー対象のカラム（updated_at）をGroup Byから除外しているが、この際の修正漏れと思われる。
- ２つのクエリを修正。
- いずれも後続クエリ条件算出用で順序が求められる箇所ではない為、Order Byを除外
https://github.com/opensource-workshop/connect-cms/issues/627
https://www.p-nt.com/technicblog/archives/204
無し
=> 【データベース検索】バグ修正 mysqlのバージョンによってはエラーになる為、不要なorderByを削除

resources/views/plugins/user/databases/default-left-col-3/databases.blade.php, resources/views/plugins/user/databases/default-left-col-3/template.ini, resources/views/plugins/user/databases/default/databases.blade.php
機能追加です。
https://github.com/opensource-workshop/connect-cms/issues/630
なし
無し
=> データベース, default-left-col-3テンプレート追加（初期表示画面のみ左側col-3にするテンプレート、左にサムネイル画像を配置する場合に利用する事を想定）

app/Models/User/Databases/DatabasesColumns.php, app/Plugins/User/Databases/DatabasesPlugin.php, database/migrations/2020_10_08_154013_add_label_hide_flag_to_databases_columns.php, resources/views/plugins/user/databases/default/databases.blade.php, resources/views/plugins/user/databases/default/databases_detail.blade.php, resources/views/plugins/user/databases/default/databases_edit_row_detail.blade.php, resources/views/plugins/user/databases/table/databases_detail.blade.php
機能追加です。
defaultテンプレート・default-left-col-3テンプレート・tableテンプレートに対応しました。
tebleテンプレートは詳細画面のみ、項目名の表示ON・OFFができます。
https://github.com/opensource-workshop/connect-cms/issues/632
なし
有り
=> データベース、項目毎に項目名の表示をOFFにできる機能追加

resources/views/plugins/user/databases/default/databases_edit_database.blade.php, resources/views/plugins/user/databases/default/databases_edit_row_detail.blade.php, resources/views/plugins/user/databases/default/databases_edit_view.blade.php, resources/views/plugins/user/databases/default/databases_input.blade.php
機能修正です。
* add: データベース、入力エラー時に上部に共通エラーメッセージを表示する
* add: データベース項目設定詳細画面、チェック処理の設定で数値入力設定の項目下に、「※ 数値で入力します。」コメントを追記
無し
無し
無し
=> add: データベース、入力エラー時に上部に共通エラーメッセージを表示する 他1件

resources/views/plugins/user/menus/default/menu_children.blade.php, resources/views/plugins/user/menus/default/menus.blade.php, resources/views/plugins/user/menus/dropdown/menu_children.blade.php, resources/views/plugins/user/menus/dropdown/menus.blade.php, resources/views/plugins/user/menus/mouseover_dropdown/menu_children.blade.php, resources/views/plugins/user/menus/mouseover_dropdown/menus.blade.php, resources/views/plugins/user/menus/mouseover_dropdown_no_root/menu_children.blade.php, resources/views/plugins/user/menus/mouseover_dropdown_no_root/menus.blade.php, resources/views/plugins/user/menus/mouseover_dropdown_no_rootlink/menu_children.blade.php, resources/views/plugins/user/menus/mouseover_dropdown_no_rootlink/menus.blade.php, resources/views/plugins/user/menus/mouseover_dropdown_no_rootlink_for_design/menu_children.blade.php, resources/views/plugins/user/menus/mouseover_dropdown_no_rootlink_for_design/menus.blade.php, resources/views/plugins/user/menus/opencurrenttree/menu_children.blade.php, resources/views/plugins/user/menus/opencurrenttree/menus.blade.php, resources/views/plugins/user/menus/opencurrenttree_for_design/menu_children.blade.php, resources/views/plugins/user/menus/opencurrenttree_for_design/menus.blade.php, resources/views/plugins/user/menus/parentsandchild/menu_children.blade.php, resources/views/plugins/user/menus/parentsandchild/menus.blade.php, resources/views/plugins/user/menus/sitemap/menu_children.blade.php, resources/views/plugins/user/menus/sitemap/menus.blade.php, resources/views/plugins/user/menus/sitemap_no_rootlink/menu_children.blade.php, resources/views/plugins/user/menus/tab/menus.blade.php
- 一部テンプレートは`<ul><li>`タグを使用せず、paddingによるインデントで見た目のみの表現しかされていなかった為、CSSからフックできる階層表現用のclassを追加（depth-0～X）
- 「ディレクトリ展開式（デザイン用）」テンプレートのバグ対応（ヌルポで落ちる）
なし
なし
なし
bladeファイルなので対象外
=> 【メニュー】デザイン用に階層の深さを表現するclassを追加

app/Enums/FormColumnType.php, app/Enums/FormStatusType.php, app/Mail/ConnectMail.php, app/Models/User/Forms/FormsColumns.php, app/Plugins/User/Forms/FormsPlugin.php, config/app.php, database/migrations/2020_10_27_161242_add_mail_attach_flag_to_forms.php, resources/views/plugins/user/forms/default/forms.blade.php, resources/views/plugins/user/forms/default/forms_confirm.blade.php, resources/views/plugins/user/forms/default/forms_edit_form.blade.php, resources/views/plugins/user/forms/default/forms_edit_input.blade.php, resources/views/plugins/user/forms/default/forms_edit_warning_messages.blade.php, resources/views/plugins/user/forms/default/forms_include_value.blade.php, resources/views/plugins/user/forms/default/forms_input_file.blade.php, resources/views/plugins/user/forms/default/forms_list_buckets.blade.php, resources/views/plugins/user/forms/default/forms_list_inputs.blade.php, resources/views/plugins/user/forms/default/forms_warning_messages_line.blade.php, resources/views/plugins/user/forms/forms_frame_edit_tab.blade.php
機能追加です。
・フォームにファイル型を追加しました。
・フォームにファイル型があり、メール通知する場合、メールにファイルを添付できます。
・フォーム設定で「データ登録しない」場合、登録したファイルは削除されます。
・フォーム設定の「メールの添付ファイル制御」で、ファイルを通知メールに添付するか制御できます。
・登録されたファイルを確認するため、登録一覧画面を追加しました。
・フォームに重複登録される事を想定して、登録一覧＞編集で登録データを削除扱いにできるようにしました。
* add: フォーム、ファイル型追加
* add: フォーム、登録一覧画面、登録一覧からの編集画面の追加 
* add: フォーム設定、メールの添付ファイル制御を追加 …
* add: フォーム、ファイル型でメール添付できる機能追加
* change: フォームのenum, FormColumnTypeをEnumsBaseを継承するように修正
* change: フォームのCSVダウンロード、基本ないが、forms_input_colsにデータが無い場合にも対応(登録一覧の表示は、forms_input_colsがない場合にも対応していた)
* change: フォーム、フォーム未選択時のメッセージの共通化
https://github.com/opensource-workshop/connect-cms/issues/489
なし
無し
=> 【フォーム】ファイル型の追加、登録一覧画面の追加等

app/Plugins/User/Databases/DatabasesPlugin.php, database/migrations/2020_11_16_161136_update_checkbox_separator_to_databases_input_cols.php, resources/views/plugins/user/databases/default/databases_edit_row_detail.blade.php
カンマを含むチェックボックス選択肢をインポートできるようにする修正のパッチです。
複数選択肢の区切り文字 , → |に修正します。
また、既に登録された複数選択肢の値を修正するパッチも含んでいます。
なし
なし
有り
=> bugfix: データベース, カンマを含むチェックボックス選択肢をインポートできないため、チェックボックスの区切り文字を,→|に見直しするパッチ

app/Plugins/User/Forms/FormsPlugin.php, database/migrations/2020_11_16_171151_update_checkbox_separator_to_forms_input_cols.php, resources/views/plugins/user/forms/default/forms_edit_row_detail.blade.php
件名の通りです。
https://github.com/opensource-workshop/connect-cms/pull/671
なし
有り
=> change: フォーム, データベースに合わせて、複数選択肢の区切り文字を, → | に変更

app/Enums/CodeColumn.php, app/Plugins/Manage/CodeManage/CodeManage.php, app/Plugins/User/Databases/DatabasesPlugin.php, app/Utilities/Csv/CsvUtils.php, config/app.php, resources/views/plugins/manage/code/code.blade.php, resources/views/plugins/manage/code/code_download.blade.php, resources/views/plugins/manage/code/code_import.blade.php, resources/views/plugins/manage/code/code_manage_tab.blade.php, resources/views/plugins/manage/code/display.blade.php, resources/views/plugins/manage/code/help_message.blade.php
下記の機能追加プルリクエストです。
* コード管理のインポート機能追加
* コード管理のダウンロード機能追加
* コード管理の一覧表示設定に、id, 注釈キー を追加
* コード管理、上部メニューが多くなってきたため、その他設定としてまとめる
* データベースプラグイン、UTF-8 BOM付でCSVインポートすると、必ずエラーになる（初めのカラムがないエラー）不具合を修正
* add: コード管理、インポート追加
* add: コード管理、ダウンロード追加
* add: コード管理、表示設定にid, 注釈キーを追加
* add: コード管理、注釈一覧に注釈キー項目を追加
* add: コード管理, コード管理のカラムのenum追加
* change: コード管理、表示設定の表示をenumsを参照するよう見直し
* change: コード管理、一覧表示をenumsを参照するよう見直し
* change: コード管理、上部メニューが多くなってきたため、その他設定としてまとめる
* change: コード管理, 変数の誤字修正 colum -> column
* change: データベースプラグイン、インポート時のストリームフィルタ内で、Shift-JIS -> UTF-8変換を、外部メソッド化対応
* delete: データベースプラグイン, 不要な変数の初期化削除
* bugfix: データベースプラグイン、UTF-8 BOM付だと初めのカラムがないと必ずエラーになる不具合を修正
https://github.com/opensource-workshop/connect-cms/issues/697
なし
無し
=> 【コード管理】インポート・ダウンロード機能対応 他３件

composer.json, composer.lock, resources/cert/.gitignore, resources/fonts/IPA_Font_License_Agreement_v1.0.txt, resources/fonts/Readme_IPAexfont00401.txt, resources/pdf/.gitignore
PDFライブラリの tcpdf と fpdi を追加するプルリクエストです。
* `tcpdf` PDF作成ライブラリ
* `fpdi` PDFのオーバーレイに必要なライブラリ（既存PDFをベースにそこに追記）
https://github.com/opensource-workshop/connect-cms/issues/720
LaravelでPDF出力
http://spacetimebubble.net/blog/2019/04/07/laravel%E3%81%A7pdf%E5%87%BA%E5%8A%9B/
STEP09：Laravel5.7 でデータを埋め込んだPDFを生成する - Qiita
https://qiita.com/nobu-maple/items/d60189231e9db9cb6b5aa
TCPDF in combination with FPDI | Setasign
https://www.setasign.com/products/fpdi/demos/tcpdf-demo/#p-252
TCPDFマニュアル（勝手訳）
http://tcpdf.penlabo.net/
無し
=> PDFライブラリ追加

config/app.php
外部プラグイン用のenumファイル（EnumsOption配下）を動的に読み込むよう改修
- Connect-CMSでは各所でenumを多用しており、app.phpのaliasesに登録することでblade等で直接参照できるようにしています。
- しかしながら、外部プラグイン系のenumは独自性や非公開等の観点からapp.phpに直接登録することができませんでした。
- 故に外部プラグインでenumを利用する為にはblade等のファイルにuse文で直接ロード、又は、フルパスで参照する必要がありました。
- これを解消する為、app.phpの定義配列に動的にクラス登録を行うようにしたものが今回の改修です。
- 懸念点として画面ロード時の負荷増加がありましたが、30ファイルのenumに対して改修前後のContent Download（Request+Responseの秒数）をそれぞれ10回確認しましたが大きな差は見られませんでした。
なし
なし
なし
=> core修正 enums_optionをaliasesに動的に登録するよう改修

app/Models/User/Bbses/BbsPost.php, resources/views/plugins/user/bbses/default/index.blade.php, resources/views/plugins/user/bbses/default/post_title_div.blade.php, resources/views/plugins/user/bbses/default/show.blade.php
日付は登録日の表示を基本として、詳細画面では、登録日時と更新日時が違うときのみ、更新日時を表示
日付は登録日の表示を基本として、詳細画面では、登録日時と更新日時が違うときのみ、更新日時を表示
無し
=> 掲示板の修正（日付の表記の統一）

app/Http/Middleware/ConnectInit.php, app/Providers/AppServiceProvider.php, resources/views/layouts/app.blade.php
バグ修正のプルリクエストです。
・マイページでサイト名が表示される事を確認
・管理画面でサイト名が表示される事を確認
・通常画面でサイト名が表示される事、タイトルが表示される事を確認
resources/views/layouts/app.blade.php　で表示していた下記ロジックを
```php
@if(isset($configs))
{{$configs['base_site_name']}}
@else
{{ config('app.name', 'Connect-CMS') }}
@endif
```
~~app/Providers/AppServiceProvider.php　の　bootメソッドに移植して、全ビュー間のデータ共有する `\View::share()` 
でセットしました。~~
app/Http/Middleware/ConnectInit.phpの　handleメソッドに移植して、全ビュー間のデータ共有する `\View::share()` 
でセットしました。
[app/Http/Middleware/ConnectInit.php](https://github.com/opensource-workshop/connect-cms/blob/master/app/Http/Middleware/ConnectInit.php#L42)
```php
/* --- 共通で使用するDB --- */
// Connect-CMS の各種設定
// bugfix:【サイト管理・バグ】サイト名が サイト管理＞サイト基本設定 以外適用されない対応
// $request->attributes->add(['configs' => Configs::get()]);
$configs = Configs::get();
// …
```
=> bugfix: 【サイト管理・バグ】サイト名が サイト管理＞サイト基本設定 以外適用されない

resources/views/plugins/manage/user/list.blade.php
ユーザ管理一覧、ダウンロードボタン位置修正のプルリクエストです。
要相談です。
⇒ 相談後修正しました。（左側に件数、右側にダウンロードボタン配置に見直し）
issue https://github.com/opensource-workshop/connect-cms/issues/779
Pull request https://github.com/opensource-workshop/connect-cms/pull/784
なし
無し
=> change: ユーザ管理一覧、ダウンロードボタン位置修正

app/Plugins/User/UserPluginBase.php, resources/views/plugins/common/frame_edit_mails.blade.php
メール設定にメールアドレスの入力チェックを追加したけど、エラーメッセージは画面にわたるけど、
入力値が渡らななくハマりました。
原因思い当たる人いますか？
バリデートエラーでやってる事。
```php
// redirect_path
$redirect_path_array = [
'redirect_path' => url('/') . "/plugin/" . $this->frame->plugin_name . "/editBucketsMails/" . $page_id . "/" . $frame_id . "/" . $bucket->id . "#frame-" . $frame_id
];
// 項目のエラーチェック
$validator = Validator::make($request->all(), [
'notice_addresses' => ['nullable', 'email', Rule::requiredIf($request->notice_on)],
'approval_addresses' => ['nullable', 'email', Rule::requiredIf($request->relate_on)],
'approved_addresses' => ['nullable', 'email', Rule::requiredIf($request->approved_on)],
]);
$validator->setAttributeNames([
'notice_addresses' => '送信先メールアドレス',
'approval_addresses' => '送信先メールアドレス',
'approved_addresses' => '送信先メールアドレス',
]);
// …
```
=> add: 共通のメール設定、メールアドレスの入力チェック追加。しかし入力エラー時に入力値が保持されない

app/Models/User/Bbses/BbsPost.php, database/migrations/2021_04_24_223934_add_first_committed_at_bbs_posts.php
バグ修正のプルリクエストです。
https://github.com/opensource-workshop/connect-cms/issues/829 の不明点を確認してからマージしようと思ってます。
* 投稿通知の変更をOFF
*  編集時にメール飛ばない事を確認
*  編集で一時保存してメール飛ばない事を確認
* 投稿通知の変更をON
*  編集時にメール飛ぶ事を確認
*  編集で一時保存してメール飛ばない事を確認（一時保存はメール飛ばない）
* 投稿通知の登録ON、変更OFF
* 登録でメール飛ぶことを確認。
* 登録で 一時保存→その後変更確定で、メール飛ぶことを確認。
https://github.com/opensource-workshop/connect-cms/issues/829
なし
有
=> bugfix: 【掲示板】メール設定で投稿通知の変更をOFFにしても変更確定時にメールが飛ぶバグ修正

resources/views/plugins/common/wysiwyg.blade.php
バグ修正のプルリクエストです。
多分この修正で問題ないと思っていますが、念のため社内で確認したあと、マージしようと思います。
いままで、ウィジウィグのオプション設定は、下記の読み込み順番でした。
1. テーマにウィジウィグのオプション設定あったら読み込む
2. テーマグループのDefaultテーマから、ウィジウィグのオプション設定あったら読み込む
修正後は、下記の読み込み順番になります。
1. テーマにウィジウィグのオプション設定あったら読み込む
2. テーマグループのDefaultテーマから、ウィジウィグのオプション設定あったら読み込む
3. **DefaultsグループのDefaultテーマから、ウィジウィグのオプション設定あったら読み込む**
・テーマグループ毎にDefaultテーマがある想定で、テーマグループのDefaultテーマから、ウィジウィグのオプション設定が読み込まれていました。
・`テーマなし`の場合、`テーマ管理で作成したテーマ（Usersシリーズ）`の場合、Defaultテーマは存在しないため、ウィジウィグのオプションは読み込まれてませんでした。
→ 基本のウィジウィグのオプション設定は、DefaultsシリーズのDefaultテーマから読み込むで、問題ないかと思いました。
https://github.com/opensource-workshop/connect-cms/issues/823
https://github.com/opensource-workshop/connect-cms/issues/701
無し
=> bugfix: 【ウィジウィグ】 テーマなしだと、ウィジウィグの書式に、アイコン(PDF)等が表示されてないバグ修正 

resources/views/plugins/common/wysiwyg.blade.php
機能追加のプルリクエストです。
各テーマごとに、wysiwygの簡易テンプレートを挿入できるように機能追加 しました。
[templates.txt](https://github.com/opensource-workshop/connect-cms/files/6426934/templates.txt)　ファイルを
public\themes\Defaults\Default\wysiwyg\templates.txt に配置する事で、テンプレート挿入機能が動きます。
https://github.com/opensource-workshop/connect-cms-ideas/issues/5
無し
=> add: wysiwyg, テーマ毎にwysiwygの簡易テンプレート挿入機能追加 

database/migrations/2014_10_12_000000_create_users_table.php, database/migrations/2014_10_12_100000_create_password_resets_table.php, database/migrations/2019_02_25_090524_add_user_id_to_users.php, database/migrations/2019_08_21_165015_add_status_etc_to_contents.php, database/migrations/2020_04_02_232011_create_sessions_table.php, database/migrations/2020_05_14_155953_add_codes_help_messages_alias_key_to_codes_table.php, database/migrations/2020_05_14_160224_create_codes_help_messages_table.php, database/migrations/2021_01_30_130730_create_jobs_table.php, database/migrations/2021_05_11_162339_alter_database_charset_to_utf8mb4.php
- 先日マージしたutf8mb4化対応の対応漏れに対する対応です。
- 現状、新規インストール時のマイグレーション実行時にINDEXサイズエラーでコケます。（↓一例）
`Syntax error or access violation: 1071 Specified key was too long; max key length is 767 bytes`
- 原因は先日のマージでDB接続設定もutf8mb4としている為、テーブル新規作成時にutf8mb4でテーブル作成されますが、各個別マイグレーションファイルのユニークKEY設定しているカラムのサイズ変更対応が漏れていた為、データ長255のまま実行され、上記エラーに繋がります。
- これを解消する為、新規マイグレーション時も考慮して各項目の初期サイズに明示的に191を指定しています。
https://github.com/opensource-workshop/connect-cms/commit/9bcf6eab5a613a5a7377d385faf954633764e102
- また、当初対応ではデータ長を191としていいか未調査だった為、sessionsテーブル（Laravelのセッション管理テーブル）をutf8mb4対応から除外していましたが、これを加える変更を行っています。これはその後の調査で、実際のデータ長が40だったこと、一般的にセッションIDの長さは入れ物サイズ的に191あれば十分であろうと推定しているからです。対応が平易だった為、平伏合わす観点で本対応に加えています。
https://github.com/opensource-workshop/connect-cms/commit/69a043e7048fba5d8b15950cbd3d2037585dc32b
- …
=> Fix bug 2 utf8mb4

app/Http/Controllers/Core/ConnectController.php, app/Plugins/Manage/SiteManage/SiteManage.php, resources/views/layouts/app.blade.php, resources/views/plugins/manage/site/site.blade.php, resources/views/plugins/manage/theme/theme.blade.php, resources/views/plugins/manage/theme/theme_css_edit.blade.php
- 現状、サイト管理から設定できるテーマは１つのみの為、例えば下記のような要件時に対応できない問題がありました。
- グループ毎に異なるサイトを構築した場合、個別サイトで共通スタイルは共有しつつも、個別にスタイルも保持したい場合に設定が出来ない。
- デザイナ業者等に依頼したベースのスタイルを維持しつつ、運用期間中に発生した追加・修正スタイル等が取り込めない。
- これに対応する為、サイト管理に追加テーマと称して、もう１つテーマを設定できるように拡張する対応です。
なし
https://connect-cms.jp/plugin/bbses/show/106/233/289#frame-233
なし
=> 追加テーマ（CSS/JS/画像）を設定できるよう改修

app/Enums/Bs4Color.php, app/Enums/RadiusType.php, app/Enums/UseType.php, app/Http/Controllers/Core/DefaultController.php, app/Models/User/Whatsnews/Whatsnews.php, app/Plugins/User/Whatsnews/WhatsnewsPlugin.php, config/app.php, database/migrations/2021_06_01_155251_add_column_whatsnews_table.php, resources/views/layouts/app.blade.php, resources/views/plugins/user/whatsnews/default/whatsnews.blade.php, resources/views/plugins/user/whatsnews/default/whatsnews_edit_whatsnew.blade.php, resources/views/plugins/user/whatsnews/onerow/whatsnews.blade.php, resources/views/plugins/user/whatsnews/whatsnews_script.blade.php, routes/web.php
- 新着プラグインに「もっと見る」ボタン機能を付与できる機能追加です。
- 新着は利用頻度が比較的高いプラグインの為、既存サイトへの影響を考慮して、該当ボタンの表示可否等は設定画面から変更できるようにしています。（設定項目：表示可否、ボタン表示名、押下時の取得件数等）※デフォルトは非表示です。
- 追加の新着一覧は非同期で取得する為、コア側にAPIコールできるI/F機能を追加しています。
- （検討中＠6/2）初動開発ではIEで動作できなかった為、ポリフィル対応を検討中です。なるべくIEでの動作も目指したいですが、調査結果次第ではIEでは本機能を無効化する可能性もあります。（追記＠6/4）ポリフィル対応を入れてIE動作OKです。
- （ポリフィルについて）app.blade.phpで表示ページに新着プラグインが存在したら、CDN経由で必要なJSライブラリをversion固定で読み込むようにしています。いずれ消す可能性のあるライブラリの為、CDN経由にしています。
https://github.com/opensource-workshop/connect-cms-ideas/issues/33
なし
有り
=> 【新着プラグイン】「もっと見る」機能を追加

app/Http/Controllers/Auth/LoginController.php, app/Traits/ConnectCommonTrait.php
・外部認証チェックする前にアカウント利用可能チェックをしていたところを修正
・NC2外部認証後アカウント作成時、ハンドルが渡ってきている場合はハンドル名を登録するように修正
・NC2外部認証時、NC2側権限によって役割設定を振り分けられるような機能を追加
・外部認証処理時、既にアカウントがある時にそのアカウントが利用停止中なのかどうかチェックする部分にEnum設定を反映
なし
=> Extern auth：NC2外部認証連携部分修正

app/Plugins/User/Cabinets/CabinetsPlugin.php
コミット漏れがあり、500エラーとなってしまっていました。
https://github.com/opensource-workshop/connect-cms/pull/910
無し
=> fix: viewに対してのcabinet変数の設定漏れを追加

app/Models/Migration/Nc2/Nc2Block.php, app/Models/User/Bbses/BbsPost.php, app/Traits/Migration/MigrationTrait.php, app/Traits/Migration/sample/migration_config/migration_config.sample.ini
掲示板→掲示板のNC2移行処理を追加しました。
もともと掲示板→ブログへ移行していましたが、
Connect-CMSに掲示板プラグインが追加されたため、対応しました。
無し
=> BBS→BBSのNC2移行を対応しました

app/Models/User/Cabinets/CabinetContent.php, app/Plugins/User/Cabinets/CabinetsPlugin.php, resources/views/plugins/user/cabinets/default/index.blade.php
管理機能のアップロードファイル管理で、ファイル名の変更ができるため、
ファイルはアップロードテーブルから名称取得する。
https://github.com/opensource-workshop/connect-cms-ideas/issues/58
無し
=> modify: ファイル名をアップロードテーブルから取ってくるよう修正

resources/views/layouts/app.blade.php
- とあるプロダクション環境でテーマファイル内CSSから設定している画像の差し替え要求があった。
- CSS内から画像ファイルを参照している箇所にクエリストリングを設定したが、そもそも大元のHTML→CSS読み込み部でブラウザキャッシュが効いてしまい、旧いCSSが読み込まれ、結果、画像も変わらないケースが発生
- 各クライアント端末側ブラウザのスーパーリロードを行えば解消はされるが、すべての閲覧者に対してリロードを要求するのは現実的ではない為、機能化に至りました。
- サイト管理で設定できる基本テーマ／追加テーマに紐づくCSSファイル／JSファイルに対して、ファイルの更新時間を取得してクエリストリングを付与するようにしました。
- これにより、ファイル更新までは各クライアントのキャッシュが維持されます。
- （一応）テーマ設定はあるが、ファイルがないケースでシステムエラーが発生しないことは確認しています。
なし
http://blog.ko-atrandom.com/?p=266
なし
- bladeファイルなのでPHP_CodeSnifferは対象外
- マニュアルは下記ページのテーマ言及部を更新
- https://connect-cms.jp/manual/manager/site
=> テーマ 基本／追加テーマのCSS／JSファイルにキャッシュバスティング用のクエリストリング追加

database/migrations/2021_08_12_141439_update_plugin_name_codes_table.php, resources/views/plugins/manage/code/edit.blade.php
codes.plugin_nameが全小文字で登録されるよう修正
bucketsやframesでは全小文字であり、Connect-CMS内で平仄を取るため
#960
有り
=> modify: codes.plugin_nameが全小文字で登録されるよう修正

app/Plugins/User/Cabinets/CabinetsPlugin.php, resources/views/plugins/user/cabinets/default/index.blade.php
以下内容を対応しました。
- 削除処理完了後のリダイレクトでシステムエラーとなる
- #1020の対応漏れが原因でした。
- リダイレクト先を修正して対応しました。
- 1ページにキャビネットのフレームが複数あると正常にファイルを選択できない
- Javascriptのセレクタでフレーム間に同名のものが出てきてしまっていたので、削除処理が想定通りに動かなくなっていました。
- ID属性にフレームIDを入れて対応しました。
#1023
無し
=> Fix キャビネットのファイル削除でエラー

app/Plugins/User/Cabinets/CabinetsPlugin.php
Zipファイル直下に空白のディレクトリができていたため解凍できないようになっていました。
例 : [ZIPファイル]\\\\foo\bar
空白のディレクトリが作られないよう修正しました。
#1029
無し
=> fix: Windowsの標準解凍ツールでZIPを解凍できない

app/Plugins/User/Blogs/BlogsPlugin.php, resources/views/plugins/user/blogs/default/blogs.blade.php, resources/views/plugins/user/blogs/default/blogs_input.blade.php
件名通り。
※ コピー押下後、登録画面へ。投稿日時は今の時間で。
* https://github.com/opensource-workshop/connect-cms-ideas/issues/95
なし
無し
=> add: ブログ, コピーして登録画面へ機能追加

app/Plugins/User/Databasesearches/DatabasesearchesPlugin.php, resources/views/plugins/user/databasesearches/default/databasesearches.blade.php
- 前回対応だとすべての項目型でサニタイズ除外されてしまいセキュリティ的に良くない為、WYSIWYG型のみに限定
https://github.com/opensource-workshop/connect-cms/pull/1044
なし
無し
=> データベース検索 HTMLエスケープ除外をWYSIWYG型のみに限定

resources/views/plugins/user/menus/breadcrumbs/template.ini, resources/views/plugins/user/menus/footersitemap/template.ini, resources/views/plugins/user/menus/footersitemap_no_rootrink/template.ini, resources/views/plugins/user/menus/mouseover_dropdown_no_rootlink_for_icon/menu_children.blade.php, resources/views/plugins/user/menus/mouseover_dropdown_no_rootlink_for_icon/menu_parent.blade.php, resources/views/plugins/user/menus/mouseover_dropdown_no_rootlink_for_icon/menus.blade.php, resources/views/plugins/user/menus/mouseover_dropdown_no_rootlink_for_icon/template.ini, resources/views/plugins/user/menus/parentsandchild/template.ini, resources/views/plugins/user/menus/sitemap/template.ini, resources/views/plugins/user/menus/sitemap_no_rootlink/template.ini
アイコンメニューテンプレ追加
メニュープラグインに、アイコン埋めこみ用デザインテンプレを追加
- 親階層が全て非表示だった場合、第二階層以降をメニューに表示できるようにした
- 親階層で表示できるページが１つしかない場合、子階層も並べて表示できるようにした（ルーム貸し対応）
- スマホ表示した場合、メニューが消えないように対応
- スマホ表示した場合、ページ名が消えるように対応
- ドロップダウンされる子要素が親要素の右側に合わせた位置に表示されるようにし、ブラウザ幅からはみ出さないようにした
- メニューの親要素にだけアイコン指定ができるようにclass指定を追加
- メニューの子要素にだけスタイルがあてられるようにclass指定を追加
```
<style>
.dropdown-toggle::after { content: unset; }  /* 子要素がある時▼が出ないようにする */
.icon_menu_main_list {display: inline-block; text-align: center; min-width: 90px;} /* 親メニューの見た目調整 */
.icon_menu_main_list li { list-style: none; } /* 子要素の記号除去 */
.icon_menu_second_list { padding-left: 0;} /* 子要素の不要なpadding除去 */
/* 1個目のアイコン */
.icon_menu_main_list:nth-child(1) > a:before {
content: url(/file/4) "\A";
white-space: pre;
}
/* 2個目のアイコン */
.icon_menu_main_list:nth-child(2) > …
```
=> アイコンメニューテンプレ追加

dev_2_option_private.ps1.example, option_private_2_dev.ps1.example, sync_dev_2_option_private.sh.example, sync_option_private_2_dev.sh.example
外部プラグインのコピーバッチでシーダーとメールテンプレートもコピーされるよう対応しました。
プライベートリポジトリでの対応
無し
無し
=> 外部プラグインのコピーバッチでシーダーとメールテンプレートを対応しました

resources/views/plugins/user/menus/mouseover_dropdown_no_rootlink_for_icon/menu_parent.blade.php, resources/views/plugins/user/menus/mouseover_dropdown_no_rootlink_for_icon/menus.blade.php
スマホ表示にした時に、メニューそのものを隠すように修正
修正前：スマホ表示にした時、ページ名だけが隠れる
修正後：スマホ表示にした時、アイコンメニューそのものが隠れる
なし
なし
なし
=> アイコンメニュー対応変更

app/Http/Controllers/Core/UploadController.php, app/Plugins/Manage/UploadfileManage/UploadfileManage.php, config/filesystems.php, resources/views/plugins/manage/uploadfile/uploadfile_manage_tab.blade.php, resources/views/plugins/manage/uploadfile/userdir.blade.php, routes/web.php, storage/user/.gitignore
- サーバに直接ファイルを置ける環境の場合
- 置いたファイルもConnect-CMSで閲覧制限したい。
- 閲覧制限はディレクトリ単位で行いたい。
無し
=> ユーザ配置ファイルのConnect-CMS閲覧制御

composer.json, composer.lock
composer.jsonにphp-jwtを追加しました。
https://github.com/firebase/php-jwt
外部API実行時にJWTを使った認証が必要となるためです。
php-jwtはfirebaseのプロジェクトであることから、
信用性は高く、今後もメンテされていくものと思います。
プライベートリポジトリでの対応
無し
=> add: php-jwtを追加

app/Plugins/User/Slideshows/SlideshowsPlugin.php
削除のwhere句カラム指定ミスが原因でSQLエラーが発生していました。
#1078
無し
=> fix: スライドショーが削除できない

app/Plugins/User/Slideshows/SlideshowsPlugin.php, database/migrations/2022_01_13_103252_add_height_to_slideshows.php, resources/views/plugins/user/slideshows/default/slideshows.blade.php, resources/views/plugins/user/slideshows/default/slideshows_edit_slideshow.blade.php
スライドショーで画像の高さをしていできるようにしました。
スライドショー設定画面から設定可能です。
スライドショーで高さ・横幅が違う画像を設定したときに
画像が切り替わるたび画面が上下するのを防ぐため対応しました。
#1075
https://github.com/opensource-workshop/connect-cms-ideas/issues/109
有り
=> add: スライドショーの高さ指定機能

app/Enums/UploadMaxSize.php, database/migrations/2022_01_14_172016_resize_upload_max_size_to_cabinets.php
#1080 の状態でNC2移行を実行すると、
cabinets.upload_max_sizeに'1048576'（1GBをKB単位に変換した値）が設定されます。
その'1048576'で app/Enums/UploadMaxSize を参照しようとして、Undefined offsetの例外が発生していました。
app/Enums/UploadMaxSize.php 
`const one_giga_byte = '1024000';`
上記定数が1GBをKB単位に変換した値になっていませんでした。
定数UploadMaxSizeの1GB(one_giga_byte)を正しい値('1048576')に修正しました。
#1080
有り
=> fix: upload_max_sizeの1GBがKB変換値となっていない

app/Enums/BlogFrameConfig.php, app/Models/User/Blogs/Blogs.php, app/Plugins/User/Blogs/BlogsPlugin.php, database/migrations/2022_01_14_143252_drop_column_view_count_to_blogs.php, resources/views/plugins/user/blogs/default/blogs_edit_blog.blade.php, resources/views/plugins/user/blogs/default/blogs_setting_frame.blade.php
ブログの表示件数をバケツからフレーム保持に変更しました。
- 設定変更画面から表示件数の入力項目を削除しました。
- 新規作成画面から表示件数の入力項目を削除しました。
- 表示条件設定画面に表示件数の入力項目を追加しました。
- blogs.view_countを列削除して、frame_configsに表示件数を保持するように変更しました
- 上記より列削除＆データ移行するマイグレーションを追加しました。
- 表示件数の初期値を設定するとなるとコアの修正が必要になりそうだったため、初期値無しにしています。
- 初期値がないとLaravelのデフォルトで15件となります。
- 変更したい場合は表示条件設定画面にてユーザが変更するようになります。
#1077
有り
=> ブログの表示件数をバケツからフレーム保持に変更しました

app/Rules/CustomValiExclusiveProcessing.php, app/Rules/CustomValiTableRecordNotExist.php
リネーム
CustomVali_TableRecordNotExist
CustomVali_ExclusiveProcessing
↓
CustomValiTableRecordNotExist
CustomValiExclusiveProcessing
社内確認後マージ予定。
* https://github.com/opensource-workshop/connect-cms/issues/863
無し
=> change: 独自バリデーションのクラス名修正

app/Plugins/User/Whatsnews/WhatsnewsPlugin.php
バグフィックスです。
getWhatsnews()にて日数で絞り込むため、修正箇所では絞り込まないようにしました。
#1063
#883
無し
=> fix: 新着の取得方式が日数で表示するのときにもっと見るボタンが表示されない

app/Plugins/User/Slideshows/SlideshowsPlugin.php
Coreでチェックされるので、プラグインでのチェック処理を削除しました。
#1110
歯車押下時のアクション:  /plugin/slideshows/**createBuckets**/{page_id}/{frame_id}
https://github.com/opensource-workshop/connect-cms/blob/6cc8157b95ecd30b81b87af9e0f40f30de53d841/config/cc_role.php#L143
createBucketsアクションではframes.createのチェックが適用されます。
無し
=> Fix: プラグイン管理者がフレームの歯車ボタンを押すと権限なしエラーになる

resources/views/plugins/user/blogs/designbase/blogs_show.blade.php
https://github.com/opensource-workshop/connect-cms/issues/1120
無し
=> ブログ designbaseテンプレートでTwitter又はFBアイコンをONで記事詳細開くとエラー

resources/views/plugins/user/blogs/default/blogs.blade.php, resources/views/plugins/user/blogs/designbase/blogs.blade.php, resources/views/plugins/user/faqs/default/faqs.blade.php, resources/views/plugins/user/learningtasks/default/learningtasks.blade.php, resources/views/plugins/user/whatsnews/card_04/whatsnews.blade.php, resources/views/plugins/user/whatsnews/default/whatsnews.blade.php, resources/views/plugins/user/whatsnews/onerow/whatsnews.blade.php
バケツ選択メッセージがされないプラグインがあったので、表示されるよう修正しました。
- すべてのユーザーで表示されない
- 新着情報
- プラグイン管理者で表示されない
- FAQ
- ブログ
- 課題管理
#1066 
#1109 
無し
=> Fix: バケツ選択メッセージが表示されない

app/Plugins/User/Opacs/OpacsPlugin.php
nullの変数にcount()を実行してエラーになっていたので、変数定義時に空のarrayを代入するように修正しました。
#1111
無し
=> Fix: 条件なしで詳細検索実行するとシステムエラーとなる

app/Plugins/User/Forms/FormsPlugin.php, resources/views/plugins/user/bbses/default/index.blade.php, resources/views/plugins/user/cabinets/default/empty_bucket.blade.php, resources/views/plugins/user/conventions/default/index.blade.php, resources/views/plugins/user/counters/default/empty_bucket.blade.php, resources/views/plugins/user/databases/default/databases.blade.php, resources/views/plugins/user/databases/design-table-dl/databases.blade.php, resources/views/plugins/user/databases/table/databases.blade.php, resources/views/plugins/user/databasesearches/card_04/databasesearches.blade.php, resources/views/plugins/user/databasesearches/default/databasesearches.blade.php, resources/views/plugins/user/forms/default/forms_error_messages.blade.php, resources/views/plugins/user/linklists/default/index.blade.php, resources/views/plugins/user/opacs/default/opacs_no_frame_setting.blade.php, resources/views/plugins/user/openingcalendars/default/openingcalendars.blade.php, resources/views/plugins/user/photoalbums/default/empty_bucket.blade.php, resources/views/plugins/user/searchs/default/searchs.blade.php, resources/views/plugins/user/slideshows/default/slideshows_error_messages.blade.php
未ログインユーザにバケツなしフレームのバケツ選択メッセージが見えています。
ユーザー全般に対してのメッセージではないため、
バケツを設定できる権限のないユーザにはメッセージが表示されないように修正しました。
#1066
無し
=> Fix: 未ログインユーザにバケツなしフレームのバケツ選択メッセージが見える

app/Plugins/User/Forms/FormsPlugin.php, resources/views/plugins/user/forms/default/forms_list_buckets.blade.php
定期的な内容※に関しては、フォーム設定、項目設定が同じなことがあるため、
作成済みのフォームをコピーして作成できるようにしました。
※ 毎年の満足度調査といった年度ごとのアンケート等
フォーム選択画面の詳細列に"コピーして新規"ボタンを設けました。
こちらから、フォームをコピーできます。
違う場所に配置したほうがいい等の意見があればいただきたいです！
#1123
無し
=> Add: フォームのコピー機能

resources/views/plugins/user/menus/hamburger_button/menus.blade.php, resources/views/plugins/user/menus/hamburger_button/menus_script.blade.php, resources/views/plugins/user/menus/hamburger_button/template.ini, resources/views/plugins/user/menus/opencurrenttree/menu_parent.blade.php, resources/views/plugins/user/menus/opencurrenttree/menus.blade.php
メニュープラグインにハンバーガーメニューテンプレート追加
メニュープラグインに、ハンバーガーメニューテンプレート追加
メニュー本体の仕様は「ディレクトリ展開式」をそのまま利用しています。
なし
=> ハンバーガーメニューを追加

app/Plugins/User/Forms/FormsPlugin.php, database/migrations/2022_02_08_151632_set_form_bucket_name.php
フォームの連番管理でデータ名がすべて"無題"となっていました。
buckets.bucket_name（＝連番管理のデータ名）が"無題”固定で登録されていたため、当事象が発生していました。
buckets.bucket_nameにフォーム名を登録するよう修正しました。
既存データを更新するため、マイグレーションありです。
#1146 
有り
=> フォームの連番管理でデータ名にフォーム名を表示する

app/Plugins/User/Forms/FormsPlugin.php
フォーム名とバケツ名は同一であるべきものなため、対応しました。
フォームコピー後にフォーム名を修正することが主であるため、バケツ名も更新します。
（フォームをコピーするとフォーム名は「〇〇_copy」となります）
新たに追加した、saveFormBucket()でplugin_nameの登録が他機能と異なっていたので、
合わせて修正しています。
（plugin_nameは全小文字が正しい。先頭大文字になっていました）
#1146 
無し
=> フォーム名更新時にバケツ名も更新する

resources/views/plugins/user/calendars/default/index.blade.php, resources/views/plugins/user/calendars/small_month/index.blade.php
カレンダーの表示パフォーマンス改善です。
posts.createは、投稿権限をチェックする処理です。
カレンダーの月表示では、日毎に「＋」ボタンがある事から、３０回程度同じposts.createチェックが実行されていました。
そのため、ループ外でposts.createをチェックする事で、処理を軽くしました。
なし
なし
無し
=> change: カレンダー, posts.createをループ外で判定

app/Plugins/User/Databasesearches/DatabasesearchesPlugin.php, resources/views/plugins/user/databasesearches/card_04/databasesearches.blade.php
データベース検索のカードタイプテンプレートの修正
・最初の項目のみにリンクを張るのではなく、カード全体にリンクを張るように修正
・カード部にCSSを当てられるようにdivを一つ追加
・項目種別が日付の場合、y/m/d形式で時間が出力されないように修正
・ウィジウィグ以外で文字列が出力された時用に、pタグを追加
なし
なし
なし
=> データベース検索　カードタイプテンプレートの修正

resources/views/plugins/user/databases/card_02/databases.blade.php
一覧画面の方もCSSを当てやすい形式に修正
データベース　カードタイプテンプレ
一覧画面の方にもCSSを当てやすいようにタグを組み替え
・項目名と値のセットが、CSSが当てにくい形になっていたので、dl、dt、ddタグに置き換え
・１データの１項目目がタイトルになるようにh2タグが当たるように修正
・ベースとしたdefaultテンプレートにあった不要部分の削除
なし
=> データベースカードタイプテンプレ

app/Models/User/Databases/DatabasesInputs.php, app/Plugins/User/Databases/DatabasesPlugin.php, app/Plugins/User/UserPluginBase.php, database/migrations/2022_03_14_144704_add_expires_at_to_databases_inputs.php, resources/lang/ja/validation.php, resources/views/plugins/user/databases/card_02/databases.blade.php, resources/views/plugins/user/databases/default/databases.blade.php, resources/views/plugins/user/databases/default/databases_confirm.blade.php, resources/views/plugins/user/databases/default/databases_input.blade.php
データベースの１データに公開終了日時を持たせて、到来時に自動で閲覧不可にする機能を追加しました。
- データの新規登録画面に公開終了日時を追加
- CSVエクスポート機能に公開終了日時を追加
- CSVインポート機能に公開終了日時を追加
- データベースの新着情報について、公開終了データは対象外とする
- データベースのサイト内検索について、公開終了データは対象外とする
- CSVインポート機能の項目不足でエラーとする
- データ行で表示順がＣＳＶの項目として抜けててもエラーとなっていなかった
- ヘッダーは項目抜けをチェックしていたので、合わせる形で修正
- Laravel のバリデーション　日本語エラーメッセージ修正
- present : 正しい日本語訳に修正
- date_format : typo修正（開くダブルクォーテーションが抜けていた） 
#1207 
有り
=> データベースの公開終了機能

app/Http/Controllers/Auth/RegisterController.php
モデレータには遷移先だったユーザー管理画面の閲覧権限がないので、遷移先をルートにすることでエラーとならないようにしました。
* #1211
無し
=> Fix: モデレータでユーザ登録すると登録完了後の遷移先で権限なしエラーとなる

app/Plugins/User/Databases/DatabasesPlugin.php
値が空で渡ってきたとき、NULLでsaveされていませんでした。
空でリクエストがあったとき、NULLになるよう修正しました。
#1233
無し
=> Fix: データベースの公開終了日時を空に更新できない

app/Plugins/User/Databases/DatabasesPlugin.php
CSVインポートで公開終了日時が空の場合には、空で登録されるように修正しました。
値が空でもnew Carbon()してたので現在日時が登録されていました。 
#1233
無し
=> Fix: CSVインポートで公開終了日時が空だと現在日時で登録される

.github/workflows/phpcs.yml, app/Enums/UserStatus.php, app/Http/Controllers/Auth/RegisterController.php, app/Http/Controllers/Auth/RegistersUsers.php, app/Plugins/Manage/UserManage/UserManage.php, app/Traits/ConnectCommonTrait.php, app/User.php, resources/views/plugins/manage/user/auto_regist.blade.php
自動ユーザ登録に管理者承認機能を追加しました。
承認がないと、利用可能とならないようにできます。
承認機能を実現するため、ユーザの状態に”承認待ち”を新たに設けます。
ユーザが公開側のユーザ登録画面（/register）から登録した場合、状態が"承認待ち"になります。
（この操作を登録申請とします）
ただし、仮登録設定が有効の場合は、状態が"仮登録"となり、
メールアドレスの有効性を確認した後で、 "承認待ち"になります。
まとめると、ユーザの状態は以下のように遷移します。
- 仮登録が有効の場合
- 仮登録→承認待ち→利用可能
- 仮登録が無効の場合
- 承認待ち→利用可能
管理者はユーザ詳細画面から状態を変更することで登録申請の承認を行えます。
- ユーザ管理 ユーザ一覧画面
- 絞り込み条件：状態に"承認待ち"を追加
- 一覧の承認待ち行の背景色をbg-infoで表示
- ユーザ管理 ユーザ登録画面、ユーザ詳細画面
- 状態の選択肢に承認待ちを追加
- 一度、承認待ち以外にすると承認待ちは選択できないようになる
- 承認待ちから利用可能に変更すると、承認完了メールが飛ぶ
- ユーザ管理 自動ユーザ登録設定画面
- 以下の設定を追加
- 管理者の承認
- 承認完了メール件名
- 承認完了メールフォーマット
- ユーザ登録画面
- 承認機能が有効の場合、状態を"承認待ち"で登録する（仮登録が有効の場合を除く）
- トークンを使った本登録の確定画面
- 承認機能が有効の場合、状態を"承認待ち"に更新する
#1220
無し
=> Add: 自動ユーザ登録の管理者承認機能

app/Http/Controllers/Auth/RegistersUsers.php, app/Plugins/Manage/UserManage/UserManage.php, config/connect.php, resources/views/plugins/manage/user/auto_regist.blade.php
ユーザ管理 自動ユーザ登録画面で、自動ユーザ登録の初期コンテンツ権限を選択可能にしました。
- ユーザ管理 自動ユーザ登録画面
- 初期コンテンツ権限の設定を追加
- .envの設定を優先して表示し、.envの値からは変更できないようにする
- .envに設定がなければ、画面から変更可能とする
- ユーザ登録画面
- ユーザ管理の初期コンテンツ権限設定を参照して権限を登録する
すでに.envで初期権限を設定できるようになっていました。(SELF_REGISTER_BASE_ROLES)
既存の仕様を生かすため、.envの方を優先して利用するように改修しています。
#1226
無し
=> Add: 自動ユーザ登録の初期権限を選択可能にする

app/Plugins/Manage/UserManage/UserManage.php, resources/views/plugins/manage/user/edit_column_detail.blade.php, resources/views/plugins/manage/user/edit_columns.blade.php, resources/views/plugins/manage/user/include_edit_column_row.blade.php, resources/views/plugins/manage/user/include_edit_column_row_add.blade.php, resources/views/plugins/manage/user/user_manage_tab.blade.php
=> 【ユーザ管理】ユーザ情報の任意項目の設定画面追加 

app/Plugins/User/Searchs/SearchsPlugin.php
画面上、必須項目なのに必須チェックが入っていませんでした。
対応するDB(searchs.count)の項目にNOT NULL制約が入っていたため、NULLを登録するとSQLエラーが発生していました。
必須チェックを追加する対応を行いました。
#1272
無し
=> Fix: 1ページの表示件数を空白で登録するとシステムエラーとなる

app/Enums/DatabaseNoticeEmbeddedTag.php, app/Models/User/Databases/DatabasesColumns.php, app/Plugins/User/Databases/DatabasesPlugin.php, config/app.php, resources/views/plugins/user/databases/default/databases_confirm.blade.php, resources/views/plugins/user/databases/default/databases_input.blade.php, resources/views/plugins/user/databases/description_frame_mails.blade.php
・汎用項目の埋め込みタグ対応
・公開日、公開終了日、表示順の埋め込みタグ対応
* https://github.com/opensource-workshop/connect-cms/issues/1275
* https://github.com/opensource-workshop/connect-cms/commit/a6108b1f68212aaa1f3e3861bd78248ee76e9618
無し
=> 【データベース】メール通知の埋め込みタグ強化対応

app/Models/User/Reservations/ReservationsInput.php, app/Plugins/User/Reservations/ReservationsPlugin.php, app/Traits/Migration/MigrationTrait.php, database/migrations/2022_05_08_110631_migrate_endtime_24h_from_reservations_inputs_and_reservations_facilities.php, database/migrations/2022_05_08_121316_migrate_first_committed_at_is_not_null_from_reservations_inputs.php, resources/views/plugins/manage/reservation/edit.blade.php, resources/views/plugins/user/reservations/default/edit_booking.blade.php, resources/views/plugins/user/reservations/default/include_calendar_modal_call.blade.php, resources/views/plugins/user/reservations/default/show_booking.blade.php
JSで24:00入力できたため、対応しました。
施設の利用終了時間も24時間設定対応しました。
* https://github.com/opensource-workshop/connect-cms/issues/1262
* https://github.com/opensource-workshop/connect-cms/issues/1280
なし
有り
=> 【施設予約】予約終了時間に 24:00 を入力できるようにする

app/Plugins/User/Forms/FormsPlugin.php, database/migrations/2022_05_11_164539_add_number_2_forms_inputs_table.php, resources/views/plugins/user/forms/default/forms_edit_form.blade.php, resources/views/plugins/user/forms/default/forms_list_inputs.blade.php
掲題の通り。契約クライアントから要望あり。
- 契約クライアントには「5月中に提供可能」で伝えてある為、急ぎません。
- （急ぎませんが）5月16日～週のどこかからフォーム＋採番値の業務運用を想定している、との発言もあり。5月中で了承頂いているので5月中であれば問題ないですが、早ければ尚、ありがたい、といったところです。
https://github.com/opensource-workshop/connect-cms/issues/659
なし
有り
=> 【フォーム】投稿したフォームデータに採番値を追加＆CSVダウンロードで確認できるようにする

app/Plugins/User/Forms/FormsPlugin.php
先のPRに対応漏れ（仮登録フローでの本登録時に採番値が登録されない）があり、これのバグFIX対応です。
- バグなので急ぎたいですが、お手すきの際で結構です。よろしくお願いいたします。
https://github.com/opensource-workshop/connect-cms/issues/659
https://github.com/opensource-workshop/connect-cms/pull/1285
なし
なし
=> 【フォーム】投稿したフォームデータに採番値を追加＆CSVダウンロードで確認できるようにする（仮登録フローでの対応漏れ）

app/Traits/Migration/MigrationTrait.php, resources/views/errors/503.blade.php
Laravel標準のメンテナンス画面がありますが、メッセージを改行できず使い勝手が悪いため、
メンテナンス画面の追加しました。
社内確認後、マージ予定です。
コマンド
```
php artisan down
```
コマンド メッセージ設定
```
php artisan down --message="<div class=\"text-center mt-4\"><h1>ただいまサイトメンテナンス中です。</h1><h3>【作業日時】</h3><h3 class=\"text-danger\">2022年○○月○○日13:00～18:00</h3><p>作業終了までしばらくお待ちください。</p></div>"
```
```
php artisan up
```
なし
なし
* [Laravel 8.x更新で変わったこと（１）メンテナンス中のアクセス – ララジャパン](https://www.larajapan.com/2021/10/31/laravel-8-x%E6%9B%B4%E6%96%B0%E3%81%A7%E5%A4%89%E3%82%8F%E3%81%A3%E3%81%9F%E3%81%93%E3%81%A8%EF%BC%88%EF%BC%91%EF%BC%89%E3%83%A1%E3%83%B3%E3%83%86%E3%83%8A%E3%83%B3%E3%82%B9%E4%B8%AD%E3%81%AE%E3%82%A2/)
* [Laravel 8 の php artisan down では --allow ではなく --secret を使う - Qiita](https://qiita.com/Crowmaru/items/a3dd10786a1764d292ad)
Laravel8でメンテナンスモード変わる。 …
=> add: メンテナンス画面追加

config/logging.php
DEBUGレベルだと出力が多すぎるため、INFOレベルの日時ログを出力する選択肢を増やしました。 
6/30
無し
=> OW-528 Add: INFOレベルの日時ログ出力 

app/Http/Controllers/Auth/RegistersUsers.php, app/Plugins/Manage/UserManage/UserManage.php, database/seeds/DefaultConfigsTableSeeder.php, resources/views/plugins/manage/user/auto_regist.blade.php, resources/views/plugins/manage/user/list.blade.php, resources/views/plugins/manage/user/mail.blade.php, resources/views/plugins/manage/user/regist.blade.php
* https://github.com/opensource-workshop/connect-cms/issues/1305
なし
なし
なし
seeder追加
=> add: 【ユーザ管理】ユーザ登録時のメール送信画面に画面名等追加

public/css/connect.css, resources/views/layouts/app.blade.php
ヘッダーのサイト名が長いと折り返してハンバーガーメニューが左側に行ってしまうため、
省略して表示するようにしました。
変更前
変更後
無し
=> Modify: ヘッダーのサイト名が長いときに省略する

resources/views/plugins/common/wysiwyg.blade.php, resources/views/plugins/manage/service/index.blade.php, resources/views/plugins/manage/site/site_manage_tab.blade.php
* https://github.com/opensource-workshop/connect-cms/issues/1319
> ・単位がピクセルではなく、remなので大きさのイメージがつかめない
という意見あり。
確かにわかりずらい（牟田口実装した本人ですが、remってわからずネットで調べました。）
文字の大きさラベル表示のみ変更。大きさ指定はremのまま。
* [change: サイト管理, 頭メニューのWYSIWYG設定のメニュー位置を変更](https://github.com/opensource-workshop/connect-cms/pull/1320/commits/8572184c279ff07f869db966c092f332710c4e49)
* サイト管理＞その他設定＞WYSIWYG設定→サイト管理＞WYSIWYG設定に移動
なし
なし
* https://www.pc-koubou.jp/magazine/23912
> ![image](https://user-images.githubusercontent.com/2756509/175205595-06925128-af8b-470a-a0e7-c4795ce7748c.png)
* https://www.tiny.cloud/docs-3x/reference/Configuration3x/Configuration3x@style_formats/
* https://www.tiny.cloud/docs-4x/configure/content-formatting/#fontsize_formats
* https://hazimaru.jp/2106/
> 	$setting['fontsize_formats'] = "超小さい=60% 小さい=75% …
=> OW-1098 change: wysiwyg, 文字の大きさの選択ラベルを％に変更

resources/views/plugins/common/wysiwyg.blade.php
件名通り
なし
なし
* https://www.tiny.cloud/docs/tinymce/6/editor-size-options/#resize
* https://stackoverflow.com/questions/55105275/tinymce-5-manual-resize
なし
=> change: wysiwyg, 入力エリアを横にも広げられるようにする

resources/views/plugins/manage/menus_list.blade.php
* データ管理系 の文字色を黒に。
* データ管理系と、その上のメニューを分けて表示
社内で確認
なし
なし
なし
=> change: 管理者メニュー, 表示見直し

resources/views/plugins/user/menus/tab/menus.blade.php, resources/views/plugins/user/menus/tab_flat/menu_children.blade.php, resources/views/plugins/user/menus/tab_flat/menus.blade.php, resources/views/plugins/user/menus/tab_flat/template.ini
=> add: メニュー, タブテンプレートでページ名を改行させない対応

app/Plugins/Manage/PageManage/PageManage.php, resources/views/plugins/manage/page/page.blade.php
編集画面に遷移して更新するのは一手間かかるため、
一覧の目玉アイコンをクリックすると切り替えられるようにしました。
7/12
無し
=> Add: ページ一覧でメニュー表示の切り替えを行う

resources/views/core/cms_frame_edit.blade.php
フレーム編集画面のフレームデザインプルダウン
選んだときにどうような色になるかが、設定してみないとわかりませんでした。
プルダウンの選択肢に色付けすることで、設定せずとも色がわかるようにしました。
有り / 無し
=> Update: フレームデザインの色を選択時にわかるようにする

app/Plugins/Manage/UserManage/UserManage.php, database/migrations/2022_07_06_160526_migrate_deleted_user_from_group_users.php
* https://github.com/opensource-workshop/connect-cms/issues/1357
なし
なし
なし
有り
=> 【グループ管理】グループ参加人数が一覧とグループ詳細ページで違う不具合修正

resources/views/plugins/manage/user/groups.blade.php, resources/views/plugins/manage/user/login_history.blade.php, resources/views/plugins/manage/user/regist.blade.php, resources/views/plugins/manage/user/user_edit_tab.blade.php, resources/views/plugins/manage/user/user_manage_tab.blade.php
ユーザ変更画面から、グループ参加・ログイン履歴に飛べますが、上部メニューに隠れてわかりずらかったです。
そのため、上部メニューの下にタブメニューとして、ユーザ変更・グループ参加・ログイン履歴　を切り出しました。
なし
なし
なし
なし
=> change: ユーザ管理, ユーザ変更画面の関連機能をタブメニューとして分離

app/Plugins/Manage/GroupManage/GroupManage.php, resources/views/plugins/manage/group/edit.blade.php
グループ管理のグループ変更画面でユーザの参加・不参加を変更できるようにしました。
ユーザー名で検索して参加させる利用者を選択できます。
一覧のマイナスボタンを押下して不参加にすることができます。
7/29（金）
無し
=> Add:グループの ユーザー追加、削除機能

resources/views/plugins/manage/page/role.blade.php
件名通り
なし
* https://github.com/opensource-workshop/connect-cms/pull/1359
なし
なし
=> change: ページ管理, ページ権限設定の参加ユーザに、グループ変更画面へのリンク付ける

app/Traits/Migration/MigrationTrait.php
=> bugfix: NC2移行, キャビネットのファイル名・コメントのタブ混入除去 

app/Plugins/User/Codestudies/CodestudiesPlugin.php, app/Plugins/User/Photoalbums/PhotoalbumsPlugin.php
* #1382 
動作確認済み
なし
* https://github.com/opensource-workshop/connect-cms/issues/1374
* https://github.com/opensource-workshop/connect-cms/pull/1376#discussion_r928361627
なし
なし
=> 【コードスタディ・フォトアルバム】複数ファイルダウンロードでAllowed memory sizeエラー時のtmpファイル削除対応

resources/views/plugins/manage/page/migration_order.blade.php, resources/views/plugins/manage/page/page_edit.blade.php, resources/views/plugins/manage/page/page_edit_tab.blade.php, resources/views/plugins/manage/page/page_manage_tab.blade.php, resources/views/plugins/manage/page/role.blade.php
件名通り
なし
* https://github.com/opensource-workshop/connect-cms/pull/1366
なし
なし
=> change: ページ管理, ページ変更画面の関連機能をタブメニューとして分離

.env.example, app/Console/Commands/Migration/Version.php, config/version.php, resources/views/plugins/manage/index/index.blade.php
画面とバッチで出力可能にしました。
.env で表示可否を決定しています（SHOW_CC_VERSION）
バージョン1.0.0がリリースされるまでは、隠しておきます。
``` bash
php artisan command:version
```
有り / 無し
=> OW-1010 Add: Connect-CMSのバージョンを出力する

app/Traits/Migration/MigrationTrait.php, app/Traits/Migration/sample/migration_config/migration_config.sample.ini
=> add: NC2移行, オプション設定で「すべての会員をデフォルトで参加させる」ルームを、グループ作成して「メンバーシップページ」で移行できるようにする

resources/views/plugins/user/menus/tab_flat/menus.blade.php
* https://github.com/opensource-workshop/connect-cms/issues/1348
なし
なし
なし
なし
=> change: 【メニュー】タブフラットの表示見直し

resources/views/plugins/manage/user/list.blade.php
NC2移行で各権限に対応するために、１ルーム⇒５グループ（パブリック_コンテンツ管理者, パブリック_モデレータ, パブリック_編集者 等）で移行するよう修正しました。
その結果、管理者等で参加グループが多くなりました。
参加グループが多いと、ユーザ一覧画面のグループ名表示が長すぎるため、見直したいと思ってます。
なし
なし
なし
なし
=> change: ユーザ管理, 一覧のグループ表示見直し

resources/views/plugins/user/photoalbums/default/index.blade.php
フォトアルバムで画像の拡大表示の不具合（スマホでの画面はみだし、画像のマウスカーソル） #1394
の修正です。
* https://github.com/opensource-workshop/connect-cms/issues/1394
無し
=>  [フォトアルバム]画像拡大表示の不具合修正（スマホでの画面はみだし、画像のマウスカーソル）

resources/views/plugins/user/databases/table/databases.blade.php
スマホで見た時に、表が画面幅を飛び出してしまい、表示がおかしいので対応しました。
軽微な改修なので急ぎません。
永原が自分のサイトで使っていて、あれ？となったものです。
画面はこんな感じになります。
無し
=> [データベース]tableテンプレートでのスマホ時の表横スクロールとタイトル行の改行禁止

resources/views/core/cms_frame_header.blade.php
* https://github.com/opensource-workshop/connect-cms/issues/1397
なし
なし
なし
なし
=> bugfix: コア, フレームデザインでprimaryの時、フレームタイトルが空だと歯車ボタンが見ずらい不具合修正

app/Plugins/Manage/SystemManage/SystemManage.php
* https://github.com/opensource-workshop/connect-cms/issues/1401
* MAIL_FROM_NAMEがダブルクォートで囲われてなかったら、ダブルクォートを付けるように修正
* これでMAIL_FROM_NAMEがダブルクォートで囲われてなくても、画面から変更可能になりました。
なし
なし
なし
なし
=> bugfix: システム管理, メール設定画面でMAIL_FROM_NAMEがダブルクォートで囲われていないと変更されない不具合修正

composer-dev.json, composer-dev.lock, composer.json, composer.lock
laravel-nestedsetがLaravel8に対応していませんでした。
そのためlaravel-nestedsetを5.xから6.xにアップグレードして対応しました。
なるはや
* #1413 
無し
=> [掲示板]掲示板投稿でシステムエラーとなる事象を修正しました

.github/release.yml
GitHubのリリースノート自動生成で利用する設定ファイルを追加しました。
https://docs.github.com/en/repositories/releasing-projects-on-github/automatically-generated-release-notes#configuration-options
有り / 無し
=> [コア]リリースノート自動生成で利用する設定ファイルを追加しました

app/Plugins/User/UserPluginBase.php, resources/views/core/cms_frame.blade.php, resources/views/errors/error_inframe.blade.php
プラグイン内で、プログラムミスなどによるシステムエラーが発生した場合、画面全体をシステムエラー表示にするのではなく、フレーム内にエラー表示を収める対応がありましたが、プラグインのactionを指定した処理では、画面全体のシステムエラーになっていたため、修正しました。
原因は、フレーム内にエラー表示時のバグで、フレーム内にエラー表示時にさらにシステムエラーが発生していたため「不要なエラーログ」が出て、原因のログが埋もれて原因が発見しずらい状態でした。
```log
[previous exception] [object] (Error(code: 0): Call to undefined method ErrorException::getStatusCode() at C:\\projects\\localhost\\htdocs\\storage\\framework\\views\\c3f41a66229ee7aac3e7c046275a5701e3f20ef3.php:7)
[stacktrace]
#0 C:\\projects\\localhost\\htdocs\\vendor\\laravel\\framework\\src\\Illuminate\\Filesystem\\Filesystem.php(107): require()
#1 C:\\projects\\localhost\\htdocs\\vendor\\laravel\\framework\\src\\Illuminate\\Filesystem\\Filesystem.php(108): Illuminate\\Filesystem\\Filesystem::Illuminate\\Filesystem\\{closure}()
#2 …
```
=> core, プラグイン内のシステムエラー表示をフレーム内に納める対応の不具合修正

app/Enums/CabinetFrameConfig.php, app/Plugins/User/Cabinets/CabinetsPlugin.php, resources/views/plugins/user/cabinets/default/frame.blade.php, resources/views/plugins/user/cabinets/default/index.blade.php
キャビネットに以下の項目を追加しました。
- ダウンロード件数
- 更新者
- 作成者
※灰色のバッジがダウンロード件数
9/20くらい
無し
=> [キャビネット]表示項目を追加しました（ダウンロード件数、更新者、作成者）

app/Plugins/User/Learningtasks/LearningtasksPlugin.php
https://github.com/opensource-workshop/connect-cms/commit/f767ac64da13fb50f715186952ac33544c563e54
上記でデグレードが発生していたので修正しました。
本日10/5リリースしたいな。
なし
なし
なし
=> [課題管理] どの科目をクリックしても同じ科目が表示される不具合修正 OW-1419

app/Plugins/User/Forms/FormsPlugin.php, resources/views/plugins/user/forms/default/forms_edit_form.blade.php, resources/views/plugins/user/forms/default/forms_thanks.blade.php
本登録後のメッセージにHTMLを記述したい要望があり、その対応です。
※ HTMLが使える旨のメッセージを追記しました。
軽微な改修なので急ぎません
なし
なし
無し
=> [フォーム] 本登録後のメッセージをHTMLで記述できるようにする

resources/views/plugins/user/databases/card_02/databases_detail.blade.php, resources/views/plugins/user/databases/default/databases_detail.blade.php, resources/views/plugins/user/databases/design-table-dl/databases_detail.blade.php
件名通り
なし
* https://github.com/opensource-workshop/connect-cms/issues/1207
なし
なし
=> [データベース] default・カードタイプ２列・design-table-dlテンプレートの詳細画面で公開終了・公開前のタグ表示が抜けていたので追加

app/Plugins/User/UserPluginBase.php, resources/views/plugins/user/databases/card_02/databases.blade.php, resources/views/plugins/user/databases/card_02/databases_detail.blade.php, resources/views/plugins/user/databases/default/databases.blade.php, resources/views/plugins/user/databases/default/databases_detail.blade.php, resources/views/plugins/user/databases/design-table-dl/databases_detail.blade.php
* 未ログインで「公開終了」した記事、投稿日前の記事は表示しない。
* ログイン済みなら、「公開終了」した記事、投稿日前の記事は表示。
* 未ログインの動きは変更なし。
* ログイン済みで記事の編集権限ないなら、「公開終了」した記事、投稿日前の記事は表示しない。
* 承認者でも「公開終了」「公開前」タグを表示に見直し。
* コンテンツ管理者、モデレータ
* 全記事編集できるため、「公開終了」した記事、投稿日前の記事は表示。
* 承認者
* 「公開終了」した記事、投稿日前の記事も承認する事が設定できるため、表示。
* 編集者
* 自分以外の記事を編集できないため、自分の「公開終了」した記事、投稿日前の記事は表示。
* 他人の「公開終了」した記事、投稿日前の記事は、表示しない。
* 未ログイン
* 「公開終了」した記事、投稿日前の記事は、表示しない。
10/24の週中。けど急いでないです。
* https://github.com/opensource-workshop/connect-cms-ideas/issues/135
* https://github.com/opensource-workshop/connect-cms/issues/1207
なし
無し
=> [データベース] 編集者は自分以外の「公開終了」した記事、投稿日前の記事は表示しない

app/Plugins/User/Blogs/BlogsPlugin.php
=> [ブログ] 一時保存で続きを表示する関連が登録されない不具合修正

database/migrations/2022_10_24_111729_change_delivery_request_opacs_books_lents.php
OpacAPIで貸出処理を行った時、配送希望フラグを渡してこない。
配送希望フラグは、デフォルト値設定なしで、NULL入力NGである為、save処理でこける。
配送希望フラグのデフォルト値を0(希望なし)に設定
なるはや
#1469 
有り
=> [Opac]OpacBookLents 配送希望フラグのデフォルト値を設定し、OpacAPIからの貸出に対応する

app/Traits/Migration/MigrationTrait.php
NC2会員項目のシステム固定値と、会員の作成日時を移行していなかったため
軽微な改修なので急ぎません、10/27（1週間）を目処にできれば
https://github.com/opensource-workshop/connect-cms/issues/1466
無し
=> [NC2移行]会員項目のNC2システム固定値と会員の作成日時を移行できるようにしました

resources/views/plugins/user/cabinets/default/index.blade.php
- ファイルが多い場合に個別に選択するのが大変だった為、１アクションで全選択ON/OFF指定ができる機能を追加しました。
- 付随してjQuery処理の一部共通化（削除押下時のファイル名列挙時に参照するリストの更新処理＆ボタンの活性化制御）を行いました。
今日から2週間程度で11/2（水）。急がないです。
https://github.com/opensource-workshop/connect-cms-ideas/issues/136
なし
なし
=> [キャビネット]一覧のコンテンツ選択チェックボックスの全選択機能を追加しました。

resources/views/layouts/app.blade.php
* cc_configsは app\Http\Middleware\ConnectInit.php で処理しているため、基本resources/views/layouts/app.blade.phpではセットされます。
* けど、.envのAPP_KEYに"xxxx"とダブルクォートで囲むと`php artisan key:generate`しても変換されない＋APP_DEBUG=falseで、cc_configsなしでここに到達する。
その時に、正しいエラーログでエラー内容を追えるようにするため、cc_configsを初期化する。（初期化しないとcc_configs変数なしエラーになり本来のエラーにたどり着かない）
なし
なし
なし
なし
=> [コア] 本来のエラーログを出力するため、cc_configs未セットなら初期化するよう対応

app/Plugins/Manage/IndexManage/IndexManage.php, resources/views/plugins/manage/index/index.blade.php
storageディレクトリのパーミッション設定ミスをしても管理画面で気付けるように対応
なし
なし
なし
なし
=> [管理画面] storageに書き込み権限がなければエラーメッセージを管理画面に表示する

app/Traits/Migration/MigrationTrait.php
公式掲示板より
* https://connect-cms.jp/plugin/bbses/show/106/233/684#frame-233
なし
* https://github.com/opensource-workshop/connect-cms/pull/1384
なし
なし
=> [nc2移行] ブログのタイトル・続きを読む・続きを隠すのタブ混入除去

app/Traits/Migration/MigrationTrait.php
* [change: [nc2移行] 管理者グループの対象をコンテンツ管理者からシステム管理者に変更](https://github.com/opensource-workshop/connect-cms/commit/db38587d64af93cf62cc7d033af4513e415da29a)
* [bugfix: [nc2移行] 事務局ユーザにページとユーザの管理権限漏れていたため追加](https://github.com/opensource-workshop/connect-cms/commit/bf2f741a128c21bcf93a52b42b3c8cf73543aaca)
なし
なし
なし
無し
=> [nc2移行] 管理者グループの対象をコンテンツ管理者からシステム管理者に変更

app/Enums/DatabaseNoticeEmbeddedTag.php, app/Plugins/User/Databases/DatabasesPlugin.php
* NC3移行の汎用DBのメール通知移行に関連して、データベースプラグインのメール通知の埋め込みタグに、全項目タグを追加しました。
* 関連修正
* [add: [データベース] メール通知の埋め込みに既に対応していたbodyを追加](https://github.com/opensource-workshop/connect-cms/pull/1487/commits/58c0dbeb9d62f68d2ce2445f5ad28611d9efb797)
なし
なし
なし
なし
=> [データベース] メール通知の埋め込みタグに全項目タグを追加

app/Models/Migration/Nc2/Nc2User.php, app/Models/Migration/Nc3/Nc3MailSetting.php, app/Models/Migration/Nc3/Nc3MultidatabaseContent.php, app/Models/Migration/Nc3/Nc3MultidatabaseFrameSetting.php, app/Models/Migration/Nc3/Nc3MultidatabaseMetadata.php, app/Models/Migration/Nc3/Nc3User.php, app/Traits/Migration/MigrationNc3ExportTrait.php, app/Traits/Migration/MigrationTrait.php, app/Traits/Migration/sample/migration_config/migration_config_nc3.sample.ini
* [nc3移行] 汎用DB移行に対応
* 関連修正
* [add: [移行インポート] データベースのメール通知設定・権限設定のインポートに対応](https://github.com/opensource-workshop/connect-cms/pull/1488/commits/ec430ed6875794789ca6c5ac2ce0eeb3d98447f0)
* [add: [移行インポート] データベースの任意項目のソート移行に対応](https://github.com/opensource-workshop/connect-cms/pull/1488/commits/cf1602aa05d3a25eaae3e0af94efc90a28c77194)
* [add: [移行インポート] データベースの行データで末尾空行があってもエラーにならないよう対応](https://github.com/opensource-workshop/connect-cms/pull/1488/commits/60eab085debd98e13b8e7981973e51f2893027cc)
* [add: [nc2移行] 汎用DBのメール通知設定/権限設定のエクスポートに対応](https://github.com/opensource-workshop/connect-cms/pull/1488/commits/2d4f1dc7d8f3b817b4e84aa58d6901740d0617de)
* [change: [nc2移行] 汎用DBの絞り込み項目の移行条件をnc2仕様に見直し](https://github.com/opensource-workshop/connect-cms/pull/1488/commits/cf6c7d03867f778dab4acea2f85 …
=> [nc3移行] 汎用DB移行に対応

app/Plugins/User/Slideshows/SlideshowsPlugin.php, resources/lang/ja/validation.php, resources/views/plugins/user/slideshows/default/slideshows_edit.blade.php, resources/views/plugins/user/slideshows/default/slideshows_edit_row_add.blade.php
PDFを画像に変換してスライドショーに登録します。
当機能の利用にはPDF Upload APIの実装＆設定が必要です。
https://github.com/opensource-workshop/connect-cms/wiki/PDF-Upload-API
有り / 無し
=> [スライドショー]PDFのアップロードに対応しました

resources/views/plugins/user/bbses/default/index.blade.php, resources/views/plugins/user/bbses/default/show.blade.php, resources/views/plugins/user/bbses/default/thread_show.blade.php, resources/views/plugins/user/bbses/no_frame/show.blade.php, resources/views/plugins/user/bbses/no_frame/thread_show.blade.php
[掲示板]枠なしテンプレートで詳細画面表示時のタイトル表示重複を改善しました
軽微な改修なので急ぎません
https://github.com/opensource-workshop/connect-cms/issues/1474
無し
=> [掲示板]枠なしテンプレートで詳細画面表示時のタイトル表示重複を改善しました

.env.example, app/Http/Controllers/Core/UploadController.php, app/Http/Middleware/ResponseHeader.php, config/connect.php, resources/views/layouts/app.blade.php
サイトの負荷軽減対策です。
* 画像キャッシュ対応
* 対応内容
* 公開されている画像等, /file/css/999.cssをキャッシュする。対象は以下。
* /file/{id?}
* /file/user/{dir}/{filename}
* /file/css/{page_id?}.css
* 公開されない画像等はキャッシュしない。（例：ログインが必要なページ、メンバーシップページ、パスワードページの画像）
* PDFはキャッシュしない。（Googleから参照されたPDFの削除依頼がそこそこあるため）
* その他はキャッシュしない。
* .env設定
* キャッシュは.envのCACHE_CONTROLで設定可能
* 設定例）`CACHE_CONTROL="max-age=604800"`
* .envのEXPIRESは廃止（キャッシュしない設定にのみ使われていたため）
* 関連修正
* /file/{id?}, /file/user/{dir}/{filename}のヘッダー対応
* Content-Disposition の最適化
* Etag対応
* /file/css/{page_id?}.css に変更あったらクエリストリングで即時反映
追加機能の改修なので急ぎません
* #1429
* 調査したら [キャッシュコントロール・ミドルウェア](https://readouble.com/laravel/8.x/ja/responses.html#cache-control-middleware) はファイルキャッシュには使えなかった。 https://github.com/opensource-workshop/connect-cms/issues/1429#issuecomment-1299792273
* …
=> [コア] (サイトの負荷軽減対策) 画像キャッシュ対応

app/Traits/Migration/MigrationTrait.php
公式掲示板より https://connect-cms.jp/plugin/bbses/show/106/233/687#frame-233
* [bugfix: [nc2移行] フォーム移行エクスポートでダブルクォーテーションを移行できるように対応、また改行の移行に対応](https://github.com/opensource-workshop/connect-cms/commit/80988c45678369604c695b5eb014db5ea16f2e84)
* 関連修正
* [bugfix: [nc2移行] ユーザ移行エクスポートで任意項目でダブルクォーテーションを移行できるように対応](https://github.com/opensource-workshop/connect-cms/commit/2110d2e76fe569b31b991b46df5c1737c3c5b44a)
なし
なし
* https://stackoverflow.com/questions/6684800/syntax-error-using-parse-ini-file-when-files-values-contain-exclamation-poin
なし
=> [nc2移行] フォーム移行エクスポートでダブルクォーテーションを移行できるように対応、また改行の移行に対応

app/Traits/Migration/MigrationTrait.php
* https://github.com/opensource-workshop/connect-cms/pull/1496
改行＋ダブルクォーテーションでエラーが発生したため、修正見直し
なし
なし
なし
なし
=> [nc2移行] ユーザ移行エクスポートで任意項目でダブルクォーテーションを移行できるように対応2

app/Http/Controllers/Core/UploadController.php, app/Models/Common/Page.php
* https://github.com/opensource-workshop/connect-cms/pull/1482
上記対応の不具合修正です。
症状：画像キャッシュを設定しても、画像キャッシュされない。
対応：ページの表示制限（パスワード設定等）の設定ありなら、キャッシュしないように修正
なし
なし
なし
なし
=> [コア] 画像キャッシュを設定しても、画像キャッシュされない不具合修正

app/Plugins/Manage/CodeManage/CodeManage.php, app/Plugins/Manage/UserManage/UserManage.php, app/Plugins/User/Databases/DatabasesPlugin.php, app/Plugins/User/Learningtasks/LearningtasksPlugin.php
* https://github.com/opensource-workshop/connect-cms/issues/1417
* 関連修正
* [bugfix: PHP8.1でインポートが出来ないバグ修正](https://github.com/opensource-workshop/connect-cms/pull/1509/commits/d52b6e39d3668ffcfb7ffc6ff95730e32c0dac9e)
* ユーザ管理インポート
* データベースインポート
* 課題管理インポート
エラーになっていた、php8.1のコード管理インポート処理でエラーが出なくなりました。
https://github.com/opensource-workshop/connect-cms/actions/runs/3560808368/jobs/5981133473
（ブランチを指定してduskテスト。指定したブランチはどっかでわかるのかな？）
なし
なし
なし
なし
=> PHP8.1でインポートが出来ないバグ修正

app/Models/Migration/Nc3/Nc3BlockSetting.php, app/Models/Migration/Nc3/Nc3Calendar.php, app/Models/Migration/Nc3/Nc3CalendarEvent.php, app/Models/Migration/Nc3/Nc3RoomRolePermission.php, app/Traits/Migration/MigrationNc3ExportTrait.php, app/Traits/Migration/MigrationTrait.php, app/Traits/Migration/sample/migration_config/migration_config.sample.ini, app/Traits/Migration/sample/migration_config/migration_config_nc3.sample.ini
* [add: [nc3移行エクスポート] カレンダー移行対応](https://github.com/opensource-workshop/connect-cms/pull/1511/commits/76caafb0d53a77d08f16e26701004cffb61188f1)
* [add: [移行インポート] カレンダーの権限設定を個別設定で移行できるよう対応](https://github.com/opensource-workshop/connect-cms/pull/1511/commits/4ccfc20b98e25131d6436226e7c509642ae62a5e)
* 関連修正
* [change: [nc2移行] カレンダー権限設定移行の汎用化対応](https://github.com/opensource-workshop/connect-cms/pull/1511/commits/c9bda080de576b2a71e36142c9ac1d56096e2d22)
* [change: [nc2移行] カレンダー予定の移行カラム見直し](https://github.com/opensource-workshop/connect-cms/pull/1511/commits/36ea856550753fb83e05a2df3766c32df8f9ab7b)
* [refactor: [nc2移行エクスポート] カレンダーの表示方法移行の処理見直し](https://github.com/opensource-workshop/connect-cms/pull/1511/commits/bf8597e411e7713150e69cbc5fb2fb875055f0a6)
* [delete: [nc2移行エクスポート] …
=> [nc3移行] カレンダーの移行対応（nc3-migrateブランチにマージ）

app/Models/Migration/Nc3/Nc3Category.php, app/Models/Migration/Nc3/Nc3ReservationEvent.php, app/Models/Migration/Nc3/Nc3ReservationLocation.php, app/Models/Migration/Nc3/Nc3ReservationLocationsApprovalUser.php, app/Models/Migration/Nc3/Nc3ReservationLocationsReservable.php, app/Traits/Migration/MigrationNc3ExportTrait.php, app/Traits/Migration/MigrationTrait.php, app/Traits/Migration/sample/migration_config/migration_config_nc3.sample.ini
* [add: [nc3移行エクスポート] 施設予約の移行対応](https://github.com/opensource-workshop/connect-cms/pull/1512/commits/e115a727609884baa55a9995afc36e2a03226491)
* [add: [移行インポート] importPluginReservations() メールの承認通知/承認済み通知設定の移行対応](https://github.com/opensource-workshop/connect-cms/pull/1512/commits/21c581e15f8b03a1f04cf155bf76d844fedbb661)
* [change: [nc2移行] 施設予約のカテゴリなし移行の見直し＆施設予約のカレンダー初期表示の移行設定を汎用的に見直し](https://github.com/opensource-workshop/connect-cms/pull/1512/commits/a238671023a2de50c0e3053c4ad89a0fd833b534)
なし
なし
なし
無し
=> [nc3移行] 施設予約の移行対応（nc3-migrateブランチにマージ）

app/Traits/Migration/MigrationNc3ExportTrait.php, app/Traits/Migration/MigrationTrait.php
* [bugfix: [nc3移行エクスポート] カレンダーの予定/施設予約の予定の状態移行ミス修正](https://github.com/opensource-workshop/connect-cms/commit/052ed5bbfe045a794046d132c9c487659fa2b442)
* [bugfix: [nc3移行エクスポート] 施設予約の予定時間の移行ミス修正](https://github.com/opensource-workshop/connect-cms/pull/1516/commits/bad87a82698c6da94ce6dd0d3b4de181e17ffa29)
* [bugfix: [移行インポート] 施設予約の予定の連絡先/補足が移行されないバグ修正](https://github.com/opensource-workshop/connect-cms/pull/1516/commits/e3683b984c9b44c8c6f5f755f6e0346a485b5176)
* 関連修正
* [change: [移行インポート] カレンダーで予定空のエラー時のコンソールログ表示を修正](https://github.com/opensource-workshop/connect-cms/commit/3df8245b49902cf212653138f46aa8c2e1e1ac51)
* [change: [移行インポート] 施設予約で予定空は、エラーではなく通知のみのため、ログ出力レベルを修正](https://github.com/opensource-workshop/connect-cms/commit/5982cad91379d1db48eff304ef72c09f075accd1)
なし
なし
なし
なし
=> [nc3移行] カレンダーの予定の状態/施設予約の予約の状態・予定時間・連絡先・補足の移行ミス修正（nc3-migrateブランチにマージ）

app/Models/Migration/Nc3/Nc3PhotoAlbumDisplayAlbum.php, app/Models/Migration/Nc3/Nc3PhotoAlbumFrameSetting.php, app/Models/Migration/Nc3/Nc3PhotoAlbumPhoto.php, app/Traits/Migration/MigrationNc3ExportTrait.php, app/Traits/Migration/MigrationTrait.php, app/Traits/Migration/sample/migration_config/migration_config_nc3.sample.ini
* [add: [nc3移行エクスポート] フォトアルバムの移行対応](https://github.com/opensource-workshop/connect-cms/commit/75dd0ae8d7a594c0797f520e785353c80de41bdc)
* [change: [nc3移行エクスポート] configのNC3_EXPORT_UPLOADS_PATH取得をメソッド化](https://github.com/opensource-workshop/connect-cms/commit/0340e0871aa67df7fd9c0226b6d6756dc83df889)
* [add: [移行インポート] フォトアルバムのアルバム/写真の並び順移行に対応](https://github.com/opensource-workshop/connect-cms/commit/884accb23e7acf77e8bda3222845ad2fa8be9b5f)
* 関連対応
* [change: [nc2移行] カウンターの表示形式の移行の汎用化対応](https://github.com/opensource-workshop/connect-cms/pull/1521/commits/f30955186655829d55b9250c84a7d45f4926c324)
* [change: [nc2/nc3移行] フォトアルバムの移行カラムを nc2_upload_id → upload_id に変更](https://github.com/opensource-workshop/connect-cms/pull/1521/commits/0c2dfa737a4a03581bb00d2d709babf1d316dcc7)
* [refactor: …
=> [nc3移行] フォトアルバムの移行対応（nc3-migrateブランチにマージ）

app/Traits/Migration/MigrationNc3ExportTrait.php, app/Traits/Migration/MigrationTrait.php
=> [nc3移行エクスポート] バグ修正-汎用DBのアップロードデータが無かった場合に対応,  施設予約で必須のブロックデータがない場合、施設予約は移行しない対応, [nc2/nc3移行エクスポート] ウィジウィグのタブコード混入を除去対応（nc3-migrateブランチにマージ）

app/Plugins/User/Reservations/ReservationsPlugin.php
件名通り
* 00:00-24:00 毎日（終了）指定日で繰り返すと＋１日される。
* 00:00-23:55 毎日（終了）指定日で繰り返すと＋１日されない。
なし
なし
なし
なし
=> [施設予約] 終日毎日繰り返し＋終了日指定だと＋１日予約される不具合修正

.env.example, config/connect.php, resources/views/layouts/app.blade.php
.envでログインのリンク名を変更できます。
```.env
LOGIN_STR="ログイン"
```
```.env
LOGIN_STR="管理者ログイン"
```
なし
なし
なし
なし
=> [コア] ログインのリンク名を.envで変更可能にする OW-1598

app/Plugins/User/Forms/FormsPlugin.php
* https://github.com/opensource-workshop/connect-cms/issues/1542 
なし
なし
なし
なし
=> [フォーム] 登録時にファイル型データをアップロードした状態で入力チェックエラーになると500エラーになる不具合の修正

app/Plugins/User/Reservations/ReservationsPlugin.php
* https://github.com/opensource-workshop/connect-cms/pull/1532
* 1/10 9:00-18:00の予約を 指定日1/11までしても１日(1/10のみ)しか予約されない。上記の修正ミス。
なし
なし
なし
なし
=> [施設予約] 終了指定日の前日までしか予約されないバグの修正

resources/views/core/cms_frame_header.blade.php
件名通り
コンテンツの後ろに歯車ボタンが回り込んでしまって押せない
歯車ボタン押せる
なし
なし
なし
なし
=> [フレーム] 左エリアにフレームタイトル空で「このページのみ表示する」を設定すると、歯車ボタンが押せなくなる不具合修正 OW-1656

resources/views/auth/registe_form.blade.php
自動ユーザ登録時に説明文章があると、autofocusが邪魔をして、説明文が初期状態で表示されなくなるため、省きます。
無し
=> 自動ユーザ登録時に説明文章があると、autofocusが邪魔をして、説明文が初期状態で表示されなくなるため、省きます。

public/css/connect.css
長いサイト名の場合、ナビバー右にあるログインリンク等が表示されなくなっていました。
この場合にサイト名が省略されるようにしました。
スマホ表示ではすでに省略する対応が入っていましたが、このPRで改善されます。
v1.4.1以前は、ウィンドウ幅に関係なく幅固定で省略していました。
そのため、余白があるにもかかわらず、省略されてしまっていました。
このPRにより余白部分が少なくなります。
修正前
修正後
無し
=> [サイト全体]ナビバーのサイト名が長い場合にウィンドウ幅に合わせて省略するようにしました

app/Models/Core/FrameConfig.php
App\Models\Core\FrameConfig::saveFrameConfigs()
チェックボックスを複数選択して入力するUIの場合、リクエストパラメータは配列となります。
この場合、パイプ区切りの値で登録するようにしました。
無し
=> [コア]FrameConfigの登録処理について、複数選択（チェックボックス）の設定値に対応しました

app/Plugins/Manage/SystemManage/SystemManage.php, app/Plugins/User/UserPluginBase.php, resources/views/plugins/manage/system/system_tab.blade.php, tests/Browser/Manage/SystemManageTest.php
* https://github.com/opensource-workshop/connect-cms/issues/1563
上記の対応しました。
システム管理＞エラーログ設定画面は、 .envで「APP_DEBUG=false」 時に、一般プラグインで500エラーが起こった際のエラーログを記録できるようにする設定です。
しかし、Laravel自体のログ機能と被っているため、①エラーログ設定画面と②Laravel自体のログ設定が異なると、２つのログができ、あれ？っとなります。
そのためログを「②Laravel自体のログ設定」に１本化しました。
（補足：システム管理＞エラーログ設定画面は、デイリーでログをローテーションする機能がなかった昔に作られて、今はLaravel自体にログのローテーション機能があるため、エラーログ設定画面が既に不要かと思われます。）
要相談
* Q. ログ出力を１本化するため、エラーログ設定画面は廃止。と思ったけど、どうか。
* Q. エラーログ設定画面のメソッド, log()のphpdocに、マニュアル生成の`@method_title` `@method_desc` `@method_detail` を残したが、メソッドをコメントアウトしてもマニュアルに生成されちゃうか？
* https://github.com/opensource-workshop/connect-cms/pull/1564/files#diff-c8da8f9f17f26ef65e465d84837b4cdd90ba298b5d516d5a619e24f60c231bdaR109-R111
* マニュアル生成されちゃうならマニュアル生成のphpdocのタグ削除する方向。
* （追記）マニュアル生成の該当メソッドをコメントアウトで対応 …
=> [システム管理] エラーログ設定画面を廃止して、出力ログを１本化する OW-1684

app/Plugins/Manage/SiteManage/SiteManage.php, tests/Browser/Manage/SiteManageTest.php
サイト管理の言語設定の削除処理が漏れていたので追加しました。
要望が上がってきているわけではないので、急ぎません。
マニュアル作成時に気付きました。
https://github.com/opensource-workshop/connect-cms/issues/1059
無し
=> [サイト管理] 言語設定の削除処理が漏れていたので追加しました。

public/robots.txt
同一ドメインでnetcommons2からConnect-CMSに移行時、nc2の短縮URL＋画像（?action=common_download_main&upload_id=9999）の場合、google image bot等の画像botがクロールし続ける問題に対応。
robots.txtに除外対象を追記して対応しました。
nc2の画像URL例
http://example.com/230lkhjfakl-19?action=common_download_main&upload_id=9999
↓
ConnectのURL例
http://example.com/230lkhjfakl-19?action=common_download_main&upload_id=9999
※ Connectは移行しても短縮URLを開けるため、302を返す。しかしnc2画像（?action=common_download_main&upload_id=9999）はないけど302が返されるため、google image bot等は何度もアクセスしてくる。
なし
なし
なし
なし
=> [robots.txt] 同一ドメイン＋nc2の短縮URLでnc2->cc移行時のgoogle image bot等へのインデックス除外対応

app/Models/Migration/Nc2/Nc2QuestionnaireAnswer.php, app/Models/Migration/Nc2/Nc2QuestionnaireBlock.php, app/Models/Migration/Nc2/Nc2QuestionnaireChoice.php, app/Models/Migration/Nc2/Nc2QuestionnaireQuestion.php, app/Traits/Migration/MigrationNc3ExportTrait.php, app/Traits/Migration/MigrationTrait.php, app/Traits/Migration/sample/migration_config/migration_config.sample.ini, resources/views/plugins/user/forms/default/forms_edit_form.blade.php
* [nc2移行] アンケートの移行対応
* 関連修正
* [add: フォーム編集画面, メール件名・フォーマットの登録日時の埋込コードの説明が抜けていたため追加](https://github.com/opensource-workshop/connect-cms/pull/1587/commits/15404f7070eda7611413d53c8029ae2e4b4bdd52)
* [change: nc2フォーム移行, メールの埋込コードはエクスポート側で置換するよう見直し](https://github.com/opensource-workshop/connect-cms/pull/1587/commits/9e65a6666f7f39e728040414c263d8fd721b6ad7)
* [change: nc3フォーム移行エクスポート, メールの埋込コード見直し](https://github.com/opensource-workshop/connect-cms/pull/1587/commits/a9606f6cee9ce173d9d95a0e63ab1c536059a3b7)
* [bugfix: nc3動画移行, redo=on時に移行用ファイルの削除が機能してなかった不具合修正](https://github.com/opensource-workshop/connect-cms/pull/1587/commits/e58b50163fe4e2c92b1da47aebb04db46aa246b0)
* [bugfix: nc3動画移行, フォトアルバムと動画のidが被ると移行できない不具合対応](https://github.com/opensource-workshop/connect-cms/pull/1587/commits/2213d …
=> [nc2移行] アンケートの移行対応

app/Enums/FormMode.php, app/Models/Migration/Nc2/Nc2QuestionnaireAnswer.php, app/Models/Migration/Nc2/Nc2QuestionnaireBlock.php, app/Models/Migration/Nc2/Nc2QuestionnaireChoice.php, app/Models/Migration/Nc2/Nc2QuestionnaireQuestion.php, app/Models/User/Forms/Forms.php, app/Plugins/User/Forms/FormsPlugin.php, app/Traits/Migration/MigrationNc3ExportTrait.php, app/Traits/Migration/MigrationTrait.php, app/Traits/Migration/sample/migration_config/migration_config.sample.ini, config/app.php, database/migrations/2023_02_18_214425_add_form_mode_and_can_view_inputs_moderator_from_forms.php, database/migrations/2023_02_18_214941_change_column_name_from_forms_columns.php, resources/views/plugins/common/wysiwyg.blade.php, resources/views/plugins/user/forms/default/aggregate.blade.php, resources/views/plugins/user/forms/default/forms_confirm_tandem.blade.php, resources/views/plugins/user/forms/default/forms_edit.blade.php, resources/views/plugins/user/forms/default/forms_edit_form.blade.php, resources/views/plugins/user/forms/default/forms_edit_row2.blade.php, resources/views/plugins/user/forms/default/forms_edit_row2_add.blade.php, resources/views/plugins/user/forms/default/forms_edit_row_add.blade.php, resources/views/plugins/user/forms/default/forms_edit_row_detail.blade.php, resources/views/plugins/user/forms/default/forms_list_buckets.blade.php, resources/views/plugins/user/forms/default/forms_list_inputs.blade.php, resources/views/plugins/user/forms/default/index_tandem.blade.php
* フォームを拡張してアンケート機能を追加
* 関連修正
* [add: フォーム, 登録一覧画面のフォーム選択へボタンの余白間隔調整](https://github.com/opensource-workshop/connect-cms/pull/1586/commits/f78f667a9061b69e3917fcdf266f35727f0bc0f4)
* [add: フォーム, 登録一覧に総件数の表示追加](https://github.com/opensource-workshop/connect-cms/pull/1586/commits/f644e9d9436ed05213a8f98fc499c4d4996170a8)
* [add: wysiwyg, 改行を p タグから br タグに変更するオプション設定 use_br を追加](https://github.com/opensource-workshop/connect-cms/pull/1586/commits/e0917bc04f8da7b721ed3f01a671e2b78d07a97b)
* https://github.com/opensource-workshop/connect-cms/pull/1587
・フォームモード（フォームorアンケートの切替）と、モデレータの集計結果のON・OFF設定を追加しました。
（フォームの場合でも、モデレータの集計結果のONにすれば、集計結果（登録一覧）を確認・ダウンロードできます）
・アンケートモードの場合
　・項目名の登録は、当画面（項目設定）で出来ます。
　・項目名の更新は、項目詳細画面で出来ます。項目設定では表示のみです。
　・項目名のwisywig対応しました。
　・編集エリアを２行で表示するようにしました。 …
=> [フォーム] フォームを拡張してアンケート機能を追加 OW-1663

.env.example, config/session.php
ブラウザを閉じたら、自動ログアウトさせる機能を.envで設定できるように対応しました。
expire_on_close=trueにすると、SESSION_LIFETIMEは無制限になります。
なし
なし
* https://laracasts.com/discuss/channels/laravel/expire-on-close-not-working
なし
=> [コア] sessionのexpire_on_closeを.envで設定できるように対応

composer-dev.json, composer-dev.lock, composer.json, composer.lock
LaravelのHTTPファサードを利用可能にするため、composer.jsonとcomposer.lockを更新しました。
https://readouble.com/laravel/8.x/ja/http-client.html
無し
=> [コア]利用パッケージにGuzzleを追加しました

composer-dev.json, composer-dev.lock, composer.json, composer.lock
LaravelのHTTPファサードを利用可能にするため、composer.jsonとcomposer.lockを更新しました。
Connect-CMS 2 にマージするPRです。
#1581 
無し
=> [コア]利用パッケージにGuzzleを追加しました（Connect-CMS 2）

resources/lang/ja/validation.php
入力チェック（validate）で`Rule::in(['はい']);`としたときの、エラーメッセージ内の選択肢がまぎれてしまって判りずらいと感じたので、見直しました。
なし
なし
なし
なし
=> [エラーメッセージ] 入力チェックのinのエラーメッセージ内の選択肢を強調するように見直し

.env.example, app/Models/Common/Numbers.php, app/Plugins/Manage/NumberManage/NumberManage.php, app/Plugins/PluginBase.php, config/connect.php, resources/views/plugins/manage/number/number.blade.php
[連番管理] 連場クリア機能の無効化設定を、`.env`に追加しました。
.envに無効化プラグイン名を設定する事で、対象プラグインの連番クリア機能を無効化できます。
.env
```env
PLUGIN_NAME_TO_DISABLE_SERIAL_NUMBER_CLEAR="forms"
```
formsプラグインの連番クリアボタン（赤いボタン）は押せなくなります。
* [bugfix: 連番, updated_id,updated_nameの自動セット対応](https://github.com/opensource-workshop/connect-cms/pull/1597/commits/e270dba16db4cc0f2e3c51e76fb91c27131602a3)
なし
なし
なし
なし
=> [連番管理] 連番クリア機能の無効化設定追加

resources/views/plugins/user/databases/design-table-dl/databases.blade.php, resources/views/plugins/user/databases/table/databases.blade.php
=> [データベース] 検索結果０件時にメッセージ出ない不具合修正（table, design-table-dlテンプレート）

resources/views/plugins/user/forms/default/forms_edit_form.blade.php
フォームの新規作成時に「データ保存」を忘れるケースの防止のため。
基本的には保存することが多いと思います。
そのため、基本は保存する。外したい時は外せるように。という方針にしたいための修正です。
トラブルが増える前にマージしたいです。
無し
=> [フォーム]新規登録の場合は「データ保存」はonにしておく対応を入れました。

resources/views/plugins/user/blogs/default/blogs_input.blade.php
* 動作に変更ない修正です。
* 詳細
* ブログ記事の一時保存のredirect_pathと、登録時のredirect_pathは同じ指定が正解です。
* しかし、一時保存のJSでセットしてる redirect_path は、登録も更新もeditに飛ぶ指定でしたが、JSでミスっていて redirect_path がセットされず、結果として正しい動きになっていました。
* （誤）`form_blogs_posts{{$frame_id}}.redirect_path = "{{url('/')}}/plugin/blogs/edit/{{$page->id}}/{{$frame_id}}#frame-{{$frame->id}}";`
* （正）`form_blogs_posts{{$frame_id}}.redirect_path.value = "{{url('/')}}/plugin/blogs/create/{{$page->id}}/{{$frame_id}}#frame-{{$frame_id}}";`
*  `.value` が抜けてた。
* 紛らわしいため、一時保存でredirect_pathをセットしている個所を削除しました。
なし
なし
なし
なし
=> [ブログ] 一時保存のredirect_pathは保存時と同一のredirect_pathでよいため、セットできてないredirect_pathのJSセット指定行を削除

app/Plugins/User/Forms/FormsPlugin.php, resources/views/plugins/common/error_messages.blade.php
* 他プラグインでも、フォームで使用していた任意のエラーメッセージテンプレートを使用したいため、commonに移動します。
* フォームコピーであるデータベースプラグインでも利用見込みありです。
なし
なし
なし
なし
=> [テンプレート] 任意のエラーメッセージテンプレートをcommonに移動

app/Plugins/User/Databases/DatabasesPlugin.php
* 項目設定で複数年月型に更新する時、キャプションが空だったらキャプションを自動設定する機能が動いていない不具合修正
* 関連修正
* 上記設定時にキャプションを自動設定したメッセージを表示。
なし
なし
なし
なし
=> [データベース] 項目設定で複数年月型に更新する時、キャプションが空だったらキャプションを自動設定する機能が動いていない不具合修正

app/Plugins/Manage/SiteManage/SiteManage.php, resources/lang/en/messages.php, resources/lang/ja/messages.php, resources/views/plugins/manage/site/document.blade.php, resources/views/plugins/manage/site/pdf/check_link.blade.php
- 先のPR対応の追加修正です。https://github.com/opensource-workshop/connect-cms/pull/1594
- 動作に影響はなく見出し名の統一のみです。
- 統一対象
- 目次
- 該当ページの見出し名
- 画面上（追加出力の選択部）の見出し名
- また「リンクチェック」のみだと内容の詳細がイメージしづらい指摘があったので、見出し名を「固定記事内のURLリンク切れチェック」に統一しています。
なし
https://github.com/opensource-workshop/connect-cms/pull/1594
なし
なし
=> [サイト管理]サイト設計書のリンク切れチェック出力で見出し名の平伏を合わせました

app/Plugins/User/Tabs/TabsPlugin.php
タブプラグインが共通エリア（ヘッダー・フッター・左・右）に配置された時、タブを配置したページ以外へと遷移すると、タブが表示されなくなる。
【タブを配置したページ：左エリア】
【ページ遷移した後：左エリア】
共通エリア（ヘッダー・フッター・左・右）に配置された時には、現表示page_idではなく、tab自身に設定されたpage_idを参照するように修正した。
タブプラグインを共通エリアに以外に配置された事が考慮されていなかった為、共通エリアにタブプラグインを配置すると、配置したページ以外へ遷移すると、タブが消える。
不具合対応なので急ぎたいです
なし
なし
なし
=> [タブ]共通エリアに配置された時、タブが表示されなくなるバグを修正しました。

app/Plugins/User/Databases/DatabasesPlugin.php
初期表示を隠す判定でページ名の変数名が間違ってました。
フレームごとにページ名を独自に採番してたので、独自採番のページ名を用いて判定するように修正しました。
#1614
無し
=> [データベース]初期表示オフの時に検索結果のページ番号を押すと検索結果が表示されない事象を修正しました

app/Plugins/Manage/UserManage/UserManage.php, resources/views/plugins/manage/user/original_role.blade.php
役割設定画面の定義名は、半角英数字のみでした。
定義名という事で、ダッシュ(-)、下線(_)も使いたくなったため、対応しました。
なし
なし
なし
なし
=> [役割設定] 定義名にダッシュ(-)、下線(_)も入力可能にする

app/Enums/UserColumnType.php, app/Http/Controllers/Auth/RegisterController.php, app/Http/Controllers/Auth/RegistersUsers.php, app/Models/Core/Section.php, app/Models/Core/UserSection.php, app/Plugins/Manage/UserManage/UserManage.php, app/Plugins/Manage/UserManage/UsersTool.php, app/User.php, database/migrations/2023_03_13_004114_create_sections_table.php, database/migrations/2023_03_13_004115_create_user_sections_table.php, resources/views/auth/registe_form_input_affiliation.blade.php, resources/views/plugins/manage/user/edit_column_detail.blade.php, resources/views/plugins/manage/user/edit_columns.blade.php, resources/views/plugins/manage/user/include_edit_column_row.blade.php, resources/views/plugins/manage/user/list_include_value.blade.php, resources/views/plugins/manage/user/list_search_affiliation.blade.php
ユーザーの任意項目に所属型を追加しました。
- ユーザ項目に所属型の選択肢を追加
- 所属は1ユーザー1つまで
- ユーザ項目に所属型は1つのみ設定可能
- 所属する組織には名称とコードを設定できる
- 所属に関する物理テーブルが作られる（sections, user_sections）
- より強い制約を持つ 
- 所属情報を設定しているユーザーがいると、所属型のユーザ項目を削除できない
- 組織に所属するユーザがいると当該組織を削除できない
オプション機能で業務的な機能で利用する想定です。
- 他のユーザ項目と同様にusers_input_colsのデータを登録するようにしました。
- 他機能と同様のデータ登録とすることで、既存処理への影響を減らしました。
有り
=> [ユーザ管理]ユーザー項目「所属型」を追加しました

app/Enums/ImageMimetype.php, app/Models/Common/Uploads.php, app/Models/User/Photoalbums/PhotoalbumContent.php, resources/views/plugins/manage/uploadfile/index.blade.php, resources/views/plugins/user/photoalbums/default/index_image.blade.php
- ~欲しかったから~ 自web運営でアップロードファイルの削除を行う時にクリックしないと中身がわからず、開く->確認->削除（所望と違ってたら残念な気持ちになる）が煩雑だった為、補助機能としてアップロードファイル一覧にサムネイル画像を追加しました。
- pdf.jsを使えばフロント側でpdfのサムネイルも表示できそうでしたが、~そっ閉じ~ アセット系ファイルのコンパイル整備が未完の為、別の機会で検討します。
- 併せて、リファクタリング（メソッドのアクセサ化）を行っています。
3/31（金）
https://github.com/opensource-workshop/connect-cms-ideas/issues/143
なし
なし
=> [アップロードファイル管理] アップロードファイル一覧にサムネイル画像を追加しました

.env.example, app/Models/User/Databases/DatabasesColumnsSelects.php, app/Plugins/User/Databases/DatabasesPlugin.php, config/connect.php
betaのうちは独自にテンプレートを作成して利用する想定です。
絞り込み項目に該当する件数を表示する機能です。
.env.sampleを参考に以下の項目を.envに追加してください。
`DATABASES_SHOW_SEARCH_COLUMN_COUNT=true`
default から databases.blade.php と databases_include_ctrl_head.blade.php をコピーして独自テンプレートを作成します。
databases_include_ctrl_headをincludeする部分をテンプレート名に修正します。
```
{{-- ヘッダー部分 --}}
@include('plugins.user.databases.{template-name}.databases_include_ctrl_head')
```
`$columns_select->registered_count`に件数が設定されています。
任意の形式で出力することが可能です。
無し
=> [データベース]絞り込み項目の登録済み件数を表示する機能を追加しました(beta)

app/Plugins/User/Databases/DatabasesPlugin.php
件名通り。
mysql5.6はサポート対象外ですが、気になったため修正しました。
mysql5.7では影響ない修正かと思います。
なし
なし
なし
なし
=> [データベース] DB選択でmysql5.6でエラーに対応（SQLSTATE[42000]: Syntax error or access violation: 1055 'cc_db.frames.bucket_id' isn't in GROUP BY）

app/Plugins/User/Databases/DatabasesPlugin.php, resources/views/plugins/user/databases/card_02/databases_detail.blade.php, resources/views/plugins/user/databases/default/databases_detail.blade.php, resources/views/plugins/user/databases/design-table-dl/databases_detail.blade.php
検索結果1ページ目の詳細で一覧へボタンを押すと、初期表示を隠す判定に引っかかり検索結果が表示されていませんでした。
一覧へボタン押下時のパラメータにページ数=1を渡すように修正しました。
これにより、初期表示を隠す判定にかからなくなります。
#1632 
無し
=> [データベース]詳細画面の一覧へボタンで戻ると検索結果が表示されない事象を修正しました

app/Plugins/User/Databases/DatabasesPlugin.php, resources/views/plugins/user/databases/default/databases_include_ctrl_head.blade.php
検索処理がPOSTでリクエストされるため、ブラウザバックするとフォーム再送信の確認が表示されます。
そこで、GETにリダイレクトすることで、フォーム再送信の確認が表示されないように修正しました。
#1634
無し
=> [データベース]詳細画面でブラウザバックするとフォーム再送信の確認が表示される事象を修正しました

app/Plugins/User/Databases/DatabasesPlugin.php, database/migrations/2023_04_05_175111_add_show_download_count_to_databases_columns_table.php, database/migrations/2023_04_05_175112_add_show_download_button_to_databases_columns_table.php, resources/views/plugins/user/databases/default/databases_edit_row_detail.blade.php, resources/views/plugins/user/databases/default/databases_include_detail_value.blade.php, resources/views/plugins/user/databases/default/databases_include_value.blade.php
ファイル項目にダウンロードボタンとダウンロード件数を表示できるようにしました。
項目設定より表示要否を選択できます。
有り
=> [データベース]ファイル項目のダウンロード件数、ダウンロードボタンを表示できるようにしました

app/Models/User/Databases/DatabasesInputs.php, app/Plugins/User/Databases/DatabasesPlugin.php, database/migrations/2023_04_13_115632_add_categories_id_to_databases_inputs_table.php, resources/views/plugins/user/databases/databases_frame_edit_tab.blade.php, resources/views/plugins/user/databases/default/databases_confirm.blade.php, resources/views/plugins/user/databases/default/databases_input.blade.php, resources/views/plugins/user/databases/default/databases_list_categories.blade.php
データベースの1データにカテゴリを設定できるようにしました。
データベースプラグインのテンプレートでカテゴリを表示するところはありません。
用途として以下を想定しています。
- 新着情報プラグインでカテゴリを表示する
- サイト内検索でカテゴリ名を入力したときにヒットする（今後対応予定）
1.  データベースメニューのカテゴリからカテゴリを追加する
2. データの登録画面、編集画面からカテゴリを選択し、登録する
カテゴリ設定画面
編集画面
ASAP
有り
=> [データベース]データにカテゴリを設定する機能を追加しました

app/Plugins/User/Databases/DatabasesPlugin.php, database/migrations/2023_04_17_154545_add_sort_download_count_to_databases_columns_table.php, resources/views/plugins/user/databases/default/databases_edit_row_detail.blade.php, resources/views/plugins/user/databases/default/databases_edit_view.blade.php, resources/views/plugins/user/databases/default/databases_include_ctrl_head.blade.php
データベースでファイル型の項目に関して、ファイルのダウンロード件数で並べ替えをする機能です。
- [項目設定] 並べ替え指定 > 昇順＆降順、昇順のみ、降順のみ のいずれかにチェック
- [項目設定] ダウンロード件数で並べ替え > 使用するにチェック
- [表示設定] 並べ替え項目の表示 > 各カラム設定にチェック
- [項目設定] 並べ替え指定 > 昇順＆降順、昇順のみ、降順のみ のいずれかにチェック
- [項目設定] ダウンロード件数で並べ替え > 使用するにチェック
- [表示設定] 初期表示での並び順 > ｛項目名｝ダウンロード数（昇順）、｛項目名｝ダウンロード数（降順）を選択する
有り
=> [データベース]ファイルのダウンロード件数で並べ替えをする機能を追加しました

resources/views/plugins/user/databases/default/databases_confirm.blade.php
=> [データベース]カテゴリ未選択時に確認画面でエラーになる問題を修正しました

app/Plugins/User/Databases/DatabasesPlugin.php
#1639 の修正です。
categoriesを結合した結果、databases_inputsが取得されていなくなっていました。
並べ替えを設定していると問題なく表示されていました。
無し
=> [データベース]詳細内容が表示されない問題を修正しました

app/Plugins/User/Databases/DatabasesTool.php
複数単語のAND検索の仕方を見直しました。
なし
なし
なし
なし
=> [データベース] 複数単語で検索した場合の結果表示が遅い問題に対応

resources/views/core/cms_frame_header.blade.php
フレームに対して
- 初期状態を非表示にする。
- このページのみ表示する。
- このページのみ表示しない。
- データがない場合にフレームも非表示にする。
上記ステータスを付与していた時、プラグイン管理の権限がないユーザにも、フレームのステータスラベルが見えてしまっていた。
なので、フレームのステータスラベルは
- ログインしている
- プラグイン管理者権限を持っている
- プレビュー画面ではない
の時のみ表示するように修正した。
不具合対応なので急ぎたいです
なし
なし
なし
=> [フレーム]ログインしていると、権限に関係なくフレームステータスラベルが見えてしまう不具合を修正しました。

app/Enums/FormsRegisterTargetPlugin.php, app/Models/User/Faqs/FaqsPosts.php, app/Models/User/Forms/Forms.php, app/Plugins/User/Forms/FormsPlugin.php, config/app.php, database/migrations/2023_04_20_140941_add_target_frame_ids_to_forms_table.php, resources/views/plugins/user/forms/default/forms_edit_form.blade.php, resources/views/plugins/user/forms/default/forms_list_inputs.blade.php
フォームの登録データを掲示板、FAQ、ブログへ連携する機能を追加しました。
登録一覧から選択して、他プラグインへ登録することができます。
登録後は一時保存状態になります。自由に編集した後、投稿を公開できます。
問合せフォームに登録された内容を、回答内容とともにブログなどで公開します。
情報を公開することで、広く知識を共有することができます。
他プラグインへの転記を自動化することで、作業効率を向上することができます。
- [フォーム設定] 他プラグイン連携 > チェックON
- [フォーム設定] 対象ページ - フレーム > 連携先のフレームをチェックする
有り
=> [フォーム]登録データを掲示板、FAQ、ブログへ連携する機能を追加しました

app/Plugins/User/Reservations/ReservationsPlugin.php
=> [施設管理] 翌月表示後に施設の詳細ボタン押下で「施設の詳細データが取得できませんでした」エラー対応 OW-1861

app/Plugins/User/Bbses/BbsesPlugin.php, app/Plugins/User/Blogs/BlogsPlugin.php, app/Plugins/User/Contents/ContentsPlugin.php, app/Plugins/User/Databases/DatabasesPlugin.php, app/Plugins/User/Faqs/FaqsPlugin.php, app/Plugins/User/Searchs/SearchsPlugin.php, resources/views/plugins/user/searchs/default/searchs_result.blade.php
検索結果に本文を表示するようにしました。
いままでの検索結果にはタイトルしか出ておらず、目的のページまで辿り着きにくくなっていました。
本文を併せて表示することで、ページ遷移せずとも内容がわかるように改善しました。
データベースプラグインの検索では、本文として出したい項目に本文指定の設定が必要です。
設定は以下から行えます。
**項目設定> 項目詳細設定 > 新着情報等の設定 > 本文指定にチェックをする**
無し
=> [サイト内検索]検索結果に本文を表示するようにしました

resources/views/plugins/user/databases/default/databases_include_ctrl_head.blade.php
絞り込み機能を表示しない設定になっていても、並べ替えが有効になっていると、絞り込みプルダウンが表示される不具合を修正しました。
修正後は表示設定に従って、表示されます。
- 絞り込み機能の表示 = 表示しない
- 並べ替え項目の表示 = チェックあり
有り / 無し
=> [データベース]絞り込みOFF＋並べ替えONで絞込みプルダウンが表示される不具合を修正しました

resources/views/plugins/user/searchs/default/searchs_edit_search.blade.php
https://github.com/opensource-workshop/connect-cms/issues/1667
なし
https://github.com/opensource-workshop/connect-cms/issues/1667
なし
なし
=> [サイト内検索] 設置画面（新規/変更）バリデートエラー時にラジオ項目の入力値巻き戻りを修正

app/Traits/Migration/MigrationNc3ExportTrait.php, app/Traits/Migration/MigrationTrait.php, app/Traits/Migration/sample/migration_config/migration_config.sample.ini, app/Traits/Migration/sample/migration_config/migration_config_nc3.sample.ini
* [add: NC3移行, リンク切れチェックOFFできるよう設定追加](https://github.com/opensource-workshop/connect-cms/commit/5924bce7e1a92206fbff11022d635b97e7e522d3)
* 初期値：なし（コメントアウト）＝リンク切れチェックしない
* 設定例： `check_deadlink_nc3 = true`
* [add: nc3移行, NC3.2.0より古いバージョンで移行する (beta)オプション設定追加](https://github.com/opensource-workshop/connect-cms/pull/1676/commits/8e809aa8e361b7073dd4749b92c09144f7dfb5b6)
* 初期値：なし（コメントアウト）＝ nc3.2.0より新しい
* 設定例： `older_than_nc3_2_0 = true`
* [add: nc移行インポート, 強制的にレイアウト上書きオプションに対応](https://github.com/opensource-workshop/connect-cms/pull/1676/commits/82d6d4b681b65cd66d63e2d4b93c95194bf95fca)
* 初期値：なし（コメントアウト）
* 設定例： `cc_import_force_layouts["0001"] = "1|1|0|1`
* ※ cc_import_force_layouts["インポートページのディレクトリNo"] = "ヘッダー|左|右|フッター"、 1:表示,0:非表示
* [bugfix: nc3移行エクスポート, …
=> [移行ツール] NC3移行バグ修正

app/Plugins/Manage/UserManage/UserManage.php, resources/views/auth/registe_form.blade.php
* [add: ユーザ管理, 最後のシステム管理者保持者は削除させない](https://github.com/opensource-workshop/connect-cms/commit/80ebd00dd5fe5d357fe4eb7e7a7453c9c4b67ed3)
* [add: ユーザ管理, 最後のシステム管理者保持者から編集でシステム管理者権限を外せない様に入力チェック追加](https://github.com/opensource-workshop/connect-cms/commit/0e5af63a66bc66909e061f116fae6bc1cd8ef86c)
なし
なし
なし
なし
=> [ユーザ管理] 最後のシステム管理者保持者は削除させない・システム管理者権限を外させない対応

app/Plugins/Manage/UserManage/UserManage.php, app/User.php, resources/views/plugins/manage/user/list.blade.php
* うっかりシステム管理者の編集・削除をさせないために、システム管理者権限持ちユーザはシステム管理者のみ編集可に見直しました。
* システム管理者権限ありユーザは、システム管理者権限ありユーザの編集・削除できます。
* ユーザ管理権限あり（システム管理者権限なし）ユーザは、システム管理者権限ありユーザー以外を編集・削除できます。
NetCommons3移行の関連対応で、NetCommons3には下位権限のユーザ（サイト管理者）は、上位権限のユーザー（システム管理者）をユーザ編集できない機能があり、その移植になります。
なし
なし
なし
なし
=> [ユーザ管理] システム管理者権限持ちユーザはシステム管理者のみ編集可

app/Traits/Migration/sample/migration_config/migration_config_nc3.sample.ini
件名通り
下記設定漏れがあった。
app\Traits\Migration\sample\migration_config\migration_config_nc3.sample.ini
```ini
[plugins]
cc_import_plugins[] = "slideshows"
[frames]
import_frame_plugins[] = "slideshows"
```
なし
なし
なし
なし
=> [移行ツール] nc3の移行設定サンプルからslideshowsの移行設定に抜けがあったため追記

resources/views/plugins/user/forms/default/forms_confirm_column_checkbox.blade.php, resources/views/plugins/user/forms/default/forms_confirm_column_radio.blade.php, resources/views/plugins/user/forms/default/forms_confirm_column_select.blade.php
任意の選択肢１個だけのフォームを作り、未選択で確認画面にいくと500エラーになる不具合の修正
通常のフォームの使い方であれば、複数の項目設定と必須項目があると思います（＋php8のサーバ環境）ので、まず遭遇しない不具合かと思います。
なし
* https://github.com/opensource-workshop/connect-cms/issues/1200
* PHP8.0がリリースされたので新機能全部やる - Qiita
https://qiita.com/rana_kualu/items/c110cb244c3ee38c6859#removed-ability-to-use-array_key_exists-with-objects
なし
=> [フォーム] php80＋任意の単一選択１つのみのフォーム＋未選択で確認画面にいくと500エラーになるバグ修正

resources/views/layouts/app.blade.php
下記エラー画面が出ないように修正しました。
例）スライドショーの編集画面を開いた後に、プレビューモードを選択
プレビューモードになるが、スライドショーの編集画面部分に403（権限がありません）エラーが表示される。
なし
なし
なし
なし
=> [コア] バケツ編集画面でプレビューモードにすると権限なしエラーが出るバグ修正

app/Traits/Migration/MigrationNc3ExportTrait.php, app/Traits/Migration/sample/migration_config/migration_config_nc3.sample.ini
件名通りです。
app\Traits\Migration\sample\migration_config\migration_config_nc3.sample.ini
```ini
[menus]
; --- エクスポート
; メニューのフレームタイトルを消さずに残す場合 true を指定
export_frame_title = true
```
なし
なし
なし
なし
=> [移行ツール] nc3移行エクスポートでメニューのフレームタイトルを残す設定を追加

app/Traits/Migration/MigrationNc3ExportTrait.php, app/Traits/Migration/sample/migration_config/migration_config_nc3.sample.ini
件名通りです。
app\Traits\Migration\sample\migration_config\migration_config_nc3.sample.ini
```ini
[pages]
; --- エクスポート
; 全ページレイアウトを出力する場合 true を指定
export_full_page_layout = true
```
なし
なし
なし
なし
=> [移行ツール] nc3移行エクスポートでページレイアウトを全件出力する設定を追加

app/Models/User/Blogs/Blogs.php, app/Plugins/User/Blogs/BlogsPlugin.php, database/migrations/2023_06_12_102116_add_use_view_count_spectator_from_blogs.php, resources/views/plugins/user/blogs/default/blogs.blade.php, resources/views/plugins/user/blogs/default/blogs_edit_blog.blade.php, resources/views/plugins/user/blogs/default/include_view_count_spectator.blade.php, resources/views/plugins/user/blogs/designbase/blogs.blade.php
* 表示件数リストを表示する設定を追加して、設定ON時に観覧者が表示件数を変更できるように対応しました。
* 関連対応
* [change: ブログの設定画面, ラジオでON・OFF時、左側はOFFで統一する](https://github.com/opensource-workshop/connect-cms/commit/5f89b65e3c02cc290a90945cd6e43e0747e28d18) https://github.com/opensource-workshop/connect-cms/issues/737
なし
なし
なし
なし
=> [ブログ] 観覧者に表示件数リストを表示する設定追加

resources/views/auth/registe_form.blade.php
* https://github.com/opensource-workshop/connect-cms/pull/1681
* 上記の関連修正です。
* システム管理者以外は、自身でシステム管理者に昇格できないように対応しました。
* システム管理者権限付与は、システム管理者のみ行えます。
なし
なし
なし
なし
=> [ユーザ管理] システム管理者権限付与は、システム管理者のみ可に修正

app/Traits/Migration/MigrationNc3ExportTrait.php
* [add: [移行ツール] NC3移行エクスポートでNC3.2.0より古いバージョンで移行するONの時、ページ順番を移行後に再現するよう対応](https://github.com/opensource-workshop/connect-cms/commit/26f726c502439b061ceb10511361728fef4e7bcd)
* [bugfix: [移行ツール] NC3移行エクスポートでNC3.2.0より古いバージョンで移行するONの時、違うページがトップページとして移行されるバグ修正](https://github.com/opensource-workshop/connect-cms/commit/b6f46190c9d1122b642840961b5de1726f441f90) 
なし
なし
なし
なし
=> [移行ツール] NC3移行エクスポートでNC3.2.0より古いバージョンで移行するONの時、ページ順番を移行後に再現するよう対応

resources/views/vendor/pagination/bootstrap-4.blade.php
* [bugfix: コア, ページ送り（paginate）が中央エリアでもフレーム幅以上になるとはみ出るため、flex-wrapで折り返しするよう対応](https://github.com/opensource-workshop/connect-cms/commit/e132fc6a205b5b6fa5b12c362865713a7f9dc419) 
* 関連修正
* [bugfix: コア, ページネーションでmd表示の時に不要な...が表示されないように修正](https://github.com/opensource-workshop/connect-cms/commit/ea587230c64fe9375fcab3a4c801f359fac86678)
* 前提
* 左右エリアを表示
* ブログの表示件数１件
* ブログ件数１５件程度
* 前提
* ブログの表示件数１件
* ブログ件数１５件程度
* ５ページ目を表示
* md幅（≥768px）でサイト表示
なし
なし
* flex-wrap
https://getbootstrap.jp/docs/4.2/utilities/flex/#wrap
* Medium ≥768px
https://getbootstrap.jp/docs/4.2/layout/grid/#grid-options
なし
=> [ページ送り] ページ送り（paginate）が中央エリアでもフレーム幅以上になるとはみ出るため、flex-wrapで折り返しするよう対応

app/Traits/Migration/MigrationNc3ExportTrait.php, app/Traits/Migration/MigrationTrait.php
=> [移行ツール] NC3のFAQを移行した時、カテゴリの絞り込み機能を常時ONで移行する

app/Traits/Migration/MigrationNc3ExportTrait.php, app/Traits/Migration/MigrationTrait.php
* [add: [移行ツール] インポート時にNC3のブログ-一覧-カテゴリ指定リンクをConnectのリンクに自動置換対応](https://github.com/opensource-workshop/connect-cms/commit/5ecc85cfb0300b906001b6709aa80ba893c137f4)
* 関連修正
* [delete: [移行ツール] NC3移行エクスポート, /cabinets/cabinet_files/download/ のリンク置換は、インポート側で既に行っていたため、現在動いてないプログラムを削除](https://github.com/opensource-workshop/connect-cms/commit/9bc276cfd1aebaa652c08cf7eddc74f07703a341) 
なし
なし
なし
なし
=> [移行ツール] インポート時にNC3のブログ-一覧-カテゴリ指定リンクをConnectのリンクに自動置換対応

app/Traits/Migration/sample/migration/@update/pages/0007/page.ini
wikiの[Migration-from-NC2](https://github.com/opensource-workshop/connect-cms/wiki/Migration-from-NC2#インポートファイルの上書き設定) ページを修正・調査していたところ、移行ツールの`@update`はframeのみ対応が判明したため、対応していないサンプルの@updateのpage.iniは削除しました。
なし
なし
なし
なし
=> [移行ツール] @updateのpage.iniは@update処理に対応してないためサンプル削除

app/Traits/Migration/MigrationNc3ExportTrait.php
=> [移行ツール] NC3エクスポート時にサイト全体ーヘッダーー非公開のお知らせの、非公開が公開されて移行されるバグ修正

app/Plugins/Manage/HolidayManage/HolidayManage.php, resources/views/plugins/manage/holiday/index.blade.php
件名通りです。
<body>
<table><tr><th colspan="14">holidays</th></tr><tr><th>id</th><th>holiday_date</th><th>holiday_name</th><th>holiday_key</th><th>status</th><th>created_id</th><th>created_name</th><th>created_at</th><th>updated_id</th><th>updated_name</th><th>updated_at</th><th>deleted_id</th><th>deleted_name</th><th>deleted_at</th></tr><tr class="odd"><td>1</td><td>2026-05-06</td><td>お休み</td><td>2026-05-06</td><td>0</td><td>&nbsp;</td><td>admin3</td><td>2023-06-17 11:56:09.000</td><td>&nbsp;</td><td>&nbsp;</td><td>2023-06-17 11:56:09.000</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td></tr>
</table>
なし
なし
* https://github.com/opensource-workshop/connect-cms/wiki/Holidays
なし
=> [祝日管理] 2025年を登録しても一覧に表示できないバグ修正 OW-1907

app/Traits/Migration/MigrationNc3ExportTrait.php, app/Utilities/Migration/MigrationUtils.php
* [add: 移行ツール, NC3移行エクスポート時、Wysiwyg内HTMLからNC3絵文字を削除](https://github.com/opensource-workshop/connect-cms/commit/5a8eba216edb4df2f460326054ffea4081ab1ba5)
* 関連修正
* [refactor: 移行ツール, cleaningContent()の正規表現の条件見直し（[]内でor条件の場合|は不要）](https://github.com/opensource-workshop/connect-cms/commit/5f5d847541c924e6e816186504642ae4cea214d8)
なし
なし
なし
なし
=> [移行ツール] NC3移行エクスポート時、Wysiwyg内HTMLからNC3絵文字を削除

resources/views/plugins/user/searchs/default/searchs_result.blade.php
サイト内検索プラグイン、defaultテンプレートについて、以下のバグを修正しました。
- タイトルが空の場合、何も表示されなかった為、「(無題)」と表示されるようにしました。
- タイトルがウィジウィグ項目の場合（※データベース等）、タグが出力されてしまっていたのを、stripするようにしました。
- タイトルがウィジウィグ項目だった場合、入力された情報が全て出てしまう為、本文と同じく160byteで途切れるようにしました。
- 登録日を非表示にした場合、カテゴリも非表示になってしまっていたので、表示されるようにしました。
使いにくかった以下の部分を修正しました。
- dlタグが、検索結果全てに対して１つしかつかなかったが、1検索結果につき1つ付くようにしました。
- 上記修正したdlタグに、searchs-result-rowクラス名を付与しました。
- 本文項目のddタグのクラス名がsearchs-result-bodyだったので、項目名と同じsearchs-result-postbodyに変更しました。
- タイトルと登録名が表示されるddタグに、searchs-result-posttitleクラス名を付与しました。
- 罫線が表示されるようにしました。
- 各プラグインからの検索結果に付与されている「plugin_name」の値について、「show_page_frame_post」と「show_page」以外が来た時のelseがなかった為、付与しました。
- 検索結果全体を囲むdivタグに、searchs-result-bodyクラス名を付与しました。
【PC】
【スマホ】
お時間のある時に
なし
なし
なし
=> [サイト内検索]defaultテンプレート、タイトル表示バグ、カテゴリ表示バグ、クラス名付与の修正を行いました。

app/Utilities/Migration/MigrationUtils.php
=> [移行ツール] NC3移行エクスポート時にNC3絵文字の削除で不要に前後の文字や画像を消す不具合を修正

app/Models/Common/Numbers.php, app/Plugins/PluginBase.php
プラグインのコントローラー以外からも連番取得できるように、連番取得functionをModelに移動しました。
既存のフォームの採番に影響がでない事を確認しました。
なし
なし
なし
なし
=> [連番管理] 連番取得functionの汎用化

app/Enums/NoticeEmbeddedTag.php, resources/views/plugins/common/description_frame_mails_common.blade.php
=> [メールの埋め込みタグ] 共通のメール設定画面の説明を任意に変更できるように対応

app/Enums/FormAccessLimitType.php, app/Models/User/Forms/Forms.php, app/Plugins/User/Forms/FormsPlugin.php, config/app.php, database/migrations/2023_06_26_094629_add_access_limit_type_form_password_from_forms.php, resources/views/plugins/user/forms/default/forms_edit_form.blade.php, resources/views/plugins/user/forms/default/index_password.blade.php
* [フォーム] 閲覧パスワード設定追加
* 関連修正
* フォーム設定画面、設定ON・OFFで設定項目のおりたたみ対応
* フォーム, ラジオでON・OFF時、左側はOFFで統一する #737
なし
なし
なし
あり
=> [フォーム] 閲覧パスワード設定追加

app/Plugins/Api/ApiPluginBase.php, config/connect.php
- SlackAppからのリクエスト検証用の共通処理を追加
- SlackAppからのリクエスト検証を行う為、Slackの秘密トークン保持用設定値を追加しました。
なし
なし
https://belltree.life/slack-verification/
なし
=> [API共通] Slackリクエスト検証の共通処理を追加＆connect設定値にSLACK_SIGNING_SECRETを追加

app/Models/Core/FrameConfig.php
* FrameConfigの値（配列指定の値）を新着で使う場合があり、値が `|` のままだと使えない（カンマにしたい）ため、修正対応しました。
* 通常は `|` のままなので、今までの処理に影響がでないように修正しました。
* またFrameConfigの値を保存時（saveFrameConfigs()）、保存する値が配列の場合に空要素があると、不要な空要素まで保存していたため、取り除きました。
なし
なし
なし
なし
=> [FrameConfig] saveFrameConfigs()時、checkbox_separatorを指定できるように対応, また配列の空要素を削除するよう対応

app/Http/Controllers/Core/DefaultController.php, app/Plugins/User/UserPluginBase.php
* 既存プラグインにオプションのテンプレートを追加できるよう対応しました。
* resources\views\plugins_option配下に、既存プラグインのディレクトリを再現して、配下にテンプレートを配置すると、フレーム編集画面から設定できます。
* （例：新着）
* 新着のオプションディレクトリを作成 resources\views\plugins_option\user\whatsnews\
* その配下にオプションテンプレート`seminar`を配置
* resources\views\plugins_option\user\whatsnews\seminar\whatsnews.blade.php
* フレーム編集のテンプレートに`seminar`出てくる。
なし
なし
なし
なし
=> [コア] 既存プラグインにオプションテンプレートを追加できるよう対応

app/Models/Migration/Nc3/Nc3Frame.php, app/Traits/Migration/MigrationNc3ExportTrait.php, app/Traits/Migration/sample/migration_config/migration_config_nc3.sample.ini
* NC3移行で、NC3側のページ左エリアで下記表示をする。
* サイト全体　　：空　　　　（非表示）
* パブリック共通：空　　　　（非表示）
* ルーム共通　　：メニュー１（表示）
* 当ページのみ　：メニュー２（非表示）
* 移行すると、非表示のメニュー２が移行される不具合を修正。
* 関連修正
* [change: 移行ツール, NC3移行設定の全ページレイアウトを出力するを初期値trueに変更](https://github.com/opensource-workshop/connect-cms/pull/1744/commits/ac3ae8b88af411fe3085e311e2081fd534e9a10b)
なし
なし
なし
なし
=> [移行ツール] NC3移行エクスポートのトップページ・ルームトップのヘッダ・フッター・左・右エリアのフレーム出力見直し

app/Traits/Migration/MigrationTrait.php, app/Utilities/Migration/MigrationUtils.php
=> [移行ツール] NC2移行エクスポート時、NC2絵文字を自動削除

app/Traits/Migration/MigrationTrait.php, app/Traits/Migration/sample/migration_config/migration_config.sample.ini
=> [移行ツール] NC2移行エクスポート時、メニューのフレームタイトルを消さずに残すオプション追加

app/Enums/CsvCharacterCode.php, app/Models/Common/Page.php, app/Models/Core/Configs.php, app/Plugins/Manage/CodeManage/CodeManage.php, app/Plugins/Manage/UserManage/UserManage.php, app/Plugins/User/Databases/DatabasesPlugin.php, app/Plugins/User/Learningtasks/LearningtasksPlugin.php, app/Utilities/Csv/CsvUtils.php, resources/views/auth/registe_form.blade.php, resources/views/plugins/manage/reservation/edit.blade.php, resources/views/plugins/manage/reservation/index.blade.php, tests/Browser/User/ReservationsPluginTest.php
php8.1になり、標準関数の引数に型指定がつき（trim、str_replace、nl2br、strip_tags等）、チェックがきつくなったことで nullを渡すとエラーが起きてました。
修正対応しました。
* 対応
* [bugfix: [管理画面系] php8.1対応](https://github.com/opensource-workshop/connect-cms/pull/1751/commits/b8a1fce3dd47eca87caadb28db68dfc843e9bd3b)
* [bugfix: [ユーザ管理] インポート時のphp8.1エラー対応](https://github.com/opensource-workshop/connect-cms/pull/1751/commits/3e86a03784f718fdb6be813ef2b7d99ea6f9abd8)
* [bugfix: [コード管理] インポート時の文字コード自動判別のcp932対応](https://github.com/opensource-workshop/connect-cms/pull/1751/commits/31510c069f64dca5dd61d5a74b118ddbdb59b430)
* [add: [課題管理] 試験日時インポート時の文字コード自動判別のcp932対応](https://github.com/opensource-workshop/connect-cms/pull/1751/commits/4c3f2cc5adc8da9a3223fcbe6c236b0f3e957ef6)
* [add: [データベース] インポート時の文字コード自動判別のcp932対応](https://github.com/opensource-workshop/conne …
=> [管理画面等] php8.1対応

.env.example, app/Models/Common/Uploads.php, app/Plugins/Manage/UploadfileManage/UploadfileManage.php, app/Utilities/File/FileUtils.php, config/app.php, config/connect.php, resources/views/plugins/manage/uploadfile/uploadfile_manage_tab.blade.php, resources/views/plugins/manage/uploadfile/userdir_public.blade.php
public配下のディレクトリを１つ指定してファイル管理できる機能です。
指定ディレクトリのファイルを削除できます。
当機能はbeta機能です。
```
MANAGE_USERDIR_PUBLIC_TARGET="uploads"
```
なし
なし
なし
なし
=> [アップロードファイル] (beta)ユーザパブリックファイルの一覧画面追加

app/Traits/Migration/MigrationNc3ExportTrait.php
* [bugfix: 移行ツール, NC3移行エクスポート＋nc3.2.0より古い場合、ページの階層がうまく移行できない不具合修正](https://github.com/opensource-workshop/connect-cms/commit/18ac9a8341b7aa2b7a753bb433e98881f68b6f36)
* 関連修正
* [bugfix: 移行ツール, NC3移行エクスポートで登録フォームのキャプションにダブルクォーテーションが含まれるとエラーになる不具合修正](https://github.com/opensource-workshop/connect-cms/commit/6ce324efbf37d218fa4d57ca5d3e60071e01893d)
* [bugfix: 移行ツール, NC3移行エクスポートでキャビネットのファイルの説明に改行が含まれるとエラーになる不具合修正](https://github.com/opensource-workshop/connect-cms/commit/4730f8cffa2c6a6c9acf3408c44b0dcd89dbe6e6)
* [bugfix: 移行ツール, NC3移行エクスポートでフォトアルバムのファイルのタイトルと説明に改行が含まれるとエラーになる不具合修正](https://github.com/opensource-workshop/connect-cms/commit/4692edc1924cfa26d83a861b8424439b28b20ca8)
* [bugfix: 移行ツール, NC3移行エクスポートでスライダーのファイルの説明に改行が含まれるとエラーになる不具合修正](https://github.com/opensource-workshop/connect-cm …
=> [移行ツール] NC3移行エクスポート＋nc3.2.0より古い場合、ページの階層がうまく移行できない不具合修正

resources/views/plugins/user/slideshows/default/slideshows_edit.blade.php, resources/views/plugins/user/slideshows/default/slideshows_edit_row.blade.php, resources/views/plugins/user/slideshows/default/slideshows_edit_row_add.blade.php
スライダーの項目設定画面はxl(横幅≥1200px)以上でないとPC表示になりませんでした。
スマホ表示は、スライダーの順番変更、表示・非表示が設定できなかったため、lg(横幅≥992px)までPC表示にする見直しをしました。
また、スマホ表示が見ずらかったため、見直しました。
なし
なし
なし
* https://v4.bootstrap-guide.com/utilities/display
なし
=> [スライダー] 項目設定画面をlgでもPC表示と同じにする修正＋スマホ表示の見直し

app/Plugins/User/Linklists/LinklistsPlugin.php, resources/views/plugins/user/linklists/default/edit.blade.php, resources/views/plugins/user/linklists/default/index.blade.php
* 件名通りです。
* 関連修正
* [change: リンクリスト, 編集画面のURLに必須タグが抜けていたため追加](https://github.com/opensource-workshop/connect-cms/commit/b85d69e434ab327772810a83be876542ab8dfa29)
なし
なし
なし
なし
=> [リンクリスト] 登録変更時にメッセージを表示＋登録後は一覧画面に遷移するよう見直し

resources/views/plugins/user/databases/design-table-dl/databases.blade.php, resources/views/plugins/user/databases/table/databases.blade.php
【対象テンプレート】
- table
- design-table-dl
項目名を非表示設定にしても、一覧上に項目名が表示されっぱなしになってしまう問題を修正しました。
【table】
【design-table-dl】
いつでも
なし
なし
なし
=> [データベース]項目名非表示フラグが効かないテンプレートに対して、フラグが利用できるように修正しました。

resources/views/plugins/common/facebook.blade.php, resources/views/plugins/common/twitter.blade.php, resources/views/plugins/user/blogs/default/blogs.blade.php, resources/views/plugins/user/blogs/default/blogs_setting_frame.blade.php, resources/views/plugins/user/blogs/default/blogs_show.blade.php, resources/views/plugins/user/blogs/designbase/blogs_show.blade.php
* [refactor: twitter・facebookボタンの汎用化対応](https://github.com/opensource-workshop/connect-cms/commit/d3f95efd0ab9d2a06baa7d1d559c6827a817c641)
* 関連対応
* [refactor: ブログ, 表示条件のTwitter・Twitterアイコン表示のコードのスリム化](https://github.com/opensource-workshop/connect-cms/commit/56c1fe417ce3e3a56b56022d84d8aaac94d8fa40)
なし
なし
なし
なし
=> [コア] twitter・facebookボタンの汎用化対応

app/Enums/ContentOpenType.php, app/Models/Common/Frame.php
件名通りです。
プラグイン管理者であればログイン後でも表示されます（非公開と同様）
なし
なし
なし
なし
=> [フレーム] ログイン後非表示機能を追加 OW-1656

resources/views/plugins/user/photoalbums/card/index_folder.blade.php, resources/views/plugins/user/photoalbums/default/bucket.blade.php, resources/views/plugins/user/photoalbums/default/index_folder.blade.php, resources/views/plugins/user/photoalbums/default/index_image.blade.php
=> [フォトアルバム] 右・左エリア = スマホ表示と同等にする

database/seeders/DefaultConfigsTableSeeder.php
seederのbase_themeのcategory値を`user_register` から`general`に念のため修正。
base_themeを取得する場合は、name="base_theme"で取得されていたため、修正前でも影響なしでした。
また、どうも設定変更時に`general`に更新されるようです。
なし
なし
なし
なし
=> [DB初期データ]  base_themeのcategory見直し

app/Models/Common/Frame.php
非公開・限定公開・ログイン後非表示設定時に、プレビュー表示しても表示されていたため、対応しました。
なし
* https://github.com/opensource-workshop/connect-cms/pull/1780
なし
なし
=> [フレーム] 非公開・限定公開・ログイン後非表示のプレビュー対応

resources/views/plugins/user/slideshows/default/slideshows.blade.php
スライドショー高さ指定は、PC・スマホで同じ値を指定するため、PCでは良い表示でも、スマホ表示だと上下に白い余白が入る事がありました。
また、スライドショー高さなしで設定しても、PC表示時に複数画像の高さX幅が異なると、比率が異なり、画像毎に高さが変わる事がありました。
上記を改善するため、スライド画像のCSSを `style="object-fit: contain;` から `style="object-fit: cover;` に見直しました。
※ 高さ指定すると、幅が横いっぱいにならず、左右に白い余白できる。
※ 高さ指定すると、他のスライド画像につられて上下に白い余白が出来る
軽微な改修なので急ぎません
なし
* 1行追加でOK！CSSだけで画像をトリミングできる「object-fit」プロパティー | Webクリエイターボックス
https://www.webcreatorbox.com/tech/object-fit
無し
=> [スライドショー] 高さ指定のレスポンシブ対応

app/Enums/EditType.php, app/Enums/UserColumnType.php, app/Enums/UserRegisterNoticeEmbeddedTag.php, app/Http/Controllers/Auth/RegisterController.php, app/Http/Controllers/Auth/RegistersUsers.php, app/Http/Middleware/ConnectLog.php, app/Models/Core/UsersColumns.php, app/Plugins/Manage/UserManage/UserManage.php, app/Plugins/Manage/UserManage/UsersTool.php, app/Plugins/Mypage/IndexMypage/IndexMypage.php, app/Plugins/Mypage/LoginHistoryMypage/LoginHistoryMypage.php, app/Plugins/Mypage/ProfileMypage/ProfileMypage.php, app/Traits/Migration/MigrationTrait.php, config/app.php, database/migrations/2023_08_10_112746_add_fixed_column_name_display_edit_type_from_users_columns.php, database/migrations/2023_08_10_114737_migration_fixed_column_from_users_columns.php, database/seeders/DatabaseSeeder.php, database/seeders/DefaultUsersColumnsSetTableSeeder.php, database/seeders/DefaultUsersColumnsTableSeeder.php, resources/views/auth/registe_form.blade.php, resources/views/plugins/manage/user/auto_regist.blade.php, resources/views/plugins/manage/user/edit_column_detail.blade.php, resources/views/plugins/manage/user/edit_columns.blade.php, resources/views/plugins/manage/user/include_edit_column_row.blade.php, resources/views/plugins/manage/user/list.blade.php, resources/views/plugins/mypage/index/index.blade.php, resources/views/plugins/mypage/profile/edit_form.blade.php, tests/Browser/Manage/users.csv
* 項目毎に「自動ユーザ登録時の表示指定」による表示ON/OFF対応
* 項目毎に「マイページの表示指定」による表示ON/OFF対応
* 項目毎に「マイページの編集指定」による編集ON/OFF対応
* 任意項目・固定項目も含めた並び順変更に対応 
なし
* https://github.com/opensource-workshop/connect-cms/pull/1792
なし
有り
=> [ユーザ情報] 項目毎に自動ユーザ登録時の表示指定、マイページの表示指定、マイページの編集指定を設定できるように対応

.gitignore, app/Enums/EnumsBase.php, app/Enums/UserColumnType.php, app/Models/Core/UsersColumns.php, app/Models/Core/UsersColumnsSet.php, app/Plugins/Manage/UserManage/UserManage.php, app/Plugins/Manage/UserManage/UsersTool.php, database/migrations/2023_08_28_134821_add_use_variable_variable_name_from_users_columns_sets.php, database/migrations/2023_08_28_135126_add_use_variable_variable_name_from_users_columns.php, resources/views/auth/registe_form.blade.php, resources/views/auth/registe_form_input_affiliation.blade.php, resources/views/auth/registe_form_input_checkbox.blade.php, resources/views/auth/registe_form_input_radio.blade.php, resources/views/auth/registe_form_input_select.blade.php, resources/views/plugins/manage/user/column_sets.blade.php, resources/views/plugins/manage/user/edit_column_detail.blade.php, resources/views/plugins/manage/user/edit_column_set.blade.php, resources/views/plugins/manage/user/include_edit_column_row.blade.php, resources/views/plugins/manage/user/list.blade.php, resources/views/plugins/manage/user/list_search_text.blade.php
* [add: ユーザ登録, 任意項目のオプションテンプレート追加対応](https://github.com/opensource-workshop/connect-cms/pull/1801/commits/9240d82cd48aacef4a07b681723e5158d32fbc50)
* enumsのEnumsOption対応（App\EnumsOption\XxxxOption）
* 例）ユーザ登録のオプション項目指定（app\EnumsOption\UserColumnTypeOption.php）
* `UserColumnType::loopNotShowColumnTypes()` のオプションEmuns対応
* ユーザ登録のオプション項目対応（auth_option.registe_form_input_xxxx）
* ユーザ管理＞一覧のオプション項目の検索対応（plugins_option.manage.user.list_search_xxxx）
* ユーザ管理＞一覧表示のオプション項目対応（plugins_option.manage.user.list_include_value）
* [add: [ユーザ管理] ユーザ項目セット, 任意項目に変数名を登録できるように対応](https://github.com/opensource-workshop/connect-cms/pull/1801/commits/72fca0f308b7f938a482ee67f6de9214d0cf94b7)
* ユーザ管理＞項目セット一覧＞項目設定でキャプションやマイページ表示等の設定値を一覧に表示
変数名の登録
キャプションやマイページ表示等の設定値を一覧に表示
変数名の登録
なし
* …
=> [ユーザ登録] 任意項目のオプションテンプレート追加対応・ユーザ項目セット, 任意項目に変数名を登録できるよう対応

app/Enums/UserColumnType.php, app/Models/Core/UsersColumns.php, app/Plugins/Manage/UserManage/UserManage.php, resources/views/plugins/manage/user/list.blade.php
* [add: ユーザ管理, ユーザ一覧検索で検索条件を開いたまま再表示できるオプション変数を追加](https://github.com/opensource-workshop/connect-cms/commit/208b5c887d4a0133565d637ce031556c8ba96014)
* [add: ユーザ管理, ユーザ一覧検索で検索条件を部分一致か完全一致かカラム型で設定できるオプションメソッドを追加](https://github.com/opensource-workshop/connect-cms/commit/7a1634e82a3f201b36843125cb7d6bfdac360b7b)
なし
なし
なし
なし
=> [ユーザ管理] ユーザ一覧検索で検索条件を開いたまま再表示できるオプション変数を追加, ユーザ一覧検索で検索条件を部分一致か完全一致かカラム型で設定できるオプションメソッドを追加

.github/workflows/laravel_dusk_connect-cms-test.yml
ChromeDriver 115+になってChromeDriverのダウンロードURLが変更になり、ChromeDriver 115以降でダウンロードできなくなりました。
そのため、Chrome browser を v114にダウングレード＋ChromeDriverもv114にして対応しました。
他のgithub actionでもChromeDriverを使いたい場合は、本修正を横展開すれば対応できる見込みです。
* https://stackoverflow.com/questions/76980975/chrome-driver-failing-in-laravel-dusk-failed-to-open-stream-http-request-fai
* https://voicetechno-jp.secure-web.jp/ChromeDriverV115orNewer.html
Laravel8.xはDusk v6.x系ですが、既にbugfixのサポート期間を過ぎていたため、修正されませんでした。
* https://github.com/laravel/dusk/issues/1055
Dusk v7.x系は https://github.com/laravel/dusk/releases/tag/v7.9.0 で修正されました。
しかし、Dusk v7.x系はphp8.xで実行（https://github.com/laravel/dusk/blob/7.x/composer.json#L13 ）のため、Laravel8.x系では使えませんでした。
無し
無し
無し
=> [GitHub action] Downgrade Chrome browser to v114

resources/views/plugins/user/forms/default/forms_edit_input.blade.php
=> [フォーム] 登録一覧の編集画面で項目名と値が被って表示される不具合修正

app/Enums/UserColumnType.php, app/Models/Core/UsersColumns.php, app/Plugins/Manage/UserManage/UserManage.php, app/Plugins/Mypage/ProfileMypage/ProfileMypage.php, resources/views/auth/registe_form.blade.php, resources/views/plugins/manage/user/edit_column_detail.blade.php, resources/views/plugins/manage/user/include_edit_column_row.blade.php, resources/views/plugins/mypage/index/include_index_column_value.blade.php, resources/views/plugins/mypage/index/index.blade.php, resources/views/plugins/mypage/profile/edit_form.blade.php
* [[ユーザ登録] 表示のみのカラム型, 自動登録のみ表示するカラム型 判定メソッド追加](https://github.com/opensource-workshop/connect-cms/commit/e453e064b83994dbf65ccd31319a0c0fc70da1ca)
* [change: マイページ, 任意項目表示のオプションテンプレート対応](https://github.com/opensource-workshop/connect-cms/commit/cc7c9bbdb1ced6c327f196ac0000db109ecb3c73)
* [change: プロフィール変更, 任意項目表示のオプションテンプレート対応](https://github.com/opensource-workshop/connect-cms/commit/a1833f192367ddfe58dbfaf5f88c4d9f4cac1b3b)
なし
なし
なし
なし
=> [ユーザ登録] 表示のみのカラム型, 自動登録のみ表示するカラム型 判定メソッド等追加

app/Plugins/Manage/UserManage/UserManage.php, resources/views/plugins/manage/user/edit_columns.blade.php, resources/views/plugins/manage/user/include_edit_column_row.blade.php
* [bugfix: ユーザ管理, 項目設定で選択肢なしの時の「選択肢がありません。」メッセージが表示されない不具合修正](https://github.com/opensource-workshop/connect-cms/commit/10cb6d359bf912c221bb0464dd3f4934055de71e)
* [bugfix: ユーザ管理, 項目設定で設定した選択肢が一覧表示されない不具合修正](https://github.com/opensource-workshop/connect-cms/commit/edb8db9f3baf98cfef815795098be51dc5d31c7d)
なし
なし
なし
なし
=> [ユーザ管理] 項目設定で選択肢なしの時の「選択肢がありません。」メッセージが表示されない不具合修正、項目設定で設定した選択肢が一覧表示されない不具合修正

app/Enums/WhatsnewFrameConfig.php, app/Plugins/User/Whatsnews/WhatsnewsPlugin.php, resources/views/plugins/user/whatsnews/card_04/whatsnews.blade.php, resources/views/plugins/user/whatsnews/default/whatsnews.blade.php, resources/views/plugins/user/whatsnews/default/whatsnews_frame.blade.php, resources/views/plugins/user/whatsnews/onerow/whatsnews.blade.php, resources/views/plugins/user/whatsnews/whatsnews_script.blade.php
1ページに新着情報をたくさん並べると、表示に時間がかかります。
表示を早くするために、非同期でコンテンツを取得するようにしました。
- 表示設定画面 - 非同期表示の項目を追加しました
- 各テンプレート - 非同期表示ONの場合、非同期でデータを取得するように変更しました
無し
=> [新着情報]非同期で表示する機能を追加しました

app/Plugins/User/Reservations/ReservationsPlugin.php
24h終了予定（例：0:00-24:00等）＋繰返し予定で、削除の「この日付以降を削除する」を指定した時、指定日のみしか削除されず、以降の日付が削除されない不具合を修正しました。
「この日付以降を削除する」を処理時、開始日・終了日を該当日を指定して削除していました（26日以降なら26, 27, 28…と）が、終了時刻が24hの場合、内部データは次の日（26日なら27日、27日なら28日）となっていて、削除できてませんでした。
「この日付以降を削除する」を処理時は、開始日のみ見て、削除するよう見直しました。
* [bugfix: 施設予約, 24h予定の繰返し予定で、この日付以降削除するが機能しない不具合修正](https://github.com/opensource-workshop/connect-cms/pull/1814/commits/369fa766a4b432bd0d08aa83d343c5fe95677649)
なし
なし
なし
なし
=> [施設予約] 24h終了予定の繰返し予定で、この日付以降削除するが機能しない不具合修正

app/Plugins/Manage/UserManage/UsersTool.php, resources/views/plugins/manage/user/description_frame_mails.blade.php
件名通りです。
* https://github.com/opensource-workshop/connect-cms/pull/1798
固定項目（ログインID等）の名称も変更できる機能を追加した時のバグです。
メール送信画面を表示時に、固定項目（ログインID等）は、任意項目のDBテーブルに値を持たないのに、無い値を参照しようとして500エラーが発生していました。
固定項目（ログインID等）は、任意項目のDBテーブルの値を参照しないように修正しました。
なし
なし
なし
なし
=> [ユーザ管理＞ユーザ登録] ユーザ登録時にメールアドレス有りの場合、グループ登録後に500エラーになる不具合修正

resources/views/plugins/manage/site/pdf/base_favicon.blade.php
* https://github.com/opensource-workshop/connect-cms/pull/1819
対応時の修正漏れです。
対応しました。
なし
概要に記載済み。
なし
なし
=> [サイト管理＞サイト設計書] サーバのphp設定で allow_url_fopen=0 の場合＋ファビコンが設定済みの場合、サイト設計書の出力で500エラーになる不具合の修正 OW-2005

resources/views/plugins/user/blogs/default/blogs_setting_frame.blade.php, tests/Browser/Manage/UserManageTest.php
* ユーザ管理テスト, #1798（任意項目にログインID等の固定項目も追加） の修正で動かなくなっていた箇所を修正
* [test: ブログテスト, 表示条件, duskでradioの選択にlabelのid必要なため追加](https://github.com/opensource-workshop/connect-cms/pull/1827/commits/e96daa4320292924f421d75964ee0f4ffff903de)
なし
概要に記載済み
なし
なし
=> [自動テスト] ユーザ管理テスト, ブログの表示条件テスト, エラーが出ていたテストケースを修正

app/Rules/CustomValiWysiwygMax.php, tests/Browser/Manage/ReservationManageTest.php
* 件名通りです。
* 関連修正
* [test: 施設管理, 施設登録後に、登録完了メッセージに含まれる文字をチェックして、登録完了しているかチェック追加](https://github.com/opensource-workshop/connect-cms/pull/1829/commits/55558628a4c3f6c7e4101f194d7738f21acad38a)
なし
* https://github.com/opensource-workshop/connect-cms/issues/1752
なし
無し
=> [入力チェック] php8.1でWYSIWYG最大バイト数越えチェック時に500エラーになる不具合修正

app/Enums/NoticeEmbeddedTag.php, tests/Browser/Manage/UserManageTest.php
* 件名通りです。
* 関連修正
* [test: ユーザ管理＞ユーザ登録＞メール送信, メール送信画面をしているかチェック追加](https://github.com/opensource-workshop/connect-cms/commit/ec7e0682c067da0891ccdcb5cd66e28b2fecb5e2)
なし
* https://github.com/opensource-workshop/connect-cms/issues/1752
なし
なし
=> [ユーザ管理＞ユーザ登録＞メール送信] php8.1で埋込タグの値がnullの場合、500エラーになる不具合修正

app/Plugins/Manage/HolidayManage/HolidayManage.php, tests/Browser/Manage/HolidayManageTest.php
件名通りです。
* [bugfix: 祝日管理, php82で祝日編集時の Creation of dynamic property App\Plugins\Manage\HolidayManage\HolidayManage::$post is deprecated 修正](https://github.com/opensource-workshop/connect-cms/commit/46ae48d8bc5bb883e596b663835fe349e1a8bbac) 
* [test: 祝日管理テスト, 祝日編集時に500エラーがでてないことをチェック](https://github.com/opensource-workshop/connect-cms/commit/0f1ceebc39cacec125df7feeef6a2acf999a9972)
なし
* https://github.com/opensource-workshop/connect-cms/pull/1831
なし
なし
=> [祝日管理] php8.2で祝日編集時の 500エラー修正

.github/workflows/laravel_dusk_connect-cms-test-matrix.yml, .github/workflows/laravel_dusk_connect-cms-test.yml
* test: github-actions, Laravel Dusk Connect-cms-test, マニュアル出力は機能しないため、コメントアウト
* [test: github-actions, Laravel Dusk Connect-cms-testの複数php実行版追加](https://github.com/opensource-workshop/connect-cms/commit/0a5f7ad9b5fb2d1cde389801a577c62476483b2d)
なし
なし
なし
なし
=> [自動テスト] github-actions の Laravel Dusk Connect-cms-test, マニュアル出力は機能しないため、コメントアウト ＆ Laravel Dusk Connect-cms-testの複数php実行版追加

app/Models/Core/UsersColumns.php, app/Plugins/Manage/UserManage/UserManage.php, database/migrations/2023_08_10_114737_migration_fixed_column_from_users_columns.php, database/seeders/DefaultUsersColumnsTableSeeder.php
* https://github.com/opensource-workshop/connect-cms/pull/1792 の不具合修正です。
.envのUSE_USERS_COLUMNS_SET=false、または設定なしであれば、不具合の影響ありません。
なし
概要に記載済み
なし
なし
=> [ユーザ管理] .envのUSE_USERS_COLUMNS_SET=true設定時、項目セット登録を行っても固定項目（ログインID等）が初期登録されない不具合修正

resources/views/plugins/common/wysiwyg.blade.php
- クライアント要望です。
- wisiwygエディタ－画像編集ボタン押下時ウィンドウに左ペイン、及び、詳細設定が追加されます。
- 詳細設定では余白や枠線の設定が可能になり、従来CSSで対応するしかなかったものが画面から対応可能になります。
10/3（火）一杯
なし
https://www.tiny.cloud/docs/plugins/opensource/image/#image_advtab
なし
=> [wysiwygエディタ]画像編集時の詳細設定タブを追加しました

app/Models/User/Databases/DatabasesInputs.php, app/Plugins/User/Databases/DatabasesPlugin.php, app/Plugins/User/Databases/DatabasesTool.php, database/migrations/2023_09_04_153112_add_full_text_search_to_databases.php, resources/views/plugins/user/databases/default/databases_edit_database.blade.php
- データベースのキーワード検索を高速化する
- OR検索、除外検索（-）を可能にする
- DB設定画面 全文検索の設定項目を追加
- 全文検索を有効にする場合、「使用する」を選択します
- 項目を検索対象にすれば、検索されます
- キーワード検索
- 「OR もしくは | 」キーワードいずれかを含むデータを検索します
- 「AND もしくは &」キーワードすべてを含むデータを検索します
- 「NOT または –」キーワードを除外したデータを検索します
databases_inputs に full_text を追加し、databases_inputs.full_text に検索対象の値をすべて結合して格納します。
全文検索を有効時には、databases_inputs.full_text をキーワード検索します。
databases_inputs.full_textは以下のタイミングで更新されます。
- 値の追加
- 値の更新
- 列の削除　検索対象ON
- 列の更新　検索対象ON
- 列の更新　検索対象OFF
- DB設定変更　全文検索を使用する
- CSVインポート
また、databases_inputs.full_textは以下のタイミングでクリアされます。
- DB設定変更　全文検索を使用しない
**バッチでのdatabases_inputs.full_textを一括更新**
スケジューラの設定が一般ユーザーにはハードルが高いため、画面から都度更新するようにしました。
有り
=> [データベース]全文検索機能を追加しました

app/Enums/DatabaseFrameConfig.php, app/Models/Common/Frame.php, app/Plugins/User/Databases/DatabasesPlugin.php, resources/views/plugins/user/databases/default/databases_edit_view.blade.php, resources/views/plugins/user/databases/default/databases_include_ctrl_head.blade.php
トップページなどにデータベースの検索ボックスを置きたい。
ただ、トップページ内で検索結果を出すと邪魔になるため、別ページへ遷移させたい。
上記を実現する場合、従来だと遷移先に配置した検索ボックスのHTMLをコピーして、トップページの固定記事に張り付けて設定していました。
ただこの手順はHTMLを読めないといけないため、ハードルが高いです。
画面から設定できるよう手順を簡略化する必要があります。
表示設定画面で検索窓としてのフレームとする設定を追加しました。
- 表示設定画面 検索後の遷移先
- 同一データベースを設定しているページ・フレームを選択できます。
無し
=> [データベース]検索窓としての表示設定を可能にしました

app/Enums/DatabaseFrameConfig.php, app/Models/User/Databases/DatabasesSearchedWord.php, app/Plugins/User/Databases/DatabasesPlugin.php, app/Plugins/User/Databases/DatabasesTool.php, database/migrations/2023_09_12_182442_add_save_search_word_to_databases.php, database/migrations/2023_09_12_183229_create_databases_searched_words.php, resources/views/plugins/user/databases/default/databases_edit_database.blade.php, resources/views/plugins/user/databases/default/databases_edit_view.blade.php, resources/views/plugins/user/databases/default/databases_include_ctrl_head.blade.php
急上昇ワード、トレンドといったような情報を表示する機能を追加しました。
管理者は、急上昇ワードを表示することで、現在どういったコンテンツが求められているか判断できます。
利用者は、トレンドを理解できます。
- DB設定画面  「検索キーワードの記録」を追加
- 表示設定画面 「急上昇ワードの表示」を追加
- 「表示する」を選択することで急上昇ワードを選択できます。
- 最新化ボタンで現在のデータをもとに表示するワードを選択できます
- ⊖を押下することで表示したくないワードを消せます
- 「表示項目名」に任意の文言を設定することでキャプションを変更できます
- 一覧画面 急上昇ワードの表示を追加
-  リンクを押下すると当該キーワードで検索します
- 自動で急上昇ワードは変更されません
有り
=> [データベース]急上昇ワードを表示する機能を追加しました

app/Enums/DatabaseColumnType.php, app/Enums/DatabaseNoticeEmbeddedTag.php, app/Enums/DatabaseSearcherSortType.php, app/Enums/DatabaseSortFlag.php, app/Models/User/Databases/DatabasesColumns.php, app/Models/User/Databases/DatabasesInputs.php, app/Plugins/User/Databases/DatabasesPlugin.php, app/Plugins/User/Databasesearches/DatabasesearchesPlugin.php, database/migrations/2023_09_20_132746_add_views_to_databases_inputs.php, resources/views/plugins/user/databases/default/databases_include_detail_value.blade.php, resources/views/plugins/user/databases/default/databases_include_value.blade.php
データの表示件数を一つの項目として、表示できる機能を追加しました。
表示件数は詳細画面を開いたタイミングで更新されます。
有り
=> [データベース]項目の型に表示件数型を追加しました

app/Plugins/Manage/SiteManage/SiteManage.php, app/Utilities/File/FileUtils.php, resources/views/plugins/manage/site/site_manage_tab.blade.php, resources/views/plugins/manage/site/total.blade.php
ファイル使用容量を確認できる画面を追加しました。
なし
なし
* （PHPで）指定ディレクトリ以下を全部チェックしてファイル一覧を取得する方法
https://blog.asial.co.jp/1250/
なし
=> [サイト管理] 使用容量 画面追加

resources/views/plugins/user/databases/default/databases_include_ctrl_head.blade.php
標題の通り。PRの競合を解消した際に発生した不具合です。
#1838
無し
=> [データベース]急上昇ワードを押下しても遷移しない問題を修正しました

resources/views/core/cms_frame_header.blade.php
フレームのヘッダーのclassに、プラグインが編集可能であることを表すclassを追加しました。
以下のようなデザインを当てるときに利用します。
- タブプラグインを利用する際、一般ユーザにタブ配下のヘッダーを隠す
- 管理者にはヘッダーを表示させて管理画面を見れるようにする
無し
=> [コア]フレームのヘッダーにプラグインが編集可能であることを表すclassを追加しました

resources/views/core/cms_frame_header.blade.php
- 編集権限があるかの判定を先頭の変数に保持するようにしました
- プラグインが編集可能であることを表すclassを「can-edit-plugin」から「can-edit-frame」に変更しました
無し
=> [コア]フレーム共通ヘッダーbladeの処理を改善しました

resources/views/plugins/user/databasesearches/card_04/databasesearches.blade.php
カード型のテンプレートを利用する場合、aタグが含まれるウィジウィグ型の項目を出力するとHTMLが崩れます。
これはは、一つのカードがaタグでくくられているためです。
aタグの中にaタグはHTMLとして許容されません。
以上より、ウィジウィグ型を出力する際にaタグを除去する処理を追加しました。
対象のテンプレート：card03, card04
バグのためなるはやでお願いします。
無し
=> [データベース検索]ウィジウィグ型にaタグが含まれるとHTMLが崩れる問題を修正しました

app/Enums/DatabaseSearcherSortType.php, app/Plugins/User/Databasesearches/DatabasesearchesPlugin.php
並べ替え条件をデータベースプラグインと合わせました。
ランダム（セッション）、ランダム（毎回）を追加しました。
データベース検索プラグインでもランダム表示を利用できます。
無し
=> [データベース検索]並べ替え条件にランダムを追加しました

app/Plugins/User/Databases/DatabasesPlugin.php
検索結果へのURLを指定できるようにするため、GETでも検索できるようにしました。
例 : /plugin/databases/search/{page_id}/{frame_id}?search_keyword=キーワード
従来は実質POSTのみでsearchアクションが機能していました。
（GETは新たな検索条件を設定できず前回の検索条件で再検索する）
**検索する画面にURLをコピーする機能があったほうがいいのでは？** by @akagane99 
別issueで積み残します！
検索画面をGETに変えちゃっていい気がします。
無し
=> [データベース]検索をGETメソッドでも実行可能にしました

resources/views/plugins/manage/page/page_import.blade.php, resources/views/plugins/manage/site/favicon.blade.php, resources/views/plugins/manage/user/import.blade.php, resources/views/plugins/user/cabinets/default/index.blade.php, resources/views/plugins/user/learningtasks/default/learningtasks_input.blade.php, resources/views/plugins/user/photoalbums/default/edit_contents.blade.php, resources/views/plugins/user/photoalbums/default/edit_video.blade.php, resources/views/plugins/user/photoalbums/default/index_head.blade.php
ファイルアップロードで入力エラー時にファイル参照欄を赤線で囲おうとしていましたが、赤線が表示されていない画面がありましたので対応しました。
エラー時 `<input type="file">` に border-danger クラスを追加しても赤線枠が表示されない
↓
エラー時 `<label class="custom-file-label">` に border-danger クラスを追加すると赤線枠が表示される
※ `<input type="file">`、`<label class="custom-file-label">`  両方に  border-danger クラスを追加している画面もありましたので、`<label class="custom-file-label">` にだけ追加するよう見直しました。
```html
<input type="file" name="upload_file[{{$frame_id}}]" value="{{old("upload_file.$frame_id")}}" class="custom-file-input @if ($errors && $errors->has("upload_file.$frame_id")) border-danger @endif" id="upload_file{{$frame_id}}">
<label class="custom-file-label" for="upload_file" data-browse="参照">ファイル選択...</label>
↓
<input type="file" name="upload_file[{{$frame_id}}]" value="{{old("upload_file.$frame_id")}}" …
```
=> [入力エラー] ファイルアップロードで入力エラー時にファイル参照欄を赤線で囲う対応の見直し

app/Plugins/User/Databases/DatabasesPlugin.php
ウィジウィグ型を含むデータベースでCSVをエクスポートし、そのCSVをExcelで開くと項目が列からはみ出て崩れていました。
これは、ウィジウィグ型に含まれる"（ダブルクォート）が原因でした。
ダブルクォートがエスケープされていないかったため、Excelが項目の区切りを正しく認識できなくなっていました。
以上より、ダブルクォートをエスケープする処理を追加しました。
無し
=> [データベース]ウィジウィグ型を含むCSVをExcelで閲覧すると崩れる問題を対応しました

app/Plugins/User/Databases/DatabasesPlugin.php
表示件数型の値が出力されない問題を対応しました。
型追加対応で出力処理の追加漏れが原因です。
無し
=> [データベース]表示件数型が出力されない問題を対応しました

database/migrations/2023_10_31_090932_change_uri_length_from_app_logs.php
件名通りです。
（ログ設定OFFの場合、エラーは起こりません）
* URL 項目の文字数を255 => 8190 へ変更
* Apache のLimitRequestLine ディレクティブのデフォルト値に合わせた。
* https://httpd.apache.org/docs/2.4/mod/core.html#limitrequestline
なし
なし
有り
=> [ログ設定] ログ設定でURIを記録する設定をした場合、長いURIで500エラーが出る問題に対応

resources/views/plugins/common/wysiwyg.blade.php, resources/views/plugins/manage/user/include_edit_column_row.blade.php
件名通りです。
（現状 page_id = null にならないため、エラーおきません。
　今はありませんが、今後 wysiwygを管理画面に使う場合に page_id = null になることが予想されます。）
なし
なし
なし
なし
=> [wysiwyg] page_id = nullだとDBに登録できないため見直し

tests/Browser/User/BbsesPluginTest.php
件名通りです。
なし
* https://github.com/opensource-workshop/connect-cms/pull/1876
なし
なし
=> [自動テスト] 掲示板, 登録時の確認ダイアログ追加に伴う自動テストの修正

app/Traits/Migration/MigrationTrait.php
DatabasesTruncate処理を修正
データベース機能追加による移行不具合修正
不具合対応なので急ぎたいです
無し
=> [移行]DatabasesTruncate処理を修正

app/Plugins/Manage/ThemeManage/ThemeManage.php, config/version.php, resources/views/plugins/manage/theme/theme.blade.php, resources/views/plugins/manage/theme/theme_template_edit.blade.php
管理機能のテーマ管理にて、WYSIWYGのテンプレートを編集できる機能を追加しました。
WYSIWYGにテンプレート機能があるが、管理画面での編集ができなかったので、機能を追加しました。
急いではいません。
* https://github.com/opensource-workshop/connect-cms-ideas/issues/10
無し
=> [テーマ管理]WYSIWYGのテンプレート編集機能を追加しました。

app/Enums/BlogFrameConfig.php, app/Enums/BlogNarrowingDownTypeForCreatedId.php, app/Models/User/Blogs/Blogs.php, app/Plugins/User/Blogs/BlogsPlugin.php, database/migrations/2023_11_15_175748_add_narrowing_down_type_for_created_id_from_blogs.php, resources/views/plugins/user/blogs/default/blogs_edit_blog.blade.php, resources/views/plugins/user/blogs/default/blogs_setting_frame.blade.php, resources/views/plugins/user/blogs/default/include_narrowing_down_for_created_id.blade.php
* https://github.com/opensource-workshop/connect-cms/pull/1882
の修正です。
投稿者の絞り込み機能はフレーム設定から、ブログ設定に移動して表示件数絞込・カテゴリ絞込と同じにしました。
投稿者毎に絞り込めます。
なし
概要に記載済み
なし
あり
=> [ブログ] 投稿者絞込機能追加2 OW-2072

app/Enums/BlogFrameScope.php, app/Models/User/Blogs/BlogsPosts.php, resources/views/plugins/user/blogs/default/blogs.blade.php, resources/views/plugins/user/blogs/default/blogs_setting_frame.blade.php, resources/views/plugins/user/blogs/default/include_scope.blade.php, resources/views/plugins/user/blogs/designbase/blogs.blade.php
=> [ブログ] 表示条件設定に 自身の投稿のみ を追加 OW-2076

app/Enums/ContentOpenType.php, app/Models/Common/Frame.php, resources/views/core/cms_frame_edit.blade.php, resources/views/core/cms_frame_header.blade.php
=> [フレーム設定] 公開設定に ログイン後表示 を追加 OW-2077

app/Plugins/Manage/UserManage/UserManage.php
* https://github.com/opensource-workshop/connect-cms/pull/1792
上記対応時に含まれた不具合です。
その不具合を修正しました。
```sql
SQLSTATE[HY000]: General error: 1364 Field 'columns_set_id' doesn't have a default value (SQL: insert into `users_columns_selects` (`users_columns_id`, `value`, `agree_description`, `display_sequence`, `created_id`, `created_name`, `updated_at`, `created_at`) values (112, 利用規約, ｄｄｄｄｄｄｄｄｄｄｄｄｄｄｄ, 1, 1, テスト企業, 2023-11-22 16:07:07, 2023-11-22 16:07:07))
```
なし
概要に記載
なし
なし
=> [ユーザ管理] 同意型の詳細でチェックボックスの名称等を更新すると500エラーになる不具合修正

app/Traits/Migration/MigrationTrait.php
https://connect-cms.jp/plugin/bbses/show/106/233/856#frame-233
掲示板で連絡あり。
移行バグだったため修正しました。
* [bugfix: 移行, ブログの続きを読む内容のリンクチェックで参照変数が間違っていたため修正](https://github.com/opensource-workshop/connect-cms/commit/75c931595cf3ddcf9c1bf2892d69e57750393ac6)
* 関連修正
* [bugfix: 移行, 再インポート時、マッピングにデータがあるとカテゴリ情報が参照できない不具合修正](https://github.com/opensource-workshop/connect-cms/commit/a64c4599c2de395ab1863d615206dde1df59bb58)
なし
なし
なし
なし
=> [移行] ブログの続きを読む内容のリンクチェックで参照変数が間違っていたため修正

database/migrations/2023_09_04_153112_add_full_text_search_to_databases.php
MariaDBは5.6以上でFULLTEXT対応のため、DBマイグレーションを見直しました。
なし
なし
有り（MariaDB 5.5以下）
=> [マイグレーション] MariaDBは5.6以上でFULLTEXT対応

resources/views/plugins/user/whatsnews/card_04/whatsnews.blade.php, resources/views/plugins/user/whatsnews/card_04_top_thumbnail/whatsnews.blade.php
card_04テンプレートはタイトルが上、サムネイルが下です。
サムネイルを上に表示したいため、card_04テンプレートのサムネイルが一番上に表示されるバージョンのテンプレート card_04_top_thumbnail を追加しました。
なし
なし
なし
なし
=> [新着情報] card_04_top_thumbnailテンプレート追加

resources/views/layouts/app.blade.php
件名通りです。
参考：マイページのコンテンツ画面へ
なし
なし
なし
なし
=> [マイページ] 管理機能 or コンテンツ権限なしでマイページ表示すると、コンテンツ画面へが表示されないバグ修正

resources/views/plugins/user/menus/opencurrenttree_for_design/menus.blade.php
他テンプレートと同様に、ディレクトリ展開式デザイン用テンプレートのliタグに、ページ詳細のクラス名を反映させる対応をしました。
https://github.com/opensource-workshop/connect-cms/wiki/Menu#ページ管理ページ詳細クラス名
なし
なし
概要に記載
なし
=> [メニュー] ディレクトリ展開式デザイン用テンプレートにページ詳細のクラス名をliタグに適用

app/Plugins/Manage/UserManage/UserManage.php
* https://github.com/opensource-workshop/connect-cms-ideas/issues/163
上記の対応です。
なし
概要に記載
なし
なし
=> [ユーザ管理] 検索時とcolumns_set_idをURL等で指定時には、表示ページ数をクリアする対応

app/Enums/UserColumnType.php, app/Models/Core/UsersColumns.php, app/Plugins/Manage/UserManage/UsersTool.php, resources/views/plugins/manage/user/description_frame_mails.blade.php
開発者向けの対応です。
ユーザ登録時のメール埋め込みタグの値を、独自に設定できるよう対応しました。
app\PluginsOption\Manage\UserManage\UsersToolOption.php に getNoticeEmbeddedTagsValue() メソッドを作ることで、独自のメール埋め込みタグの値をセットできます。
なし
なし
なし
なし
=> [ユーザ登録] メール埋め込みタグをカスタマイズできるように対応

app/Http/Controllers/Core/UploadController.php
参照権限のない画像を表示すると、forbidden画像が表示されますが、その画像がブラウザキャッシュされていたため、キャッシュしないよう対応しました。
1. これはログイン前に見れなかった画像がforbidden画像とキャッシュされ
1. その後、ログインして、画像の参照権限ありだとしても、ブラウザキャッシュが残っている影響でforbidden画像が表示されていました。
　→ forbidden画像が表示される事自体が稀なため、キャッシュしないよう見直しました。
1. サイト全体を表示パスワードで閲覧制限をつける。
1. スライドショープラグインを配置する。
1. 表示パスワードを入力して、サイトを見る。
1. 次の日、サイトを開くとブラウザキャッシュの影響で、一時的にサイトが見れるけど、表示パスワードの有効時間は切れている。その時にサーバに取りにいった画像（ここではスライドショー）は表示パスワードの時間切れでforbidden画像になる。
1. 再度サイトを開くと、 表示パスワードの入力画面になり、再入力してサイトを開くと、スライドショーの画像はブラウザキャッシュされたforbidden画像が表示される。
（ブラウザキャッシュをクリアすれば解消する）
なし
なし
なし
なし
=> [コア] forbidden画像はキャッシュしない

app/Http/Controllers/Core/UploadController.php, app/Plugins/Manage/SiteManage/SiteManage.php, resources/views/plugins/manage/site/page_error.blade.php
* https://github.com/opensource-workshop/connect-cms-ideas/issues/165
上記の対応です。
なし
概要に記載
なし
無し
=> [サイト管理] エラー設定画面にNo Image画像の設定追加

app/Plugins/User/Whatsnews/WhatsnewsPlugin.php, resources/views/plugins/user/whatsnews/default/whatsnews_edit_whatsnew.blade.php, resources/views/plugins/user/whatsnews/default/whatsnews_frame.blade.php, resources/views/plugins/user/whatsnews/default/whatsnews_list_buckets.blade.php, resources/views/plugins/user/whatsnews/whatsnews_frame_edit_tab.blade.php
* https://github.com/opensource-workshop/connect-cms-ideas/issues/166 の対応を行いました。
* 関連対応
* 表示設定
* [add: 新着情報, 表示設定変更後にメッセージを表示](https://github.com/opensource-workshop/connect-cms/pull/1911/commits/2b68fe1d4e0ff912764ade4f6fda1f3176088b7b)
* [change: 新着情報, 表示設定の本文の表示文字数、最大画像サイズは表示する時のみ条件チェックを行うよう修正](https://github.com/opensource-workshop/connect-cms/pull/1911/commits/58310c517dd7ccc72bc4f467b3f0e08c56d4e1b8)
* バケツ選択
* [add: 新着情報, 新着情報選択変更後に変更メッセージを表示](https://github.com/opensource-workshop/connect-cms/pull/1911/commits/9f68e596111d6328faa67d6d905df9986a742ff5)
* [change: 新着情報, バケツ選択の変更ボタンはツールチップ表示](https://github.com/opensource-workshop/connect-cms/pull/1911/commits/3975734932bec76cc274577d5976035e6986f253)
なし
* https://github.com/opensource-workshop/connect-cms/issues/856
なし
なし
=> [新着情報] プラグインを配置して新規作成＞登録後は設定変更に画面遷移させる等の対応

resources/views/plugins/user/whatsnews/whatsnews_script.blade.php
* 公式掲示板の報告より https://connect-cms.jp/plugin/bbses/show/106/233/866#frame-233
* おそらく上記の原因を対応しました。
* 新着情報のもっと見るボタンのURLに、不要な末尾/がついていましたので、削除しました。
* 末尾/ があると、.htaccess の mod_rewrite 設定に引っ掛かり、getへ自動リダイレクトされます。
* 自動リダイレクト後、http → httpsへの自動リダイレクト設定がない場合、mixed content（混在コンテンツ）となり、もっと見るの記事がブラウザによって表示されませんでした。
なし
なし
* laravelでトレイリングスラッシュを有効にする方法 #Laravel - Qiita
https://qiita.com/naoqoo2/items/cdbd84220e97eb160ea8
* > トレイリングスラッシュ（URL末尾のスラッシュ）
* 混在コンテンツ - ウェブセキュリティ | MDN
https://developer.mozilla.org/ja/docs/Web/Security/Mixed_content
なし
=> [新着情報] もっと見るボタン押下時に不要なリダイレクトの発生をなくす

resources/views/plugins/manage/menus.blade.php, resources/views/plugins/manage/menus_list_option.blade.php
今までオプション管理プラグインを管理者メニューに表示するには、plugins_option.manage.menus_list bladeの追加が必須でした。
修正後はオプション管理プラグインに所定のconstを設定すれば、管理者メニューに自動表示されます。
また、いままでのオプション管理者メニューも有効です。
```php
class TotalizationManage extends ManagePluginOptionBase
{
/**
* プラグイン名
* 管理者メニュー表示に必要
*
* @var string
*/
const plugin_name = 'totalization';
/**
* プラグイン名（和名）
* 管理者メニュー表示に必要
*
* @var string
*/
const plugin_name_full = '集計機能';
(略)
}
```
なし
なし
なし
なし
=> [コア] オプション管理プラグインの管理者メニュー自動対応

app/Plugins/Manage/PageManage/PageManage.php, resources/views/plugins/manage/page/migration_order.blade.php
* [bugfix: ページ管理, 外部ページインポートで取り込み済み移行データがあると500エラー（File not found at path: migration/import/pages/1）になる不具合修正](https://github.com/opensource-workshop/connect-cms/pull/1916/commits/98ecee5dcef1c4e26b9123143b72e03a0a29f3a4) 
* 関連対応
* [buffix: ページ管理, 外部ページインポートの取り込み済み移行データが削除できない不具合修正](https://github.com/opensource-workshop/connect-cms/pull/1916/commits/1e560aa7bc1f7c6b99bfa393091fc5e167a4abfd)
なし
なし
なし
なし
=> [ページ管理] 外部ページインポートで取り込み済み移行データがあると500エラー（File not found at path: migration/import/pages/1）になる不具合等対応

app/Plugins/Manage/PageManage/PageManage.php, resources/views/plugins/manage/page/migration_order.blade.php
* https://github.com/opensource-workshop/connect-cms/pull/1916
上記の変数名の修正のみのため、リリースに含めない対応としてマージします。
なし
なし
なし
なし
=> [ページ管理] 外部ページインポートの取り込み済み移行データが削除できない不具合の変数名見直し

.gitignore, tests/Browser/Common/WysiwygTest.php, tests/Browser/screenshots/.gitignore
・Chromeドライバが新しくなって、挙動が少し変わったようなので対応しました。
・テスト時の生成される画像フォルダがgitignoreされていなかったので指定しました。
特に問題はないと思うので、明日にでもマージします。
無し
=> [テスト＆マニュアル]WYSIWYSテスト時のタイミング変更

app/Http/Controllers/Core/ClassController.php, app/Http/Kernel.php
共通変数のtop_pageは、middlewareのconnect.pageでセットされますが、管理画面系は不要と考え除外していました。
しかしページ管理の一覧画面で、継承関係の表示をするために、1ページ1ページで自身を遡ってページツリーを取得する際、共通変数のtop_pageがなく、毎回DBに再取得しに行っていた事が調査でわかったため、修正しました。
また、権限チェックのGate処理時にも、ページを遡る処理があり、同様の状態でした。
対応後は毎回DBに再取得がなくなるため、大量ページのサイトでページ管理の表示が若干早くなります。
なし
なし
なし
なし
=> [コア] ページ管理等で共通変数のtop_pageがセットされず毎回再取得していた不具合修正

app/Exceptions/Handler.php, resources/views/common/flash_message_for_header.blade.php, resources/views/core/cms.blade.php, resources/views/core/cms_frame_header.blade.php, resources/views/plugins/manage/manage.blade.php
419エラー時は、自動リダイレクト（NC2と同様の動き）＋入力保持＋画面上部にエラーメッセージ表示で対応します。
要件等
なし
* セッション切断時にPOST通信をし419エラーになるのを防ぐ方法
https://zenn.dev/yuzuyuzu0830/articles/3952e36dc91705
なし
=> [コア] トークンの時間切れ（419エラー）時は自動で画面再表示（自動リダイレクト）

resources/views/plugins/user/forms/default/forms.blade.php, resources/views/plugins/user/forms/default/forms_confirm.blade.php, resources/views/plugins/user/forms/default/include_error_multiple_group.blade.php
* https://github.com/opensource-workshop/connect-cms/issues/1039
上記の不具合対応です。500エラーを出さないようにする＋エラーメッセージ表示をするようにしました。
※ ２つエラーメッセージ表示されるのはご愛敬。
※ 権限なしだとエラーメッセージ表示しない。
なし
概要に記載
なし
なし
=> [フォーム] まとめ行を入れ子にするとエラーになる不具合対応

app/Plugins/User/Forms/FormsPlugin.php
まとめ行に必須チェックを設定できるが、まとめ行自体に入力項目がない＋入力時にエラーチェックにひっかかりフォームが登録できない状態でした。
そのため、いったんまとめ行の必須チェックはさせないよう対応しました。
（プログラム内コメントに「まとめ行以外の項目について、バリデータールールをセット」とありましたので、本来はまとめ行の入力チェックをしない事を想定していたと思われます。）
なし
* https://github.com/opensource-workshop/connect-cms/issues/1037
なし
なし
=> [フォーム] まとめ行の必須チェックは一旦させない

app/Traits/Migration/MigrationTrait.php
移行ツールのインポートコマンドにはredo（やり直し）オプションがありますが、未設定でもtargetとなるccデータが全削除されていました。
そのため、redo=trueの時のみクリアするよう修正しました。
```
php artisan command:ImportSite all           ← クリアしないように変更。
php artisan command:ImportSite all redo   ←今までと動作変わらず、クリアされる。
```
```
$ php artisan command:ImportSite all {redo}  
$ php artisan command:ImportSite uploads {redo}  
$ php artisan command:ImportSite categories {redo}  
$ php artisan command:ImportSite users {redo}  
```
なし
なし
* https://github.com/opensource-workshop/connect-cms/wiki/Migration-from-NC2
なし
=> [移行ツール] インポートコマンド実行時、redoオプション未設定でもtargetのデータが消える不具合修正

resources/views/plugins/common/errors_inline.blade.php
・件名通りです。
・通常通り、1項目１入力エラーの表示もいままで通り表示されます。
なし
なし
なし
なし
=> [エラー表示] 同じ項目で2つ以上入力エラーがあった場合に表示できるよう対応

app/Plugins/Manage/UserManage/UserManage.php, resources/views/plugins/manage/user/auto_regist.blade.php
* いままで承認完了メールは、サイト名・ログインIDの2種類しか埋め込みタグを対応していませんでした。
本登録メールでは、ユーザー名等の他項目も埋め込みタグが利用できましたので、同等の対応をしました。
* 関連対応
* 管理者の承認(必要・不要)で、不要であれば、承認完了メール件名・本文を非表示するよう対応しました。
なし
なし
なし
なし
=> [ユーザ管理] 承認完了メールの埋め込みタグに本登録メールと同じものを実装

app/Http/Controllers/Core/CookieCore.php, resources/views/layouts/app.blade.php, resources/views/plugins/manage/message/message.blade.php
初回確認メッセージは、サイト表示時にクッキー情報の利用などの同意を確認するために使える機能です。
メッセージ内容は、変更されることがありますが、変更したら以前同意した人にも再度同意をする必要があるため、当対応をしました。
* 「メッセージ内容 `message_first_content`」の更新日のタイムスタンプをクッキーにセット
* 「メッセージ内容」の更新日のタイムスタンプより、クッキーのタイムスタンプが古ければ、再度メッセージ表示
* クッキーのタイムスタンプが古いチェックは `Cookie::get('connect_cookie_message_first') < CookieCore::getCookieForMessageTimestamp()` でやっていて、同意済みの古いクッキーの値 'agreed' を比較すると `'agreed' < タイムスタンプのint値`  で 文字列はintに暗黙キャストで `0 < タイムスタンプのint値` と比較されてtrueで、再度メッセージが表示されることを確認済み。
* クッキーのタイムスタンプが古いチェック
https://github.com/opensource-workshop/connect-cms/pull/1946/files#diff-66a3ba2334a6e1eebc24807619f1d4e991f1e8f58c5b5af2c787198d62c547d7R348
* 備考
* 初回確認メッセージ画面で、「メッセージ内容」が1文字も変わらなければ、「メッセージ内容」の更新日は変わらない。
* 「メッセージ内容」が空でも、DBレコードは出来るため、「メッセージ内容」の更新日は取得可能。 …
=> [メッセージ管理] 初回確認メッセージを更新した場合、以前同意済みでも再度初回メッセージを表示する対応 OW-1965

resources/views/auth/passwords/email.blade.php, resources/views/auth/passwords/reset.blade.php
* 件名通りです。
* 関連修正
* 入力エラー時の表示を共通部品を使う
なし
なし
なし
無し
=> [パスワードリセット] 新しいパスワードの項目名をプロフィール変更と同じに見直し

app/Http/Controllers/Auth/RegistersUsers.php, app/Plugins/Manage/UserManage/UserManage.php, resources/views/plugins/manage/user/auto_regist.blade.php
下記対応です。
* https://github.com/opensource-workshop/connect-cms-ideas/issues/167
* 関連対応
* [change: 自動ユーザ登録設定, 項目の入力エラー表示で共通部品を使う](https://github.com/opensource-workshop/connect-cms/pull/1952/commits/9b5814debf7f8738a881b5c511d5eb4dbada39db)
* [change: 自動ユーザ登録設定, ラジオでON・OFF時、左側はOFFで統一する](https://github.com/opensource-workshop/connect-cms/pull/1952/commits/299475815762991e2fdf42457db0198fcfeb1ffa) 
https://github.com/opensource-workshop/connect-cms/issues/737
なし
概要に記載
なし
無し
=> [ユーザ登録] 登録後の自動ログイン

app/Enums/ResizedImageSize.php, resources/views/plugins/manage/site/pdf/base_wysiwyg.blade.php
今まで、Connect-CMSをインストール時にSeederで設定している、wysiwygの初期画像サイズは「原寸大」でした。
wysiwygは、固定記事やブログ、掲示板等、多岐にわたり利用されるワープロ機能ですが、意識せず画像を「原寸大」のままアップロードし続けると、サーバーのディスク容量を圧迫します。
そのため、学校ブログでアップロードされる画像サイズを考慮して、初期画像サイズを「小」に変更しました。
※ インストール時にDB設定される値（Seeder）の変更ですので、すでにインストール済みConnect-CMSには影響ありません。
※ インストール後は、管理者メニューから初期画像サイズを変更できます。https://manual.connect-cms.jp/manage/site/wysiwyg/index.html
原寸 1.83MB jpg
大  214KB
中  112KB
小   38KB
極小 13KB
なし
なし
なし
なし
=> [wysiwyg] インストール時「初期に選択させる画像サイズ」を小に変更

app/Models/Common/Uploads.php, app/Plugins/Manage/CodeManage/CodeManage.php, app/Plugins/Manage/PageManage/PageManage.php, app/Plugins/Manage/UserManage/UserManage.php, app/Plugins/User/Calendars/CalendarsPlugin.php, app/Plugins/User/Databases/DatabasesPlugin.php, app/Plugins/User/Learningtasks/LearningtasksPlugin.php, app/Utilities/Csv/CsvUtils.php, app/Utilities/File/FileUtils.php, resources/views/plugins/user/learningtasks/default/learningtasks_import_examinations.blade.php
開発者向けアップデートで、共通メソッド setlocale の追加です。
setlocale()はxampp(win)とLinuxとで、対応が若干異なっていて、xamppのみでfgetcsv()使用時にエラーが出る場合がありましたので、共通メソッドで対応するようにしました。
なし
なし
・Japanese Moodle: ユーザの一括登録に関して | Moodle.org
https://moodle.org/mod/forum/discuss.php?d=383085
> XAMPP 7.1.26で確認したのですが、下記ブログ記事にあるとおり fgetcsv() で日本語などが含まれると正常にカンマなどの区切り文字を認識できないためカラム数がおかしくなりエラーとなっています。
> http://iamapen.hatenablog.com/entry/2017/08/10/134224
・PHP: setlocale - Manual
https://www.php.net/manual/ja/function.setlocale.php
・locale
// win
[MS-LCID]: Appendix A: Product Behavior | Microsoft Learn
https://learn.microsoft.com/en-us/openspecs/windows_protocols/ms-lcid/a9eac961-e77d-41a6-90a5-ce1a8b0cdb9c
> (表列)Language tag ＞ ja-JP
// CentOS7
ja_JP.UTF-8
なし
=> [Utils] setlocale()のwin & linux対応

resources/views/plugins/user/slideshows/default/slideshows.blade.php
ファーストビューに画像の遅延読み込みがあると、描画が遅くなります。
そのため、ファーストビューで使われることが多いスライドショーの一枚目の画像について遅延読み込みをしないようにしました。
無し
=> [スライドショー]初期表示の速度を改善しました

.github/workflows/laravel_dusk.yml, .github/workflows/laravel_dusk_connect-cms-test-matrix.yml, .github/workflows/laravel_dusk_connect-cms-test.yml, .github/workflows/laravel_dusk_daily.yml, .github/workflows/phpcs.yml, .github/workflows/wiki.yml
開発向けアップデートです。
github actionで警告メッセージが表示されていたため対応しました。
Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: actions/checkout@v3, actions/cache@v3, actions/upload-artifact@v3. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.
https://github.com/opensource-workshop/connect-cms/actions/runs/7984164693
なし
なし
* https://github.com/actions/checkout
* https://github.com/actions/cache
* https://github.com/actions/upload-artifact
無し
=> [github action] 警告メッセージ対応（Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20）

phpunit.xml
開発者向けアップデートです。
phpunit実行時にWarningが出ていましたので、設定ファイルをコマンドを使って新バージョンに自動更新しました。（どうやら設定ファイルの内容が古かったみたい）
```php
PS C:\projects\connect-cms\connect-cms\htdocs\connect-cms> composer phpunit -- tests/Unit/xxxx
> phpunit tests/Unit/xxxx
PHPUnit 9.6.15 by Sebastian Bergmann and contributors.
Warning:       Your XML configuration validates against a deprecated schema.
Suggestion:    Migrate your XML configuration using "--migrate-configuration"!
.....                                                               5 / 5 (100%)
Time: 00:09.463, Memory: 44.00 MB
OK (5 tests, 19 assertions)
```
```php
PS C:\projects\connect-cms\connect-cms\htdocs\connect-cms> composer phpunit -- --migrate-configuration         
> phpunit --migrate-configuration
PHPUnit 9.6.15 by Sebastian Bergmann and contributors.
Created …
```
=> [phpunit] Warning:Your XML configuration validates against a deprecated schema.対応

public/css/option/.gitignore, resources/views/layouts/app.blade.php
オプションプラグインのCSSファイル読み込みを追加しました。
public/css/option配下にあるcssファイルを対象にします。
オプションプラグインのCSSよりテーマのCSSを優先したいため、読み込み順をテーマより先にしています。
2/29
無し
=> [コア]オプションプラグインのCSSファイル読み込みを追加しました

app/Plugins/User/Bbses/BbsesPlugin.php, app/Plugins/User/Blogs/BlogsPlugin.php, app/Plugins/User/Cabinets/CabinetsPlugin.php, app/Plugins/User/Calendars/CalendarsPlugin.php, app/Plugins/User/Contents/ContentsPlugin.php, app/Plugins/User/Conventions/ConventionsPlugin.php, app/Plugins/User/Counters/CountersPlugin.php, app/Plugins/User/Databases/DatabasesPlugin.php, app/Plugins/User/Databasesearches/DatabasesearchesPlugin.php, app/Plugins/User/Faqs/FaqsPlugin.php, app/Plugins/User/Forms/FormsPlugin.php, app/Plugins/User/Knowledges/KnowledgesPlugin.php, app/Plugins/User/Learningtasks/LearningtasksPlugin.php, app/Plugins/User/Linklists/LinklistsPlugin.php, app/Plugins/User/Menus/MenusPlugin.php, app/Plugins/User/Opacs/OpacsPlugin.php, app/Plugins/User/Openingcalendars/OpeningcalendarsPlugin.php, app/Plugins/User/Photoalbums/PhotoalbumsPlugin.php, app/Plugins/User/Reservations/ReservationsPlugin.php, app/Plugins/User/Rsses/RssesPlugin.php, app/Plugins/User/Searchs/SearchsPlugin.php, app/Plugins/User/Slideshows/SlideshowsPlugin.php, app/Plugins/User/Tabs/TabsPlugin.php, app/Plugins/User/Whatsnews/WhatsnewsPlugin.php
プラグインの設定アイコンをクリックした際、バケツの編集画面が開くケースとフレームの設定画面が開くケースがりました。
必要な操作を素早く実行できるように。という意図をもって、プラグイン毎にプラグインの設定アイコンをクリックした際に開く画面を変えられるようにしていました。
しかし、この動きが原因となり、意図せずにバケツを削除し、ブログやカレンダーなどのデータを消してしまうという誤操作が複数あったため、画面の動きを見直しました。
プラグインの設定アイコンをクリックした際はフレームの編集画面が開くことにより、そのまま勢いでの削除を押すという誤操作は防げるようになることを期待しています。
無し
=> [プラグイン全般]プラグインの設定アイコンで開く画面をフレーム編集に統一しました。

public/js/tinymce/plugins/image/plugin.min.js, resources/views/plugins/common/wysiwyg.blade.php
詳細設定タブで保存ボタンを押すと、パラメータに画像サイズが設定されないのが原因でした。
下記コードで値を設定していましたが、詳細設定タブを開くと一般タブの要素はすべて入れ替わるため、値を設定できていませんでした。
`document.getElementById('cc-resized-image-size-' + frame_id).value = jQuery('.tox-listbox--select')[0].dataset.value`
そこで、以下のように修正しました。
`document.getElementById('cc-resized-image-size-' + frame_id).value = event.value.resize;`
併せて、TinyMCEのコードも修正し、event.valueに画像サイズのデータを追加しました。
この修正により詳細設定タブでも画像サイズがサーバーに送信されます。
#1961 
無し
=> [WYSIWYG]画像ダイアログの詳細タブで保存すると画像がリサイズされない問題を修正しました

app/Plugins/Manage/UserManage/UserManage.php
CSVインポート処理で必須項目であるusers.columns_set_idを設定する処理がなかったため、SQLエラーになっていました。
そのため、users.columns_set_idを設定する処理を追加しました。
更新時にはすでにusers.columns_set_idが設定されているためにエラーとならず、新規登録時のみエラーとなっていました。
バグのためなるべく早めにお願いします
#1965
無し
=> [ユーザ管理]インポートの新規登録でシステムエラーとなる問題を修正しました

resources/views/plugins/mypage/index/index.blade.php, resources/views/plugins/mypage/menus_list.blade.php, resources/views/plugins/mypage/profile/profile_mypage_tab.blade.php
実質と画面名がずれていたため、画面名を修正します。
左側メニュー「マイページ」を「プロフィール」に、「プロフィール」を「プロフィール変更」に変更します。
（修正前：左メニュー）
マイページ：実質プロフィールの確認画面
プロフィール：実質プロフィール変更画面
なし
なし
なし
なし
=> [マイページ] マイページトップページとプロフィールページの画面名変更

resources/views/plugins/manage/user/list_include_value.blade.php
php8時のバグ修正です。
なし
* https://github.com/opensource-workshop/connect-cms/issues/1200
なし
なし
=> [ユーザ管理] ユーザ一覧表示時にユーザ項目の複数選択肢がnull時のphp8対応

app/Plugins/Manage/PageManage/PageManage.php, resources/views/plugins/manage/page/page_form.blade.php
* #734
ページ変更画面の「クラス名」の名称がわかりずらかったため、現状の機能と合わせるために「メニュークラス名」に変更しました。
なし
概要に記載
なし
なし
=> [ページ管理] ページ変更画面のクラス名の名称変更

app/Enums/DatabaseFrameConfig.php, app/Plugins/User/Databases/DatabasesPlugin.php, resources/views/plugins/user/databases/default/databases.blade.php, resources/views/plugins/user/databases/default/databases_edit_view.blade.php, resources/views/plugins/user/databases/default/databases_include_page_total_views.blade.php, resources/views/plugins/user/databases/default/databases_include_view_count.blade.php, resources/views/plugins/user/databases/design-table-dl/databases.blade.php
データベースの表示件数を閲覧者がセレクトボックスで変更できるようにしました。
あわせて、いま何件表示しているかわかりやすくするため、件数表示機能も追加しました。
表示設定画面で、表示可否を選択できます。
無し
=> [データベース]閲覧者による表示件数の変更機能を追加しました

app/Plugins/User/Forms/FormsPlugin.php, resources/views/plugins/user/forms/default/forms.blade.php, resources/views/plugins/user/forms/default/forms_confirm.blade.php, resources/views/plugins/user/forms/default/forms_confirm_tandem.blade.php, resources/views/plugins/user/forms/default/forms_confirm_token.blade.php
フォームには登録後画面を再表示すると、重複してデータが登録される事がありました。
今回の対応は、登録後画面を再表示しても、重複したデータが登録されないようにするための対応です。
なし
* https://github.com/opensource-workshop/connect-cms/issues/856
なし
なし
=> [フォーム] 登録時のリダイレクト対応

app/Plugins/Api/Nc2Sso/Nc2Sso.php, app/Plugins/Manage/UserManage/UserManage.php, app/Plugins/Manage/UserManage/UsersTool.php
* https://github.com/opensource-workshop/connect-cms/pull/1792
上記対応時に含まれた不具合です。
その不具合を修正しました。
なし
概要に記載
なし
無し
=> [API] NC2からのSSOで自動ユーザ作成時に500エラー対応

resources/views/plugins/user/forms/default/index_captcha.blade.php
- クライアントから指摘あり
```
リリースいただきましたCAPTHA機能画面で、
入力ボックスの下部にある以下の文章を修正いただくことはできますでしょうか。
旧：画像の文字を入力してください。
新：画像の文字を入力してください。次の画面でお問合せ内容を入力することができます。
```
- ページ訪問者は「問い合わせ」や「〇〇申請」等のリンク文字を頼りに画面遷移してくることが多いと思われる為、リンク先開いていきなり「文字入力せよ」は面食らう印象はありそう。故に「これ入力したらその先に目的地があるよ」は分かった方が、変に誤解して離脱する人もいなくなりそうではある為、テキストを微修正します。
- ただ、「お問合せ」という文言は少し具象的（フォームの種々使い方の一部分に若干寄り気味）な気がするので、「フォーム」という文言にします。
- 新テキスト案：画像の文字を入力してください。次の画面でフォーム内容を入力することができます。
なし
なし
なし
なし
=> [フォーム] CAPTCHAの注釈テキストに追記

app/Plugins/User/Forms/FormsPlugin.php
- クライアントから指摘あり。より明示的で次の所作がわかりやすい為、そのまま採用します。
```
画像認証画面で、入力をミスした場合に表示されるエラーメッセージを、
画像認証には正しい画像の文字を指定してください。
→ 画像上に表示されている正しい文字を入力してください。
のようにご修正いただくことはできますでしょうか。
（※「指定」ではなく「入力」としていただきたい点と、
　　「正しい」がかかる言葉を、近くに置きたい、という主旨でのご依頼です。）
```
なし
なし
なし
=> [フォーム] キャプチャのバリデーションメッセージ修正

app/Plugins/Manage/CodeManage/CodeManage.php, app/Plugins/Manage/UserManage/UserManage.php, app/Plugins/User/Counters/CountersPlugin.php, app/Plugins/User/Databases/DatabasesPlugin.php, app/Plugins/User/Forms/FormsPlugin.php, app/Plugins/User/Learningtasks/LearningtasksPlugin.php, app/Plugins/User/Opacs/OpacsPlugin.php
```
content-Disposition
↓
Content-Disposition
```
ヘッダー指定の大文字・小文字の修正です。
動作に変わりありません。
なし
なし
* https://developer.mozilla.org/ja/docs/Web/HTTP/Headers/Content-Disposition
無し
=> CSVダウンロードのヘッダー指定の大文字・小文字修正

database/seeders/DefaultConfigsTableSeeder.php
インストール時に以下のログは初期値で取得するようにしました。
・ログイン・ログアウト
・メール送信
・パスワード関係
・ユーザ登録
無し
=> [ログ管理]インストール時に初期値で取得するログの設定を追加しました。

app/Plugins/User/Slideshows/SlideshowsPlugin.php, resources/views/plugins/user/slideshows/default/slideshows_edit_row.blade.php
```
管理画面のアップロードファイルから、スライドショーにアップされた画像を削除すると、
スライドショーデータの方にゴミが残ってしまうが、編集画面から当該データを削除できなくなる。
```
項目設定画面用のスライドショーの子テーブル（slideshows_items）抽出時、
アップロードテーブルと内部結合していた為、
アップロード管理等で削除すると表示されなくなっていた
- アップロードテーブルとの結合を外部結合にする
- アップロードテーブル取得できない場合は明示的にno_image画像を表示するよう画面側も修正
- ブラウザキャッシュで画像表示されるケースがあり、画像の有無が項目一覧から判別できなくなる為。
バグなのでなるはや
なし
なし
=> [スライドショー] アップロード管理等でファイル削除時、スライドショー管理画面でレコードが表示されなくなるのを修正

app/Plugins/User/Calendars/CalendarsPlugin.php, resources/views/plugins/user/calendars/default/edit.blade.php
予定を新規で登録する際、開始日時・終了日時の初期値を以下のように変更します。
**変更前**
- 開始日時：空白（テキストボックスを選択すると現在時刻が選ばれる）
- 終了日時：空白（テキストボックスを選択すると現在時刻が選ばれる）
**変更後**
- 当日の予定
- 開始日時：現在時刻から1時間後の00分
- 終了日時：現在時刻から2時間後の00分
- 当日以外の予定
- 開始日時：09:00
- 終了日時：10:00
例えば、現在時刻が18:15の場合、以下のようになります。
開始日時 ⇒ 19:00
終了日時 ⇒ 20:00
- カレンダーの予定には00分以外の分（12分など1分単位の値）を入力することが少ない
- 現在時刻の予定を入力することは少ない
無し
=> [カレンダー]開始日時・終了日時の初期値を利用しやすい時刻にしました

routes/web.php
* https://github.com/opensource-workshop/connect-cms/issues/2019
上記不具合対応です。
パスワード付ページではURLの末尾ページIDが必須だったため、処理を見直しました。
http://localhost/password/input
なし
概要に記載
なし
なし
=> [パスワード付ページ] 末尾のページIDを消して表示すると500エラー対応

app/Models/Common/Buckets.php, app/Models/Common/Frame.php, database/factories/Common/BucketsFactory.php, database/factories/Common/FrameFactory.php
開発者用アップデートです。
Bucktes, Frameモデルにテストデータを自動生成するFactoryクラスを追加しました。
なし
なし
なし
なし
=> [単体テスト] Bucktes, FrameにFactory追加

app/Console/Kernel.php
- Kernelに毎分実行用のスケジュール読込処理がなかった為、これを追加しました。
7/5（金）
なし
なし
なし
=> [コア] Kernelに毎分実行用のオプションバッチスケジュール処理を追加

database/factories/UserFactory.php
開発者用の修正です。
factoryで作成されるUserのテストデータで、ログインIDはDB制約によりユニークにする必要があります。
テストデータを自動生成時にログインIDが重複すると、テストケースと関係なくエラーで落ちるため、修正しました。
なし
なし
なし
なし
=> [テスト] UserFactory, テストデータでログインIDはユニークにする必要あり

app/Plugins/User/Photoalbums/PhotoalbumsPlugin.php
- フォトアルバムにアップロード画像のリサイズ機能がありますが、リサイズ設定（例えば極小）をしても、管理機能－アップロードファイルの一覧に表示される「サイズ」には原寸サイズが表示されていました。
- ※実体ファイルはリサイズされており、表記のみ誤りがある。
- フォトアルバムからのアップロード時、リサイズ後のサイズをuploadsに登録するよう修正
8/28（水）
https://github.com/opensource-workshop/connect-cms/issues/2037
なし
なし
=> [フォトアルバム] リサイズ設定をしてアップロードしても、アップロードファイル一覧の「サイズ」に原寸サイズが表示されているのを修正しました

.env.example, config/connect.php, resources/views/layouts/app.blade.php, resources/views/plugins/manage/index/index.blade.php
サイトのサポートをするURLがある場合に記述できるようにしました。
このURLは以下の2か所で表示されます。
・管理者メニューのトップ
・ログイン後のヘッダーメニュー
また、サポートページがパスワード付きページに設定されている場合、パスワードも表示するようにしています。
サポートページの設定は.envで行います。
.env.exampleに書き方として以下を追加しました。
＃support info (If there is a support URL and if a viewing password is required.) 
＃INDIVIDUAL_SUPPORT_URL=
＃INDIVIDUAL_SUPPORT_PASSWORD=
なるはやを希望
無し
=> 個別サポートURL情報の表示機能を追加

config/database.php
開発者向けの修正です。
ConnectのDBとは別に、外部のSQL ServerとDB接続するための、DB接続情報を.envで設定できるようにしました。
```.env
SQLSRV_DB_HOST=localhost
SQLSRV_DB_PORT=1433
SQLSRV_DB_DATABASE=forge
SQLSRV_DB_USERNAME=forge
SQLSRV_DB_PASSWORD="forge"
```
CentOS＋remiの場合
```shell
--- remi, epelを導入
yum list installed | grep epel
yum install http://rpms.remirepo.net/enterprise/remi-release-7.rpm
--- php8.1インストール(remi)
yum install --enablerepo=epel,remi-safe php81-php php81-php-devel php81-php-mbstring php81-php-mysqlnd php81-php-xml php81-php-gd php81-php-bcmath php81-php-fpm php81-php-zip php81-php-opcache
```
```shell
#Download appropriate package for the OS version
#Choose only ONE of the following, corresponding to your OS version
#RHEL 7 and Oracle Linux 7
curl https://packages.microsoft.com/config/rhel/7/prod.repo | sudo tee …
```
=> [コア] 外部のsqlsrvに繋ぐDB設定を追加

app/Plugins/Manage/SecurityManage/SecurityManage.php, resources/views/plugins/manage/security/loginpermit.blade.php, resources/views/plugins/manage/security/purifier.blade.php
* https://github.com/opensource-workshop/connect-cms/issues/737
上記対応です。
なし
概要に記載
なし
無し
=> [セキュリティ管理] ラジオでON・OFF時、左側はOFFで統一する

app/Plugins/User/Bbses/BbsesPlugin.php, app/Plugins/User/Faqs/FaqsPlugin.php, app/Plugins/User/Learningtasks/LearningtasksPlugin.php
- （掲示板）（FAQ）動確済み
- （課題管理）サイト内検索の対象外なので動確未
https://github.com/opensource-workshop/connect-cms/issues/2067
11/22（金）
https://github.com/opensource-workshop/connect-cms/issues/2067
なし
なし
=> [サイト内検索] 多言語モード採用時、対象言語ページの絞り込みが効かないバグを修正

resources/views/plugins/user/databases/default/databases_edit_row_detail.blade.php
* https://github.com/opensource-workshop/connect-cms/issues/737
上記の修正です。
なし
概要に記載
なし
無し
=> [データベース] 項目設定＞項目詳細設定＞DBカラム設定, ラジオでON・OFF時、左側はOFFで統一する

tests/Browser/Manage/GroupManageTest.php
開発者向け修正です。
下記修正に含まれていた、グループ登録時のボタン名修正をした影響で、テストでエラーになっていたため、修正しました。
* 下記修正
* https://github.com/opensource-workshop/connect-cms/pull/2071
* テストでエラー
* https://github.com/opensource-workshop/connect-cms/actions/runs/11937190694/job/33272584802
https://github.com/opensource-workshop/connect-cms/actions/runs/11944885264
エラー解消を確認しました。
なし
概要に記載
なし
なし
=> [テスト] GroupManageTest, グループ登録時のテスト修正

app/Enums/ContentOpenType.php, resources/views/core/cms_frame_edit.blade.php
* #737 
* リファクタリング
* #1785
上記の修正です。
なし
概要に記載
なし
なし
=> [プラグイン共通] フレーム編集のラジオでON・OFF時、左側はOFFで統一する

resources/views/plugins/user/bbses/default/bucket.blade.php, resources/views/plugins/user/searchs/default/searchs_edit_search.blade.php
* https://github.com/opensource-workshop/connect-cms/issues/737
上記の修正です。
なし
概要に記載
なし
無し
=> [掲示板][サイト内検索] 歯車＞新規作成, ラジオでON・OFF時、左側はOFFで統一する

resources/views/plugins/user/databases/default/databases_edit_database.blade.php, resources/views/plugins/user/photoalbums/default/frame.blade.php, resources/views/plugins/user/slideshows/default/slideshows_edit_slideshow.blade.php, resources/views/plugins/user/whatsnews/default/whatsnews_edit_whatsnew.blade.php, resources/views/plugins/user/whatsnews/default/whatsnews_frame.blade.php
* https://github.com/opensource-workshop/connect-cms/issues/1785
上記修正です。
https://github.com/opensource-workshop/connect-cms/actions/runs/12021772987/job/33512856001
php8.2で画面表示にエラーがない事を確認しました。
（※ Connect1.x系のため、実際にはphp8.2はメール処理が動かないです。）
急ぎません
概要に記載
なし
無し
=> [PHP8.2] Using ${var} in strings is deprecated fix

resources/views/core/cms_frame_edit.blade.php
* #2074
上記不具合の修正です。
vue＋datetimepicker同時使用で不具合でした。
・vueは正常動作。
・使用しているdatetimepickerで初期表示時にreadonlyを強制解除されていました。
・datetimepicker定義後に、追加で公開日時From、Toをreadonlyする処理を追加して対応しました。
https://github.com/user-attachments/assets/2e28d96e-7b6c-409c-ae74-a32f99c78409
急ぎません
概要に記載
* https://github.com/tempusdominus/bootstrap-4/issues/362
無し
=> [フレーム編集] 公開日時From、Toが限定公開以外でも入力できる不具合修正

app/Plugins/Manage/ReservationManage/ReservationManage.php, resources/views/plugins/manage/reservation/bookings.blade.php
* https://github.com/opensource-workshop/connect-cms-ideas/issues/177
上記の対応です。
なし
概要に記載
* https://github.com/opensource-workshop/connect-cms/wiki/Datetimepicker
* https://getdatepicker.com/5-4/Options/#date
* https://momentjs.com/docs/#/displaying/format/
* https://developer.mozilla.org/ja/docs/Web/CSS/overflow
無し
=> [施設管理] 予約一覧の絞込条件に利用日を追加 OW-2441

app/Plugins/User/Faqs/FaqsPlugin.php
- FAQプラグインの詳細画面で前へ／次へボタン押下時、投稿日時が同値のデータが飛ばされる事象があった為、これの解消対応です。
バグなので早目がよいかと思います。
* https://github.com/opensource-workshop/connect-cms/issues/2082
* https://github.com/opensource-workshop/connect-cms/blob/master/app/Plugins/User/Blogs/BlogsPlugin.php `show()`
なし
=> [FAQ] 投稿日時が同値の場合、前へ／次へボタンで同値の投稿が飛ばされて表示される

app/Traits/ConnectRoleTrait.php
開発者向け修正です。
ConnectRoleTrait::choiceUserRolesOrPageRoles()で$user->user_rolesがnullの場合の再取得する処理を追加しました。
元々はapp\Providers\ConnectEloquentUserProvider::judgmentLogin()で画面ログイン時の入力チェックで $user->user_roles をセットしていましたが、API時は未セットだったため、ConnectRoleTrait::choiceUserRolesOrPageRoles()側で対応しました。
なし
なし
無し
=> [Trait] ConnectRoleTrait::choiceUserRolesOrPageRoles()で$user->user_rolesがnullの場合の再取得する処理を追加

.github/workflows/laravel_dusk_connect-cms-test-matrix.yml, .github/workflows/laravel_dusk_connect-cms-test.yml
Connect 2.x系のDuskテストがgithub actionsのエラーで動かなくなっていました。
エラーは RuntimeException: Invalid path to Chromedriver で対応しました。
```shell
Run php artisan dusk tests/Browser/Manage/LogManageTest.php no_manual
Warning: TTY mode requires /dev/tty to be read/writable.
PHPUnit 9.6.21 by Sebastian Bergmann and contributors.
E                                                                   1 / 1 (100%)
Time: 00:00.002, Memory: 10.00 MB
There was 1 error:
1) Tests\Browser\Manage\LogManageTest::testInvoke
RuntimeException: Invalid path to Chromedriver [/home/runner/work/connect-cms/connect-cms/vendor/laravel/dusk/src/Chrome/../../bin/chromedriver-linux]. Make sure to install the Chromedriver first by running the dusk:chrome-driver command. in /home/runner/work/connect-cms/connect-cms/vendor/laravel/dusk/src/Chr …
```
=> [GitHub Actions] DuskテストのInvalid path to Chromedriver対応

.github/workflows/laravel_dusk_connect-cms-test-matrix-daily.yml, .github/workflows/laravel_dusk_connect-cms-test-matrix.yml, .github/workflows/laravel_dusk_connect-cms-test.yml
Connect 1.x系のDuskテストがgithub actionsのエラーで動かなくなっていました。
エラーは Facebook\WebDriver\Exception\UnknownErrorException: unknown error: Chrome failed to start: crashed. で対応しました。
```shell
Run php artisan dusk tests/Browser/Manage/LogManageTest.php no_manual
Warning: TTY mode requires /dev/tty to be read/writable.
PHPUnit [9](https://github.com/opensource-workshop/connect-cms/actions/runs/12483864336/job/34840363665#step:23:10).6.21 by Sebastian Bergmann and contributors.
E                                                                   1 / 1 ([10](https://github.com/opensource-workshop/connect-cms/actions/runs/12483864336/job/34840363665#step:23:11)0%)
Time: 00:03.198, Memory: 28.00 MB
There was 1 error:
1) Tests\Browser\Manage\LogManageTest::testInvoke …
```
=> [GitHub Actions] Connect 1.x系のDuskテストのChrome failed to start: crashed. 対応

resources/views/plugins/user/blogs/default/blogs.blade.php
* https://github.com/opensource-workshop/connect-cms/issues/2085
上記issueの修正です。
https://github.com/opensource-workshop/connect-cms/commit/32157c5835f148358cb5317b52e05842c6f3e7d0
該当箇所はブログのアクセシビリティ対応で入れた修正でした。
しかし、アクセシビリティとclassありなしは関係ないので、最後の記事にもclassを追加しました。（最後の記事の下に下線が付くのを気にしてclass抜いたのかもです）
なし
概要に記載
なし
無し
=> [ブログ] 最後の記事だけクラス属性が付与されない不具合修正

app/Plugins/User/Blogs/BlogsPlugin.php, app/Utilities/String/StringUtils.php
* https://github.com/opensource-workshop/connect-cms/issues/2086
上記を修正しました。
記事の中に → (&rarr;) があってもRSSが表示できることを確認しました。
なし
概要に記載
* PHPエラー対処方法「RSSをXML取得時に不正文字が存在する場合」
https://deaimobi.com/mbnk-264/
無し
=> [ブログ] 記事の中に → (&rarr;) があると「RSS2.0」アイコンをクリック時にエラーになる不具合対応

app/Plugins/Manage/GroupManage/GroupManage.php
* https://github.com/opensource-workshop/connect-cms/issues/1898
上記の対応です。
グループ削除時に、関連するページ権限、グループユーザーのみが論理削除される事を目検しました。
なし
概要に記載
なし
無し
=> [グループ管理] グループ削除時に、関連するページ権限・グループユーザーを削除する

app/Plugins/Manage/UserManage/UserManage.php, app/Plugins/Manage/UserManage/UsersTool.php
開発者向けの対応です。
ユーザ管理＞ダウンロードの出力値を、独自に設定できるよう対応しました。
app\PluginsOption\Manage\UserManage\UsersToolOption.php に getUsersInputColValue() メソッドを作ることで、独自の出力値に変更できます。
（ここでダウンロードの出力値を変更できますが、同時にインポートできない値（DB登録値とは異なる値）になりますので、ユーザ管理＞インポートを使用しない前提での変更になります）
なし
* https://github.com/opensource-workshop/connect-cms/pull/1906
なし
無し
- [x ] プルリクエストにわかりやすいタイトルとラベルを付けました。https://github.com/opensource-workshop/connect-cms/wiki/Pull-requests-Rule
=> [ユーザ管理] ダウンロードの出力値をカスタマイズできるように対応

.github/workflows/laravel_dusk_connect-cms-test-matrix-daily.yml, .github/workflows/laravel_dusk_connect-cms-test-matrix.yml, .github/workflows/laravel_dusk_connect-cms-test.yml, .github/workflows/phpcs.yml, composer-dev.lock, composer.json, composer.lock
composerの [league/commonmark](https://github.com/thephpleague/commonmark) に対するアップデート対応です。
なし
なし
なし
なし
=> build(deps): bump league/commonmark from 1.6.7 to 2.6.1

sync_dev_2_option_private.sh.example, sync_option_private_2_dev.sh.example
* sync_dev_2_option_private.sh.example
* sync_option_private_2_dev.sh.example
上記のoption_plugin_resources_dir変数に対して、以前記載のあった小文字変換を復活させました。
なし
なし
なし
なし
=> [サンプルコピーシェル] option_plugin_resources_dirの全小文字変換に対応

database/migrations/2025_02_04_092725_change_value_from_reservations_inputs_columns.php
公式掲示板で報告のあった不具合修正です。
https://connect-cms.jp/plugin/bbses/show/106/233/965#frame-233
なし
なし
なし
あり
=> [施設管理] 補足に256文字以上を登録すると500エラーになる不具合修正

app/Plugins/User/Forms/FormsPlugin.php, app/Utilities/Csv/CsvUtils.php
CSV出力時、項目にダブルクォーテーションが含まれる場合、正しくエスケープするよう修正しました。
ExcelなどのスプレッドシートソフトでCSVを開いた際に、ダブルクォーテーションが正しく表示されない問題を解決するため。
- ダブルクォーテーションをエスケープする処理を追加しました。
- ダブルクォーテーションを含むCSVを出力し、Excelで開いて正しく表示されることを確認しました。
CSVを出力する以下の機能に適応されます。
- コード管理
- ユーザ管理
- フォームプラグイン
- ~~カウンタープラグイン~~
- 項目にダブルクォーテーションが入ることはない 
- データベースプラグイン
- 課題管理プラグイン
- OPACプラグイン
無し
=> [コア]CSVの項目にダブルクォーテーションが含まれると正しく出力されない事象を修正しました

app/Enums/PageCvsIndex.php, app/Plugins/Manage/PageManage/PageManage.php
=> [ページ管理] 同じ固定リンクを登録できないように重複チェックを追加

app/Enums/UserStatus.php, app/User.php, resources/views/plugins/manage/user/import.blade.php
* [ユーザ管理] CSVインポート時の状態で承認待ち(4)に変更できないように修正
*  関連修正
* [change: ユーザ管理, CSVインポート時のエラー表示は、共通画面を使う](https://github.com/opensource-workshop/connect-cms/pull/2121/commits/b87a60753555f5a13dd85d0ece2d2a436691e6ef)
* [change: Userモデル, getStstusTemporaryDisabled()はクラス外から使われてないためprivateに変更](https://github.com/opensource-workshop/connect-cms/pull/2121/commits/41d7fdc06339844e973a821da141c402808fe784)
* [change: ユーザ管理, CSVインポートのインポートボタン下部の不要な余白削除](https://github.com/opensource-workshop/connect-cms/pull/2121/commits/03138a39cd923c69159ee464bd2015ecbba5a98c)
ユーザ変更で変更できるのは、利用不可(1)、利用可能(0)、仮削除(3)の３つ
ざっくりテストを実行、OK
https://github.com/opensource-workshop/connect-cms/actions/runs/13321167405
なし
なし
なし
なし
=> [ユーザ管理] CSVインポート時の状態で承認待ち(4)に変更できないように修正

app/Traits/Migration/MigrationTrait.php
大量のuploadsがあるNC2移行を実行時に、memory_limit=1Gを指定してもメモリ使用量オーバーエラーになるため、対応しました。
```shell
page_id,block_id,category,message
,,Start exportNc2.,
,,Start this->nc2ExportBasic.,
,,Start this->nc2ExportUploads.,
PHP Fatal error:  Allowed memory size of 1073741824 bytes exhausted (tried to allocate 20480 bytes) in /srv/public_html/example.com/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php on line 262
PHP Fatal error:  Allowed memory size of 1073741824 bytes exhausted (tried to allocate 65536 bytes) in /srv/public_html/example.com/vendor/composer/ClassLoader.php on line 576
```
```shell
page_id,block_id,category,message
,,importSite() Start.,
,,Basic import Start.,
,,uploads import Start.,
PHP Fatal error:  Allowed memory size of 1073741824 bytes exhausted (tried to allocate 20480 bytes) …
```
=> [NC2移行] メモリ使用量オーバー対応

database/migrations/2025_02_17_174343_add_target_source_table_and_source_key_index_from_migration_mappings.php
移行のインポート時に、既に移行済みか確認するテーブル MigrationMapping を1件1件参照していますが、DBインデックスがありませんでした。
DBインデックスを追加したところ、参照速度が改善されましたので、プルリクエストを作成しました。
```php
// マッピングテーブルの取得
$mapping = MigrationMapping::where('target_source_table', 'uploads')->where('source_key', $upload_key)->first();
```
```sql
SELECT * FROM `migration_mappings` WHERE target_source_table = 'uploads' and source_key = '11'; 
-- 行 0 - 0 の表示 (合計 1, クエリの実行時間： 0.0060 秒。) 
-- ↓index追加後
-- 行 0 - 0 の表示 (合計 1, クエリの実行時間： 0.0001 秒。) 
```
移行データ1件につき、1Selectしているため、
例えば10万件などの大量データの移行時、速度改善が期待できます。
なし
なし
なし
有り
=> [移行-インポート] DBインデックス追加によるパフォーマンス改善

app/Traits/Migration/MigrationTrait.php
* [移行インポート＞Groups] パフォーマンス改善
* [change: 移行インポート＞Groups, 数万件のデータ移行に対応するため、バルクINSERT／upsert対応](https://github.com/opensource-workshop/connect-cms/commit/74a495ec963ccbb064118fb312eb144118e0ef55)
* 他対応
* [bugfix: 移行インポート, フォトアルバムインポート時にUploadsが40万件程度あるとメモリオーバーになる不具合修正2](https://github.com/opensource-workshop/connect-cms/commit/b159f0d8cc9d9568dbd699b96a088977a5fc1ec4)
*  [add: 移行インポート, 移行時間計測追加](https://github.com/opensource-workshop/connect-cms/commit/0aaa9a8002dc648cf9c1cb010fe8ad031d8c8318)
* [add: 移行インポート, 1度検索したCCユーザIDはクラス変数に保持して再利用する](https://github.com/opensource-workshop/connect-cms/commit/9d77cffe17a11ab0b2ca44c2e75e84c4d130dcbf)
* [change: 移行インポート, 出力メッセージ「importSite() Start.」に import_base の内容を出力](https://github.com/opensource-workshop/connect-cms/commit/dc0d015f17c27ddfe776f2142792 …
=> [移行インポート＞Groups] 数万件のデータ移行に対応するため、バルクINSERT／upsert対応 他4件

app/Traits/Migration/MigrationTrait.php
移行インポートでユーザ移行時に「ユーザーのメールアドレスがRFC違反」チェックがあり、エラーメッセージを表示していましたが、エラーメッセージから、ユーザ移行されないように読めたため（実際はRFC違反でもユーザ移行される）、
ユーザ移行される旨をエラーメッセージに追記しました。
なし
なし
なし
なし
=> [移行インポート＞ユーザ移行] ユーザーのメールアドレスがRFC違反時のエラーメッセージ修正

public/themes/Defaults/Blue/wysiwyg/content_css.txt, public/themes/Defaults/CornflowerBlue/wysiwyg/content_css.txt, public/themes/Defaults/DarkBlue/wysiwyg/content_css.txt, public/themes/Defaults/DarkGoldenrod/wysiwyg/content_css.txt, public/themes/Defaults/DarkGreen/wysiwyg/content_css.txt, public/themes/Defaults/DarkOrange/wysiwyg/content_css.txt, public/themes/Defaults/DarkOrchid/wysiwyg/content_css.txt, public/themes/Defaults/DarkRed/wysiwyg/content_css.txt, public/themes/Defaults/DeepPink/wysiwyg/content_css.txt, public/themes/Defaults/Default/wysiwyg/content_css.txt, public/themes/Defaults/DefaultAccessibility/wysiwyg/content_css.txt, public/themes/Defaults/Gray/wysiwyg/content_css.txt, public/themes/Defaults/Green/wysiwyg/content_css.txt, public/themes/Defaults/HotPink/wysiwyg/content_css.txt, public/themes/Defaults/LightGreen/wysiwyg/content_css.txt, public/themes/Defaults/Lime/wysiwyg/content_css.txt, public/themes/Defaults/MediumOrchid/wysiwyg/content_css.txt, public/themes/Defaults/MediumPurple/wysiwyg/content_css.txt, public/themes/Defaults/Olive/wysiwyg/content_css.txt, public/themes/Defaults/Orange/wysiwyg/content_css.txt, public/themes/Defaults/OrangeRed/wysiwyg/content_css.txt, public/themes/Defaults/Orchid/wysiwyg/content_css.txt, public/themes/Defaults/Pink/wysiwyg/content_css.txt, public/themes/Defaults/Purple/wysiwyg/content_css.txt, public/themes/Defaults/Red/wysiwyg/content_css.txt, public/themes/Defaults/Teal/wysiwyg/content_css.txt
* https://github.com/opensource-workshop/connect-cms/pull/2133
* 上記修正時のミスです。再修正しました。
* 原因
* WYSIWYGの読み込みファイル content_css.txt の設定値で、ダブルクォーテーションで囲う必要のある値の、片側のダブルクォーテーションを誤って消してしまったため、WYSIWYGがエラーとなり表示できなくなりました。
* 「関連」github actionsエラー
* この原因によりgithub actionsの Laravel Dusk Connect-cms-test matrix daily でエラーになっていました。
当修正によりエラーは解消見込みです。
* github actionsエラー
* https://github.com/opensource-workshop/connect-cms/actions/runs/13750171630/job/38450141974
* 修正後にgithub actionsの Laravel Dusk Connect-cms-test matrix を動かし、PHP7.4でエラーが解消されていることを確認しました。
* https://github.com/opensource-workshop/connect-cms/actions/runs/13757554619/job/38467596151
なし
概要に記載
なし
なし
=> [WYSIWYG] WYSIWYGが開けなくなる不具合修正

tests/Browser/Common/FrameTest.php, tests/Browser/Common/PasswordPageTest.php, tests/Browser/Common/WysiwygTest.php, tests/Browser/ConnectStudy/DroneStudyTest.php, tests/Browser/Manage/ReservationManageTest.php, tests/Browser/User/BbsesPluginTest.php, tests/Browser/User/BlogsPluginTest.php, tests/Browser/User/CabinetsPluginTest.php, tests/Browser/User/CalendarsPluginTest.php, tests/Browser/User/CountersPluginTest.php, tests/Browser/User/DatabasesPluginTest.php, tests/Browser/User/DatabasesearchesPluginTest.php, tests/Browser/User/FaqsPluginTest.php, tests/Browser/User/FormsPluginTest.php, tests/Browser/User/LinklistsPluginTest.php, tests/Browser/User/OpacsPluginTest.php, tests/Browser/User/OpeningcalendarsPluginTest.php, tests/Browser/User/PhotoalbumsPluginTest.php, tests/Browser/User/QuestionnairesPluginTest.php, tests/Browser/User/ReservationsPluginTest.php, tests/Browser/User/RssesPluginTest.php, tests/Browser/User/SearchsPluginTest.php, tests/Browser/User/SlideshowsPluginTest.php, tests/Browser/User/TabsPluginTest.php, tests/Browser/User/ThemechangersPluginTest.php, tests/Browser/User/WhatsnewsPluginTest.php, tests/DuskTestCase.php
* https://github.com/opensource-workshop/connect-cms/issues/2141
上記の修正です。
一部のDuskテストでエラーになった箇所に「画面表示がおいつかない場合があるので、ちょっと待つ」処理を追加して、対応しました。
* Laravel Dusk Connect-cms-test matrix · opensource-workshop/connect-cms@a3a3b58
https://github.com/opensource-workshop/connect-cms/actions/runs/13889293334
エラーが解消したことを確認しました。
検証と推測をしたのですが、github actionsのブラウザがChrome 133 → 134 に変わったことで、ブラウザの画面表示が少し遅くなったようで、
ブラウザテストのプラグラム実行の方が早くなってしまい、ブラウザ画面表示をしきる前にボタン押下等の処理が走り、
一部のテストエラーが発生していたようです。
上記テストエラーは、ローカル環境で再現するものと、しないものがありました。
その点もテストしているPCやgithub actionsのサーバ環境の違いが影響しているかもしれません。
なし
概要に記載
* assertPathBeginsWith < 8.x Laravel Dusk Laravel
https://readouble.com/laravel/8.x/ja/dusk.html#assert-path-begins-with
無し
=> [テスト] DuskテストがChrome 134系になって出るエラーの修正

resources/views/plugins/user/databases/default/databases_input.blade.php, resources/views/plugins/user/forms/default/forms.blade.php, resources/views/plugins/user/forms/default/index_tandem.blade.php
fontawesome6にfa-facebook-messengerの対応アイコンは無くなったが、表示はできていた。
fontawesome6に対応した似たようなアイコンfa-commentに修正しました。
* https://github.com/opensource-workshop/connect-cms/pull/2137
* fa-facebook-messengerアイコン
* https://fontawesome.com/icons/facebook-messenger?s=brands
* fa-commentアイコン
* https://fontawesome.com/icons/comment?f=classic&s=solid
無し
=> [アイコン] fontawesome6にfa-facebook-messengerがないため、fa-commentに修正

resources/views/plugins/common/description_plugin_category.blade.php, resources/views/plugins/manage/site/categories.blade.php, resources/views/plugins/manage/site/page_error.blade.php, resources/views/plugins/manage/user/original_role.blade.php
カテゴリの「文字色」「背景色」を反映するには、クラス名の設定が必要でしたが、説明がなかったため、追記しました。
なし
なし
なし
無し
=> [カテゴリ設定] 「文字色」「背景色」の反映に関するメッセージ追記

resources/views/plugins/manage/reservation/edit_column_detail.blade.php, resources/views/plugins/manage/reservation/edit_columns.blade.php, resources/views/plugins/manage/reservation/include_edit_column_row.blade.php, resources/views/plugins/manage/reservation/include_edit_column_row_add.blade.php, resources/views/plugins/manage/user/edit_column_detail.blade.php, resources/views/plugins/manage/user/edit_columns.blade.php, resources/views/plugins/manage/user/include_edit_column_row.blade.php, resources/views/plugins/manage/user/include_edit_column_row_add.blade.php
管理画面は幅100%表示で横幅に余裕があるため、項目設定のボタン名をPC・スマホどちらでも表示するよう変更しました。
なし
* https://github.com/opensource-workshop/connect-cms/issues/2144
なし
無し
=> [施設管理][ユーザ管理] 管理画面は幅100%表示のため、項目設定のボタン名は常時表示に変更

app/Models/Common/Page.php, app/Plugins/User/Learningtasks/LearningtasksPlugin.php, app/Plugins/User/Learningtasks/LearningtasksTool.php, tests/Unit/Models/Common/PageTest.php
課題管理プラグインにおいて、親ページ継承のメンバーシップ設定が正常に機能しない不具合を修正しました。
**当該ページの限定公開設定が親の継承である場合**
親ページの設定を使用せず、当該ページの設定を使用していました。
そのため、ある学生が親ページの設定でグループ参加していても、当該ページの課題管理プラグインに学生として出てこない問題などがありました。
不具合の解消
以下箇所において、親ページのページ権限設定が子ページにも適用されるようにしました。
*   設定 > 参加設定 > 受講者 > 配置ページのメンバーシップ受講者から選ぶ > リスト
*   設定 > 参加設定 > 教員 > 配置ページのメンバーシップ教員から選ぶ > リスト
*   科目詳細 > 受講者選択（教員用）> 評価する受講者 > プルダウン
*   （参加方式：配置ページのメンバーシップ教員全員）教員へのメール送信先
無し
OW-2529
=> [課題管理]親ページ継承のメンバーシップが正常に機能しない問題を修正しました

app/Plugins/User/Learningtasks/LearningtasksPlugin.php, app/Plugins/User/Learningtasks/LearningtasksTool.php
課題の履歴に関するファイルのダウンロード権限チェックを変更し、ファイルへのアクセス権限を適正にしました。
*   課題の履歴に関するファイルへのアクセス制御を強化し、ファイルアクセスを適正にする。
*   適切な権限を持つユーザーのみが課題の履歴に関するファイルをダウンロードできるようにする。
*  以下のいずれかの条件を満たす場合に、ダウンロードできるようにしました。
*   ログインユーザが管理者である
*   ログインユーザが課題の教員である
*   ログインユーザが学生であり、自身の履歴のファイルである
*   学生アカウントでログインし、他者のレポートファイルをダウンロードできないことを確認しました。
*   教員アカウントでログインし、自身の担当する課題のレポートファイルをダウンロードできることを確認しました。
*   管理者アカウントでログインし、全てのレポートファイルをダウンロードできることを確認しました。
無し
OW-2531
=> [課題管理]履歴ファイルへのアクセス権限を適正化しました

.github/ISSUE_TEMPLATE/config.yml
issue登録時に「フリー入力」と「Blank Issue」がどちらも表示され、どちらも同じフォーマットのため、「Blank Issue」を消しました。
なし
なし
* https://docs.github.com/ja/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository
なし
=> [Github Issues] issue登録時にフリー入力とBlank Issueがどちらも表示されている

app/Jobs/DeleteNoticeJob.php
* https://github.com/opensource-workshop/connect-cms/issues/2140
上記の不具合修正です。
* メール通知のテストは、確かないと思いますが、念のためテスト
* https://github.com/opensource-workshop/connect-cms/actions/runs/14236013800
* エラーなしを確認
なし
概要に記載
なし
なし
=> [メール通知] 削除通知が送信先グループに通知されない不具合修正

app/Jobs/ApprovalNoticeJob.php, app/Jobs/ApprovedNoticeJob.php, app/Jobs/DeleteNoticeJob.php, app/Jobs/PostNoticeJob.php, resources/views/plugins/manage/log/log.blade.php
* 今まで
* メール通知時に送信メールアドレスなしの場合、ログ出力していました。
* 残っていたコメントに、管理画面で確認できる形でログ出力したい旨の記載がありました。
* これから
* ログ管理でメール通知ログをONにしていた場合、メール通知時に送信メールアドレスなしのログを登録します。
* 送信メールアドレスなしのログには、バケツIDに加えて、バケツ名も出力するようにしました。（例えばブログ名（=バケツ名）でログを見た管理者が、判別つけられるようにするため）
送信メールアドレスなしのログ
なし
なし
なし
無し
=> [メール通知] 送信メールアドレスなしの場合、ログ管理にログ登録するように対応

resources/views/plugins/manage/theme/theme_manage_tab.blade.php
* テンプレート編集時、上部に画面名を表示するよう対応
* カスタムテーマ生成時、上部の画面名を表示状態にする
なし
なし
なし
なし
=> [テーマ管理] テンプレート編集時、上部に画面名を表示するよう対応

app/Models/Common/PageRole.php, app/Models/Core/UsersRoles.php, app/Models/User/Learningtasks/Learningtasks.php, app/Models/User/Learningtasks/LearningtasksPosts.php, app/Models/User/Learningtasks/LearningtasksUseSettings.php, app/Models/User/Learningtasks/LearningtasksUsers.php, app/Models/User/Learningtasks/LearningtasksUsersStatuses.php, app/Plugins/User/Learningtasks/LearningtasksPlugin.php, app/Plugins/User/Learningtasks/LearningtasksReportCsvExporter.php, app/Traits/Learningtasks/LearningtaskPostTrait.php, app/Utilities/File/FileUtils.php, database/factories/Common/PageRoleFactory.php, database/factories/Core/UsersRolesFactory.php, database/factories/User/Learningtasks/LearningtasksFactory.php, database/factories/User/Learningtasks/LearningtasksPostsFactory.php, database/factories/User/Learningtasks/LearningtasksUseSettingsFactory.php, database/factories/User/Learningtasks/LearningtasksUsersFactory.php, database/factories/User/Learningtasks/LearningtasksUsersStatusesFactory.php, resources/views/plugins/user/learningtasks/default/learningtasks_show.blade.php, tests/Unit/Plugins/User/Learningtasks/LearningtasksReportCsvExporterTest.php, tests/Unit/Traits/Learningtasks/LearningtaskPostTraitTest.php, tests/Unit/Utilities/File/FileUtilsTest.php
レポート提出状況をCSVで出力する機能を追加しました。
レポート提出状況をCSVで出力できるようにすることで、課題の進捗管理および分析の効率化を図ります。
- レポート詳細画面に、CSV出力ボタンを追加しました。
- CSV出力ボタンは初期非表示、データ管理ボタンを押下することでアコーディオン表示します。
- CSV出力時に、以下の列を出力するようにしました。
- ユーザID
- ユーザ名
- 提出日時
- 提出回数
- 本文（アップロードを使用する場合のみ）
- ファイルURL（本文を使用する場合のみ）
- 評価（評価を使用する場合のみ）
- コメント（評価のコメントを使用する場合のみ）
レポート詳細画面からCSVファイルが正常に出力されることを確認しました。
また、ファイルURL、本文、評価、コメントなどの各列が仕様通りに出力されることを確認しました。
CSVは1ユーザー1行とし、複数回提出がある場合は、最後の提出および評価を出力します。
無し
OW-2532
=> [課題管理]レポート提出状況をCSVで出力する機能を追加しました

app/Plugins/Manage/PageManage/PageManage.php, app/Plugins/Manage/UserManage/UserManage.php, app/Traits/Migration/MigrationTrait.php, resources/views/plugins/manage/group/edit.blade.php
* [change: ページ管理＞ページ権限一覧, 数万ユーザでもページ開けるように対応](https://github.com/opensource-workshop/connect-cms/commit/4c1487d2c7cdb75d406371696b3d990a169d3118)
* [change: ページ管理＞ページ権限設定, 数万ユーザでもページ開けるように対応](https://github.com/opensource-workshop/connect-cms/commit/72d6c9864b14fa3f6bb8746dc61edb806e63cc6f)
* [change: ユーザ管理＞ユーザ一覧＞ダウンロード, 数万ユーザでもダウンロードできるように対応](https://github.com/opensource-workshop/connect-cms/commit/8772754b8364ac44623b11fb3b2fa4fa139e1118)
* 関連修正
* [bugfix: グループ管理＞グループ変更, 移行後のグループユーザーに作成日・更新日なしで500エラーの修正](https://github.com/opensource-workshop/connect-cms/pull/2165/commits/c88747b417cde71d31c76cd59b68727041bc4856)
* https://github.com/opensource-workshop/connect-cms/actions/runs/14310931682
* エラーなしを確認しました
なし
なし
なし
なし
=> [ページ管理][ユーザ管理] 数万ユーザでもページ開ける, ダウンロードできるように対応

public/themes/Defaults/Blue/wysiwyg/content_css.txt, public/themes/Defaults/CornflowerBlue/wysiwyg/content_css.txt, public/themes/Defaults/DarkBlue/wysiwyg/content_css.txt, public/themes/Defaults/DarkGoldenrod/wysiwyg/content_css.txt, public/themes/Defaults/DarkGreen/wysiwyg/content_css.txt, public/themes/Defaults/DarkOrange/wysiwyg/content_css.txt, public/themes/Defaults/DarkOrchid/wysiwyg/content_css.txt, public/themes/Defaults/DarkRed/wysiwyg/content_css.txt, public/themes/Defaults/DeepPink/wysiwyg/content_css.txt, public/themes/Defaults/Default/wysiwyg/content_css.txt, public/themes/Defaults/DefaultAccessibility/wysiwyg/content_css.txt, public/themes/Defaults/Gray/wysiwyg/content_css.txt, public/themes/Defaults/Green/wysiwyg/content_css.txt, public/themes/Defaults/HotPink/wysiwyg/content_css.txt, public/themes/Defaults/LightGreen/wysiwyg/content_css.txt, public/themes/Defaults/Lime/wysiwyg/content_css.txt, public/themes/Defaults/MediumOrchid/wysiwyg/content_css.txt, public/themes/Defaults/MediumPurple/wysiwyg/content_css.txt, public/themes/Defaults/Olive/wysiwyg/content_css.txt, public/themes/Defaults/Orange/wysiwyg/content_css.txt, public/themes/Defaults/OrangeRed/wysiwyg/content_css.txt, public/themes/Defaults/Orchid/wysiwyg/content_css.txt, public/themes/Defaults/Pink/wysiwyg/content_css.txt, public/themes/Defaults/Purple/wysiwyg/content_css.txt, public/themes/Defaults/Red/wysiwyg/content_css.txt, public/themes/Defaults/Teal/wysiwyg/content_css.txt
* https://github.com/opensource-workshop/connect-cms/issues/2171
上記不具合の修正です。
ディレクトリインストール時にブログ記事の編集時なのに表示しているTinyMCEで、CSSが読み込めていませんでした(404)
TinyMCEのパラメータを修正して、CSSを相対パスで読み込むように修正しました。
ディレクトリインストール時に404になっていたapp.css等が読み込めていることを確認しました。
* https://github.com/opensource-workshop/connect-cms/actions/runs/14461205823
* エラーなしを確認しました。
なし
概要に記載
なし
無し
=> [WYSIWYG] ディレクトリインストールでTinyMCE関連のcssが404になる不具合対応

public/themes/Defaults/Blue/wysiwyg/content_css.txt, public/themes/Defaults/CornflowerBlue/wysiwyg/content_css.txt, public/themes/Defaults/DarkBlue/wysiwyg/content_css.txt, public/themes/Defaults/DarkGoldenrod/wysiwyg/content_css.txt, public/themes/Defaults/DarkGreen/wysiwyg/content_css.txt, public/themes/Defaults/DarkOrange/wysiwyg/content_css.txt, public/themes/Defaults/DarkOrchid/wysiwyg/content_css.txt, public/themes/Defaults/DarkRed/wysiwyg/content_css.txt, public/themes/Defaults/DeepPink/wysiwyg/content_css.txt, public/themes/Defaults/Default/wysiwyg/content_css.txt, public/themes/Defaults/DefaultAccessibility/wysiwyg/content_css.txt, public/themes/Defaults/Gray/wysiwyg/content_css.txt, public/themes/Defaults/Green/wysiwyg/content_css.txt, public/themes/Defaults/HotPink/wysiwyg/content_css.txt, public/themes/Defaults/LightGreen/wysiwyg/content_css.txt, public/themes/Defaults/Lime/wysiwyg/content_css.txt, public/themes/Defaults/MediumOrchid/wysiwyg/content_css.txt, public/themes/Defaults/MediumPurple/wysiwyg/content_css.txt, public/themes/Defaults/Olive/wysiwyg/content_css.txt, public/themes/Defaults/Orange/wysiwyg/content_css.txt, public/themes/Defaults/OrangeRed/wysiwyg/content_css.txt, public/themes/Defaults/Orchid/wysiwyg/content_css.txt, public/themes/Defaults/Pink/wysiwyg/content_css.txt, public/themes/Defaults/Purple/wysiwyg/content_css.txt, public/themes/Defaults/Red/wysiwyg/content_css.txt, public/themes/Defaults/Teal/wysiwyg/content_css.txt, resources/views/plugins/common/wysiwyg.blade.php
* https://github.com/opensource-workshop/connect-cms/issues/2171
上記不具合の再対応です。
ディレクトリインストール時にブログ記事の編集時なのに表示しているTinyMCEで、CSSが読み込めていませんでした(404)
TinyMCEのパラメータを修正して、CSSを相対パスで読み込むように修正しました。
ディレクトリインストール時に404になっていたapp.css等が読み込めていることを確認しました。
* https://github.com/opensource-workshop/connect-cms/actions/runs/14506346740
* エラーなしを確認しました。
なし
* https://github.com/opensource-workshop/connect-cms/pull/2172
なし
なし
=> [WYSIWYG] ディレクトリインストール＋WYSIWYGでTinyMCE関連のcssが404になる不具合対応2

resources/views/plugins/user/databases/default/databases_edit_view.blade.php
データベース＞表示設定＞急上昇ワード の設定方法に迷ったため、その項目の下部に、急上昇ワードの説明と設定方法の説明メッセージを追加しました。
なし
* https://github.com/opensource-workshop/connect-cms/pull/1838
なし
なし
=> [データベース] 表示設定＞急上昇ワードの下部に説明メッセージ追加

public/robots.txt
* NC3から移行後に、bot系からくるNC3系のアクセスをrobots.txtで除外する設定を追加しました。
なし
* https://github.com/opensource-workshop/connect-cms/pull/1788
なし
なし
=> [robots.txt] 他システムから移行後に不要な検索botのクロールを除外

sync_option_private_2_dev.sh.example
* マイグレーションとEnum同期時に、他オプションのファイルを消してしまうrsyncオプション(--delete)を消しました。
* バリデーションの同期フォルダが違っていたため、修正しました。
なし
なし
なし
無し
=> [開発ツール] sync_option_private_2_dev.shのrsyncのオプション指定見直し

app/Plugins/Manage/PageManage/PageManage.php, resources/views/plugins/manage/page/role.blade.php, resources/views/plugins/manage/page/role_list.blade.php
* ページ権限一覧画面, ページ権限設定画面で、数万ユーザでもページが開けるように、グループ参加ユーザの表示を見直しました。
* 全角400字(約1000バイト)までグループ参加者名を表示します。（おおむね５０名程度表示できます）それ以上は (ユーザ多数のため以下省略) として表示を省略します。
* ※ グループ参加者多数の場合は、グループ管理で参加者を確認できます。
* ※ バイト数の制約は、mysqlの関数 `GROUP_CONCAT()` を使用した事による制約です。
* グループの参加人数の表示を追加しました。
なし
* https://github.com/opensource-workshop/connect-cms/pull/2165
* MySQLのGROUP_CONCAT
* [複数行返ってくるサブクエリを文字列に連結して取得するSQLまとめ - hikky nikky](https://mb-strlen.hatenadiary.org/entry/20100322/1269246561)
* [MySQLのGROUP_CONCAT関数の結果が切れる事象の対策 #MySQL - Qiita](https://qiita.com/nwsoyogi/items/196cb92f79c6f01871e0)
* Laravel
* [Laravel8 クエリビルダでgroup_concatを使う方法 – 半力投球](https://halfpower.work/2021/12/12/laravel8-%E3%82%AF%E3%82%A8%E3%83%AA%E3%83%93%E3%83%AB%E3%83%80%E3%81%A7group_concat%E3%82%92%E4%BD%BF%E3%81%86%E6%96%B9%E6%B3%95/)
* [素のSQL …
=> [ページ管理] ページ権限一覧, ページ権限設定で数万ユーザでもページ開けるように対応

app/Enums/LearningtaskUseFunction.php, app/Plugins/User/Learningtasks/LearningtasksPlugin.php, app/Plugins/User/Learningtasks/LearningtasksTool.php, resources/views/plugins/user/learningtasks/default/learningtasks_edit_learningtasks.blade.php, resources/views/plugins/user/learningtasks/default/learningtasks_edit_report.blade.php, resources/views/plugins/user/learningtasks/default/learningtasks_show.blade.php, resources/views/plugins/user/learningtasks/default/learningtasks_show_report_status.blade.php
学生がレポート提出後に提出内容を修正できるようにします。
- 現状、学生が提出内容を修正するためには、教員が提出履歴を削除する必要があり、システム外でのやり取りが発生していました。
- この変更により、学生は提出後に誤りに気づいたり、内容を改善したくなったりした場合でも、システム内で修正・再提出が可能になります。
- 教員・学生双方の手間を削減し、より効率的な課題管理を実現します。
課題提出後に、学生自身が提出内容を編集・再提出できる機能を追加しました。
- 評価前で提出期限内であれば、何度でも修正可能です
- 修正履歴は保存され、教員が確認可能です
- 修正可否は設定で変更可能です
- 修正可能であることを示すメッセージを表示します
- （教員、管理者のみ）修正履歴をモーダルダイアログで確認できます
- 修正がある場合、”（修正済み）”を表示します
- レポート設定 「提出内容の修正」で修正可否を設定します
無し
OW-2533
=> [課題管理]学生がレポート提出内容の修正を行えるようにしました

app/Plugins/User/Databases/DatabasesPlugin.php, app/Plugins/User/Forms/FormsPlugin.php, resources/views/plugins/user/databases/default/databases_edit.blade.php, resources/views/plugins/user/databases/default/databases_edit_row.blade.php, resources/views/plugins/user/databases/default/databases_edit_row_detail.blade.php, resources/views/plugins/user/forms/default/forms_edit.blade.php, resources/views/plugins/user/forms/default/forms_edit_row.blade.php, resources/views/plugins/user/forms/default/forms_edit_row2.blade.php, resources/views/plugins/user/forms/default/forms_edit_row_detail.blade.php
* change: フォーム＞項目詳細設定＞選択肢の設定, 表示順をつまんで移動(ドラック＆ドロップ)できるように対応
* change: フォーム＞項目設定, 表示順をつまんで移動(ドラック＆ドロップ)できるように対応
* change: データベース＞項目詳細設定＞選択肢の設定, 表示順をつまんで移動(ドラック＆ドロップ)できるように対応
* change: データベース＞項目設定, 表示順をつまんで移動(ドラック＆ドロップ)できるように対応
Laravel Dusk Connect-cms-test matrix · opensource-workshop/connect-cms@b64b934
https://github.com/opensource-workshop/connect-cms/actions/runs/14654293659
→ エラーがない事を確認しました
なし
* https://github.com/opensource-workshop/connect-cms/pull/2021
* SortableJS
https://sortablejs.github.io/Sortable/
* `<tbody>`: テーブル本体要素 - HTML: ハイパーテキストマークアップ言語 | MDN
https://developer.mozilla.org/ja/docs/Web/HTML/Reference/Elements/tbody
* Tooltips - Bootstrap 4.2 - 日本語リファレンス
https://getbootstrap.jp/docs/4.2/components/tooltips/
なし
=> [フォーム][データベース] 表示順をつまんで移動(ドラック＆ドロップ)できるように対応

app/Plugins/Manage/PageManage/PageManage.php
ページ管理機能において、ページ登録または更新時に固定リンクを空のまま保存しようとするとシステムエラーが発生する問題を修正しました。
固定リンクが未入力の状態で保存操作が行われた際に、予期せぬシステムエラー（`strncmp()` 関数の型エラー）が発生するのを防ぎ、アプリケーションの安定性を向上させます。
`app/Plugins/Manage/PageManage/PageManage.php` の 224 行目付近にある `strncmp()` 関数において、第一引数 `$request->permanent_link` が `null` となる可能性がありました。
`null` 合体演算子 (`??`) を使用し、`$request->permanent_link` が `null` の場合に空文字列 (`''`) を `strncmp()` 関数に渡すよう修正しました。
```php
// 修正前
// if (strncmp($request->permanent_link, '/', 1) !== 0) {
// 修正後
if (strncmp($request->permanent_link ?? '', '/', 1) !== 0) {
```
#2183
無し
=> [ページ管理]固定リンクを空で登録するとシステムエラーとなる問題を修正しました

app/Models/Common/Frame.php, app/Models/Common/Group.php, app/Models/Common/GroupUser.php, app/Models/Common/PageRole.php, app/Models/Core/UsersLoginHistories.php, app/Models/Migration/Nc3/Nc3Announcement.php, app/Models/Migration/Nc3/Nc3AuthorizationKey.php, app/Models/Migration/Nc3/Nc3Frame.php, app/Models/User/Blogs/BlogsPosts.php, app/Models/User/Blogs/BlogsPostsTags.php, app/Models/User/Calendars/CalendarPost.php, app/Models/User/Contents/Contents.php, app/Models/User/Counters/CounterCount.php, app/Models/User/Databases/DatabasesInputs.php, app/Models/User/Faqs/FaqsPosts.php, app/Models/User/Faqs/FaqsPostsTags.php, app/Models/User/Forms/Forms.php, app/Models/User/Learningtasks/LearningtasksExaminations.php, app/Models/User/Learningtasks/LearningtasksPosts.php, app/Models/User/Learningtasks/LearningtasksPostsFiles.php, app/Models/User/Learningtasks/LearningtasksUseSettings.php, app/Models/User/Opacs/OpacsBooks.php, app/Models/User/Opacs/OpacsBooksLents.php, app/Models/User/Reservations/ReservationsInput.php, app/User.php
* https://github.com/opensource-workshop/connect-cms/pull/2191
* 上記対応時に気付きました。
* モデルの$dates → $castsに切替えて、Laravel 8.x(Connect 1.x系)で動作する事を確認しました。
* https://github.com/opensource-workshop/connect-cms/actions/runs/14871924142
なし
概要に記載
なし
なし
=> [モデル] モデルの$dates → $castsに切替（Laravel10.xで$date廃止に対応）

.env.example, tests/DuskTestCase.php
Connect-CMS 1.x（Laravel8.x）ではdusk実行時の引数を指定しても、テスト実行できていましたが、
Laravel10.xでdusk実行時の引数は、テストケースのパスとして認識されるようになり、no_manual, no_api_test の引数がテストケースのパスとして誤認され、そんなテストケースはないのでエラーが出るようになりました。
そのため、現在のdusk実行時の引数を指定に加えて、.envからもDUSK_NO_MANUAL_ALL／DUSK_NO_API_TEST_ALLを設定できるよう修正しました。
* https://github.com/opensource-workshop/connect-cms/actions/runs/14953975329
なし
* https://github.com/opensource-workshop/connect-cms/pull/2191
なし
無し
=> [ブラウザテスト] .envからDUSK_NO_MANUAL_ALL／DUSK_NO_API_TEST_ALLを設定できるように対応

resources/views/plugins/manage/user/include_edit_column_row.blade.php
* https://github.com/opensource-workshop/connect-cms/issues/2013
上記不具合の修正です。
同様の不具合が「プレースホルダ」「変数名」にもあったため、対応しました。
* 一覧で表示するキャプションは、60文字以下で表示するようになっており、今回のHTML入りのキャプションでは、ちょうどAタグの開始のみ記載されて、HTMLを有効にして表示するようになっていたため、レイアウトが崩れていました。
* 上記不具合を回避するため、一覧でのキャプションのHTML表示は無効（サニタイジング対応）をしました。
HTML有りのキャプションを設定した時に、一覧のレイアウトが崩れない事を確認しました。
* https://github.com/opensource-workshop/connect-cms/actions/runs/15310891675
なし
概要に記載しました。
なし
無し
=> [ユーザ管理] ユーザ管理＞項目設定, 一覧のレイアウトが崩れるケースがある不具合（HTML有りのキャプション時）に対応

resources/views/plugins/manage/menus_list.blade.php, resources/views/plugins/manage/uploadfile/uploadfile_manage_tab.blade.php, resources/views/plugins/manage/user/user_manage_tab.blade.php
* https://github.com/opensource-workshop/connect-cms/issues/1717
* 上記の不具合修正です。
* アップロードファイル／ユーザ管理 を対応しました。
* ユーザ管理の例に話をすると、２ページ目のユーザ編集後に２ページを表示して欲しいので、ページ保持機能はそのままにしました。
* 左メニュー／上部メニュー押下時のみ、1ページ目表示のクエリストリング `?page=1` を追加して、必ず１ページ目を表示するように対応しました。
画面表示に変更はないため、ありません。
* https://github.com/opensource-workshop/connect-cms/actions/runs/15312356653
なし
概要に記載しました。
なし
無し
=> [アップロードファイル][ユーザ管理] 一覧のページャ指定が、別ページ遷移後でも残っている不具合対応

app/Rules/CustomValiDuplicateBookings.php
施設予約で「重複予約を許可しない」設定にしていても、予約の終了時間を「24:00」にすると重複して予約ができてしまう不具合がありましたので、重複予約チェックを修正しました。
* 施設管理
* 「重複予約を許可しない」設定にする
* 施設予約
* 2025-05-30 14:00-17:00予定あり
* 2025-05-30 12:00-24:00予定を登録すると、登録できてしまう
※ 終了時間の24:00表示は、施設予約特有の表示で、変換して表示しています。
　システム上では`2025-05-30 24:00`はイレギュラーな値で、CarbonやDBのdatetime型ですと、正しい値は 翌日の0時 `2025-05-31 00:00` になります。
　`2025-05-30 24:00`のイレギュラーな値で、予約重複チェックを行ったため、うまくチェックが働きませんでした。
* 重複チェックで`2025-05-30 24:00`等の24:00がきた場合、正しい値の 翌日の0時 `2025-05-31 00:00` に変換してチェックするよう対応しました。
5/30(金)
* https://github.com/opensource-workshop/connect-cms/actions/runs/15311849492
なし
なし
無し
=> [施設予約] 「重複予約を許可しない」設定にしていても、予約の終了時間を「24:00」にすると重複して予約ができてしまう不具合対応

app/Enums/LearningtaskUseFunction.php, app/Models/User/Learningtasks/LearningtasksUsersStatuses.php, app/Plugins/User/Learningtasks/DataProviders/ReportCsvDataProvider.php, app/Plugins/User/Learningtasks/Services/LearningtaskReportColumnDefinition.php, resources/views/plugins/user/learningtasks/default/learningtasks_edit_learningtasks.blade.php, resources/views/plugins/user/learningtasks/default/learningtasks_edit_report.blade.php, resources/views/plugins/user/learningtasks/default/learningtasks_show_report_status.blade.php, tests/Unit/Models/User/Learningtasks/LearningtasksUsersStatusesTest.php, tests/Unit/Plugins/User/Learningtasks/DataProviders/ReportCsvDataProviderTest.php
レポートのコメント欄の下に、入力されたテキストの単語数と文字数を表示する機能を追加しました。
この表示は、設定画面から個別にON/OFFを切り替えることが可能です。
教員が学生のレポートを評価する際、その記述量を参考情報の一つとして活用できるようにするため。
- **レポート設定の変更**
- 「表示方法」の項目に、「単語数を表示する」および「文字数を表示する」チェックボックスを追加しました。
- **画面表示の変更**
- 上記設定が有効な場合、レポート提出履歴画面のコメント欄の下に「X単語 / Y文字」の形式でそれぞれの数を表示します。
- **CSVエクスポートの変更**
- レポート提出履歴をCSVファイルとしてエクスポートする際に、「単語数」と「字数」の列を追加し、それぞれの値が出力されるようにしました。
以下の項目について、動作確認を行いました。
- レポート設定画面に記載の通り、単語数のカウントは日本語などのマルチバイト文字に対応していません。主にスペースで区切られる言語（英語など）を想定した機能となります。
無し
=> [課題管理] レポートのコメントに単語数と文字数を表示する機能を追加しました

app/Models/User/Databases/DatabasesInputCols.php, app/Models/User/Databases/DatabasesInputs.php, app/Observers/User/Databases/DatabasesInputColsObserver.php, app/Plugins/User/Databases/DatabasesPlugin.php, app/Providers/EventServiceProvider.php, database/migrations/2025_01_31_172824_add_last_col_updated_at_to_databases_inputs_table.php, resources/views/plugins/user/databases/default/databases_include_detail_value.blade.php, resources/views/plugins/user/databases/default/databases_include_value.blade.php
データベースの詳細画面を閲覧した際に、意図せず最終更新日が現在の日時で上書きされてしまう不具合を修正しました。
「更新日型」として設定された項目が、データの詳細を閲覧するだけで毎回更新されてしまう問題を解決するため。本来、この項目はデータが実際に編集された際にのみ更新されるべきです。
証跡用の更新日(`updated_at`)と、画面表示用の最終更新日を分離することで対応しました。
- `databases_inputs`テーブルに、最終更新日を管理するための`last_col_updated_at`カラムを追加しました。
- 項目の更新時に、Observerを利用して`last_col_updated_at`を更新するようにしました。
- 画面やCSVに出力する更新日型のデータを、従来の`updated_at`から新設した`last_col_updated_at`に変更しました。
以下の手順で、修正が正しく反映されていることを画面上で確認しました。
1.  「更新日型」の項目を持つデータベースを用意し、データを登録します。
2.  登録したデータの詳細画面を閲覧します。
3.  一覧画面に戻り、**最終更新日が閲覧した日時に変わっていないこと**を確認します。
4.  データを編集して保存し、一覧画面で**最終更新日が正しく更新されていること**を確認します。
5. CSVを出力し、「更新日型」の項目が**画面と同様の値になっていること**を確認します。
- NC2およびNC3からの移行プログラムは、今回の修正範囲外です。
有り
=> [データベース]詳細閲覧時にデータの更新日が更新される不具合を修正しました

CLAUDE.md
Claude Code用のガイダンスファイル（CLAUDE.md）を追加しました。このファイルは将来のClaude Codeインスタンスがこのリポジトリで効率的に作業できるよう、プロジェクトのアーキテクチャ、開発コマンド、コーディング規約などの重要な情報を日本語で記載しています。
軽微な改修なので急ぎません
- .github/copilot-instructions.md の内容を参考にClaude Code用の指示を含めています
- composer.json から開発コマンドを抽出して記載しています
無し
=> [開発支援] CLAUDE.mdファイルを追加しました

app/Plugins/User/Forms/FormsPlugin.php, resources/views/plugins/user/forms/default/forms_list_inputs.blade.php
登録一覧画面、ダウンロードデータに登録ユーザを含むようにしました。
ログインしていないゲストでの登録時は空になります。
GithubのIssueは以下です。
https://github.com/opensource-workshop/connect-cms/issues/2213
ログイン前提のサイトで、フォームに登録したデータが誰が登録したかわからなかったため。
https://github.com/opensource-workshop/connect-cms/issues/2213
無し
=> #2213 登録データのユーザをダウンロードできるようにしました。

resources/views/plugins/common/wysiwyg.blade.php
WYSIWYGエディタ（TinyMCE）でのiframe埋め込み機能のセキュリティ設定を改善しました。
- `sandbox_iframes: true` を設定し、iframeのサンドボックス機能を有効化
- `sandbox_iframes_exclusions` でホワイトリストを設定し、以下の外部サービスからの埋め込みを許可：
- YouTube (youtube.com, youtu.be)
- Vimeo (vimeo.com, player.vimeo.com)
- Dailymotion (dailymotion.com, dai.ly)
- Apple Music (embed.music.apple.com)
- Spotify (open.spotify.com)
- Giphy (giphy.com)
- CodePen (codepen.io)
セキュリティを向上させながら、主要な動画・音楽配信サービスのコンテンツ埋め込みを可能にする
超特急
なし
- [TinyMCE Content Filtering Documentation](https://www.tiny.cloud/docs/tinymce/latest/content-filtering/#sandbox-iframes-exclusions)
=> [WYSIWYG] TinyMCEのiframe埋め込みセキュリティ設定を追加しました

app/Http/Controllers/Auth/LoginController.php, app/Http/Kernel.php, app/Http/Middleware/ForceLogoutMiddleware.php, app/Plugins/Manage/UserManage/UserManage.php, database/migrations/2025_07_03_093934_add_force_logout_to_users_table.php, resources/views/plugins/manage/user/force_logout.blade.php, resources/views/plugins/manage/user/user_manage_tab.blade.php
授業などで使用している際、強制的に全ユーザをログアウトさせたいときがあります。
管理画面で全ユーザの強制ログアウトをさせることで、ログイン済みのセッションを使用しているユーザも次の画面操作で強制的にログアウトします。 ただし、ログイン中の自分のみは強制ログアウトされないようにします。
Issuesは以下です。
https://github.com/opensource-workshop/connect-cms/issues/2221
有り
=> [認証]全ユーザの強制ログアウト機能を作りました。

app/Plugins/Manage/ThemeManage/ThemeManage.php
テーマ管理の「ユーザ・テーマ機能」および「カスタムテーマ生成機能」において、ディレクトリ名のバリデーションルールを修正・統一しました。
サーバーの文字コード設定によっては、ディレクトリ名に日本語などのマルチバイト文字を使用すると文字化けが発生し、テーマが正常に参照できなくなる問題がありました。
また、同名のテーマディレクトリが存在すると意図しない上書きが発生する可能性があるため、これらの問題を未然に防ぐ目的でバリデーションを強化します。
**対象機能**
- ユーザ・テーマ機能
- カスタムテーマ生成機能
**修正内容**
- **ユーザ・テーマ機能**：正しく機能していなかったディレクトリ名の正規表現(regex)を修正しました。
- **カスタムテーマ生成機能**：ディレクトリ名のバリデーションを追加し、さらに同名のディレクトリが存在しないかチェックする処理も追加しました。
**新しいバリデーションルール**
- **使用可能な文字**：半角の英数字、アンダースコア(\_)、ハイフン(-)。
- **先頭の文字**：半角の英数字、またはアンダースコア(\_)。
- **使用不可能な文字**：スペース、スラッシュ(/)、その他の記号。
両機能の画面にて、以下の項目を確認しました。
- 許可されていない文字（全角文字、スペース、記号など）を入力した場合に、エラーメッセージが正しく表示されること。
- カスタムテーマ生成機能で、既に存在するディレクトリ名を入力した場合にエラーメッセージが表示されること。
- 許可されている形式のディレクトリ名で、正常に登録・作成できること。
無し
=> [テーマ管理] ディレクトリ名のバリデーション不備による文字化けや重複の問題を修正しました

app/Plugins/User/Rsses/RssesPlugin.php, resources/views/plugins/user/rsses/default/rsses_error_messages.blade.php
RSSフィードの取得時に、XMLのパースエラーが原因でシステムエラーが発生する問題を修正しました。
RSSフィードの提供元URLがリンク切れになっている場合や、不正な形式のXMLが返された場合に、フレーム内にシステムエラーが表示される問題がありました。これを防ぎ、安定した運用ができるようにすることが目的です。
XMLのパース処理に例外処理を追加しました。パースエラーが発生した際にはシステムエラーとせず、エラー内容をログに出力します。
また、エラー発生時に表示するメッセージを権限に応じて変更しました。
- **管理者向け：** 原因調査のヒントとなるよう「RSSフィードの取得に失敗しました。URLが正しいか、またはフィードが有効であるかご確認ください。」というメッセージを表示します。
- **一般ユーザー向け：** シンプルに「RSSフィードの読み込みに失敗しました。しばらくしてから再度お試しください。」というメッセージを表示します。
- 意図的にリンク切れのURLを設定し、システムエラーが発生しないことを確認しました。
- 不正な形式のXMLを返すURLを設定し、システムエラーが発生しないことを確認しました。
- 管理者アカウントでログイン時、専用のエラーメッセージが表示されることを確認しました。
- 一般ユーザー（非ログイン含む）で、専用のエラーメッセージが表示されることを確認しました。
- エラー発生時、管理者には原因の調査に役立つメッセージを、一般ユーザーにはシンプルなメッセージを表示するように制御しています。
無し
=> [RSS]XMLパースエラー発生時にシステムエラーとなる問題を修正しました

app/Models/Common/BucketsMail.php, app/Plugins/User/UserPluginBase.php, resources/views/plugins/common/frame_edit_mails.blade.php, tests/Unit/Models/Common/BucketsMailTest.php
ブログプラグインなどで、メール設定において「投稿通知の件名」を空の状態で記事を新規登録すると500エラーが発生する問題を修正しました。
- null/空文字列を許容するよう型定義を変更（`string < /dev/null | null`）
- 件名が未設定の場合に「【件名未設定】」をデフォルト値として返すよう修正
- 既存データへの対応も考慮したコメントを追加
- `useBucketMailMethods()`で有効なメール機能を動的に判定
- 通知機能がONの場合のみ件名フィールドを必須とするバリデーションを追加
- 適切な日本語エラーメッセージを設定
- 全ての件名フィールドに赤い「必須」バッジを追加
- ユーザーに必須項目であることを視覚的に伝達
- `BucketsMailTest::testGetFormattedSubjectWithNull()`: null値処理のテスト
- `BucketsMailTest::testGetFormattedSubjectWithEmptyString()`: 空文字列処理のテスト
- 既存テストでカバーされていなかったエッジケースを追加
メール通知の本文についても必須にすることを検討しましたが、以下の理由により実装を見送りました：
- **シンプル通知の要求**: 件名のみで十分な情報を伝える通知の需要（例：「【ブログ更新】新しい記事が投稿されました」）
- **運用の柔軟性**: 組織によって通知の詳細度要求が異なる
- **モバイル対応**: スマートフォンでの通知表示を重視し、URLアクセスを促進する運用
- **既存設計**: Connect-CMSは本文を`nullable`として設計されており、設計思想との整合性 …
=> [プラグイン共通] 投稿通知の件名が未設定の場合に500エラーが発生する問題を修正しました

resources/views/plugins/user/faqs/full_display/faq_item.blade.php, resources/views/plugins/user/faqs/full_display/faqs.blade.php, resources/views/plugins/user/faqs/full_display/template.ini
FAQプラグインに新しいテンプレート「Q&A全表示」を追加しました。
従来のアコーディオン形式とは異なり、全てのQ&Aを常時表示するテンプレートです。
- 一覧性の向上（スクロールで全FAQ確認可能）
- 印刷対応の改善
- アクセシビリティの向上
- 検索エンジン最適化対応
- `resources/views/plugins/user/faqs/full_display/` ディレクトリ作成
- `template.ini` - テンプレート設定ファイル
- `faqs.blade.php` - メインテンプレート
- `faq_item.blade.php` - Q&A表示コンポーネント
- template.iniの文字エンコーディング問題（`&`文字）対応
お時間のある時で構いません
なし
- 既存テンプレート: default（アコーディオン）、category（カテゴリ別アコーディオン）
- 新テンプレート: full_display（Q&A全表示）
=> [FAQ] Q&A全表示テンプレートを追加しました

app/Enums/FaqFrameConfig.php, app/Plugins/User/Faqs/FaqsPlugin.php, resources/views/plugins/user/faqs/category/faqs.blade.php, resources/views/plugins/user/faqs/clear_conditions.blade.php, resources/views/plugins/user/faqs/count_display.blade.php, resources/views/plugins/user/faqs/default/faqs.blade.php, resources/views/plugins/user/faqs/default/faqs_edit_faq.blade.php, resources/views/plugins/user/faqs/full_display/faqs.blade.php, resources/views/plugins/user/faqs/search_form.blade.php
FAQプラグインにキーワード検索機能を追加し、ユーザーがキーワードでFAQを検索できるようにしました。
- **キーワード検索機能の実装**
- タイトル・本文・カテゴリ・タグを対象とした包括的な検索
- **設定機能の追加**
- フレーム設定でキーワード検索機能の表示/非表示を切り替え可能
- デフォルトは「表示しない」設定
- **UI・UX改善**
- 件数表示機能を追加（「表示件数 X 件 (開始-終了)」形式）
- **コード整理**
- 検索フォーム、件数表示、条件クリアを共通部品化
特になし
なし
- データベースプラグインの検索UIを参考に実装
- 既存の絞り込み機能との整合性を保持
=> [FAQ] キーワード検索機能を追加しました

app/Models/Common/BucketsMail.php
PHP8のUnion型記法（`string|null`）がPHP7系で動作しないため、Nullable型記法（`?string`）に修正し、PHP7系との互換性を確保しました。
- Connect-CMSはPHP7.4以上をサポートしているが、PHP8のUnion型記法がPHP7系でエラーとなっていた
- メール通知機能（ブログ等）でPHP7系環境において Fatal Error が発生していた
- `app/Models/Common/BucketsMail.php` の `getFormattedSubject` メソッドの引数型を修正
- 変更前: `string|null $subject`（PHP8のUnion型記法）
- 変更後: `?string $subject`（PHP7互換のNullable型記法）
特になし
https://github.com/opensource-workshop/connect-cms/pull/2225
- PHP8.0のUnion型仕様: https://www.php.net/manual/ja/language.types.declarations.php#language.types.declarations.union
- 社内チケットID：OW-2613
なし
=> [メール] PHP7系でメール通知設定のUnion型エラーを修正しました

app/Traits/Migration/MigrationNc3ExportTrait.php
NetCommons3からConnect-CMSへの移行処理において、多言語ページ（日本語・英語）のインポート時に英語ページが先に登録される問題を修正しました。
- `MigrationNc3ExportTrait.php` の多言語ページエクスポート処理で、言語ID順を降順（DESC）に変更
- 日本語ページ（language_id=2）が英語ページ（language_id=1）より先に処理されるように修正
- 英語ページ（/en）が日本語ページ（/）より小さいIDで登録されていた
- 言語ID昇順（1→2）で処理されていたため、英語→日本語の順で登録
- 日本語ページ（/）が英語ページ（/en）より小さいIDで登録される
- 言語ID降順（2→1）で処理されるため、日本語→英語の順で登録
なし
https://opensource-workshop.atlassian.net/browse/OW-2614
- NC3言語ID定数: 英語=1, 日本語=2
=> [NC3移行] 多言語ページで日本語ページを優先して登録するよう修正しました

package-lock.json, package.json
tui-image-editor経由で使用されているform-dataパッケージのCritical脆弱性（CVE-2025-7783, CVSS 9.4）を修正しました。
- `package.json`にnpm overridesを追加し、form-data@^4.0.4を強制適用
- tui-image-editor → fabric → jsdom → request → form-data の依存チェーンで発生していた脆弱性を解決
- **脆弱性**: form-data@2.3.3のunsafe random function使用によるboundary値の予測可能性
- **影響範囲**: Node.js環境でのfabric.js使用時のみ（ブラウザでの画像編集機能には影響なし）
- **解決方法**: npm overridesでform-data@4.0.4以上を強制
- `npm ls form-data`で全ての依存関係が4.0.4に更新されることを確認
- ウィジウィグ上の画像エディタで一通りの画像編集でモンキー打鍵を実施、問題ないことを確認
なし
Dependabot security alert #111
=> [共通] form-dataパッケージのセキュリティ脆弱性を修正しました

.env.example, app/Plugins/Manage/IndexManage/IndexManage.php, app/Plugins/Manage/UploadfileManage/UploadfileManage.php, app/Utilities/Storage/StorageUsageCalculator.php, resources/views/plugins/manage/index/index.blade.php, resources/views/plugins/manage/uploadfile/index.blade.php, tests/Unit/Utilities/Storage/StorageUsageCalculatorTest.php
サービス提供者向けに、ストレージ使用量の監視とプラン容量管理機能を追加しました。
- **プラン容量表示機能**: アップロードファイル管理画面にプラン容量と使用率を表示
- **容量警告機能**: 管理者お知らせ画面に使用率が閾値に達した際の警告メッセージを表示
- **使用量詳細表示**: データ使用量とアップロードファイル使用量の内訳表示
- **共通化**: ストレージ使用量計算ロジックを共通クラス化
1. **プラン容量表示**
- env設定（`STORAGE_LIMIT_MB`）によりプラン容量を設定可能
- 使用率をパーセンテージとプログレスバーで視覚的に表示
- 100%超過時も実際の使用率を表示（緊急度判断のため）
---
2. **容量警告機能**
- 管理者お知らせ画面に警告カードを表示
- 閾値（`STORAGE_USAGE_WARNING_THRESHOLD`、デフォルト80%）で警告表示
- アップロードファイル管理への直接リンク提供
---
3. **使用量内訳表示**
- データ使用量：データベーステーブルの使用量
- アップロードファイル使用量：storage/app/uploads配下の使用量
- 各項目にツールチップで詳細説明を追加
```bash
--- 設定例
STORAGE_LIMIT_MB=20480
- 設定あり：
- アップロードファイル画面にプラン容量を表示
- お知らせ画面にストレージ容量警告を表示（使用量警告閾値に応じて。使用量警告閾値未設定の場合は80%超えで表示）
STORAGE_USAGE_WARNING_THRESHOLD=0.8
- 初期値：0.8
```
- `StorageUsageCalculator`クラス新規作成により使用量計算ロジックを共通化
- …
=> [アップロードファイル管理] プラン容量表示と使用量警告機能を追加しました

app/Utilities/Storage/StorageUsageCalculator.php
STORAGE_LIMIT_MB設定が未設定の場合でも警告ログが頻繁に出力される問題を修正しました。
設定していない顧客が多い想定のため、未設定時は警告を出力せず、設定されているが無効な値の場合のみ警告を出力するように改善しました。
- `StorageUsageCalculator.php` の `getPlanLimitFormatted()` メソッドで、STORAGE_LIMIT_MBが未設定（empty）の場合は警告ログを出力しないように修正
- 設定されているが無効な値（非数値、0以下）の場合のみ警告ログを出力するよう条件分岐を改善
```php
if (empty($storage_limit_mb) || !is_numeric($storage_limit_mb) || $storage_limit_mb <= 0) {
Log::warning('Invalid STORAGE_LIMIT_MB configuration: ' . $storage_limit_mb);
return null;
}
```
→ 未設定でも警告が出力されていた
```php
// 設定がない場合はnullを返す（警告なし）
if (empty($storage_limit_mb)) {
return null;
}
// 設定があるが無効な値の場合のみ警告を出す
if (!is_numeric($storage_limit_mb) || $storage_limit_mb <= 0) {
Log::warning('Invalid STORAGE_LIMIT_MB configuration: ' . $storage_limit_mb);
return null;
}
```
→ 未設定時は警告なし、無効値のみ警告出力
特になし
なし
- …
=> [アップロードファイル管理] STORAGE_LIMIT_MB未設定時の警告ログを出力しないよう改善しました

.github/workflows/laravel_dusk_connect-cms-test-matrix-daily.yml, .github/workflows/laravel_dusk_connect-cms-test-matrix.yml, .github/workflows/laravel_dusk_connect-cms-test.yml, tests/Browser/Manage/SiteManageTest.php, tests/Browser/User/FaqsPluginTest.php, tests/Browser/User/PhotoalbumsPluginTest.php, tests/DuskTestCase.php
CI上のLaravel Dusk実行がフレークしやすかったため、安定化の変更を行いました。
- Dusk基底の安定化:
- `DUSK_DRIVER_URL` が設定されている場合、`startChromeDriver()` を起動しないように調整
- Chrome起動引数に `--no-sandbox` / `--disable-dev-shm-usage` を追加
- スクリーンショットの幅/高さ取得の取り違えを修正
- 既定待機時間 `Browser::$waitSeconds` を 10 秒に延長
- CIワークフローの安定化:
- `DUSK_DRIVER_URL=http://localhost:9515` をジョブに設定（ワークフロー起動のドライバと整合）
- `DUSK_NO_MANUAL_ALL=1` と `DUSK_NO_API_TEST_ALL=1` を既定で有効化（マニュアル出力/外部API依存を無効化）
- `laravel_dusk_connect-cms-test.yml` に `chore/dusk-stability-flags` への push トリガを追加
- テストの安定化:
- PhotoalbumsPluginTest: 作成したアルバムのフォルダIDをDBから動的取得して遷移。`#photo_1` 固定を排し `[id^="photo_"]` の待機＋クリックに変更
- SiteManageTest: `waitForReload()` タイムアウト箇所を `waitForText()` や短い `pause` へ置換
- FaqsPluginTest: 共通カテゴリ要素の存在チェックを追加し、初期状態依存の失敗を回避
CIの安定運用のため、可能であれば今週中のレビューをお願いできると助かります。（急ぎではありません） …
=> [E2Eテスト] 安定化対応（ChromeDriver起動整理・スクショ修正・CIフラグ適用・脆弱テスト修正）

app/Plugins/User/Forms/FormsPlugin.php, resources/views/plugins/user/forms/default/forms_edit_form.blade.php
フォーム設定画面において、「本登録後のメッセージ」フィールドを必須項目に変更しました。
これにより、フォーム作成時の設定漏れを防ぎ、ユーザーに適切な完了メッセージを表示することができます。
- バリデーションルールに`after_message`の必須チェックを追加
- 設定画面のラベルに「必須」バッジを表示
- エラーメッセージの表示処理を追加
特になし
なし
なし
=> [フォーム] 本登録後のメッセージを必須項目に設定しました

app/Plugins/User/Cabinets/CabinetsPlugin.php, app/Rules/CabinetNoDuplicateNameInDestination.php, app/Rules/CabinetNotIntoDescendant.php, app/Rules/CabinetSameCabinet.php, app/Rules/CabinetValidDestinationFolder.php, resources/views/plugins/user/cabinets/default/folder_options.blade.php, resources/views/plugins/user/cabinets/default/index.blade.php, tests/Feature/Plugins/User/Cabinets/CabinetMoveFeatureTest.php, tests/Unit/Plugins/User/Cabinets/CabinetMoveValidationTest.php
キャビネットのフォルダ間移動機能を追加しました（複数選択対応）。
- UI: 一覧のアクションバーに「移動」ボタン追加、移動先選択モーダル、フォルダツリーの再帰セレクト
- API: `move` アクションを追加し、権限（`posts.update`）とフレーム内フラッシュ表示に対応
- バリデーション: ルール化して整理
- `CabinetValidDestinationFolder`: 移動先がフォルダであること／同一キャビネットであること
- `CabinetSameCabinet`: 各移動対象が同一キャビネットであること
- `CabinetNotIntoDescendant`: 自身／配下への移動を禁止
- `CabinetNoDuplicateNameInDestination`: 移動先での同名重複を禁止
- リダイレクト: `redirect_path` はビュー側で指定、コントローラでは指定しない方針に統一
- 移動ボタンを追加
- 移動先選択ダイアログ
特になし（通常レビューで問題ありません）。
- #2262 fix(cabinets): cabinet_id 誤設定の修正＋既存データ修復マイグレーション
（なし）
無し
=> [キャビネット] フォルダ間の移動機能を追加しました

.github/workflows/create-release-v1-v2.yml
リリース自動化ワークフローにおいて、v2ブランチへのマージ処理をPR作成方式に変更し、version.phpの競合解決ロジックを改善しました。
**変更の背景**:
- 手動リリース手順に合わせてPR経由でのマージに変更
**改善内容**:
- masterから2ブランチへのPR自動作成機能を実装
- 競合解決用の一時ブランチ作成とマージ処理を追加  
なし
なし
GitHub CLIを使用したPR作成・マージ処理
一時ブランチによる競合解決方式
なし
- pull-requests: write権限の追加
- PR作成→競合解決→PR置き換え→自動マージのフロー実装
- sedコマンドによる適切なversion.php処理
=> [GitHub Actions] v2リリース時のPR作成と競合解決処理を改善しました

app/Models/Core/Configs.php
例外経路（例: /index.php%3F などの変則URL）で `ConnectInit` ミドルウェアが未実行のままエラービュー描画に進む場合があり、その際にレイアウトから呼ばれる `UploadController::getSiteCssTimestamp()` → `Configs::getSharedConfigs()` が `null` を返し、`firstWhere()` 実行時に「Call to a member function firstWhere() on null」で 500 となっていました。
対策として、`Configs::getSharedConfigs()` が `null` を返す状況では `collect()`（空コレクション）でフォールバックするようにし、例外レンダリング時の null 参照を防止しました。正常系の挙動に影響はありません。
変更内容:
- app/Models/Core/Configs.php
- `getSharedConfigs()` に null ガードを追加し、`$request->attributes['configs']` が未設定の場合は `collect()` を返却
軽微な修正のため急ぎません。ご都合の良いタイミングでご確認ください。
なし
- エラー発生箇所（ログより）:
- app/Http/Controllers/Core/UploadController.php: getSiteCssTimestamp() → getConfigsMaxUpdatedAt()
- resources/views/layouts/app.blade.php: サイトCSSリンクの `?version=` 生成で `UploadController::getSiteCssTimestamp()` 呼び出し
- …
=> [コア] 例外レンダリング時のnull参照を防止しました

app/Enums/MenuFrameConfig.php, app/Plugins/User/Menus/MenusPlugin.php, config/app.php, resources/views/plugins/user/menus/ancestor_descendant_sibling/menus.blade.php, resources/views/plugins/user/menus/breadcrumbs/menus.blade.php, resources/views/plugins/user/menus/common/edit_button.blade.php, resources/views/plugins/user/menus/default/menus.blade.php, resources/views/plugins/user/menus/default/menus_edit_roles.blade.php, resources/views/plugins/user/menus/default/menus_select.blade.php, resources/views/plugins/user/menus/dropdown/menus.blade.php, resources/views/plugins/user/menus/dropdown_hamburger/menus.blade.php, resources/views/plugins/user/menus/footersitemap/menus.blade.php, resources/views/plugins/user/menus/footersitemap_no_rootrink/menus.blade.php, resources/views/plugins/user/menus/hamburger/menus.blade.php, resources/views/plugins/user/menus/hamburger_button/menus.blade.php, resources/views/plugins/user/menus/menus_frame_edit_tab.blade.php, resources/views/plugins/user/menus/mouseover_dropdown/menus.blade.php, resources/views/plugins/user/menus/mouseover_dropdown_hamburger/menus.blade.php, resources/views/plugins/user/menus/mouseover_dropdown_no_rootlink/menus.blade.php, resources/views/plugins/user/menus/mouseover_dropdown_no_rootlink_for_design/menus.blade.php, resources/views/plugins/user/menus/mouseover_dropdown_no_rootlink_for_icon/menus.blade.php, resources/views/plugins/user/menus/opencurrenttree/menus.blade.php, resources/views/plugins/user/menus/opencurrenttree_for_design/menus.blade.php, resources/views/plugins/user/menus/parentsandchild/menus.blade.php, resources/views/plugins/user/menus/sitemap/menus.blade.php, resources/views/plugins/user/menus/sitemap_no_rootlink/menus.blade.php, resources/views/plugins/user/menus/tab/menus.blade.php, resources/views/plugins/user/menus/tab_flat/menus.blade.php, tests/Feature/Plugins/User/Menus/MenusModeratorEditFeatureTest.php
メニュープラグインでモデレータが「メニューを編集」操作を行えるようにしました。
従来はプラグイン管理者のみメニューの編集が可能でした。
モデレータへ編集許可の設定をすることで、プラグイン管理者でなくてもメニューを編集することができるようにしました。
- フレーム設定メニューにあったページ選択画面について、メニューの初期表示ページから遷移できるように変更
- ログインユーザーに編集権限がある場合に限り、各メニューテンプレートで編集ボタンを表示
- フレーム設定メニューに権限設定タブを追加し、設定画面を通じて「モデレータ編集許可」を設定できるように整備
なりません。
管理者が権限設定画面でモデレータに権限を付与しない限り、モデレータはメニューを編集できません。
メニュープラグインはバケツを持たないプラグインであるため、Connect-CMSのBucketsRolesを利用した権限チェック処理を利用していません。
その代わりに、FrameConfigを利用した権限チェックをプラグイン内に実装しました。
なし
#2271
なし
無し
=> [メニュー] モデレータがメニューを編集できるようにしました

config/.gitignore
Option Plugins用の設定ファイルディレクトリ (`config/option/`) をGit管理対象外にする設定を追加しました。
- `config/.gitignore` にて `option/` ディレクトリを除外対象に追加
- Option Plugins用設定ファイルのコメントを追記
Option Pluginsの設定ファイルには環境固有の情報が含まれる可能性があるため、Git管理対象外とすることでセキュリティと環境分離を向上させる。
特になし
なし
なし
=>   [システム] Option Plugins用設定ファイルをgitignoreに追加しました

resources/views/core/cms_frame_edit.blade.php
フレーム編集画面の「公開設定」で「限定公開」を選択して保存した後、画面を再表示すると「公開」が選択されてしまう不具合を修正しました。
- ラジオボタンの`checked`属性判定ロジックを修正
- 修正前: `{{ old('content_open_type', $frame->content_open_type) ? 'checked' : '' }}`
- 修正後: `{{ old('content_open_type', $frame->content_open_type) == $key ? 'checked' : '' }}`
1. フレーム編集画面で「限定公開」を選択して保存
2. 画面を再表示して「限定公開」が選択されていることを確認
3. 他の公開設定でも同様に動作することを確認
なし
https://github.com/opensource-workshop/connect-cms/issues/2274
なし
なし
=> [フレーム] 公開設定のラジオボタン選択状態が正しく表示されない不具合を修正しました
