public/info.php
https://github.com/opensource-workshop/connect-cms/issues/95
@nagasheep 
このファイルは削除でいいですか？
OKならマージお願いします。
=> phpinfo()ファイルが残っているため削除

.env.example, composer.json
https://github.com/opensource-workshop/connect-cms/issues/161
=> mod: composer.jsonのname等laravelのままなので修正 

config/cc_api_config.sample.php
=> add: SSOのsite_key、site_url、saltの説明コメントを追記

resources/views/plugins/manage/user/user_manage_tab.blade.php
=> bugfix: ユーザ管理＞タブ表示。<li>閉じタグ忘れ修正

app/Models/Common/Codes.php, app/Plugins/Manage/CodeManage/CodeManage.php, database/migrations/2020_02_03_154940_create_codes.php, resources/views/plugins/manage/code/code.blade.php, resources/views/plugins/manage/code/code_manage_tab.blade.php, resources/views/plugins/manage/code/regist.blade.php, resources/views/plugins/manage/menus_list.blade.php
=> add: コード管理追加

app/Plugins/Manage/CodeManage/CodeManage.php, resources/views/plugins/manage/code/regist.blade.php
・コピーして登録ボタンの表示/非表示を、チェックボックスで切り替えるように見直し
・ソート順の最後にcodeを追加
マージします。
=> mod: ・コード管理、別名登録⇒コピーして登録にボタン名変更

app/Plugins/Manage/CodeManage/CodeManage.php, resources/views/plugins/manage/code/code.blade.php
=> mod: ・コード管理の一覧にprefix表示

resources/views/plugins/manage/code/code.blade.php, resources/views/plugins/manage/code/regist.blade.php
* bugfix: 入力エラー時に値を保持してなかったため、保持するように対応
マージします。
=> add: コード管理、一覧に登録件数を表示

resources/views/plugins/manage/code/code.blade.php
=> mod: コード管理、管理画面のテーブル表示はclass=cc-font-90を使うといい感じ

app/Plugins/Manage/CodeManage/CodeManage.php, resources/views/plugins/manage/code/regist.blade.php
* mod: コピーして登録ボタンをチェックボックス切替をやめて、上に移動
マージします。
=> bugfix: 入力チェックエラーで、値を保持できてなかったバグ修正 他1件

app/Plugins/User/UserPluginBase.php
一般プラグインでも、設定画面で標準関数(editBuckets等)以外を追加した場合、標準関数と同様の権限チェックして欲しいため、
一般プラグインに`declareRole()`関数があれば、そこも追加で権限チェックしてくれるよう対応しました。
これがないと、独自で対応してない限り、標準関数(editBuckets等)以外 & 未ログイン & 設定画面のURL直打ちで画面見えちゃいます。
`declareRole()`関数は、管理プラグインの実装をそのまま持ってきました。
問題なさそうであれば、マージしようと思ってます。
```php
/**
*  追加の権限定義（コアから呼び出す）
*/
public function declareRole()
{
// 標準権限以外で設定画面などから呼ばれる権限の定義
// 標準権限は右記で定義 config/cc_role.php
$role_ckeck_table = array();
$role_ckeck_table["classCapture"]     = ['frames.edit'];
$role_ckeck_table["classCaptureSave"] = ['frames.create'];
return $role_ckeck_table;
}
```
=> add: 一般プラグインでも管理プラグインと同様に、追加の権限チェック関数declareRole()を利用できるように対応

app/Models/Common/Codes.php, app/Plugins/Manage/CodeManage/CodeManage.php
mod: バリデーションエラーのreturnで不要な括弧を削除
マージします。
=> add: コード管理: モデルにコードから値を取り出し関数 getCodeToValue() 追加

app/UserableNohistory.php
=> add: コード管理などの履歴なしmodelに適用するtrait（UserableNohistory）を作成。created_idを自動登録する

app/Models/Common/Codes.php
=> mod: コード管理のモデルCodesのホワイトリストfillableにadditional1～5が追加もれれたため対応

app/Userable.php, app/UserableNohistory.php
=> bugfix: deleted_id、deleted_name カラムがないテーブルが削除できなくなるバグを修正

resources/views/core/cms_frame_base.blade.php
Classを追加して実現する方法
Pull request のテスト
=> Bladeファイル修正の提案

resources/views/core/cms_frame_base.blade.php
=> 【bootstrapクラスを利用しstyleプロパティ削除】PULL リクエストの練習

app/Plugins/User/Databases/DatabasesPlugin.php, public/themes/Defaults/Default/themes.css, resources/views/plugins/user/databases/default/databases_edit.blade.php, resources/views/plugins/user/databases/default/databases_edit_row.blade.php, resources/views/plugins/user/databases/default/databases_edit_row_add.blade.php, resources/views/plugins/user/databases/default/databases_edit_row_detail.blade.php
永原さんに 作ってもらった migrations ファイルに対応させた、データベースプラグインの編集フォームです。
サイズ指定で気になった箇所があったので、Default の CSS に width の指定を追加しました。
=> データベースプラグインのカラム設定にClass名を追加その４

app/Plugins/Manage/CodeManage/CodeManage.php, resources/views/plugins/manage/code/code.blade.php, resources/views/plugins/manage/code/code_manage_tab.blade.php, resources/views/plugins/manage/code/display.blade.php, resources/views/plugins/manage/code/regist.blade.php
コード管理に一覧表示設定を追加する対応です。
マージします。
=> add: コード管理、一覧表示設定対応

.github/PULL_REQUEST_TEMPLATE.md
PR文化が根付いてきたのでPR用のテンプレです。
あまりガチガチにしたり項目増やしても面倒なので、緩めにしたつもり。
せっかくコードチェッカー導入したので、それはチェックリストに含めました。
=> プルリクエスト用テンプレート初版

app/Plugins/Manage/CodeManage/CodeManage.php, resources/views/plugins/manage/code/code.blade.php, resources/views/plugins/manage/code/regist.blade.php
コード管理に検索機能を追加しました。
マージします。
なし
Generic.Files.LineLength.TooLong   1行長い指摘が2件WARNINGSあるけど、マージしちゃいます。
1行長い指摘は、phpcsから外しちゃってもいいかもしれません。要相談かなぁ。
```
PHP CODE SNIFFER REPORT SUMMARY
----------------------------------------------------------------------------------------------------------------
FILE                                                                                            ERRORS  WARNINGS
----------------------------------------------------------------------------------------------------------------
/srv/public_html/iep-cc.opensource-workshop.jp/app/Plugins/Manage/CodeManage/CodeManage.php     0       2
----------------------------------------------------------------------------------------------------------------
A …
```
=> add: コード管理に検索機能追加

composer.json
composer.jsonのscripts-descriptions（scriptsの説明）をより具体的に記述しました。
マージします。
なし
https://getcomposer.org/doc/articles/scripts.md#writing-custom-commands
composer.jsonのみ修正のため、対象外
=> change: composer.json scripts-descriptions

resources/views/plugins/manage/code/code.blade.php
コード管理のバグ修正です。
マージします。
このプルリクの続き　https://github.com/opensource-workshop/connect-cms/pull/329
なし
bladeファイルのみの修正のため、対象外です。
=> bugfix: コード一覧、検索URLに不要な末尾の/が入っていて、不要なリダイレクトがかかり、検索条件に登録した日本語検索ができない不具合を修正

public/css/app.css
データベースプラグイン使用時に body に設定した class名 とコンフリクトを解消するため。
現在の app.css（bootstrap4.3.1）の該当部分を詳細指定に差し替えました。
【スタイルシート変更】app.css の差し替え
https://github.com/opensource-workshop/connect-cms/pull/404
https://github.com/opensource-workshop/connect-cms/wiki/PHP_CodeSniffer
=> 【スタイルシート変更】app.css の差し替え

resources/views/plugins/common/wysiwyg.blade.php
=> Youtube動画埋め込み用にmediaプラグイン追加

app/Traits/Migration/MigrationTrait.php
=> Nc2 migration - 最新取り込みのための同期

app/Models/User/Databases/DatabasesColumns.php, app/Models/User/Databases/DatabasesInputs.php, app/Traits/Migration/MigrationTrait.php
区切りの良いところでマージ
データベースプラグインのModelも変更が入っています。
無し
=> Nc2 migration 2020-07-18 16:00

app/Traits/Migration/MigrationTrait.php
=> テストのCommit

app/Traits/Migration/MigrationTrait.php
=> Nc2 migration 選択肢の移行

app/Models/Migration/Nc2/Nc2Item.php, app/Models/Migration/Nc2/Nc2User.php, app/Traits/Migration/MigrationTrait.php
=> 作業区切り（ユーザ移行）

app/Models/User/Learningtasks/Learningtasks.php, app/Models/User/Learningtasks/LearningtasksExaminations.php, app/Models/User/Learningtasks/LearningtasksPostsFiles.php, app/Models/User/Learningtasks/LearningtasksUsersStatuses.php, app/Plugins/User/Learningtasks/LearningtasksPlugin.php, app/Plugins/User/Learningtasks/LearningtasksUser.php, app/Providers/AppServiceProvider.php, composer.json, composer.lock, config/cc_role.php, database/migrations/2020_07_23_123511_mod_learningtasks_users_statuses_file_id.php, database/migrations/2020_07_24_085422_create_learningtasks_examinations.php, database/migrations/2020_07_24_180407_mod_learningtasks_posts_files_upload.php, database/migrations/2020_07_25_124336_add_learningtasks_repo_flag.php, resources/views/plugins/user/learningtasks/default/learningtasks.blade.php, resources/views/plugins/user/learningtasks/default/learningtasks_edit_examinations.blade.php, resources/views/plugins/user/learningtasks/default/learningtasks_edit_learningtasks.blade.php, resources/views/plugins/user/learningtasks/default/learningtasks_input.blade.php, resources/views/plugins/user/learningtasks/default/learningtasks_list_buckets.blade.php, resources/views/plugins/user/learningtasks/default/learningtasks_list_categories.blade.php, resources/views/plugins/user/learningtasks/default/learningtasks_show.blade.php, resources/views/plugins/user/learningtasks/old/learningtasks.blade.php, resources/views/plugins/user/learningtasks/old/learningtasks_edit_learningtasks.blade.php, resources/views/plugins/user/learningtasks/old/learningtasks_input.blade.php, resources/views/plugins/user/learningtasks/old/learningtasks_list_buckets.blade.php, resources/views/plugins/user/learningtasks/old/learningtasks_list_categories.blade.php, resources/views/plugins/user/learningtasks/old/learningtasks_show.blade.php
課題管理プラグインにレポート機能、レポート試験機能を追加の途中
有り
=> Learning task 機能アップ（途中）

app/Plugins/Manage/PageManage/PageManage.php, resources/views/plugins/manage/group/edit.blade.php, resources/views/plugins/manage/page/role.blade.php, resources/views/plugins/manage/user/groups.blade.php
ページの権限設定のバグ修正（前ページ同じ設定値が表示される）
まだ実装していない機能へのコメントなど追記
無し
- [×] PHP_CodeSnifferを実行して、本PR内に指摘が存在しないことを確認した。https://github.com/opensource-workshop/connect-cms/wiki/PHP_CodeSniffer
フレーム関係の関数でsnake 形式を使っているが、修正の影響が大きいため、今回はそのままにする。
=> ページ権限周りの修正

app/Http/Controllers/Core/DefaultController.php, app/Models/User/Learningtasks/LearningtasksUsersStatuses.php, app/Plugins/User/Learningtasks/LearningtasksPlugin.php, app/Plugins/User/Learningtasks/LearningtasksUser.php, resources/views/plugins/user/learningtasks/default/learningtasks_edit_users.blade.php, resources/views/plugins/user/learningtasks/default/learningtasks_input.blade.php, resources/views/plugins/user/learningtasks/default/learningtasks_list_grade.blade.php, resources/views/plugins/user/learningtasks/default/learningtasks_show.blade.php, resources/views/plugins/user/learningtasks/learningtasks_setting_edit_tab.blade.php
=> Learningtasks

resources/views/plugins/user/learningtasks/default/learningtasks_input.blade.php
=> 新規課題のキャンセル、とび先バグ修正

app/Plugins/User/Learningtasks/LearningtasksUser.php, resources/views/plugins/user/learningtasks/default/learningtasks_show.blade.php
=> 学生、教員両方の役割で、学生選択できなかったのを修正

app/Models/User/Learningtasks/Learningtasks.php, app/Models/User/Learningtasks/LearningtasksUsers.php, app/Plugins/User/Learningtasks/LearningtasksPlugin.php, app/Plugins/User/Learningtasks/LearningtasksUser.php, database/migrations/2020_07_26_113446_add_learningtasks_posts_join_flag.php, database/migrations/2020_07_30_102302_add_role_learningtasks_users.php, database/migrations/2020_07_30_103326_add_teacher_flag_learningtasks_posts.php, resources/views/plugins/user/learningtasks/default/learningtasks.blade.php, resources/views/plugins/user/learningtasks/default/learningtasks_edit_examinations.blade.php, resources/views/plugins/user/learningtasks/default/learningtasks_edit_learningtasks.blade.php, resources/views/plugins/user/learningtasks/default/learningtasks_edit_users.blade.php, resources/views/plugins/user/learningtasks/default/learningtasks_list_grade.blade.php, resources/views/plugins/user/learningtasks/default/learningtasks_select_function.blade.php, resources/views/plugins/user/learningtasks/default/learningtasks_show.blade.php, resources/views/plugins/user/learningtasks/learningtasks_setting_edit_tab.blade.php
バグ修正
有り
- [-] PHP_CodeSnifferを実行して、本PR内に指摘が存在しないことを確認した。https://github.com/opensource-workshop/connect-cms/wiki/PHP_CodeSniffer
あとで再度やります。
=> 作業区切り＆バグ修正

resources/views/plugins/user/learningtasks/learningtasks_setting_edit_tab.blade.php
無し
- [-] PHP_CodeSnifferを実行して、本PR内に指摘が存在しないことを確認した。https://github.com/opensource-workshop/connect-cms/wiki/PHP_CodeSniffer
あとで実施します。
=> 新規の課題作成時の課題設定メニューの修正

app/Http/Controllers/Auth/LoginController.php, app/Traits/ConnectCommonTrait.php, app/Traits/Migration/MigrationTrait.php
無し
- [-] PHP_CodeSnifferを実行して、本PR内に指摘が存在しないことを確認した。https://github.com/opensource-workshop/connect-cms/wiki/PHP_CodeSniffer
後で再度チェックします。
=> Nc2 migration

app/Traits/Migration/MigrationTrait.php, config/migration.php
=> NC2 ファイルのパスを.env に。

app/Models/Migration/Nc2/Nc2Config.php, app/Traits/Migration/MigrationTrait.php
=> サイト基本設定の移行を追加

app/Traits/Migration/MigrationTrait.php
=> 追加設定（メニュー）、frame の更新に対応

app/Console/Commands/Migration/ExportNc2.php, app/Traits/Migration/MigrationTrait.php, app/Traits/Migration/sample/migration_config/migration_config.sample.ini
=> エクスポート時にルームを絞る方式に変更

.env.example
無し
- [-] PHP_CodeSnifferを実行して、本PR内に指摘が存在しないことを確認した。https://github.com/opensource-workshop/connect-cms/wiki/PHP_CodeSniffer
=> nc2 migration .env サンプル追加

app/Models/Migration/Nc2/Nc2Registration.php, app/Models/Migration/Nc2/Nc2RegistrationBlock.php, app/Models/Migration/Nc2/Nc2RegistrationData.php, app/Models/Migration/Nc2/Nc2RegistrationItem.php, app/Models/Migration/Nc2/Nc2RegistrationItemData.php, app/Models/User/Forms/Forms.php, app/Models/User/Forms/FormsColumns.php, app/Models/User/Forms/FormsColumnsSelects.php, app/Models/User/Forms/FormsInputCols.php, app/Models/User/Forms/FormsInputs.php, app/Traits/Migration/MigrationTrait.php, app/Traits/Migration/sample/migration_config/migration_config.sample.ini
=> 登録フォームの移行ができた。

app/Traits/Migration/MigrationTrait.php
=> フォームのデータが空だった場合の対応

app/Traits/Migration/MigrationTrait.php
=> フォームのインポート修正

app/Traits/Migration/MigrationTrait.php, app/Traits/Migration/sample/migration/@addition/nc2_blocks/block_overwrite_18.ini
=> 元の設定を上書きできるオーバーライド設定の対応

app/Traits/Migration/MigrationTrait.php
=> ユーザーデータが新ディレクトリ構成に対応できていなかったので修正

app/Traits/Migration/MigrationTrait.php
=> データベースインポートなど修正

app/Plugins/User/Learningtasks/LearningtasksPlugin.php, resources/views/plugins/user/learningtasks/default/learningtasks.blade.php
=> 教員のタスク一覧追加

app/Models/Common/Frame.php, app/Traits/Migration/MigrationTrait.php
=> 初期値設定にフレームclass名を追加

app/Traits/Migration/MigrationTrait.php
=> uploads の指定でid の桁考慮

app/Models/User/Databases/Databases.php
=> fillable のカラム不足

app/Plugins/User/Learningtasks/LearningtasksPlugin.php, app/Plugins/User/Learningtasks/LearningtasksTool.php, config/connect.php, resources/views/plugins/user/learningtasks/default/learningtasks_show.blade.php
=> 課題管理メール送信対応

app/Models/User/Learningtasks/LearningtasksConfigs.php, app/Plugins/User/Learningtasks/LearningtasksPlugin.php, app/Plugins/User/Learningtasks/LearningtasksTool.php, config/connect.php, database/migrations/2020_08_26_153806_create_learningtasks_configs.php, resources/views/plugins/user/learningtasks/default/learningtasks_edit_mail.blade.php, resources/views/plugins/user/learningtasks/default/learningtasks_list_grade.blade.php, resources/views/plugins/user/learningtasks/learningtasks_frame_edit_tab.blade.php
=> 課題管理のメール設定対応

app/Http/Controllers/Core/UploadController.php, app/Models/Common/Uploads.php, app/Models/User/Learningtasks/LearningtasksUsersStatuses.php, app/Plugins/User/Learningtasks/LearningtasksPlugin.php, app/Plugins/User/Learningtasks/LearningtasksTool.php, database/migrations/2020_08_28_093924_add_check_method_uploads.php, resources/views/plugins/user/learningtasks/default/learningtasks_edit_learningtasks.blade.php, resources/views/plugins/user/learningtasks/default/learningtasks_show.blade.php
アップロードファイルの個別のチェックを行うために、CallBack機能の実装
有り
=> アップロードファイルのCallBackチェックの実装

app/Traits/Migration/MigrationTrait.php, public/css/connect.css
=> Migration でフッタ幅の指定を可能に。CSS フッターパターン追加。

app/Plugins/User/Databases/DatabasesPlugin.php, app/Providers/AppServiceProvider.php, app/Utilities/csv/SjisToUtf8EncodingFilter.php, config/cc_role.php, resources/views/plugins/user/databases/databases_frame_edit_tab.blade.php, resources/views/plugins/user/databases/default/databases_edit_row.blade.php, resources/views/plugins/user/databases/default/databases_import.blade.php, resources/views/plugins/user/databases/default/databases_list_buckets.blade.php
データベースプラグインにインポート機能追加します。
* add: database plugin, インポート機能追加
* add: import処理のCC_AUTHORITY・CC_METHOD_AUTHORITY・CC_METHOD_REQUEST_METHOD追加
* add: CC_METHOD_AUTHORITYにimportに関係するdownloadCsvFormat権限追加
* add: import追加に伴うbuckets.uploadCsv権限のゲートチェック追加
* change: database plugin, DB選択一覧画面のページ送りに、#frame-XXX アンカー追加
* change: database plugin, DB選択一覧画面の設定変更ボタンは画面遷移ボタンのため、btn-primary⇒btn-successに変更
* change: database plugin, DB選択一覧画面のダウンロードボタンは実行ボタンのため、btn-success⇒btn-primaryに変更
* change: database plugin, 項目設定の詳細ボタンは画面遷移のため、btn-primary⇒btn-success（青⇒緑色）に変更
詳細はこちらのリンク先
https://connect-cms.jp/manual/user/database#frame-178
https://github.com/opensource-workshop/connect-cms/issues/508
なし
無し
=> 【データベース】インポート機能追加

app/Plugins/Api/ApiPluginBase.php, app/Plugins/Api/Opac/OpacApi.php, app/Plugins/Api/User/UserApi.php
=> Opac 書籍情報API 追加

app/Plugins/Api/User/UserApi.php, app/Plugins/Manage/SystemManage/SystemManage.php, app/Traits/ConnectCommonTrait.php, resources/views/plugins/manage/system/auth.blade.php
=> API と外部認証の連携

app/Models/User/Opacs/OpacsBooksLents.php, app/Plugins/Api/Opac/OpacApi.php, app/Plugins/User/Opacs/OpacsPlugin.php
=> Opac のAPI 対応

app/Plugins/User/Opacs/OpacsPlugin.php, resources/views/plugins/user/opacs/default/opacs_my.blade.php, resources/views/plugins/user/opacs/default/opacs_rentlist.blade.php
=> Opac貸し出し中一覧

resources/views/errors/template_notfound.blade.php
開発時やバグの場合にわかりやすくする。
https://github.com/opensource-workshop/connect-cms/issues/533
無し
=> #533 テンプレートがないときのエラー画面をBootstrap 対応

app/Models/Migration/Nc2/Nc2Bbs.php, app/Models/Migration/Nc2/Nc2BbsBlock.php, app/Models/Migration/Nc2/Nc2BbsPost.php, app/Models/Migration/Nc2/Nc2BbsPostBody.php, app/Models/Migration/Nc2/Nc2Block.php, app/Traits/Migration/MigrationTrait.php, app/Traits/Migration/sample/migration_config/migration_config.sample.ini
=> BBS to Blog への移行など

app/Models/Migration/Nc2/Nc2Block.php, app/Models/Migration/Nc2/Nc2Faq.php, app/Models/Migration/Nc2/Nc2FaqBlock.php, app/Models/Migration/Nc2/Nc2FaqCategory.php, app/Models/Migration/Nc2/Nc2FaqQuestion.php, app/Models/User/Faqs/Faqs.php, app/Models/User/Faqs/FaqsPosts.php, app/Traits/Migration/MigrationTrait.php, app/Traits/Migration/sample/migration_config/migration_config.sample.ini
=> FAQ のNC2 to Connect-CMS 移行

app/Models/User/Databases/Databases.php, app/Models/User/Databases/DatabasesColumns.php, app/Models/User/Databases/DatabasesColumnsSelects.php, app/Models/User/Databases/DatabasesFrames.php, app/Models/User/Databases/DatabasesInputCols.php, app/Models/User/Databasesearches/Databasesearches.php, database/migrations/2020_09_16_140113_add_create_id_to_databases.php, database/migrations/2020_09_16_140126_add_create_id_to_databases_columns.php, database/migrations/2020_09_16_140135_add_create_id_to_databases_columns_selects.php, database/migrations/2020_09_16_140141_add_create_id_to_databases_frames.php, database/migrations/2020_09_16_140148_add_create_id_to_databases_input_cols.php, database/migrations/2020_09_16_140154_add_create_id_to_databasesearches.php
機能追加です。
https://github.com/opensource-workshop/connect-cms/issues/372
なし
有り
=> add: database plugin, dbカラムのシステム項目対応

resources/views/auth/login.blade.php, resources/views/core/cms.blade.php, resources/views/plugins/user/menus/default/menus_select.blade.php, resources/views/plugins/user/menus/dropdown/menus.blade.php, resources/views/plugins/user/menus/mouseover_dropdown/menus.blade.php, resources/views/plugins/user/menus/mouseover_dropdown_no_root/menus.blade.php, resources/views/plugins/user/menus/mouseover_dropdown_no_rootlink/menus.blade.php, resources/views/plugins/user/menus/mouseover_dropdown_no_rootlink_for_design/menus.blade.php, resources/views/plugins/user/menus/opencurrenttree/menus.blade.php, resources/views/plugins/user/menus/opencurrenttree_for_design/menus.blade.php, resources/views/plugins/user/menus/parentsandchild/menus.blade.php, resources/views/plugins/user/menus/tab/menus.blade.php, resources/views/plugins/user/themechangers/default/themechangers.blade.php
=> 画面上の指摘点の修正

app/Models/User/Databases/DatabasesInputs.php, app/Traits/Migration/MigrationTrait.php
=> データベースの機能アップへの追従

app/Models/Common/Permalink.php, app/Models/Migration/Nc2/Nc2AbbreviateUrl.php, app/Traits/Migration/MigrationTrait.php, database/migrations/2020_09_18_164305_create_permalink.php
=> Nc2 migration - 固定URLのインポートとエクスポート

app/Http/Controllers/Core/ConnectController.php, app/Http/Controllers/Core/MypageController.php, app/Plugins/Mypage/IndexMypage/IndexMypage.php, app/Plugins/Mypage/MypagePluginBase.php, app/Plugins/Mypage/ProfileMypage/ProfileMypage.php, app/Traits/ConnectCommonTrait.php, config/connect.php, resources/views/layouts/app.blade.php, resources/views/plugins/mypage/index/index.blade.php, resources/views/plugins/mypage/menus.blade.php, resources/views/plugins/mypage/menus_list.blade.php, resources/views/plugins/mypage/mypage.blade.php, resources/views/plugins/mypage/profile/edit.blade.php, resources/views/plugins/mypage/profile/edit_form.blade.php, resources/views/plugins/mypage/profile/profile_mypage_tab.blade.php, routes/web.php
機能追加です。
・マイページのURL /mypage/ はログインしないと開けません。
・自身のパスワード変更画面の追加です。
https://github.com/opensource-workshop/connect-cms/issues/572
なし
無し
=> add: core, マイページ、プロフィールの追加

app/Traits/ConnectCommonTrait.php, resources/views/layouts/app.blade.php, routes/web.php
=> mypage へのリンクの判断

app/Http/Controllers/Core/ConnectController.php, app/Traits/Migration/MigrationTrait.php, app/Traits/Migration/sample/migration_config/migration_config.sample.ini
=> NC2移行の固定URLの表示処理

app/Traits/Migration/MigrationTrait.php, app/Traits/Migration/sample/migration_config/migration_config.sample.ini
=> 移行時のコンテンツ、クリーニング。Style、Strong など。

app/Plugins/User/Menus/MenusPlugin.php, resources/views/plugins/user/menus/dropdown/menu_children.blade.php, resources/views/plugins/user/menus/dropdown/menus.blade.php, resources/views/plugins/user/menus/mouseover_dropdown/menus.blade.php, resources/views/plugins/user/menus/mouseover_dropdown_no_root/menus.blade.php, resources/views/plugins/user/menus/mouseover_dropdown_no_rootlink/menus.blade.php, resources/views/plugins/user/menus/tab/menus.blade.php
=> タブ系メニューのカレント処理の見直し

app/Traits/Migration/MigrationTrait.php, app/Traits/Migration/sample/migration_config/migration_config.sample.ini
=> エクスポート後にページの順番を入れ替える。

app/Http/Controllers/Core/UploadController.php, app/Models/Common/Uploads.php, app/Plugins/Manage/UploadfileManage/UploadfileManage.php, resources/views/plugins/manage/menus_list.blade.php, resources/views/plugins/manage/uploadfile/edit.blade.php, resources/views/plugins/manage/uploadfile/index.blade.php, resources/views/plugins/manage/uploadfile/uploadfile_manage_tab.blade.php
データベース定義を変更しない範囲での先行実装。
今後、別名登録やファイル削除などの機能を実装予定です。
#262 
https://github.com/opensource-workshop/connect-cms/issues/262
#250 
https://github.com/opensource-workshop/connect-cms/issues/250
#210
https://github.com/opensource-workshop/connect-cms/issues/210
#182
https://github.com/opensource-workshop/connect-cms/issues/182
無し
=> アップロードファイル管理

app/Models/Common/Page.php, resources/views/plugins/manage/page/page.blade.php, resources/views/plugins/manage/page/page_form.blade.php
ユーザーを指定するのではなく、ログインユーザ全員が閲覧できる設定が必要だったため追加
無し
=> 「ログインユーザ全員参加」ページの対応

resources/views/plugins/user/opacs/default/opacs.blade.php
=> 画面 フレームIDの対応で修正

app/Traits/Migration/MigrationTrait.php
=> データ中にタブ文字が存在するケースがあったため、タブ文字は半角スペースに置き換えるようにした。

public/fontawesome/css/all.css
アクセシビリティ指摘にCSSが含まれる事があり、CSSを調査するのにxxxx.min.cssでは調査しずらいため、
該当バージョンのxxxx.cssを含める形にしました。
なし
なし
無し
=> add: lib, font awesomeのall.css、CMSから参照されないが、CSSの内容理解のために対応バージョンのall.cssが必要なため

app/Models/User/Conventions/Convention.php, app/Models/User/Conventions/ConventionFrame.php, app/Models/User/Conventions/ConventionJoin.php, app/Models/User/Conventions/ConventionPost.php, app/Plugins/User/Conventions/ConventionsPlugin.php, app/Plugins/User/Conventions/ConventionsTool.php, app/Plugins/User/Conventions/plugin.ini, database/migrations/2020_10_02_190236_create_conventions.php, database/migrations/2020_10_02_190243_create_convention_posts.php, database/migrations/2020_10_02_190250_create_convention_frames.php, database/migrations/2020_10_05_174155_create_convention_joins.php, resources/views/plugins/user/conventions/conventions_frame_edit_tab.blade.php, resources/views/plugins/user/conventions/default/bucket.blade.php, resources/views/plugins/user/conventions/default/edit.blade.php, resources/views/plugins/user/conventions/default/frame.blade.php, resources/views/plugins/user/conventions/default/index.blade.php, resources/views/plugins/user/conventions/default/list_buckets.blade.php
=> Event plugin

app/Traits/Migration/MigrationTrait.php
=> データベースの移行でposted_at を反映

app/Traits/Migration/MigrationTrait.php, app/Traits/Migration/sample/migration/@nc2_override/blocks/24.ini
=> エクスポート時にブロック情報を上書きする仕組み

app/Traits/Migration/MigrationTrait.php, app/Traits/Migration/sample/migration_config/migration_config.sample.ini
=> 強制的にフレームデザインを適用する（none は対象外）オプション

public/themes/Defaults/DefaultAccessibility/themes.css
不具合修正です。
https://github.com/opensource-workshop/connect-cms/pull/614
なし
無し
=> bugfix: ログイン後のプラグイン右上の歯車マークが消える不具合修正

app/Traits/Migration/MigrationTrait.php
=> NC2 のWYSIWYGで 相対パス指定している場合の対応

resources/views/plugins/user/menus/dropdown/menus.blade.php, resources/views/plugins/user/menus/mouseover_dropdown/menus.blade.php, resources/views/plugins/user/menus/mouseover_dropdown_no_root/menus.blade.php, resources/views/plugins/user/menus/mouseover_dropdown_no_rootlink/menus.blade.php, resources/views/plugins/user/menus/mouseover_dropdown_no_rootlink_for_design/menus.blade.php, resources/views/plugins/user/menus/tab/menus.blade.php
=> 横メニューにページのクラス名設定を反映

resources/views/plugins/user/databases/default/databases.blade.php
バグ修正です。
詳細はissueを参照してください。https://github.com/opensource-workshop/connect-cms/issues/625
なし
なし
無し
=> bugfix: 各項目のcss class指定がきくように対応（入力値のみにclassを反映させる）

app/Traits/Migration/MigrationTrait.php
=> GA 削除の順番変更

app/Http/Controllers/Auth/LoginController.php, app/Http/Controllers/Auth/RegisterController.php, app/Http/Controllers/Auth/RegistersUsers.php, app/Http/Controllers/Core/ApiController.php, app/Plugins/Manage/UserManage/UserManage.php, app/Traits/ConnectCommonTrait.php, app/User.php, database/migrations/2020_10_07_151613_add_status_users.php, resources/views/auth/login.blade.php, resources/views/auth/registe_form.blade.php, resources/views/plugins/manage/uploadfile/index.blade.php, resources/views/plugins/manage/user/list.blade.php
=> API 呼び出し処理の修正、ユーザ管理の機能アップ

app/Plugins/Api/Opac/OpacApi.php
=> 貸し出し状況取得に対応

app/Traits/Migration/MigrationTrait.php
=> NC2 移行、汎用データベースの画像型とファイル型

app/Models/Common/Frame.php, app/Traits/Migration/MigrationTrait.php, app/Traits/Migration/sample/migration/@nc2_override/blocks/24.ini, app/Traits/Migration/sample/migration_config/migration_config.sample.ini
=> 登録フォームの登録データの移行しないフラグ。など。

app/Traits/Migration/MigrationTrait.php, app/Traits/Migration/sample/migration_config/migration_config.sample.ini
=> データベース、行列の位置など

app/Http/Controllers/Core/ConnectController.php, app/Plugins/Manage/PageManage/PageManage.php, database/migrations/2020_10_23_130043_add_transfer_lower_page_flag_to_pages.php, resources/views/plugins/manage/page/page_form.blade.php
機能追加です。
「下層ページへ自動転送する」をチェックすると、
下層ページの中から、メニュー表示「表示する」がチェックされた一番上のページに自動転送します。
https://github.com/opensource-workshop/connect-cms/issues/651
なし
有り
app\Plugins\Manage\PageManage\PageManage.phpでエラーが出ているが、今回修正箇所ではないため、スルーする。
```
> php composer.phar phpcs-any -- app\Plugins\Manage\PageManage
> phpcs --standard=phpcs.xml "app\Plugins\Manage\PageManage"
E 1 / 1 (100%)
FILE: app\Plugins\Manage\PageManage\PageManage.php
------------------------------------------------------------------------
FOUND 7 ERRORS AFFECTING 7 LINES
------------------------------------------------------------------------
LINE 229: ERROR Method
name
"PageManage::sequence_up"
is
not
in
camel
caps
format
(PSR1.Methods.CamelCapsMethodName.NotCamelCaps)
------------------------------------------------------------------------ …
```
=> add: ページ管理、カテゴリトップを下層有効ページに飛ばす機能を追加

app/Plugins/User/Opacs/OpacsPlugin.php
=> Opac NDL https に修正

app/Plugins/User/UserPluginBase.php
=> HTML チェックの修正（添付ファイルの _blank が効かなかったので）

app/Plugins/Manage/SecurityManage/SecurityManage.php
=> HTMLPurifier 対応

app/Plugins/User/Codestudies/CodestudiesPlugin.php, public/codemirror/lib/codemirror.css, public/codemirror/lib/codemirror.js, public/codemirror/lib/codemirror_cc.css, public/codemirror/mode/clike/clike.js, public/codemirror/mode/fortran/fortran.js, public/codemirror/mode/javascript/javascript.js, public/codemirror/mode/php/php.js, public/codemirror/mode/python/python.js, resources/views/plugins/user/codestudies/default/codestudies.blade.php
=> CodeStudyへのCodeMirrorの追加

app/Plugins/User/Codestudies/CodestudiesPlugin.php, resources/views/core/cms_frame_header.blade.php, resources/views/layouts/app.blade.php, resources/views/plugins/user/codestudies/default/codestudies.blade.php
=> CodeStudy 修正

app/Plugins/User/Codestudies/CodestudiesPlugin.php, resources/views/plugins/user/codestudies/default/codestudies.blade.php
=> 新コアのチェック対応

app/Plugins/User/Blogs/BlogsPlugin.php
=> 記事に編集URL などがあった場合の対応

app/Plugins/User/UserPluginBase.php, resources/views/plugins/manage/security/purifier.blade.php
=> htmlpurifier キャッシュディレクトリと設定時のエラー処理

.env.example, app/Http/Kernel.php, app/Http/Middleware/ResponseHeader.php, config/connect.php
=> HTTP ヘッダーセキュリティ強化

app/Plugins/User/Opacs/OpacsPlugin.php, resources/views/plugins/user/opacs/default/opacs.blade.php
=> Opac 検索機能の拡張

app/Plugins/User/Blogs/BlogsPlugin.php, app/Plugins/User/Contents/ContentsPlugin.php
=> HTMLpurifier 対応の追加

app/Models/Common/Uploads.php
=> pathinfo 関数のlocale 対応

app/Models/User/Calendars/CalendarPost.php, app/Plugins/User/Calendars/CalendarsPlugin.php, resources/views/plugins/user/calendars/default/edit.blade.php, resources/views/plugins/user/calendars/default/index.blade.php
=> カレンダー、当日表記や月跨り等の修正

app/Plugins/User/Calendars/CalendarsPlugin.php, resources/views/plugins/user/calendars/default/edit.blade.php
=> カレンダープラグイン From-To 関係チェックの追加

app/Enums/WhatsnewsTargetPlugin.php, app/Plugins/User/Bbses/BbsesPlugin.php, app/Plugins/User/Whatsnews/WhatsnewsPlugin.php
=> 掲示板（Bbses plugin）新着情報の対応

app/Http/Controllers/Auth/RegisterController.php, app/Plugins/Manage/SiteManage/SiteManage.php, resources/views/auth/registe_form.blade.php, resources/views/auth/register.blade.php, resources/views/plugins/manage/site/site.blade.php
=> ユーザ登録時の処理の追加

app/Models/User/Bbses/BbsPost.php
=> 返信時のタイトルの: の間違い修正

public/js/tinymce/plugins/file/plugin.min.js, resources/views/plugins/common/wysiwyg.blade.php
=> ディレクトリ・インストール時のファイルアップロードの修正

app/Models/User/Bbses/BbsFrame.php, app/Plugins/User/Bbses/BbsesPlugin.php, database/migrations/2021_02_27_081932_add_list_format_bbs_frames.php, resources/views/plugins/user/bbses/default/frame.blade.php, resources/views/plugins/user/bbses/default/index.blade.php, resources/views/plugins/user/bbses/default/post_title.blade.php, resources/views/plugins/user/bbses/default/post_title_div.blade.php, resources/views/plugins/user/bbses/default/show.blade.php
掲示板の表示方法を追加する。
https://github.com/opensource-workshop/connect-cms/issues/740
無し
=> #740 掲示板の表示方法の追加

app/Jobs/ApprovedNoticeJob.php, app/Jobs/DeleteNoticeJob.php, app/Jobs/PostNoticeJob.php, app/Jobs/RelateNoticeJob.php, app/Mail/ApprovedNotice.php, app/Mail/DeleteNotice.php, app/Mail/PostNotice.php, app/Mail/RelateNotice.php, app/Models/Common/BucketsMail.php, app/Plugins/User/Bbses/BbsesPlugin.php, app/Plugins/User/Databases/DatabasesPlugin.php, app/Plugins/User/UserPluginBase.php, resources/views/mail/post/approval_text.blade.php, resources/views/mail/post/approved_text.blade.php, resources/views/mail/post/delete_text.blade.php, resources/views/mail/post/post_text.blade.php, resources/views/mail/post/relate_text.blade.php, resources/views/plugins/common/frame_edit_mails.blade.php, resources/views/plugins/user/bbses/bbses_frame_edit_tab.blade.php
掲示板でもメール通知が欲しかった。
https://github.com/opensource-workshop/connect-cms/issues/746
無し
=> #746 掲示板のメール通知対応

app/Plugins/User/Receives/ReceivesPlugin.php
=> 最終ログ日付の取得を修正

resources/views/plugins/user/bbses/default/index.blade.php
記事一覧にあるので、そっちを参照。
タイトルは、スレッドを表すものとして、根記事のものを表示する。
無し
=> 一覧での展開方法：すべて閉じるの場合は、スレッドの枠に投稿時間、投稿ユーザを表示しない。

app/Plugins/Manage/UserManage/UserManage.php, app/User.php, resources/views/plugins/manage/user/list.blade.php
機能追加のプルリクエストです。
https://github.com/opensource-workshop/connect-cms/issues/779
なし
無し
=> add: ユーザ管理、エクスポート機能の追加

app/Plugins/Manage/MigrationManage/MigrationManage.php, app/Traits/Migration/MigrationTrait.php, app/Traits/Migration/sample/migration_config/migration_config.sample.ini, resources/views/plugins/manage/menus_list.blade.php, resources/views/plugins/manage/migration/migration_manage_tab.blade.php, resources/views/plugins/manage/migration/nc2upload.blade.php
NetCommons2 からのワンクリック移行が必要だったため。
無し
=> NetCommons2からのワンクリック移行

app/Plugins/Manage/SiteManage/SiteManage.php, resources/views/layouts/app.blade.php, resources/views/plugins/manage/page/page.blade.php, resources/views/plugins/manage/site/site.blade.php
サイト管理に基本ヘッダー任意クラスの追加するプルリクエストです。
特に問題ない追加対応だと思うのですが、一旦社内で確認するため、下書き（ドラフト）で作成します。
https://github.com/opensource-workshop/connect-cms/issues/811
無し
=> add: サイト管理、基本ヘッダー任意クラスの追加

app/Plugins/User/Forms/FormsPlugin.php, resources/views/plugins/user/forms/default/forms_edit.blade.php, resources/views/plugins/user/forms/default/forms_edit_row.blade.php, resources/views/plugins/user/forms/default/forms_edit_row_add.blade.php
- 関連PRに記載
- 項目設定画面がボタンだらけなのでUIは今後調整する
https://github.com/opensource-workshop/connect-cms/issues/867
https://github.com/opensource-workshop/connect-cms-ideas/issues/30
なし
なし
=> フォーム 項目のコピー機能の追加

resources/views/plugins/user/whatsnews/onerow/whatsnews.blade.php
新着情報の表示にて、１行表示用テンプレート追加
テンプレ追加なので、他機能への影響はありません。
なし。
なし
なし
=> add: 新着情報１行表示テンプレ追加

app/Enums/UserStatus.php, app/Plugins/Manage/UserManage/UserManage.php, app/Traits/ConnectCommonTrait.php, app/User.php, public/css/connect.css, resources/views/auth/registe_form.blade.php, resources/views/plugins/manage/user/bulk_delete.blade.php, resources/views/plugins/manage/user/user_manage_tab.blade.php
機能追加のプルリクエストです。
https://github.com/opensource-workshop/connect-cms/issues/868
なし
無し
composer phpcs-any -- app/Traits/ConnectCommonTrait.php  ※ 以前からメソッド名でphpcsエラーあり
=> 【ユーザ管理】一括削除機能の追加

app/Models/Migration/Nc2/Nc2Block.php, app/Models/Migration/Nc2/Nc2CabinetBlock.php, app/Models/Migration/Nc2/Nc2CabinetFile.php, app/Models/Migration/Nc2/Nc2CabinetManage.php, app/Models/User/Cabinets/Cabinet.php, app/Models/User/Cabinets/CabinetContent.php, app/Traits/Migration/MigrationTrait.php, app/Traits/Migration/sample/migration_config/migration_config.sample.ini, config/database.php, database/migrations/2021_07_08_145710_drop_columns_cabinets.php, database/migrations/2021_07_08_150018_add_columns_cabinet_contents.php
=> NC2キャビネット移行処理を追加しました

app/Plugins/User/Cabinets/CabinetsPlugin.php
500エラーの対応になります。
#930 
PR #907
無し
=> キャビネットプラグインにてファイル追加、削除すると500エラーとなる

app/Models/Migration/Nc2/Nc2Block.php, app/Models/Migration/Nc2/Nc2Counter.php, app/Models/User/Counters/CounterFrame.php, app/Plugins/User/Counters/CountersPlugin.php, app/Traits/Migration/MigrationTrait.php, app/Traits/Migration/sample/migration_config/migration_config.sample.ini, database/migrations/2021_08_03_153133_change_column_name_typo_yesterday_from_counter_frames.php, resources/views/plugins/user/counters/default/frame.blade.php, resources/views/plugins/user/counters/default/index.blade.php
NC2移行のカウンター対応です。
https://github.com/opensource-workshop/connect-cms/issues/936
なし
**あり**
=> add: nc2移行, カウンター対応

app/Http/Controllers/Core/DefaultController.php, app/Models/Common/Categories.php, app/Models/Common/Like.php, app/Models/Common/LikeUser.php, app/Models/User/Blogs/Blogs.php, app/Plugins/User/Blogs/BlogsPlugin.php, config/app.php, database/migrations/2021_08_19_132338_create_likes_table.php, database/migrations/2021_08_19_132344_create_like_users_table.php, database/migrations/2021_08_19_171538_add_use_like_and_like_button_name_from_blogs.php, database/migrations/2021_08_19_172344_drop_column_approval_flag_from_blogs.php, database/migrations/2021_08_19_172741_add_create_id_from_blogs.php, resources/views/layouts/app.blade.php, resources/views/plugins/common/like.blade.php, resources/views/plugins/user/blogs/default/blogs.blade.php, resources/views/plugins/user/blogs/default/blogs_edit_blog.blade.php, resources/views/plugins/user/blogs/default/blogs_show.blade.php, resources/views/plugins/user/blogs/designbase/blogs_show.blade.php, routes/web.php
* 【ブログ】いいねの追加 https://github.com/opensource-workshop/connect-cms/issues/956
* 関連対応
* 共通部品としていいねボタン追加
* add: コア, jsonアクションでもidを受け渡しするように対応
* change: vue, IE11非同期時のPolyfill対象プラグインにブログ追加 （いいねボタンを使うプラグインはこの対応必要） https://github.com/opensource-workshop/connect-cms/pull/970/files#diff-66a3ba2334a6e1eebc24807619f1d4e991f1e8f58c5b5af2c787198d62c547d7
* add: ブログ, blogsテーブルにcreated_id等のシステム項目追加 #853
* delete: ブログ, blogsテーブルで使用していないapproval_flag削除 
概要参照
なし
有り
=> 【ブログ】いいねの追加 

app/Models/Core/ConfigsLoginPermits.php, app/Plugins/Manage/SecurityManage/SecurityManage.php, database/migrations/2021_09_10_134446_add_column_memo_configs_login_permits_table.php, resources/views/plugins/manage/security/loginpermit.blade.php
https://github.com/opensource-workshop/connect-cms-ideas/issues/70
なし
あり
=> セキュリティ管理 ログイン制限にメモ欄を追加

.env.example, config/connect.php
オプション機能でPDF文字列変換APIを利用するため、
その設定値を定義しました。
#984
無し
=> add: PDF文字列変換APIの設定を追加

app/Enums/DisplayNumberType.php, resources/lang/en/messages.php, resources/lang/ja/messages.php
検索画面を多言語化するため、言語ファイルおよび検索画面で使われるenumを修正しました。
プライベートリポジトリ
プライベートリポジトリ
無し
=> 検索画面の多言語対応

resources/lang/en/messages.php, resources/lang/ja/messages.php
検索画面を多言語化するため、言語ファイルを修正しました。
プライベートリポジトリ
プライベートリポジトリ
無し
=> add: 検索項目の英語対応

app/Plugins/User/Databases/DatabasesTool.php
https://github.com/opensource-workshop/connect-cms/issues/1041
無し
=> データベース フリーワード検索で内部的に全角スペースは半角スペースに置換して検索処理にかける

resources/views/plugins/user/databasesearches/default/databasesearches.blade.php
https://github.com/opensource-workshop/connect-cms/issues/1043
無し
=> データベース検索 表示指定した列でHTMLがエスケープされてHTML表示されない

app/Enums/BlogFrameConfig.php, app/Plugins/User/Blogs/BlogsPlugin.php, resources/views/plugins/common/facebook.blade.php, resources/views/plugins/common/twitter.blade.php, resources/views/plugins/user/blogs/default/blogs.blade.php, resources/views/plugins/user/blogs/default/blogs_setting_frame.blade.php, resources/views/plugins/user/blogs/default/blogs_show.blade.php, resources/views/plugins/user/blogs/designbase/blogs_show.blade.php
https://github.com/opensource-workshop/connect-cms/issues/51
要望があったこと＆もともとの予定にもあったため。
無し
マニュアルはあとで、自動化で実施したい。
=> ブログにTwitter、Facebookボタンの表示設定を追加

resources/views/plugins/common/facebook.blade.php, resources/views/plugins/common/twitter.blade.php, resources/views/plugins/user/blogs/default/blogs.blade.php, resources/views/plugins/user/blogs/default/blogs_show.blade.php
環境によってはSNS投稿ウィンドウがオープンしなかったので修正
無し
=> Blog sns plus 修正

resources/views/core/cms_frame.blade.php, resources/views/errors/403_inframe.blade.php, resources/views/errors/404_inframe.blade.php, resources/views/errors/500_inframe.blade.php, resources/views/errors/error_inframe.blade.php
さっきのマージの追加修正
https://github.com/opensource-workshop/connect-cms/pull/1071
無し
=> メッセージの受け渡し修正

app/Enums/SearchsTargetPlugin.php, app/Plugins/User/Bbses/BbsesPlugin.php, app/Plugins/User/Blogs/BlogsPlugin.php, app/Plugins/User/Contents/ContentsPlugin.php, app/Plugins/User/Databases/DatabasesPlugin.php, app/Plugins/User/Searchs/SearchsPlugin.php
サイト内検索プラグイン
検索対象の対象プラグインにデータベースプラグインを追加しました。
#1085
https://github.com/opensource-workshop/connect-cms-ideas/issues/72
無し
=> 【サイト内検索】データベースプラグイン対応

app/Traits/Migration/MigrationTrait.php
view_countの列削除に関する移行プログラムへの対応漏れ
#1082
無し
=> fix: view_countの列削除によるエラー

app/Plugins/Mypage/IndexMypage/IndexMypage.php, resources/views/plugins/mypage/index/index.blade.php
=> add: mypage出力

app/Http/Controllers/Auth/LoginController.php, app/Http/Middleware/ConnectMypage.php, app/Plugins/Mypage/IndexMypage/IndexMypage.php, app/Plugins/Mypage/LoginHistoryMypage/LoginHistoryMypage.php, app/Plugins/Mypage/ProfileMypage/ProfileMypage.php, resources/views/layouts/app.blade.php
マイページ、ログイン画面のサイトテーマ適応
無し
無し
無し
=> Include theme

app/Models/Core/Dusks.php, app/Plugins/Manage/UserManage/UserManage.php, resources/views/manual/common/layout_base.blade.php, resources/views/manual/method.blade.php, resources/views/manual/pdf/method.blade.php, resources/views/manual/pdf/plugin.blade.php, resources/views/manual/plugin.blade.php, tests/Browser/Manage/UserManageTest.php, tests/Manual/html_src/css/manual.css, tests/Manual/insertion/manage/user/foot.txt, tests/bin/connect-cms-test.bat
=> Test&manual マニュアルにユーザ管理を追加

app/Plugins/Manage/GroupManage/GroupManage.php, tests/Browser/Manage/GroupManageTest.php, tests/bin/connect-cms-test.bat
=> マニュアルにグループ管理を追加

app/Plugins/Manage/ApiManage/ApiManage.php, app/Plugins/Manage/MessageManage/MessageManage.php, tests/Browser/Manage/ApiManageTest.php, tests/Browser/Manage/MessageManageTest.php, tests/bin/connect-cms-test.bat
=> マニュアルにAPI管理とメッセージ管理を追加

docker/app/Dockerfile
Docker定義について、以下の改善を行いました。
- GDのインストール
- #1038 でGDを利用する機能が追加された
- PHPのTImezone設定
- Dockerfile内のコメント修正
無し
=> Docker定義の改善

resources/views/layouts/app.blade.php
https://github.com/opensource-workshop/connect-cms/issues/1118
無し
=> コア テーマCSSのファイル存在チェックを追加

app/Plugins/User/Learningtasks/LearningtasksPlugin.php
=> bugfix: 課題管理、設定変更すると500エラーを修正 

app/Plugins/Manage/LogManage/LogManage.php, resources/views/plugins/manage/log/edit.blade.php, resources/views/plugins/manage/log/log.blade.php, tests/Browser/Manage/LogManageTest.php, tests/DuskTestCase.php, tests/bin/connect-cms-test.bat
=> テスト＆マニュアルにログ管理を追加

app/Plugins/Manage/HolidayManage/HolidayManage.php, tests/Browser/Manage/HolidayManageTest.php, tests/bin/connect-cms-test.bat
=> テスト＆マニュアルに祝日管理を追加

app/Plugins/Manage/HolidayManage/HolidayManage.php, app/Plugins/Manage/MigrationManage/MigrationManage.php, tests/Browser/Manage/MigrationManageTest.php, tests/bin/connect-cms-test.bat
=> テスト＆マニュアルに他システム移行を追加

app/Plugins/User/Learningtasks/LearningtasksPlugin.php
件名通り
* https://github.com/opensource-workshop/connect-cms/issues/1137
なし
無し
=> bugfix: 課題管理、管理者で試験を代理提出できないバグ修正

app/Plugins/User/Blogs/BlogsPlugin.php, tests/Browser/User/BlogsPluginTest.php
=> ブログのマニュアルに説明追加

app/Models/Common/Buckets.php
=> プラグイン管理者は承認不要を見直し、承認必要に変更する

app/Plugins/User/Calendars/CalendarsPlugin.php, resources/views/manual/method.blade.php, resources/views/manual/pdf/method.blade.php, resources/views/plugins/user/calendars/default/edit.blade.php, tests/Browser/User/CalendarsPluginTest.php, tests/bin/connect-cms-test.bat
=> テスト＆マニュアル　カレンダー追加

resources/views/manual/method.blade.php, resources/views/manual/pdf/method.blade.php, tests/Browser/User/SlideshowsPluginTest.php, tests/DuskTestCase.php, tests/Manual/src/ManualOutput.php, tests/bin/connect-cms-test.bat
=> マニュアルのテンプレートの対応

app/Plugins/User/Whatsnews/WhatsnewsPlugin.php, resources/views/plugins/user/whatsnews/default/whatsnews_edit_whatsnew.blade.php, tests/Browser/User/WhatsnewsPluginTest.php, tests/bin/connect-cms-test.bat
=> 自動テスト＆マニュアルに新着情報を追加

app/Plugins/User/Faqs/FaqsPlugin.php, resources/views/plugins/user/faqs/default/faqs.blade.php, resources/views/plugins/user/faqs/default/faqs_edit_faq.blade.php, tests/Browser/User/FaqsPluginTest.php, tests/bin/connect-cms-test.bat
=> 自動テスト＆マニュアルにFAQを追加

app/Plugins/User/Linklists/LinklistsPlugin.php, tests/Browser/User/LinklistsPluginTest.php, tests/bin/connect-cms-test.bat
=> 自動テスト＆マニュアル　リンクリスト対応

app/Plugins/User/Blogs/BlogsPlugin.php, app/Plugins/User/Calendars/CalendarsPlugin.php, app/Plugins/User/Contents/ContentsPlugin.php, app/Plugins/User/Faqs/FaqsPlugin.php, app/Plugins/User/Openingcalendars/OpeningcalendarsPlugin.php, app/Plugins/User/Slideshows/SlideshowsPlugin.php, app/Plugins/User/Whatsnews/WhatsnewsPlugin.php, tests/Browser/User/BlogsPluginTest.php, tests/Browser/User/CalendarsPluginTest.php, tests/Browser/User/FaqsPluginTest.php, tests/Browser/User/LinklistsPluginTest.php, tests/Browser/User/MenusPluginTest.php, tests/Browser/User/OpeningcalendarsPluginTest.php, tests/Browser/User/SlideshowsPluginTest.php, tests/Browser/User/WhatsnewsPluginTest.php, tests/DuskTestCase.php
=> 自動テスト＆マニュアル　表記の調整

app/Plugins/User/Opacs/OpacsPlugin.php, resources/views/plugins/user/opacs/default/opacs.blade.php, resources/views/plugins/user/opacs/default/opacs_setting_frame.blade.php, tests/Browser/User/LinklistsPluginTest.php, tests/Browser/User/OpacsPluginTest.php, tests/Browser/User/OpeningcalendarsPluginTest.php, tests/bin/connect-cms-test.bat
=> 自動テスト＆マニュアルにOPACを追加

resources/lang/en/messages.php, resources/lang/ja/messages.php
=> Add: 検索結果0件時のダウンロード不可メッセージ

app/Plugins/User/Blogs/BlogsPlugin.php, app/Plugins/User/Cabinets/CabinetsPlugin.php, app/Plugins/User/Calendars/CalendarsPlugin.php, app/Plugins/User/Faqs/FaqsPlugin.php, app/Plugins/User/Linklists/LinklistsPlugin.php, app/Plugins/User/Whatsnews/WhatsnewsPlugin.php, tests/bin/connect-cms-test.bat
=> マニュアル用クラスコメントの修正

app/Plugins/User/Tabs/TabsPlugin.php, resources/views/plugins/user/tabs/default/tabs_select.blade.php, tests/Browser/User/TabsPluginTest.php, tests/bin/connect-cms-test.bat
=> 自動テスト＆マニュアルにタブを追加

resources/views/manual/common/badge_menu.blade.php
=> 公開に向けて、まだの部分は非表示にする。

app/Plugins/User/Reservations/ReservationsPlugin.php, resources/views/plugins/manage/reservation/index.blade.php, resources/views/plugins/user/reservations/default/choice_facilities.blade.php, resources/views/plugins/user/reservations/default/frame.blade.php, tests/Browser/Common/WysiwygTest.php, tests/Browser/Manage/ReservationManageTest.php, tests/Browser/User/ReservationsPluginTest.php, tests/bin/connect-cms-test.bat
=> 自動テスト＆マニュアルに施設予約を追加

resources/views/plugins/user/databases/card_02/databases.blade.php, resources/views/plugins/user/databases/card_02/databases_detail.blade.php, resources/views/plugins/user/databases/card_02/template.ini
データベーステンプレート作成
カードタイプ（２列）
データベースプラグイン　一覧画面がカードタイプ（２列）のテンプレートを作成しました
無し
=> データベーステンプレート作成（カードタイプ）

resources/views/plugins/user/whatsnews/card_04/whatsnews.blade.php
カードタイプなので、カード全体がリンクになるように変更。
なし
=> 新着情報カードタイプ変更

resources/views/plugins/user/whatsnews/card_03/whatsnews.blade.php, resources/views/plugins/user/whatsnews/card_04/whatsnews.blade.php
=> 新着情報カードタイプ：修正

resources/views/plugins/user/databasesearches/card_03/databasesearches.blade.php, resources/views/plugins/user/databasesearches/card_04/databasesearches.blade.php
=> データベース検索：カード３タイプ追加

.github/PULL_REQUEST_TEMPLATE.md, app/Http/Controllers/Core/DefaultController.php, app/Plugins/User/Bbses/BbsesPlugin.php, app/Plugins/User/Blogs/BlogsPlugin.php, app/Plugins/User/Codestudies/CodestudiesPlugin.php, app/Plugins/User/Contents/ContentsPlugin.php, app/Plugins/User/Faqs/FaqsPlugin.php, app/Plugins/User/Learningtasks/LearningtasksPlugin.php, app/Plugins/User/Opacs/OpacsPlugin.php, app/Plugins/User/Reservations/ReservationsPlugin.php, app/Plugins/User/Searchs/SearchsPlugin.php, app/Plugins/User/Slideshows/SlideshowsPlugin.php, app/Plugins/User/UserPluginBase.php, app/Plugins/User/Whatsnews/WhatsnewsPlugin.php, app/Traits/ConnectCommonTrait.php
phpcsチェックの修正で、`ConnectCommonTrait::view_error()` ⇒ `viewError()` に修正しました。
関連Pull requestsがあるため、社内確認してからマージ予定。
なし
無し
=> fix: phpcs ConnectCommonTrait::viewError()

app/Http/Middleware/ConnectPage.php, app/Models/Common/Frame.php, app/Models/Common/Page.php, app/Plugins/User/Whatsnews/WhatsnewsPlugin.php, resources/views/core/cms_frame.blade.php
下記対応
* https://github.com/opensource-workshop/connect-cms/issues/1061
* フレーム違いの同じ新着が表示される不具合修正
概要通り
なし
無し
=> 新着情報, 表示データの見直し

app/Plugins/User/Whatsnews/WhatsnewsPlugin.php, resources/views/plugins/user/whatsnews/card_04/whatsnews.blade.php, resources/views/plugins/user/whatsnews/default/whatsnews.blade.php, resources/views/plugins/user/whatsnews/onerow/whatsnews.blade.php
=> bugfix: 新着情報, データベースでウィジウィグ型のタイトル指定の場合でも、タグを表示しないよう対応 

.gitignore, sync_dev_2_option_private.sh.example, sync_option_private_2_dev.sh.example
オプションプラグインで独自ルールを追加するため、コピーバッチも修正します。
無し
=> Add: オプションプラグインの独自ルールをコピーする

app/Enums/NoticeEmbeddedTag.php, app/Enums/UserRegisterNoticeEmbeddedTag.php, app/Http/Controllers/Auth/RegisterController.php, app/Http/Controllers/Auth/RegistersUsers.php, app/Models/Common/BucketsMail.php, app/Plugins/Manage/UserManage/UserManage.php, app/Plugins/Manage/UserManage/UsersTool.php, config/app.php, resources/views/auth/registe_form.blade.php, resources/views/auth/registe_form_input_agree.blade.php, resources/views/auth/registe_form_input_checkbox.blade.php, resources/views/auth/registe_form_input_mail.blade.php, resources/views/auth/registe_form_input_radio.blade.php, resources/views/auth/registe_form_input_select.blade.php, resources/views/auth/registe_form_input_text.blade.php, resources/views/auth/registe_form_input_textarea.blade.php, resources/views/plugins/manage/user/auto_regist.blade.php, resources/views/plugins/manage/user/mail.blade.php
件名通り。
軽めの全体動作確認。
https://github.com/opensource-workshop/connect-cms/actions/runs/2038751291
* #1223
無し
=> 【ユーザ管理】ユーザ登録後にメール通知機能の追加

resources/views/core/cms_frame_edit.blade.php, resources/views/manual/pdf/backfront.blade.php, tests/Browser/Common/FrameTest.php, tests/Browser/User/BbsesPluginTest.php, tests/Browser/User/DatabasesPluginTest.php, tests/Browser/User/ReservationsPluginTest.php
=> メール通知設定を共通部分に移動

app/Plugins/User/Photoalbums/PhotoalbumsPlugin.php, app/Utilities/Zip/UnzipUtils.php, resources/views/plugins/user/photoalbums/default/index.blade.php
Zipファイルで一気に画像をアップロードしたい。という要望対応
無し
=> Photoalbums 画像のzipファイル対応

tests/Browser/Common/FrameTest.php, tests/Browser/Manage/UploadfileManageTest.php, tests/Browser/User/BbsesPluginTest.php, tests/Browser/User/BlogsPluginTest.php, tests/Browser/User/ContentsPluginTest.php, tests/Browser/User/FaqsPluginTest.php, tests/DuskTestCase.php
=> github actionsのduskテストエラー修正

.env.example
=> .env サンプルの整理

app/Models/Core/Dusks.php, config/connect.php, resources/views/manual/method.blade.php, tests/Browser/User/PhotoalbumsPluginTest.php, tests/Manual/src/ManualVideo.php
=> 動画マニュアルのテスト

app/Traits/Migration/MigrationTrait.php
・社内確認してからマージ予定。
・現在の固定URLの移行は、下記手順でないと固定URLの移行データができない処理になっているため、その修正です。
１．移行エクスポート →固定URLの移行データが正しくできない。
２．移行インポート
３．移行エクスポート →固定URLの移行データができあがる。
なし
無し
=> bugfix: 移行, 固定URLはエクスポート・インポートを２週しないと移行できない不具合修正

app/Http/Middleware/ConnectPage.php, app/Models/Common/Permalink.php, app/Traits/Migration/MigrationTrait.php, database/migrations/2022_04_06_085625_add_nc2_block_id_from_permalinks.php
=> change: 移行, 固定URLの移行改善 

app/Models/Core/Dusks.php, resources/views/manual/category.blade.php, resources/views/manual/plugin.blade.php, tests/Manual/src/ManualVideo.php
=> 動画マニュアルのカテゴリ対応

app/Models/Core/Dusks.php, tests/Manual/src/ManualVideo.php
=> 設計以外のカテゴリの動画

app/Plugins/User/Databases/DatabasesPlugin.php, resources/views/plugins/user/databases/default/databases_import.blade.php
使い方を間違えやすかったので改善しました。
**修正１**
注意書きを補記
**修正２**
エラーメッセージを正確に。
ついでに、マニュアルのリンクを新サイトへ変更しました。
#1255 
#1256 
無し
=> Update: ZIPファイルインポートの説明を強化

app/Enums/ManualCategory.php, app/Models/Core/Dusks.php, resources/views/manual/index.blade.php, tests/Browser/Common/WysiwygTest.php, tests/Browser/Top/IndexTopTest.php, tests/Manual/src/ManualPdf.php, tests/Manual/src/ManualVideo.php, tests/bin/connect-cms-test.bat
Test&manual PDFにtopカテゴリを含めない。
無し
=> Test&manual PDFにtopカテゴリを含めない。

resources/views/plugins/common/wysiwyg.blade.php
IE のファイルアップロード対応
https://github.com/opensource-workshop/connect-cms/issues/1267
無し
IE、Chrome、Edge（Chrome版）確認済みです。
=> #1267 WYSIWYG のファイルアップロードをIEでも動くように修正

resources/views/plugins/common/wysiwyg.blade.php
* https://github.com/opensource-workshop/connect-cms/issues/1269
issueの不具合修正
無し
=> bugfix: ウィジウィグ, 罫線が反映されない不具合修正

tests/Browser/Theme/ThemeTest.php
=> 書きかけが混じったので修正

app/Models/Core/Dusks.php, resources/views/manual/category.blade.php, resources/views/manual/index.blade.php, resources/views/manual/method.blade.php, resources/views/manual/plugin.blade.php, tests/Manual/src/ManualOutput.php
=> poster画像対応

resources/views/plugins/common/frame_edit_buckets.blade.php
=> Labelの識別子の追加

resources/views/manual/index.blade.php
=> マーケットサイトのリンクを追加

app/Models/Migration/Nc2/Nc2Block.php, app/Traits/Migration/MigrationTrait.php, app/Traits/Migration/sample/migration_config/migration_config.sample.ini
件名通り。
スライド表示は、スライダーに移行したいけど、まだ。
なし
なし
なし
無し
=> add: OW-672 移行: NC2フォトアルバムの移行対応

app/Models/Migration/Nc2/Nc2PhotoalbumBlock.php, app/Traits/Migration/MigrationTrait.php
件名通り
なし
* https://github.com/opensource-workshop/connect-cms/pull/1299
なし
なし
=> add: OW-672 移行: NC2フォトアルバムのスライド表示はスライドショーに移行

.github/workflows/phpcs.yml, app/Models/Migration/Nc2/Nc2Assignment.php, app/Models/Migration/Nc2/Nc2Circular.php, app/Models/Migration/Nc2/Nc2MultidatabaseContent.php, app/Models/Migration/Nc2/Nc2Questionnaire.php, app/Models/Migration/Nc2/Nc2Quiz.php, app/Models/Migration/Nc2/Nc2Todo.php, app/Traits/Migration/MigrationTrait.php, app/Traits/Migration/sample/migration_config/migration_config.sample.ini
* エクスポート時にnc2リンクチェックする
* チェックするリンク
* ウィジウィグ内のリンク
* リンクリスト
* 汎用DBのリンク型
なし
なし
なし
なし
=> add: OW-947 移行, nc2リンク切れチェック機能追加

resources/views/plugins/user/forms/default/forms_confirm.blade.php
https://github.com/opensource-workshop/connect-cms/issues/1303
6/16（木）急ぎません。とりあえず1週間
https://github.com/opensource-workshop/connect-cms/issues/1303
なし
なし
該当なし
=> 【フォーム】登録／仮登録のボタン多重クリック防止

app/Plugins/Manage/PageManage/PageManage.php, app/Plugins/Mypage/IndexMypage/IndexMypage.php
件名通り
なし
* https://github.com/opensource-workshop/connect-cms/issues/1309
なし
なし
=> OW-1069 bugfix: ページ管理のCSVインポートで日本語の固定リンクもインポートできるように対応

resources/lang/en/messages.php, resources/lang/ja/messages.php
横スクロールがある表に対する注釈用のメッセージを追加しました。
6/23（木）
無し
=> OW-1047 Add: 横スクロールがある表の注釈

app/Models/User/Reservations/ReservationsInput.php, app/Plugins/User/Reservations/ReservationsPlugin.php
* https://github.com/opensource-workshop/connect-cms/issues/1317
なし
なし
なし
なし
=> bugfix: 施設予約, 承認済みメールの埋め込みタグ対応

public/js/tinymce/langs/ja.js
* https://github.com/opensource-workshop/connect-cms/issues/1322
なし
なし
なし
なし
=> add: WYSIWYG, 表の「列」の詳細メニューの英語表示を日本語に対応

resources/views/plugins/user/menus/default/menus.blade.php, resources/views/plugins/user/menus/sitemap/menus.blade.php, resources/views/plugins/user/menus/sitemap_no_rootlink/menus.blade.php, resources/views/plugins/user/menus/tab_flat/menus.blade.php
* メニューの表示見直しテンプレート
* default
* サイトマップ
* サイトマップ（ルートのリンクなし）
* タブフラット
メニューの全テンプレートを調査・確認しました。
なし
なし
なし
なし
=> OW-1072 change: メニュー, 表示見直し

app/Enums/BlogNoticeEmbeddedTag.php, app/Models/User/Blogs/BlogsPosts.php, app/Plugins/User/Blogs/BlogsPlugin.php, app/Traits/Migration/MigrationTrait.php, app/UserableNohistory.php, config/app.php, database/migrations/2022_06_22_140435_add_first_committed_at_from_blogs_posts.php, resources/views/plugins/user/blogs/blogs_frame_edit_tab.blade.php, resources/views/plugins/user/blogs/description_frame_mails.blade.php, resources/views/plugins/user/reservations/description_frame_mails.blade.php
* https://github.com/opensource-workshop/connect-cms/issues/1283
* [bugfix: core, 初回確定日時カラム（first_committed_at）は値がセット済みであれば更新しない](https://github.com/opensource-workshop/connect-cms/pull/1316/commits/4ff8ec8057d937f0571ac29f7836a014055941c8)
* [doc: 施設予約, メール設定bladeのコメント修正](https://github.com/opensource-workshop/connect-cms/pull/1316/commits/2367eba70c980372924e2a2b72d2c4c155f82839)
* [add: 移行, ブログのメール送信設定移行対応](https://github.com/opensource-workshop/connect-cms/pull/1316/commits/975a3cd90cd1893fe118610c0fc3c916e532957d)
なし
なし
なし
あり
=> 【ブログ】メール通知機能の追加 

app/Http/Middleware/ConnectPage.php, resources/views/layouts/app.blade.php, resources/views/layouts/default_menu.blade.php, resources/views/layouts/opencurrenttree_menu.blade.php
=> OW-1055 バグFIX

app/Enums/FaqFrameConfig.php, app/Plugins/User/Faqs/FaqsPlugin.php, config/app.php, resources/views/plugins/user/faqs/default/faqs.blade.php, resources/views/plugins/user/faqs/default/faqs_edit_faq.blade.php, resources/views/plugins/user/faqs/default/faqs_show.blade.php
FAQに投稿者名を表示する機能を追加しました。
6/30（木）
無し
=> Add: FAQの投稿者名表示

app/Http/Controllers/Auth/RegisterController.php, resources/views/auth/registe_form.blade.php
=> OW-986 Fix

app/Enums/MembershipFlag.php, app/Http/Middleware/ConnectPage.php, app/Models/Common/Page.php, app/Plugins/Manage/PageManage/PageManage.php, app/Traits/ConnectRoleTrait.php, config/app.php, resources/views/plugins/manage/page/page.blade.php, resources/views/plugins/manage/page/page_form.blade.php, resources/views/plugins/manage/page/role.blade.php
* https://github.com/opensource-workshop/connect-cms/issues/1328
* [change: core, ページのIP制限・公開設定はトップページを継承するよう修正](https://github.com/opensource-workshop/connect-cms/pull/1329/commits/0a462ba1af255bb163cc1705e3642e05d7d93c81)
社内確認してから
なし
なし
無し
=> add: ページ管理, 継承している設定を画面表示

app/Traits/Migration/MigrationTrait.php
=> bugfix: 移行, 掲示板の一時保存の記事を一時保存のまま移行する

app/Plugins/Manage/PageManage/PageManage.php
* https://github.com/opensource-workshop/connect-cms/issues/1341
なし
なし
なし
なし
=> bugfix: 【ページ管理】ページ権限設定でグループの並び順を、グループの並び順でソートするよう対応

app/Plugins/Api/Opac/OpacApi.php
=> OW-998 Fix

resources/views/plugins/user/contents/default/template.ini, resources/views/plugins/user/contents/frame_title_only/contents.blade.php, resources/views/plugins/user/contents/frame_title_only/template.ini
* https://github.com/opensource-workshop/connect-cms/issues/1350
なし
なし
なし
なし
=> add: 固定記事, フレームタイトルのみテンプレート追加

app/Traits/Migration/MigrationTrait.php
=> bugfix: NC2移行, 事務局・管理者の権限移行に対応

app/Traits/Migration/MigrationTrait.php
=> bugfix: NC2移行, 汎用DBの一時保存・未承認の移行修正

app/Plugins/Manage/UserManage/UserManage.php, resources/views/plugins/manage/user/import.blade.php, tests/Browser/Manage/UserManageTest.php
https://github.com/opensource-workshop/connect-cms/issues/1353
- 注釈イメージ
- PC
- モバイル
7月25日（月）
https://github.com/opensource-workshop/connect-cms/issues/1353
なし
なし
=> OW-1111 ユーザインポートでログインユーザは更新できないようにする

public/css/connect.css, resources/views/layouts/app.blade.php
ブランド名の幅固定をやめて100％の表示幅としました。
有り / 無し
=> Update: ブランド名折り替えし不可

app/Traits/Migration/MigrationTrait.php
件名通り
* https://github.com/opensource-workshop/connect-cms/issues/1338
なし
なし
なし
なし
=> change: NC2移行, ルーム移行を権限ごとにグループ分割

public/css/connect.css, resources/views/layouts/app.blade.php
Reverts opensource-workshop/connect-cms#1370
=> Revert "Update: ブランド名折り替えし不可"

app/User.php, resources/views/plugins/manage/user/list.blade.php
=> add: ユーザ管理, ユーザ一覧で権限列にゲストを表示する

app/Plugins/User/Cabinets/CabinetsPlugin.php
* https://github.com/opensource-workshop/connect-cms/issues/1374
7/25～の週位
なし
なし
なし
=> change: キャビネット, 複数ファイルダウンロードでAllowed memory sizeエラー時のtmpファイル削除対応

app/Http/Controllers/Auth/RegistersUsers.php
仮削除状態のユーザーは仮登録メールに記載あるURLからの本登録はできないようにしました。
8/2くらい
有り / 無し
=> OW-991 Modify: 仮削除で本登録は不可

app/Http/Controllers/Auth/RegisterController.php, app/Http/Controllers/Auth/RegistersUsers.php, app/Plugins/Manage/UserManage/UserManage.php, resources/views/plugins/manage/user/groups.blade.php, resources/views/plugins/manage/user/regist.blade.php
* https://github.com/opensource-workshop/connect-cms/issues/1240
ユーザ登録
ユーザ登録＞グループ参加
ユーザ登録＞グループ参加＞メール送信 （※メールアドレス入力ありで表示）
なし
なし
なし
なし
=> change: ユーザ管理, ユーザ登録登録時、ユーザ登録＞グループ参加＞メール送信 と画面遷移するよう見直し

app/Traits/Migration/MigrationTrait.php
* https://github.com/opensource-workshop/connect-cms/issues/1390
なし
なし
なし
なし
=> bugfix: NC2移行, 汎用DBのタイトル指定が移行されなかった不具合対応

app/Plugins/Manage/PageManage/PageManage.php, resources/views/plugins/manage/page/page_manage_tab.blade.php, resources/views/plugins/manage/page/role_list.blade.php
* https://github.com/opensource-workshop/connect-cms/issues/1399
なし
なし
なし
なし
=> ページ管理, ページ権限一覧追加

app/Plugins/User/Calendars/CalendarsPlugin.php
=> カレンダー, 登録時は終了日に今日日付もセットする

app/Traits/ConnectCommonTrait.php
NC2ログイン時に設定した画面遷移が行われない不具合修正
無し
=> add: NC2ログイン時のリダイレクト対応

app/Http/Controllers/Core/UploadController.php
アップロードファイル機能：ユーザーディレクトリ機能で、独自JSファイルを表示・読み込みができなかった為
急ぎぎみでレビューをお願いします。
#1405
無し
=> [アップロードファイル]ユーザーディレクトリ機能、JSファイルの読み込みもできるように追加しました

app/Http/Controllers/Core/UploadController.php
Connect-CMSでZoomify（画像を拡大・縮小できるJavascript製のビューワー）を使いたいです。
そこで、ユーザーディレクトリにZoomifyを配置して、クライアントでZoomifyを利用できるようにするつもりです。
ZoomifyではパラメータをXMLファイルで管理しています。
今のユーザーディレクトリ機能だとXMLファイルのレスポンスが許可されていないので、XMLファイルを許可する変更を行いました。
早めにレビューしていただきたいです
#1407
#1406 
http://www.zoomify.com/index.html
無し
=> [アップロードファイル]ユーザーディレクトリ機能、xmlファイルの読み込みもできるように追加しました

.github/workflows/laravel_dusk.yml, .github/workflows/laravel_dusk_daily.yml
github actionのduskテストが動かなくなっていたため修正。
なし
なし
なし
無し
=> Bugfix GitHub action dusk

tests/Browser/Test/CapturepageTest.php
ページのキャプチャで移行後の結果などを確認したいと思い、作りました。
無し
=> 全ページキャプチャのテスト実装

app/Plugins/User/Opacs/OpacsPlugin.php
=> OW-1326 OPAC, 貸出リクエストのユーザIDが存在しないと貸出処理でシステムエラーになる不具合対応

app/Plugins/Manage/ThemeManage/ThemeManage.php, resources/views/plugins/manage/theme/theme_generate.blade.php
=> [テーマ管理] テーマディレクトリに書込権限ない場合は、注意メッセージを表示

.github/PULL_REQUEST_TEMPLATE.md
件名通り
なし
なし
https://github.com/opensource-workshop/connect-cms/wiki/Pull-requests-Rule
なし
=> PULL_REQUEST_TEMPLATE.md のチェックリストにプルリクエストのルールのリンクを追加

resources/views/plugins/user/photoalbums/card/index.blade.php, resources/views/plugins/user/photoalbums/card/index_folder.blade.php, resources/views/plugins/user/photoalbums/default/index_folder.blade.php, resources/views/plugins/user/photoalbums/default/index_foot.blade.php, resources/views/plugins/user/photoalbums/default/index_head.blade.php, resources/views/plugins/user/photoalbums/default/index_image.blade.php, tests/Browser/User/PhotoalbumsPluginTest.php
詳細は以下のIssueに書きました。
https://github.com/opensource-workshop/connect-cms/issues/1430
無し
=> [フォトアルバム]アルバム（フォルダ）もカード形式で表示されるテンプレートを追加します。

app/Plugins/User/Faqs/FaqsPlugin.php, resources/views/plugins/user/faqs/default/faqs_edit_faq.blade.php
利用方法によってはカテゴリが重要な情報であり、整理して表示できるようにしました。
defaultテンプレートでカテゴリ順に表示することができます。
できれば早く
#1433 
無し
=> [FAQ]表示の順序条件にカテゴリ順を追加しました

app/Enums/SearchsTargetPlugin.php, app/Plugins/User/Faqs/FaqsPlugin.php
サイト内検索でFAQプラグインの検索に対応しました。
来週中くらい
無し
=> [サイト内検索]FAQプラグインの検索に対応しました

app/Http/Controllers/Core/ApiController.php
API処理でオプションプラグインは使えないようになっていましたが、扱えるようにしました。
無し
=> [コア]API処理でオプションプラグインも扱えるようにしました。

tests/Manual/insertion/user/forms/editColumnDetail/foot.txt
table の幅の間違いの修正
tr タグの漏れの修正
tr タグの漏れに関しては、PDF生成時にTCPDFがエラーになったので要注意
無し
=> [マニュアル]マニュアル用HTMLデータを修正しました。

resources/lang/ja/validation.php
* https://github.com/opensource-workshop/connect-cms/issues/983
軽微な改修なので急ぎません
なし
なし
無し
=> [コア] ファイル形式チェックのエラーメッセージをわかりやすくしました

app/Plugins/Mypage/ProfileMypage/ProfileMypage.php, app/Traits/ConnectCommonTrait.php, app/Traits/Migration/MigrationTrait.php
NC2移行ユーザーのパスワード認証を強化しました。
10/17までにお願いします。
OW-969
無し
=> OW-969 [コア]NC2移行ユーザーのパスワード認証を強化しました

config/version.php
1.1.0リリースの準備となります。
このバージョンから画面とコマンドでバージョンを出力できます。
#1375 
無し
=> [コア] Connect-CMSのバージョンを出力するようにしました

app/Models/User/Bbses/BbsPost.php, app/Plugins/User/Bbses/BbsesPlugin.php
返信あり状態での保存判定の修正をしました
2022/10/4 希望 不具合対応なので急ぎたいです
無し
* https://github.com/opensource-workshop/connect-cms/issues/1448
=> [掲示板投稿]返信あり状態での保存判定の修正をしました

config/version.php, resources/views/plugins/user/opacs/default/opacs_lent.blade.php
Opac #1455
郵送リクエスト画面の配送希望メッセージ修正
郵送リクエスト画面の配送希望メッセージ修正
10/14まで
#1455 
無し
=> [Opac]郵送貸し出しリクエスト画面の配送希望の文言修正

resources/views/plugins/user/slideshows/default/slideshows.blade.php
機能追加 #1443 で、多くの画像がスライドショーに登録されることが想定されます。
画像読み込みによる、サーバー負荷の増加、表示速度の低下を防ぐため、画像を遅延読み込みするようにしました。
10/31
#1457 
無し
=> [スライドショー]画像の遅延読み込みに対応しました

app/Plugins/User/Bbses/BbsesPlugin.php
掲示板の投稿エラー不具合に対応しました
不具合対応なので急ぎたいです
https://github.com/opensource-workshop/connect-cms/issues/1461
無し
=> [掲示板]投稿エラー不具合に対応しました

app/Http/Controllers/Core/UploadController.php
#1459
ユーザディレクトリ機能にて、txtファイルを展開表示させる
ユーザディレクトリ機能にて、インライン表示させるファイル種類に、テキストファイルを追加
早め
#1459 
無し
=> [ユーザディレクトリ]テキストファイルを展開表示させる

resources/lang/en/messages.php, resources/lang/ja/messages.php
掲題の通り。
11/4（金）
https://opensource-workshop.atlassian.net/browse/OW-1468
なし
なし
=> [共通]多言語の辞書ファイルを修正しました。

app/Models/Migration/Nc3/Nc3BlockRolePermission.php, app/Models/Migration/Nc3/Nc3BlockSetting.php, app/Models/Migration/Nc3/Nc3BlogEntry.php, app/Models/Migration/Nc3/Nc3Category.php, app/Models/Migration/Nc3/Nc3Language.php, app/Models/Migration/Nc3/Nc3Like.php, app/Models/Migration/Nc3/Nc3MailSetting.php, app/Traits/Migration/MigrationNc3ExportTrait.php, app/Traits/Migration/sample/migration_config/migration_config_nc3.sample.ini
件名通り
なし
* https://github.com/opensource-workshop/connect-cms/pull/1480
なし
無し
=> [nc3移行] ブログ移行対応

app/Models/Migration/Nc2/Nc2User.php, app/Models/Migration/Nc3/Nc3MailSetting.php, app/Models/Migration/Nc3/Nc3MultidatabaseContent.php, app/Models/Migration/Nc3/Nc3MultidatabaseFrameSetting.php, app/Models/Migration/Nc3/Nc3MultidatabaseMetadata.php, app/Models/Migration/Nc3/Nc3User.php, app/Traits/Migration/MigrationNc3ExportTrait.php, app/Traits/Migration/MigrationTrait.php, app/Traits/Migration/sample/migration_config/migration_config_nc3.sample.ini
件名通り。
詳細は下記参照。
* https://github.com/opensource-workshop/connect-cms/pull/1488
なし
なし
なし
なし
=> [nc3移行] 汎用DB移行に対応

app/Models/Migration/Nc3/Nc3BlockRolePermission.php, app/Models/Migration/Nc3/Nc3CabinetFile.php, app/Models/Migration/Nc3/Nc3RolesRoom.php, app/Models/Migration/Nc3/Nc3RoomRolePermission.php, app/Traits/Migration/MigrationNc3ExportTrait.php, app/Traits/Migration/MigrationTrait.php, app/Traits/Migration/sample/migration_config/migration_config_nc3.sample.ini
* [add: [nc3移行] キャビネットの移行対応](https://github.com/opensource-workshop/connect-cms/pull/1491/commits/07469f40a712dcceee09d907d846c71504b8af47)
* 関連修正
* [add: [nc3移行] block_role_permissionに値なかった場合のroom_role_permissionsから取得する対応追加](https://github.com/opensource-workshop/connect-cms/pull/1491/commits/6f5c9796ce36ecaa4bf53d87b1580a09e78fc7d2) 
* [bugfix: [nc3移行] ブログの記事のハンドルが正しくエクスポートされない不具合の修正](https://github.com/opensource-workshop/connect-cms/pull/1491/commits/652ff426151d3a9acb65d22ccdd21a3e8afc5fd9)
* [add: [移行インポート] キャビネットの権限設定の移行に対応](https://github.com/opensource-workshop/connect-cms/pull/1491/commits/5ddd73fbf9b14020a8602cb5905a124928db238b)
なし
なし
なし
なし
=> [nc3移行] キャビネットの移行対応（nc3-migrateにマージ）

resources/views/plugins/manage/page/page.blade.php
ページ数が多いサイトでの表示遅延改善のため
次回リリース時には含めたいです
https://github.com/opensource-workshop/connect-cms/issues/1476
無し
=> [管理画面]ページ管理のページ移動を改善しました（セレクトボックス選択→モーダル表示ラジオボタン選択へ）

public/robots.txt
サイトの負荷軽減対策です。
下記処理がGoogleBotからアクセスがあり、インデックス不要だったため、robots.txtに追記しました。
* pluginの詳細表示＋他フレームのページ移動
* (例) 1ページ2ブログとかで「aブログ詳細表示でbブログページ移動」で例えば (a:記事数(90記事) × b:ページ数(150ページ(1ページ1記事)) + (b:記事数(150記事) × a:ページ数(30ページ(1ページ3記事)) 分クロールしてたため除外
* /plugin/blogs/show/1/2/3?frame_2_page=1
* /plugin/bbses/reply/4/5/6?frame_2_page=2
* /plugin/calendars/show/7/8/9?frame_2_page=3
* json処理
* /json/blogs/saveLikeJson/10/1/2
* 再表示処理
* /redirect/plugin/bbses/approval/1/11/4
軽微な改修なので急ぎません。
* https://github.com/opensource-workshop/connect-cms/pull/1482
* robots.txt ファイルを作成して送信する | Google 検索セントラル  |  ドキュメント  |  Google Developers
https://developers.google.com/search/docs/crawling-indexing/robots/create-robots-txt?hl=ja&bookmark=true
* robots.txtの書き方 | URLやサイトマップ、リダイレクト | テクニカルSEO BLOG …
=> [コア] (サイトの負荷軽減対策) robots.txtでインデックス不要な処理を拒否

tests/Browser/User/SlideshowsPluginTest.php
外部サービスの実行待ち時間は5秒では足りなかったので10秒に変更しました。
無し
=> 外部サービスの実行待ち時間は5秒では足りなかったので10秒に変更しました。

app/Plugins/User/Databases/DatabasesPlugin.php, resources/views/plugins/common/frame_edit_mails.blade.php, resources/views/plugins/user/databases/description_frame_mails.blade.php, tests/Browser/User/BbsesPluginTest.php, tests/Browser/User/BlogsPluginTest.php, tests/Browser/User/DatabasesPluginTest.php
=> メール送信設定をマニュアルへ追記しました。

app/Models/Migration/Nc3/Nc3RegistrationAnswerSummary.php, app/Models/Migration/Nc3/Nc3RegistrationChoice.php, app/Models/Migration/Nc3/Nc3RegistrationPage.php, app/Models/Migration/Nc3/Nc3RegistrationQuestion.php, app/Traits/Migration/MigrationNc3ExportTrait.php, app/Traits/Migration/MigrationTrait.php, app/Traits/Migration/sample/migration_config/migration_config_nc3.sample.ini
* [add: [nc3移行] 登録フォームの移行対応](https://github.com/opensource-workshop/connect-cms/pull/1497/commits/26e8e68206d5eaa98199230b731f2027f7ada33d)
* [add: [移行インポート] フォームのファイル添付移行に対応](https://github.com/opensource-workshop/connect-cms/pull/1497/commits/2622001ea232293778496ff56be63494e51c9b5f)
* 関連修正
* [add: [nc2移行エクスポート] 登録フォームの添付ファイル移行対応](https://github.com/opensource-workshop/connect-cms/pull/1497/commits/aa938a979b211c88942fdbe130b295e487e037ba)
なし
なし
なし
なし
=> [nc3移行] 登録フォームの移行対応（nc3-migrateブランチにマージ）

resources/views/layouts/app.blade.php
件名通り
```
[2022-11-22 12:54:20] production.ERROR: md5_file(): https:// wrapper is disabled in the server configuration by allow_url_fopen=0 (View: /var/www/html/resources/views/layouts/app.blade.php) (View: /var/www/html/resources/views/layouts/app.blade.php) {"exception":"[object] (Illuminate\\View\\ViewException(code: 0): md5_file(): https:// wrapper is disabled in the server configuration by allow_url_fopen=0 (View: /var/www/html/resources/views/layouts/app.blade.php) (View: /var/www/html/resources/views/layouts/app.blade.php) at /var/www/html/storage/framework/views/7246959fc25bfec98506e8a518d580d7cd418b49.php:109)
```
```html
<link href="{{url('/')}}/file/css/{{$page->id}}.css?version={{ md5_file(url('/') . '/file/css/' . $page->id . '.css') }}" rel="stylesheet">
```
上記だと、md5_file() …
=> [コア] トップページ500エラー対応

app/Enums/FaqSequenceConditionType.php, app/Models/Migration/Nc3/Nc3FaqQuestion.php, app/Models/User/Faqs/Faqs.php, app/Models/User/Faqs/FaqsPosts.php, app/Traits/Migration/MigrationNc3ExportTrait.php, app/Traits/Migration/MigrationTrait.php, app/Traits/Migration/sample/migration_config/migration_config_nc3.sample.ini, config/app.php
* [add: [nc3移行] FAQ移行対応](https://github.com/opensource-workshop/connect-cms/commit/f764033e990849059900b67de8d98065c1e6dce3)
* 関連修正
* [change: [移行インポート] FAQの投稿日時の時刻変換をエクスポート側に移動](https://github.com/opensource-workshop/connect-cms/commit/6b0f797426c4ad06eeff1d99a09c42af575e3f84)
* [delete: [移行インポート] importBlogsで使ってない変数$room_idをコメントアウト](https://github.com/opensource-workshop/connect-cms/commit/266dc5170718aced4b43bfb96d2826046138f8cf)
* [delete: [移行インポート] importFaqsで使ってない変数$room_idをコメントアウト](https://github.com/opensource-workshop/connect-cms/commit/75105f34d4dfd4c9cd1e0d4507d7d4a284fb4c7b)
* [change: [nc2移行エクスポート] FAQの権限設定移行・FAQを指定順で移行・FAQバケツの登録・更新日等を移行](https://github.com/opensource-workshop/connect-cms/commit/a001fbb806a1e3bd3268c921ffc7bdd5bc2e40cc)
なし
なし
なし
なし
=> [nc3移行] FAQ移行対応（nc3-migrateブランチにマージ）

app/Models/Migration/Nc3/Nc3AccessCounterFrameSetting.php, app/Traits/Migration/MigrationNc3ExportTrait.php, app/Traits/Migration/MigrationTrait.php, app/Traits/Migration/sample/migration_config/migration_config_nc3.sample.ini
=> [nc3移行] カウンターの移行対応（nc3-migrateブランチにマージ）

.github/workflows/laravel_dusk_connect-cms-test.yml
=> [開発] github action に Laravel Dusk connect-cms-test 追加

.github/workflows/laravel_dusk.yml, .github/workflows/laravel_dusk_connect-cms-test.yml, .github/workflows/laravel_dusk_daily.yml, .github/workflows/phpcs.yml, .github/workflows/stale.yml
github actionのwarning修正
例）
詳細 [github action] phpcs warning https://github.com/opensource-workshop/connect-cms/actions/runs/3557878931
なし
なし
* warning修正例 https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#environment-files
* https://zenn.dev/hankei6km/articles/use-github-acions-workflow-dispatch-inputs-safely#fn-d988-3
なし
=> [github action] warning fix

.github/workflows/laravel_dusk.yml, .github/workflows/laravel_dusk_connect-cms-test.yml, .github/workflows/laravel_dusk_daily.yml
=> [GitHub action] dusk test bugfix

.github/workflows/laravel_dusk_connect-cms-test.yml, tests/Browser/User/SlideshowsPluginTest.php, tests/DuskTestCase.php
=> [github action] duskでapiテストをしないパラメータ追加

.github/workflows/laravel_dusk.yml, .github/workflows/laravel_dusk_connect-cms-test.yml
=> [github action] php8.1のcomposer updateは不要になったためコメントアウト

app/Http/Controllers/Core/UploadController.php
=> [コア] アップロードしたページがない場合、今まで500エラーで見えなかった。そのためページがない場合、ファイルは非表示とする

resources/views/plugins/user/calendars/default/edit.blade.php
* https://github.com/opensource-workshop/connect-cms/issues/1368
なし
なし
なし
なし
=> [カレンダー] 予定登録時にキャンセルボタンがきかないバグ修正

app/Plugins/User/Calendars/CalendarsPlugin.php
=> [カレンダー] 登録後は初期画面へ画面遷移を見直し OW-1577

resources/views/plugins/user/contents/default/contents_list_buckets.blade.php
=> [固定記事] 表示コンテンツ選択のソートにアンカーを設定

app/Models/Common/YasumiHoliday.php, app/Plugins/Manage/HolidayManage/HolidayManage.php, app/Traits/ConnectCommonTrait.php
* [bugfix: [祝日管理] 独自設定の祝日と同じ日が計算の祝日にあれば、計算の祝日を消して、独自設定を有効にする。が実現できてなかったため修正](https://github.com/opensource-workshop/connect-cms/pull/1520/commits/82a84553384fd4d9eed813d20b5109d2c6d05fc9)
* 関連修正
* [refactor: [祝日管理] 複数ある同一処理 getYasumis()メソッドをYasumiHolidayクラスに移動](https://github.com/opensource-workshop/connect-cms/pull/1520/commits/d12d4f4c46032915913cdf2a06a29bebdc3ef1d6)
* [refactor: [祝日管理] privateからしかアクセスしてないメソッドをprivateに変更](https://github.com/opensource-workshop/connect-cms/pull/1520/commits/ed9418ee4919f3f7e818105548079dd4cf5bd69d)
* [delete: [祝日管理] 参照されてないprivateメソッド getData()削除](https://github.com/opensource-workshop/connect-cms/pull/1520/commits/b6471b24e9f2ffefad544001ab3ec3bd1baa24b3)
登録前）
2023年1月2日登録）
登録後）
カレンダー表示例）
施設予約表示例）
なし
* …
=> [祝日管理] 独自設定の祝日と同じ日が計算の祝日にあれば、計算の祝日を消して、独自設定を有効にする。が実現できてなかったため修正

app/Models/Migration/Nc2/Nc2SearchBlock.php, app/Models/Migration/Nc3/Nc3SearchFramePlugin.php, app/Models/Migration/Nc3/Nc3SearchFrameSetting.php, app/Models/User/Searchs/Searchs.php, app/Traits/Migration/MigrationNc3ExportTrait.php, app/Traits/Migration/MigrationTrait.php, app/Traits/Migration/sample/migration_config/migration_config.sample.ini, app/Traits/Migration/sample/migration_config/migration_config_nc3.sample.ini
* [add: [nc3移行エクスポート/移行インポート] 検索の移行対応](https://github.com/opensource-workshop/connect-cms/pull/1522/commits/754857675184b941555b6f0395eeaf6afdb0fbe4)
* 関連修正
*  [add: [nc2移行エクスポート] 検索の移行対応](https://github.com/opensource-workshop/connect-cms/pull/1522/commits/b162b8e3a317c54047404526db2472a2df5338d4)
なし
なし
なし
なし
=> [nc3移行エクスポート/移行インポート] 検索の移行対応（nc3-migrateブランチにマージ）

app/Traits/Migration/MigrationNc3ExportTrait.php, app/Traits/Migration/MigrationTrait.php
* [add: [nc2/nc3移行エクスポート] リンクチェックでmailtoはチェックしない](https://github.com/opensource-workshop/connect-cms/commit/d4e471f42fa3a7351e1417ee07daa6a4839c64bc)
* [bugfix: [nc3移行エクスポート] 内部リンクチェックのダウンロードURLチェックミス修正](https://github.com/opensource-workshop/connect-cms/commit/3c88f4bb4950c4bcd5733617703f4318390794f2)
* [bugfix: [nc3移行エクスポート] メニューの表示しないページ移行ミス修正](https://github.com/opensource-workshop/connect-cms/commit/4a0148f22ff8debaf83edd4b2b03685b2fc1a772)
なし
なし
なし
なし
=> [nc2/nc3移行エクスポート] リンクチェックでmailtoはチェックしない [nc3移行エクスポート] 内部リンクチェックのダウンロードURLチェックミス修正, メニューの表示しないページ移行ミス修正（nc3-migrateブランチにマージ）

app/Traits/Migration/MigrationNc3ExportTrait.php, app/Traits/Migration/MigrationTrait.php
* [add: [移行インポート] nc3プラグイン固有リンク（nc3ブログ・nc3汎用DB）をccプラグインリンクに置換](https://github.com/opensource-workshop/connect-cms/pull/1526/commits/e9133b791cfd942ef6ba2efa3c1f96cb1f66257e)
* 関連修正
* [add: [nc3移行エクスポート] 内部リンクのプラグイン固有リンクチェックに、ブログ/汎用DBのチェック追加](https://github.com/opensource-workshop/connect-cms/pull/1526/commits/85de887052e08a053feb49e9fdeae408862f390b)
* [add: [移行インポート] nc3プラグイン固有リンク（nc3ブログ・nc3汎用DB）をccプラグインリンクに置換2](https://github.com/opensource-workshop/connect-cms/pull/1526/commits/7ca1003cb8a59c8a8e3e476e5d7f21ebd8ac093b)
なし
なし
なし
なし
=> [移行インポート] nc3プラグイン固有リンク（nc3ブログ・nc3汎用DB）をccプラグインリンクに置換（nc3-migrateブランチにマージ）

app/Traits/Migration/MigrationNc3ExportTrait.php
=> [nc3移行エクスポート] createdがnullの場合"0000-00-00 00:00:00"が返ってきていたので対応

app/Models/Migration/Nc3/Nc3Video.php, app/Models/Migration/Nc3/Nc3VideoFrameSetting.php, app/Traits/Migration/MigrationNc3ExportTrait.php, app/Traits/Migration/MigrationTrait.php, app/Traits/Migration/sample/migration_config/migration_config_nc3.sample.ini
* [add: [nc3移行] 動画の移行対応](https://github.com/opensource-workshop/connect-cms/commit/f2e775842efbef00dd866ed199dd42b2931db54c)
* 関連対応
* [change: [nc3移行] [source_info][plugin_key]⇒[source_info][module_name] に統一](https://github.com/opensource-workshop/connect-cms/commit/e6d2bccfa0236fc3b7bb28f609f4b9f2b21eb97a)
* [[移行] nc3プラグイン固有リンク（nc3動画埋込）をccプラグインリンクに置換](https://github.com/opensource-workshop/connect-cms/pull/1529/commits/6d658d2fc60fea3d79735f8c0f1cdeb8f6bab397)
なし
なし
なし
なし
=> [nc3移行] 動画の移行対応（nc3-migrateブランチにマージ）

app/Traits/Migration/MigrationNc3ExportTrait.php
=> [nc3移行エクスポート] 新着のtopic_frame_settingデータなしも移行する対応（nc3-migrateブランチにマージ）

app/Traits/Migration/MigrationNc3ExportTrait.php, app/Traits/Migration/MigrationTrait.php
* [add: [nc3移行] nc3プラグイン固有リンク（nc3掲示板）をccプラグインリンクに置換](https://github.com/opensource-workshop/connect-cms/commit/0b044149947a7aba908e4f8b71a345fee76481db)
* [add: [nc3移行] nc3プラグイン固有リンク（nc3キャビネット-フォルダ）をccプラグインリンクに置換](https://github.com/opensource-workshop/connect-cms/commit/569a5dbd529fa956716a0fe579d7f8724a22c2ed)
* [add: [nc3移行] nc3プラグイン固有リンク（nc3キャビネット-ファイル）をccプラグインリンクに置換](https://github.com/opensource-workshop/connect-cms/commit/96d6a9b9e7cd344137a9c9f7848e8e30b1382f9c)
* [add: [nc3移行] nc3プラグイン固有リンク（nc3FAQ）をccプラグインリンクに置換](https://github.com/opensource-workshop/connect-cms/commit/5590118f2ed39b382b5d0a8147aec745beb96061)
* [add: [nc3移行] nc3プラグイン固有リンク（nc3フォトアルバム-アルバム表示）をccプラグインリンクに置換](https://github.com/opensource-workshop/connect-cms/commit/2746686db157994811cdd2b2a4a4c26a9bb4966f)
* [add: …
=> [nc3移行] nc3プラグイン固有リンク（掲示板/キャビネット/FAQ/フォトアルバム/施設予約/カレンダー）をccプラグインリンクに置換（nc3-migrateブランチにマージ）

config/connect.php
=> [コア] ダウンロード時にカウントする拡張子にmp3追加

app/Plugins/Manage/PageManage/PageManage.php, tests/Browser/Manage/IndexManageTest.php, tests/Browser/Manage/PageManageTest.php, tests/Browser/Manage/ReservationManageTest.php, tests/Browser/Manage/page.csv
=> マニュアルを1.3に対応させました。

tests/Browser/Manage/PageManageTest.php
=> マニュアルにページ管理の説明を追加しました。

tests/Browser/Manage/SiteManageTest.php
=> サイト管理のマニュアル説明内容を追加しました。

tests/Browser/Manage/GroupManageTest.php, tests/Browser/Manage/GroupManageTest2.php, tests/bin/connect-cms-test.bat
=> グループ管理のマニュアルを更新しました。

app/Plugins/User/Databases/DatabasesPlugin.php
=> [データベース] タイトル指定にした項目を空でデータ登録/更新するとエラーになる不具合対応

app/Plugins/User/Databases/DatabasesPlugin.php
ファイル型アップロード時のセッション作成処理を修正
次月リリースまでに
https://github.com/opensource-workshop/connect-cms/issues/1533
なし
有り / 無し
=> Bugfix: ファイル型アップロード時のセッション作成処理を修正

tests/Browser/Manage/UploadfileManageTest.php
=> ファイル削除の説明を追加しました。

app/Plugins/Manage/UploadfileManage/UploadfileManage.php, app/Plugins/User/Themechangers/ThemechangersPlugin.php, resources/views/plugins/user/themechangers/default/themechangers.blade.php, tests/Browser/User/ThemechangersPluginTest.php, tests/bin/connect-cms-test.bat
マニュアルにテーマチェンジャーを追加＆細かい修正をしました。
無し
=> マニュアルにテーマチェンジャーを追加＆細かい修正をしました。

app/Plugins/User/Themechangers/ThemechangersPlugin.php, resources/views/manual/index.blade.php, resources/views/manual/pdf/cover.blade.php, tests/Browser/Common/WysiwygTest.php, tests/DuskTestCase.php, tests/Manual/src/ManualPdf.php, tests/bin/connect-cms-test.bat
=> マニュアルPDFの出力方式を増やしました。

tests/Manual/insertion/manage/function_foot_pdf.txt
=> 機能一覧PDFの追加データの漏れに対応しました。

tests/Manual/insertion/user/function_foot.txt, tests/Manual/insertion/user/function_foot_pdf.txt
=> 開発予定にRSSが抜けていたので追記しました。

tests/Browser/Common/LoginLockTest.php, tests/Browser/Common/LoginLogoutTest.php, tests/bin/connect-cms-test.bat
ログイン失敗時のロック機能についてマニュアルに追記しました。
無し
=> ログイン失敗時のロック機能についてマニュアルに追記しました。

app/Plugins/Manage/UserManage/UserManage.php
件名通り
なし
なし
https://tadtadya.com/php-do-not-use-array_filter-to-delete-empty-elements-of-array/
無し
=> [ユーザ管理] php8.1＋自動ユーザ登録設定の登録時の500エラーに対応

.gitignore
=> [.gitignore] .vscode配下と/resources/views/mail_option/配下をgit管理から除外

.env.example
件名通り
https://github.com/opensource-workshop/connect-cms/blob/master/config/logging.php#L50-L62
なし
* https://github.com/opensource-workshop/connect-cms/pull/1302
なし
無し
=> [.env] LOG_CHANNELをdaily(level=debug) => daily_info(level=info)に修正

.env.example, app/Plugins/User/UserPluginBase.php, config/connect.php
以下の環境でメール送信できない不具合があったため、対応しました。
・非同期でメール送信設定（.envのQUEUE_CONNECTION=database）
・php-cgi
・同期でメール送信設定（.envのQUEUE_CONNECTION=sync）に変更すると、php-cgiでもメール送信できます。
なし
なし
なし
なし
=> [メール送信] .envのQUEUE_CONNECTION=database＋php-cgiで掲示板等のメールが送れなかった不具合に対応 OW-1704

app/Plugins/User/Databases/DatabasesPlugin.php, app/Plugins/User/Databases/DatabasesTool.php
=> [検索] データベースに１つでも絞り込み条件が設定されていると、全データベース絞り込まれて検索結果にでてこない不具合修正

app/Plugins/User/Databases/DatabasesTool.php
件名通り。
リリースに含まないため、そのままマージします。
なし
なし
なし
なし
=> [データベース] phpcs fix.

composer-dev.lock, composer.lock, config/version.php
* 2.xブランチに最新バージョンを適用します。
* composer.lockは1.x系とは異なるため、composer.lockマージせず、再生成します。
* 再生成はphp8.0でします。
* （※ php8.1の場合、composer.lockはphp8.1に依存したライブラリを使うため、php8.1のみ実行できる環境になるためです。）
なし
* https://github.com/opensource-workshop/connect-cms/pull/1569
* https://github.com/advisories/GHSA-h7vf-5wrv-9fhv
* 2.xもアップデート対象バージョンだったため、composer.lockを更新しました。
* https://github.com/opensource-workshop/connect-cms/blob/b89b4b30bb89ead2670b56dde20b8228b7fe84a1/composer.lock#L4235-L4236
なし
なし
=> Merge v1.4.4 into 2.x 

docker/app/Dockerfile
件名通り。
リリースに含めないため、マージします。
なし
なし
なし
なし
=> [docker] dockerイメージ宣言箇所にコメント追記

composer-option.json, composer-option.lock
aws/aws-sdk-php あり。
オプションプラグインで使用するパッケージなどを含めたものです。
無し
=> オプション開発用のcomposerです。

.gitignore
オプション用composer関係ファイルをgitirnoreします。
無し
=> オプション用composer関係ファイルをgitirnoreします。

resources/views/plugins/user/forms/default/forms_edit_row2.blade.php
=> [フォーム] アンケートモードで項目設定で型が変更できない不具合修正

app/Plugins/Manage/SystemManage/SystemManage.php
=> [システム管理] 「メール設定」の入力項目に null という文字列が付く不具合の修正

app/Plugins/Manage/SystemManage/SystemManage.php, composer-dev.json, composer-dev.lock, composer.json, composer.lock, config/version.php, resources/views/plugins/user/forms/default/forms_edit_row2.blade.php
2.xブランチに最新バージョンを適用します。
なし
* https://github.com/laravel/framework/blob/9.x/composer.json#L18
* >  "php": "^8.0.2",
なし
なし
=> Merge v1.5.1 into 2.x（update 2.1.1）

resources/views/plugins/common/frame_edit_mails.blade.php
=> [メール送信] オプションプラグインに対応

app/Plugins/User/Databases/DatabasesPlugin.php
=> [データベース] 数値チェック=ONにした後、選択肢型に切替て、登録時に選択肢未入力で確認画面に行くと500エラーになる不具合対応

resources/views/plugins/common/empty_bucket_setting.blade.php
=> [エラー画面] バケツ未選択ワーニング画面をオプションプラグインにも対応

.gitignore
JobsにOptionsを設置できるよう、gitに除外設定を追加
なし
なし
なし
なし
=> [Git] /app/Jobs/Options/*をgitから除外

app/Jobs/ConnectMailJob.php, app/Plugins/User/UserPluginBase.php
`app\Mail\ConnectMail.php`がありますが、対応するjobがなかったため、追加しました。
また、非同期でキューワーカ実行が、各プラグインコントローラから呼び出せなかったため、呼び出せるよう見直ししました。
なし
なし
なし
なし
=> [メール送信] 非同期でConnectMailを送れるよう対応

app/Enums/ManualCategory.php, app/Models/Core/Dusks.php, composer-dev.json, composer-dev.lock, config/connect.php, resources/views/core/cms_frame_header.blade.php, resources/views/manual/category.blade.php, resources/views/manual/index.blade.php, resources/views/plugins/user/forms/default/forms_edit.blade.php, resources/views/plugins/user/forms/default/forms_edit_form.blade.php, resources/views/plugins/user/forms/default/forms_edit_row_detail.blade.php, tests/Browser/ConnectStudy/SpeechStudyTest.php, tests/Browser/Manage/PageManageTest.php, tests/Browser/Manage/page.csv, tests/Browser/Top/IndexTopTest.php, tests/Browser/User/QuestionnairesPluginTest.php, tests/Browser/User/ThemechangersPluginTest.php, tests/DuskTestCase.php, tests/Manual/insertion/user/function_foot.txt, tests/Manual/insertion/user/function_foot_pdf.txt, tests/Manual/src/ManualVideo.php, tests/bin/connect-cms-test.bat
・v1.6.0 への対応
・アンケートの説明追加
・音声を指定できるようにする。（デフォルトはTomoko）
・aws/sdkをcomposer経由にしました。
・トップページの動画に説明を追加しました。
無し
=> v1.6.0 への対応、アンケートの説明追加、音声を指定できるようにするなどの対応をしました。

.env.example, app/Plugins/User/Databases/DatabasesPlugin.php, config/connect.php, resources/views/plugins/user/databases/default/databases_edit_row_detail.blade.php
betaのうちは独自にテンプレートを作成して利用する想定です。
詳細画面で表示しない設定になっている項目について、ユーザーが検索画面で表示したい項目を選択することで、詳細画面で閲覧できるようにする機能です。
.env.sampleを参考に以下の項目を.envに追加してください。
`DATABASES_FORCE_SHOW_COLUMN_ON_DETAIL=true`
default から databases.blade.php と databases_include_ctrl_head.blade.php をコピーして独自テンプレートを作成します。
databases_include_ctrl_headをincludeする部分をテンプレート名に修正します。
```
{{-- ヘッダー部分 --}}
@include('plugins.user.databases.{template-name}.databases_include_ctrl_head')
```
\<form>内に、 `value = databases_columns.id name="force_show_columns[]"` の パラメータを追加してください。
検索ボタンを押下するとサーバーサイドでsessionに登録され、詳細画面で選択した項目が表示されるようになります。
参考コード
```
{{-- $column -> DatabasesColumn --}}
@php
$checked_values = (array)Session::get("force_show_columns." . $frame->id);
@endphp
<div class="custom-control custom-checkbox">
<input type="checkbox" …
```
=> [データベース]詳細画面で非表示項目をパラメータのID指定で強制的に表示する機能を追加しました(beta)

app/Traits/Migration/MigrationNc3ExportTrait.php
=> [NC3移行] 汎用DBのファイル型のファイルが全て同じファイルで移行される不具合の修正

composer-dev.json, composer-dev.lock
=> [コア]Install AWS SDK for PHP

app/Http/Controllers/Auth/LoginController.php
=> [NC3移行] 移行元ユーザで一部のユーザーがログインできない不具合修正

app/Plugins/User/Databases/DatabasesTool.php
* https://github.com/opensource-workshop/connect-cms/pull/1646 の修正がうまくいってなかったため、再修正しました。
なし
なし
なし
なし
=> [データベース] 複数単語で検索した場合の結果表示が遅い問題の再対応 OW-1838

app/Plugins/User/Blogs/BlogsPlugin.php, app/Plugins/User/Databases/DatabasesPlugin.php, app/Plugins/User/Databases/DatabasesTool.php, app/Plugins/User/Faqs/FaqsPlugin.php, resources/views/plugins/user/databases/default/databases_input.blade.php
カテゴリとタグをサイト内検索の検索対象にしました。
- カテゴリを設定できるプラグイン
- ブログ
- FAQ
- データベース
- タグを設定できるプラグイン 
- ブログ
- FAQ
無し
=> [サイト内検索]カテゴリとタグを検索対象に追加しました 

database/migrations/2023_04_20_195212_add_narrow_down_label_to_searchs_table.php
=> [サイト内検索]対象を絞って検索するかユーザが選択できるようにしました（追加ファイル）

app/Plugins/User/Searchs/SearchsPlugin.php, database/migrations/2023_04_25_234933_drop_narrow_down_label_to_searchs_table.php, resources/views/plugins/user/searchs/default/searchs_edit_search.blade.php, resources/views/plugins/user/searchs/default/searchs_form.blade.php, resources/views/plugins/user/searchs/default/searchs_result.blade.php
固定記事でサイト内検索をするformを設定する際、以下のパラメータを設定してください。
`<input type="hidden" name="narrow_down_page_id" value="{page_id}"/>`
※ #1644 から機能を修正したPRです。
有り
=> [サイト内検索]指定ページ配下を検索対象にする機能を追加しました

app/Plugins/User/Searchs/SearchsPlugin.php
=> [サイト内検索]設定変更でシステムエラーの問題を修正しました

resources/views/plugins/common/user_list_category.blade.php
=> [カテゴリの設定画面] キャンセルボタンで画面遷移のみのボタンはaタグで対応

app/Traits/Migration/MigrationTrait.php
Issueに記載の通り
なし
https://github.com/opensource-workshop/connect-cms/issues/1663
なし
なし
=> bugfix: [ページ管理-インポート] 参照PATHの補填処理でディレクトリインストールも考慮するよう修正

resources/views/plugins/user/blogs/default/blogs.blade.php, resources/views/plugins/user/blogs/default/blogs_show.blade.php, resources/views/plugins/user/blogs/designbase/blogs.blade.php, resources/views/plugins/user/blogs/designbase/blogs_show.blade.php
https://github.com/opensource-workshop/connect-cms/issues/1669
なし
https://github.com/opensource-workshop/connect-cms/issues/1669
なし
なし
=> fix: [ブログ] 編集権限が許可されたユーザであっても重要記事マークが見えないのを修正しました

resources/views/plugins/user/blogs/default/blogs.blade.php, resources/views/plugins/user/blogs/default/blogs_show.blade.php, resources/views/plugins/user/blogs/designbase/blogs.blade.php, resources/views/plugins/user/blogs/designbase/blogs_show.blade.php
https://github.com/opensource-workshop/connect-cms/issues/1677
なし
https://github.com/opensource-workshop/connect-cms/issues/1677
なし
なし
=> [ブログ] 未ログイン状態で一覧／参照画面を照会するとエラーになる事象を修正しました。

app/Plugins/Manage/SiteManage/SiteManage.php
=> [サイト管理] NC3移行後にサイト設計書出力すると500エラーになるバグ修正

app/Plugins/Manage/UserManage/UserManage.php
* https://github.com/opensource-workshop/connect-cms/pull/1680
上記の追加チェックです。
なし
なし
なし
なし
=> [ユーザ管理] 最後のシステム管理者保持者から編集で利用不可・仮削除にしたときの入力チェック追加

app/Traits/Migration/MigrationNc3ExportTrait.php, app/Traits/Migration/MigrationTrait.php, app/Traits/Migration/sample/migration_config/migration_config.sample.ini, app/Traits/Migration/sample/migration_config/migration_config_nc3.sample.ini
=> [移行ツール] NC2・3移行エクスポート, 固定記事の置換オプションに対応

resources/views/layouts/app.blade.php
ディレクトリインストールの場合に、アプリのルートが"/"ではないためファイルが読み込まれなくなっていました。
絶対パスでURLを指定するように修正しました。
#1696
#1672
無し
=> [コア]ディレクトリインストールの場合にapp.cssとapp.jsが読み込まれない問題を修正しました

app/Traits/Migration/MigrationNc3ExportTrait.php
件名通りです。
なし
* https://github.com/opensource-workshop/connect-cms/issues/1699
なし
なし
=> [移行ツール] nc3移行エクスポート, NC3お知らせの限定公開From-Toのいずれかが空の場合、インポート時にエラーで落ちるバグ対応

app/Http/Controllers/Core/FrameCore.php
以下のバグ修正です。
* https://github.com/opensource-workshop/connect-cms/issues/1699
なし
なし
* https://readouble.com/laravel/8.x/ja/validation.html#rule-after-or-equal
なし
=> [フレーム] 公開日時From, Toにtimestamp型の範囲内の入力チェックを追加

app/Traits/Migration/MigrationNc3ExportTrait.php, app/Traits/Migration/MigrationTrait.php
件名通りです。
なし
* https://github.com/opensource-workshop/connect-cms/pull/1702
なし
なし
=> [移行ツール] NC2・3から移行する時は、常に表示件数リストを表示ONで移行

app/Traits/Migration/MigrationNc3ExportTrait.php
=> [移行ツール] NC3移行エクスポートでNC3.2.0より古いバージョンで移行するONの時、ページ階層が移行後に再現するよう対応

app/Enums/BlogNarrowingDownType.php, app/Models/User/Blogs/Blogs.php, app/Plugins/User/Blogs/BlogsPlugin.php, config/app.php, database/migrations/2023_06_14_005653_add_narrowing_down_type_from_blogs.php, resources/views/plugins/user/blogs/default/blogs.blade.php, resources/views/plugins/user/blogs/default/blogs_edit_blog.blade.php, resources/views/plugins/user/blogs/default/include_narrowing_down.blade.php, resources/views/plugins/user/blogs/default/include_view_count_spectator.blade.php, resources/views/plugins/user/blogs/designbase/blogs.blade.php
=> [ブログ] カテゴリの絞り込み機能追加

app/Traits/Migration/MigrationNc3ExportTrait.php, app/Traits/Migration/MigrationTrait.php
件名通りです。
* https://github.com/opensource-workshop/connect-cms/pull/1712
なし
なし
=> [移行ツール] NC2・3からブログを移行する時は、常にカテゴリの絞り込み機能ONで移行

app/Traits/Migration/MigrationNc3ExportTrait.php
=> [移行ツール] NC3移行エクスポートでNC3.2.0より古いバージョンで移行するONの時、汎用DBの記事が移行されない不具合の対応

resources/views/layouts/app.blade.php
https://github.com/opensource-workshop/connect-cms-ideas/issues/151
なし
https://github.com/opensource-workshop/connect-cms-ideas/issues/151
なし
なし
=> [コア－共通] 新着情報プラグイン用のポリフィル対応を除去

app/Models/Common/Frame.php
=> Merge v1.8.4 into 2.x (fix: phpcs対応)

tests/Browser/Manage/ApiManageTest.php, tests/Browser/Manage/SiteManageTest.php, tests/Browser/Manage/ThemeManageTest.php
=> [自動テスト] API管理,テーマ管理,サイト管理のgithub action testで表示が遅いのか、セレクターが見つからなくてエラーになるため、ちょっと待つ処理を追加

app/Plugins/Manage/UploadfileManage/UploadfileManage.php, resources/views/plugins/manage/uploadfile/edit.blade.php
=> [アップロードファイル管理] 一時保存を更新してファイルを削除せず非公開にできるように対応2 OWSP-806

sync_dev_2_option_private.sh.example, sync_option_private_2_dev.sh.example
=> サンプルシェルの不要な記号を削除, 既に削除済みのマイグレーションファイルの除外指定を削除

resources/views/plugins/manage/api/api.blade.php
件名通りです。
なし
* https://github.com/opensource-workshop/connect-cms/issues/1200
なし
なし
=> [API管理] php8.0で管理画面が開けないバグ修正

app/Plugins/Manage/UploadfileManage/UploadfileManage.php
=> [アップロードファイル] ユーザパブリックファイルの一覧画面パス修正

app/Models/Core/Plugins.php, app/Plugins/User/Whatsnews/WhatsnewTargetPluginTool.php, app/Plugins/User/Whatsnews/WhatsnewsPlugin.php
=> [新着情報] オプションプラグインのもっと見るが機能しないバグ修正

app/Plugins/User/Whatsnews/WhatsnewsPlugin.php
=> [新着情報] もっと見る時のclassnameを初期表示と同じになるよう対応

app/Plugins/Manage/SiteManage/SiteManage.php, resources/views/plugins/manage/site/pdf/migrate_main.blade.php
=> [サイト管理]設計書出力にNC3移行データの出力を追加しました

app/Traits/Migration/MigrationNc3ExportTrait.php
redo時に@insertディレクトリを削除する
７月２１日
無し
=> [NC3移行]データエクスポート時（redo時）に@insertディレクトリを削除する修正を入れました

app/Plugins/User/Reservations/ReservationsPlugin.php, app/Traits/ConnectCommonTrait.php
=> [施設予約] カレンダー月表示データの生成を汎用化

resources/views/plugins/user/reservations/default/edit_booking.blade.php
=> [施設予約] 予約終了時間の 00:00 を 24:00 に自動変換がされないパターンに対応

resources/views/plugins/manage/reservation/edit.blade.php
* https://github.com/opensource-workshop/connect-cms/pull/1771
対応の施設管理側の対応が漏れていたため、対応しました。
なし
なし
なし
なし
=> bugfix: 施設管理, 利用終了時間の 00:00 を 24:00 に自動変換がされないパターンに対応 OW-1940

app/Plugins/Manage/SiteManage/SiteManage.php
移行データ出力NC3汎用データベース移行件数の取得SQLを修正しました
NC3の移行データ汎用データベース出力件数の取得SQLを修正しました
7月25日
無し
=> [管理画面]サイト管理NC3移行データ出力を修正しました

resources/views/plugins/user/forms/default/forms_input_date.blade.php, resources/views/plugins/user/forms/default/forms_input_mail.blade.php, resources/views/plugins/user/forms/default/forms_input_text.blade.php, resources/views/plugins/user/forms/default/forms_input_textarea.blade.php, resources/views/plugins/user/forms/default/forms_input_time.blade.php, resources/views/plugins/user/forms/default/forms_input_time_from_to.blade.php
件名通りです。
なし
* https://github.com/opensource-workshop/connect-cms/issues/1200
なし
なし
=> [フォーム] 閲覧パスワードON＋php8でパスワード入力後に500エラーになるバグ修正

app/Traits/Migration/MigrationTrait.php
=> [移行ツール] NC2移行エクスポートの汎用DB, カスタマイズ順の移行に対応

app/Traits/Migration/MigrationNc3ExportTrait.php
=> [NC3移行]カレンダータイトルの不要文字削除処理を追加

app/Models/Common/Frame.php
件名通りです。
なし
* https://github.com/opensource-workshop/connect-cms/pull/1780
なし
なし
=> [フレーム] 利用者が見れるフレーム判定にログイン後非表示を対応

public/robots.txt
=> [robots.txt] 不要な検索botのクロールを除外

app/Traits/Migration/MigrationNc3ExportTrait.php
NC3移行でのカウンター名出力箇所を修正しました
8/3
無し
=> 【NC3移行】NC3移行でのカウンター名出力箇所を修正しました

app/Traits/Migration/MigrationNc3ExportTrait.php
=> [NC3移行]多言語サイトでの出力不具合を修正しました

app/Plugins/User/Databases/DatabasesPlugin.php
処理速度の向上、およびメモリ使用量の軽減を目的に処理を改善しました。
※500件程度のデータ量、30件程度の絞り込み項目でローカル環境にて計測
改修前：2.2秒、53.8MB
改修後：0.1秒、1.2MB
#1627 
無し
=> [データベース]絞り込み項目の登録済み件数を表示する機能（beta）の処理を改善しました

app/Traits/Migration/MigrationNc3ExportTrait.php
NC3フォトアルバム（スライドショー）対象取得クエリの修正
無し
=> [NC3移行]NC3フォトアルバム（スライドショー）対象取得クエリの修正

app/Traits/Migration/MigrationNc3ExportTrait.php
=> [NC3移行]長すぎるファイル名の場合には文字数を削除する

resources/views/plugins/user/openingcalendars/designbase/openingcalendars.blade.php
パターンデータが登録されていない場合の修正
パターンデータなしで開館カレンダーでdesignbaseを選択した際にエラーの対処
9/1
無し
=> [開館カレンダー]パターンデータが登録されていない場合にエラーの修正

app/Http/Controllers/Core/UploadController.php
画像縮小表示時の回転不具合の修正
画像縮小表示時に画像が回転する不具合を修正しました
9/1
無し
=> [コア]画像縮小表示時の回転不具合の修正

.env.example, app/Http/Middleware/TrustProxies.php, config/trustedproxy.php
件名通り
なし
なし
* https://readouble.com/laravel/8.x/ja/requests.html#configuring-trusted-proxies
なし
=> [コア] TrustProxiesを.envで設定できるように対応

app/Providers/AppServiceProvider.php
件名通りです。
なし
なし
* https://qiita.com/madayo/items/d9ea39320d78e1590d3e#b-%E6%A1%88-laravel-%E3%83%97%E3%83%AD%E3%82%B0%E3%83%A9%E3%83%A0%E5%81%B4%E3%81%A7%E5%AF%BE%E5%BF%9C
なし
=> [コア] .envのAPP_URLを見てhttps 始まりかをもとに強制的に scheme を設定する

app/Plugins/Manage/PageManage/PageManage.php
件名通りです。
なし
* https://github.com/opensource-workshop/connect-cms/issues/1821
なし
なし
=> [ページ登録] php8.1でパーマリンクを空で登録すると500エラーになる不具合対応

tests/Browser/Manage/ThemeManageTest.php
件名通りです。
なし
* https://github.com/opensource-workshop/connect-cms/pull/1827
なし
なし
=> [自動テスト] テーマ管理テスト, クリック後タイトル確認で表示が遅いため確認がとれない疑いのため、クリック後少しまつ処理を追加

.github/workflows/laravel_dusk_connect-cms-test-matrix.yml, .github/workflows/laravel_dusk_connect-cms-test.yml, composer-dev.json, composer-dev.lock, composer.lock
=> [自動テスト] 2.x, composerでlaravel/duskを7.10以上に見直し & 合わせてcomposer update実施

.github/workflows/laravel_dusk_connect-cms-test-matrix.yml, .github/workflows/laravel_dusk_connect-cms-test.yml
件名通りです。
なし
* https://github.com/opensource-workshop/connect-cms/pull/1835
なし
なし
=> [自動テスト] 2.x, github actionsのUpgrade Chrome Driverコマンド見直し

app/Enums/StatusType.php
=> [enum] StatusTypeを継承でるように修正

app/Plugins/User/Databases/DatabasesPlugin.php, tests/Browser/User/DatabasesPluginTest.php
=> [データベース]並び替え設定がない場合にシステムエラーとなる事象を修正しました

app/User.php, database/factories/UserFactory.php
テストコードで[factory](https://readouble.com/laravel/8.x/ja/database-testing.html)を利用するため、現在のテーブル定義に合わせて最新化しました。
無し
=> [コア]UserFactoryを最新化しました

database/seeders/PTASeeder.php
PTAサンプルデータを登録するPTASeederを実行すると、DBエラーが出ていたため修正しました。
なし
なし
なし
なし
=> [PTASeeder] 実行時エラーの対応

app/Plugins/Manage/SiteManage/SiteManage.php, app/Plugins/User/Databases/DatabasesPlugin.php, app/User.php, app/Utilities/File/FileUtils.php, config/version.php, database/factories/UserFactory.php, database/seeders/PTASeeder.php, resources/views/plugins/manage/site/site_manage_tab.blade.php, resources/views/plugins/manage/site/total.blade.php, resources/views/plugins/user/databases/default/databases_include_ctrl_head.blade.php, tests/Browser/User/DatabasesPluginTest.php
Reverts opensource-workshop/connect-cms#1854
=> Revert "Revert "Merge v1.12.2 into 2.x""

app/Models/Common/BucketsMail.php
件名通り.
通常の処理に影響がないことを動作確認済み。
なし
なし
なし
なし
=> [メール] グループから通知するメールアドレス取得する処理を他でも使えるようfunction化

resources/views/plugins/common/like.blade.php
フレームID取得処理の統一することで、他プラグインから呼び出し時に、$frameを引数指定することで、いいねを使用できるようになります。
なし
なし
なし
なし
=> [いいね] フレームID取得処理の統一

resources/views/plugins/manage/theme/theme_template_edit.blade.php
* https://github.com/opensource-workshop/connect-cms/pull/1799
へのプレースホルダーを修正したプルリクエストです。
動作未確認のため、動作確認後、マージします。
なし
概要に記載
なし
なし
=> Update theme_template_edit.blade.php change placeholder

app/Enums/BlogFrameConfig.php, app/Enums/BlogNarrowingDownTypeForCreatedId.php, app/Models/User/Blogs/Blogs.php, app/Models/User/Blogs/BlogsPosts.php, app/Models/User/Blogs/BlogsPostsTags.php, app/Plugins/User/Blogs/BlogsPlugin.php, config/app.php, resources/views/plugins/user/blogs/default/blogs_setting_frame.blade.php, resources/views/plugins/user/blogs/default/include_narrowing_down.blade.php
投稿者絞込機能を追加しました。
投稿者毎に絞り込めます。
なし
なし
なし
なし
=> [ブログ] 投稿者絞込機能追加 OW-2072

app/Http/Controllers/Core/UploadController.php
現状ではカテゴリcssをキャッシュするため、カテゴリ設定画面からカテゴリ色を変更しても、ブラウザキャッシュが働くため、即時反映されませんでした。
そのため、カテゴリcssをキャッシュしないよう見直しました。
適時
なし
なし
無し
=> [カテゴリ設定] カテゴリcssをキャッシュしないよう見直し

app/Plugins/User/Counters/CountersPlugin.php, app/Utilities/Request/RequestUtils.php
botチェックを他処理でも使えるように App\Utilities\Request\RequestUtils に切り出しました。
なし
なし
なし
なし
=> カウンター, botチェックを他でも使えるようにUtilitiesに切り出し

sync_option_private_2_dev.sh.example
=> [開発ツール] sync_option_private_2_dev.sh.exampleのモデルとビューにディレクトリがなければ作成するコマンド追加

resources/views/plugins/manage/user/description_frame_mails.blade.php
[ユーザ管理＞自動ユーザ登録設定＞メールの埋め込みタグ説明] 不要な { 表示削除しました。
なし
なし
なし
なし
=> [自動ユーザ登録設定] メールの埋め込みタグ説明で不要な { 表示削除

app/Models/Common/Page.php, database/factories/Common/PageFactory.php
ページのテストデータ作成に利用できるFactoryを追加しました。
【開発環境での利用例】
・composer-dev.jsonを利用
・コマンドラインで `php artisan tinker`を実行
・`\App\Models\Common\Page::factory(10)->create();` でページのテストデータが10件できる。
なし
なし
* [laravel]Factoryの基本的な使い方とちょっと便利な使い方 #Laravel - Qiita
https://qiita.com/yastinbieber/items/61b7a598c5d30311c5f7
なし
=> [テスト] PageFactory追加

app/Models/Common/Page.php, app/Plugins/Manage/PageManage/PageManage.php, resources/views/plugins/manage/page/page.blade.php
少しだけパフォーマンス改善
なし
* https://github.com/opensource-workshop/connect-cms/pull/1920
* [Laravel] Eloquent リレーションと Eager Loading #Laravel - Qiita
https://qiita.com/shosho/items/abf6423283f761703d01
無し
=> [ページ管理] パフォーマンス改善

app/Plugins/Manage/CodeManage/CodeManage.php, app/Plugins/Manage/UserManage/UserManage.php, app/Plugins/User/Counters/CountersPlugin.php, app/Plugins/User/Databases/DatabasesPlugin.php, app/Plugins/User/Learningtasks/LearningtasksPlugin.php, app/Plugins/User/Opacs/OpacsPlugin.php, app/Utilities/Csv/CsvUtils.php
=> [CSVダウンロード] レスポンス版のCSVデータ整形処理をメソッド化

resources/views/plugins/user/forms/default/forms.blade.php
* https://github.com/opensource-workshop/connect-cms/pull/1923
上記の修正ミス修正
なし
概要に記載
なし
なし
=> [フォーム] まとめ行を入れ子にするとエラーになる不具合対応2

routes/web.php
非同期で更新処理を行うため、ルートを追加しました。
有り / 無し
=> [コア]一般プラグインのJSONレスポンスアクションでPOSTも許可します

app/Plugins/Manage/UserManage/UsersTool.php
件名通りです。
削除したカラムの値は、ダウンロードに含まないよう対応しました。
なし
なし
なし
なし
=> [ユーザ管理] CSVダウンロードで削除したカラムの値まで含まれる不具合対応

app/Models/Migration/Nc2/Nc2Authority.php
=> [移行ツール] Nc2Authorityモデル追加

app/Http/Controllers/Core/FrameCore.php, app/Models/Common/Frame.php, database/migrations/2024_01_07_114703_add_classname_body_from_frames.php, resources/views/core/cms_frame_base.blade.php, resources/views/core/cms_frame_edit.blade.php, resources/views/core/cms_frame_header.blade.php
フレーム設定にbody classの設定を追加しました。
なし
なし
なし
あり
=> [フレーム設定] body class名設定追加

database/migrations/2024_01_10_100428_add_users_id_and_users_columns_id_index_from_users_input_cols.php
=> [DB] users_input_colsテーブルにインデックス追加

app/Plugins/User/Blogs/BlogsPlugin.php
* https://github.com/opensource-workshop/connect-cms/pull/1883
上記の不具合修正です。
なし
概要に記載
なし
なし
=> [ブログ] 投稿者絞込用リストに全投稿者がリスト表示されない場合がある不具合対応

app/Plugins/User/Opacs/OpacsPlugin.php, app/Utilities/Curl/CurlUtils.php
* 国会図書館APIのURLが変わったことにより、書籍データ取得で500エラーが起こっていましたので、修正しました。
* 国会図書館APIのURLを新しいものに変更
* CurlUtilsを使う方法に変更＋URLリダイレクトに対応
* 関連修正
* OPAC, 書籍データ取得エラー時に、入力が保持されない不具合対応
* [add: CurlUtils, リダイレクト対応](https://github.com/opensource-workshop/connect-cms/commit/af492ddaa25acff91e0d1154644bee7e8f3c002e)
旧国会図書館API（リダイレクトされます）
'url' => 'https://iss.ndl.go.jp/api/opensearch?isbn=4873116686',
```php
[2024-01-12 11:58:05] local.ERROR: ErrorException: Trying to get property 'channel' of non-object in C:\projects\connect-cms\connect-cms\htdocs\connect-cms\app\Plugins\User\Opacs\OpacsPlugin.php:225
Stack trace:
#0 C:\projects\connect-cms\connect-cms\htdocs\connect-cms\app\Plugins\User\Opacs\OpacsPlugin.php(225): Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(8, 'Trying to get p...', …
```
=> [OPAC] 書籍データ取得で国会図書館APIのURLが変わったことによる500エラー対応

app/Plugins/Manage/UserManage/UserManage.php, resources/views/plugins/manage/user/auto_regist.blade.php
=> [ユーザ管理] 承認完了メールが飛ばない不具合対応

.gitignore
件名通り
なし
* https://github.com/opensource-workshop/connect-cms/pull/1929
なし
なし
=> [オプション] オプションプラグインの除外設定追加

app/Plugins/Manage/PageManage/PageManage.php, resources/views/plugins/manage/page/page.blade.php, resources/views/plugins/manage/user/list.blade.php
* ページ管理でページ移動をする際、1ページづつ上下に移動できましたが、新しいページを追加した場合、一番下に追加されるため、一番上に移動するのに、↑ボタンを何回も押す必要がありました。
そのため、一番上へ・一番下へボタンを追加しました。
* 関連対応
* [add: ページ管理, 横スクロールのコメント追記](https://github.com/opensource-workshop/connect-cms/pull/1947/commits/75a52dc36330dbf82384b9891a8d66c807dbb616)
* [add: ユーザ管理, 横スクロールのコメント見直し](https://github.com/opensource-workshop/connect-cms/pull/1947/commits/e5ce458b28f9c61c0c57f93e27209f88d9ee9da5)
【横スクロールのコメント追記】
なし
なし
なし
なし
=> [ページ管理] 一番上へ・一番下へボタン追加

resources/views/plugins/user/blogs/default/blogs_input.blade.php
開発用のアップデートです。
cssで制御できるように、記事登録の重要記事・カテゴリにcssクラス追加しました。
なし
なし
なし
なし
=> [ブログ] 記事登録の重要記事・カテゴリにcssクラス追加

resources/views/plugins/common/wysiwyg.blade.php
ディレクトリインストール時のcontent_css:のパスを修正しました
不具合修正
不具合対応なので急ぎたいです
https://github.com/opensource-workshop/connect-cms/issues/1941
無し
=> 【WYSIWIG】ディレクトリインストール時のcontent_css:のパス修正

app/Enums/PluginName.php, app/Models/User/Rsses/RssUrls.php, app/Models/User/Rsses/Rsses.php, app/Plugins/User/Rsses/RssesPlugin.php, app/Plugins/User/Rsses/plugin.ini, app/Traits/Migration/MigrationTrait.php, app/Traits/Migration/sample/migration_config/migration_config.sample.ini, database/migrations/2023_12_18_140036_create_rsses_table.php, database/migrations/2023_12_18_140041_create_rss_urls_table.php, resources/views/plugins/user/rsses/default/rsses.blade.php, resources/views/plugins/user/rsses/default/rsses_edit.blade.php, resources/views/plugins/user/rsses/default/rsses_edit_row.blade.php, resources/views/plugins/user/rsses/default/rsses_edit_row_add.blade.php, resources/views/plugins/user/rsses/default/rsses_edit_rss.blade.php, resources/views/plugins/user/rsses/default/rsses_error_messages.blade.php, resources/views/plugins/user/rsses/default/rsses_list_buckets.blade.php, resources/views/plugins/user/rsses/default/template.ini, resources/views/plugins/user/rsses/rsses_frame_edit_tab.blade.php, tests/Browser/User/RssesPluginTest.php
=> 【RSS】プラグイン作成

resources/views/plugins/user/rsses/side/rsses.blade.php, resources/views/plugins/user/rsses/side/template.ini
左右カラムに配置すると表示が崩れるため、サイド用を追加
３月１日
無し
=> [RSS]左右用のテンプレートを追加しました

app/Plugins/User/Calendars/CalendarsPlugin.php
* https://github.com/opensource-workshop/connect-cms/issues/1963
上記の対応です。
なし
概要に記載
なし
無し
=> [カレンダー] 同一日内の予定を時間順に表示

resources/views/layouts/app.blade.php
=> [マイページ] コンテンツ画面へ→トップページへ表示に見直し

composer-dev.lock, composer.lock
2系ブランチに対する開発者向けアップデートです。
なし
* https://github.com/opensource-workshop/connect-cms/pull/1978
なし
無し
=> composer require mews/captcha for php8.0

tests/Browser/Manage/PageManageTest.php
=> [ページマネージャー・テスト] RSSプラグインの修正漏れ対応です。

.github/workflows/laravel_dusk_connect-cms-test-matrix.yml, .github/workflows/laravel_dusk_connect-cms-test.yml
件名通りです。
なし
* https://github.com/opensource-workshop/connect-cms/pull/1980
なし
なし
=> [github action] RSSテスト追加

composer-dev.json, composer-dev.lock, composer.json, composer.lock
* https://github.com/opensource-workshop/connect-cms/issues/1984
上記不具合の対応です。
なし
* https://github.com/opensource-workshop/connect-cms/pull/1971
* Composer · opensource-workshop/connect-cms Wiki
https://github.com/opensource-workshop/connect-cms/wiki/Composer#%E5%8F%82%E8%80%83composer%E3%81%AE%E3%83%90%E3%83%BC%E3%82%B8%E3%83%A7%E3%83%8B%E3%83%B3%E3%82%B0
無し
=> [composer] captchaライブラリのphp8.0対応のバージョン指定

app/Http/Controllers/Auth/LoginController.php, app/Traits/Migration/MigrationTrait.php
* https://github.com/opensource-workshop/connect-cms/pull/1792
上記対応時に含まれた不具合です。
その不具合を修正しました。
なし
概要に記載
なし
なし
=> [外部認証] 外部認証後のCCユーザ自動作成時に500エラー対応

app/Utilities/Request/RequestUtils.php
=> [カウンター]ボット判定を追加

.github/workflows/laravel_dusk_connect-cms-test-matrix.yml, .github/workflows/phpcs.yml, composer-dev.lock, composer.lock
今まで通りphp7.3で動作するようにcomposer updateするよう見直し
なし
* https://github.com/opensource-workshop/connect-cms/pull/1994
なし
無し
=> Change composer update php73

docker-compose.yml, docker/app/setup.sh
件名通りです。
* [change: docker, version 指定不要のため削除](https://github.com/opensource-workshop/connect-cms/pull/2001/commits/6f04f5289ae2765042281151a503875c5f942c59)
* docker-compose.yamlのversionがobsoleteという警告がでるようになったので、不要になっていたのはいつからか調べた 
https://blog.n-z.jp/blog/2024-04-02-docker-compose-yaml-version.html
* [change: docker, setup.sh, DBマイグレーションとシーダーをyesで強制実行](https://github.com/opensource-workshop/connect-cms/pull/2001/commits/4b93e05be13379975f75228a9102bbf57c11f3dd)
なし
なし
なし
なし
=> [Docker] 設定値見直し

.github/workflows/laravel_dusk_connect-cms-test-matrix.yml
github actionのphp7.3対応です。
なし
なし
なし
なし
=> [github action] Update laravel_dusk_connect-cms-test-matrix.yml php7.3対応

composer-dev.lock, composer.lock
composer update対応です。
※ php73環境で実施
```cmd
composer update
set COMPOSER=composer-dev.json
composer update
```
なし
* https://github.com/opensource-workshop/connect-cms/pull/1994
なし
なし
=> composer update php73

app/Plugins/User/Reservations/ReservationsPlugin.php
* https://github.com/opensource-workshop/connect-cms-ideas/issues/173
上記の対応です。
なし
概要に記載
なし
なし
=> [施設予約] 施設予約の各施設へ（今月）リンク機能を追加

tests/bin/connect-cms-test.bat
Windowsでテストする際のバッチでは、オプションのConnect-Studyも実行しています。
しかし、Connect-Studyのマイグレーションファイルが実行されていなかったので、コケていたため、Connect-Studyのマイグレーションを設定しました。
無し
=> [テスト＆マニュアル]Windowsでテストする際のバッチにConnect-Studyのマイグレーションを設定しました。

resources/views/plugins/user/forms/default/forms_edit_form.blade.php, tests/Browser/ConnectStudy/SpeechStudyTest.php, tests/Browser/ConnectStudy/study_page.csv, tests/Browser/User/FormsPluginTest.php
Connect-Speechに音声入力のテンプレートを追加したので、その説明を追加。
フォームの作成時に説明を追加しました。
無し
=> [マニュアル＆テスト]Connect-Speechとフォームのマニュアル＆テスト・プログラムを追加しました。

tests/Browser/ConnectStudy/ConnectStudyCommon.php
ConnectSpeech のテストページの階層を修正
無し
=> [テスト＆マニュアル]Connect-Studyのテストの微修正

app/Utilities/Csv/CsvUtils.php
開発者用にCSV出力時にダブルクォーテーションを全角に変換するメソッドを追加しました。
なし
なし
なし
なし
=> [CsvUtils] ダブルクォーテーション対策のメソッドを追加

app/Enums/UserStatus.php
* https://github.com/opensource-workshop/connect-cms/issues/737
上記対応です。
なし
概要に記載
なし
なし
=> [ユーザ管理＞ユーザ変更] ラジオでON・OFF時、左側はOFFで統一する

app/Http/Controllers/Core/UploadController.php, config/connect.php
* https://github.com/opensource-workshop/connect-cms/issues/2061
上記不具合修正です。
なし
なし
* カウントアップ処理
* https://github.com/opensource-workshop/connect-cms/commit/70b9b35c0f382e17f135ce9fa4eb52e7ac6231e5
なし
=> [アップロードファイル] ダウンロード数が全ての拡張子でカウントされるように修正

dev_2_option_private.ps1.example, option_private_2_dev.ps1.example, sync_dev_2_option_private.sh.example, sync_option_private_2_dev.sh.example
開発者向け修正です。
件名通りです。
なし
なし
なし
無し
=> [開発ツール] オプションリポジトリ ←→ 開発環境のコピーサンプルShellにComposer Optionを追加

app/Plugins/User/Reservations/ReservationsPlugin.php
繰り返し予定で毎日＋指定の回数後＋回数空で500エラーが出ていましたので対応しました。
入力チェックに到達する前に、カレンダー繰り返し予定 `RRule` の設定箇所で、指定の回数が空でエラーになっていました。指定の回数が空の場合、仮値を設定して、入力チェックまで処理が通るように修正しました。
```log
[2025-01-08 15:24:39] production.ERROR: COUNT must be a positive integer (> 0) {"userId":1,"exception":"[object] (InvalidArgumentException(code: 0): COUNT must be a positive integer (> 0) at /var/www/html/connect-cms/vendor/rlanvin/php-rrule/src/RRule.php:301)
[stacktrace]
#0 /var/www/html/connect-cms/app/Plugins/User/Reservations/ReservationsPlugin.php(923): RRule\\RRule->__construct(Array)
#1 /var/www/html/connect-cms/app/Plugins/User/UserPluginBase.php(299): App\\Plugins\\User\\Reservations\\ReservationsPlugin->saveBooking(Object(Illuminate\\Http\\Request), '12', '27', NULL)
#2 …
```
=> [施設管理] 繰り返し予定で毎日＋指定の回数後＋回数空で500エラー対応

.github/workflows/laravel_dusk_connect-cms-test-matrix-daily.yml, app/Plugins/Manage/GroupManage/GroupManage.php, app/Plugins/User/Blogs/BlogsPlugin.php, app/Plugins/User/Faqs/FaqsPlugin.php, app/Plugins/User/Reservations/ReservationsPlugin.php, app/Traits/ConnectRoleTrait.php, app/Utilities/String/StringUtils.php, composer-dev.lock, composer.lock, config/version.php, dev_2_option_private.ps1.example, option_private_2_dev.ps1.example, resources/views/plugins/user/blogs/default/blogs.blade.php, sync_dev_2_option_private.sh.example, sync_option_private_2_dev.sh.example
=> Merge v1.23.0 into 2

app/Plugins/User/Reservations/ReservationsPlugin.php
繰り返し予定で毎月＋日付指定後＋日付指定空で500エラーが出ていましたので対応しました。
入力チェックに到達する前に、カレンダー繰り返し予定 RRule の設定箇所で、日付指定が空でエラーになっていました。日付指定が空の場合、仮値を設定して、入力チェックまで処理が通るように修正しました。
500エラーならず、入力エラーが表示される事を確認しました。
```log
[2025-01-14 14:11:23] production.ERROR: Invalid BYMONTHDAY value: 0 (valid values are 1 to 31 or -31 to -1) {"userId":1,"exception":"[object] (InvalidArgumentException(code: 0): Invalid BYMONTHDAY value: 0 (valid values are 1 to 31 or -31 to -1) at /var/www/html/connect-cms/vendor/rlanvin/php-rrule/src/RRule.php:378)
[stacktrace]
#0 /var/www/html/connect-cms/app/Plugins/User/Reservations/ReservationsPlugin.php(928): RRule\\RRule->__construct(Array)
#1 /var/www/html/connect-cms/app/Plugins/User/UserPluginBase.php(299): App\\Plugins\\User\\Reservations\\ReservationsPlugin->saveBooking(Object(Illuminate\\Http\\Re …
```
=> [施設管理] 繰り返し予定で毎月＋日付指定後＋日付指定空で500エラー対応

composer-dev.json, composer-dev.lock, composer.json, composer.lock
composer.jsonのphpバージョン指定方法を見直しました。
```json
"php": ">=7.4.0",
↓
↓ (変更)
↓
"php": "^7.4.0",
```
なし
* https://github.com/opensource-workshop/connect-cms/pull/2104
* https://github.com/opensource-workshop/connect-cms/wiki/Composer#参考composerのバージョニング
なし
=> [composer] php7.4に変更

composer-dev.json, composer-dev.lock, composer.json, composer.lock
* https://github.com/opensource-workshop/connect-cms/pull/2106
github actionsのテストで失敗してしまうため、上記から修正します。
[修正後] github actionsのテストで、各phpバージョンが成功する事を確認しました。
https://github.com/opensource-workshop/connect-cms/actions/runs/12784815334
なし
概要に記載
* [修正前] github actionsのテストで失敗
* https://github.com/opensource-workshop/connect-cms/actions/runs/12784456303
無し
=> [composer] php7.4に変更2

resources/views/plugins/manage/code/code_import.blade.php, resources/views/plugins/user/databases/default/databases_import.blade.php
=> [データベース][コード管理] CSVインポート時の入力エラー表示を共通部品を使うように見直し

app/Plugins/Manage/LogManage/LogManage.php, resources/views/plugins/manage/log/log.blade.php
=> [ログ管理] 絞込条件に日時・URIを追加

app/Plugins/User/Opacs/OpacsPlugin.php, app/Plugins/User/Rsses/RssesPlugin.php, app/Plugins/User/Slideshows/SlideshowsPlugin.php
* https://github.com/opensource-workshop/connect-cms/issues/882
* index()で表示される opacs.blade.php、opacs_my.blade.php でold()を使用していないため、index()から $request->flash(); を削除しました。
上記の不具合対応です。
* [bugfix: RSS, RSSプラグインのフレーム以下にあるフレームでold()が取得できないバグ修正](https://github.com/opensource-workshop/connect-cms/pull/2117/commits/282bbeedb0056a31b91f84943f3c75c2f0e81664)
* index()で表示される rsses.blade.php でold()を使用していないため、index()から $request->flash(); を削除しました。
* [bugfix: スライドショー, スライドショープラグインのフレーム以下にあるフレームでold()が取得できないバグ修正](https://github.com/opensource-workshop/connect-cms/pull/2117/commits/285677122c070082abcc2de32d39bdd0925f232c)
* index()で表示される slideshows.blade.phpでold()を使用していないため、index()から $request->flash(); を削除しました。
なし
概要に記載
なし
なし
=> [RSS][スライドショー][OPAC] プラグインのフレーム以下にあるフレームでold()が取得できないバグ修正

app/Plugins/Manage/PageManage/PageManage.php, resources/views/plugins/manage/page/page_form.blade.php, resources/views/plugins/manage/page/page_import.blade.php, tests/Manual/insertion/manage/page/upload/foot.txt
* ページ管理, CSVインポートのフォーマットとサンプルをダウンロード出来るように対応
* 関連対応
* ページ管理, ページ登録時に固定リンクの先頭に / がない場合、追加されることを表示
なし
なし
なし
なし
=> [ページ管理] CSVインポートのフォーマットとサンプルをダウンロード出来るように対応

resources/views/plugins/common/datetimepicker.blade.php
yyyyMMフォーマットで入力可能にするため、 date オプションを追加しました。
```blade
{{-- DateTimePicker 呼び出し --}}
@include('plugins.common.datetimepicker', ['element_id' => "date{$frame_id}", 'format' => 'yyyyMM', 'clock_icon' => false, 'view_mode' => 'months', 'date' => false])
```
なし
* https://github.com/opensource-workshop/connect-cms/pull/2152
* https://getdatepicker.com/6/options/
なし
=> [日付入力] datetimepicker.bladeに date オプション追加

README.md
スマートフォンで参照した場合、一番初めに見る（ファーストビュー）の README.md に インストール・アップデート方法があった方が良いと思い、追加しました。
なし
なし
なし
なし
=> [ドキュメント] README.md にインストール、アップデート方法のリンク追加

app/Traits/Migration/MigrationTrait.php
* 移行エクスポート＞NC2に移行時間計測追加
* 移行エクスポート＞NC2, ページ移行のメッセージ追加 start - end
* 関連対応
* importGroups(), アップロードなしの場合にEndメッセージ表示対応
* importPermalinks(), データなしの場合にEndメッセージ表示対応
※ 移行データ少ないと0秒表示になります。
```shell
root@580f4f913c01:/var/www/html/connect-cms# php -d memory_limit=512M artisan command:ExportNc2 all redo
page_id,block_id,category,message
,,Start exportNc2.,
,,Start nc2ExportBasic.,
,,End nc2ExportBasic.,0秒
,,Start nc2ExportUploads.,
,,End nc2ExportUploads.,0秒
,,Start nc2ExportUsers.,
,,End nc2ExportUsers.,0秒
,,Start nc2ExportRooms.,
,,「すべての会員をデフォルトで参加させる」ルームはグループ作成しない,ルーム名=ログインユーザ共通ルーム
,,End nc2ExportRooms.,0秒
,,Start nc2ExportJournal.,
,,End nc2ExportJournal.,0秒
,,Start nc2ExportBbs.,
,,End nc2ExportBbs.,0秒
,,Start nc2ExportMultidatabase.,
,,End nc2ExportMultidatabase.,0秒
,,Start …
```
=> [移行ツール] 移行エクスポート＞NC2に移行時間計測追加

app/Traits/Migration/MigrationLogTrait.php, app/Traits/Migration/MigrationNc3ExportTrait.php, app/Traits/Migration/MigrationTrait.php
* 移行エクスポート＞NC3に移行時間計測追加
* 移行エクスポート＞NC3, ページ移行のメッセージ追加 start - end
* 関連対応
* timerStart(), timerEnd()を app/Traits/Migration/MigrationLogTrait.php に移動
※ 移行データが少ないと0秒表示になります。
```shell
root@580f4f913c01:/var/www/html/connect-cms# php -d memory_limit=512M artisan command:ExportNc3 all redo
frame_id,,category,message
,,ExportNc3 Start.,
,,Nc3ExportBasic Start.,
,,Nc3ExportBasic End.,0秒
,,Nc3ExportUploads Start.,
,,Nc3ExportUploads End.,0秒
,,Nc3ExportUsers Start.,
,,Nc3ExportUsers End.,0秒
,,Nc3ExportRooms Start.,
,,「すべての会員をデフォルトで参加させる」ルームはグループ作成しない,ルーム名=コミュニティ
,,「すべての会員をデフォルトで参加させる」ルームはグループ作成しない,ルーム名=ログインユーザ共通ルーム
,,Nc3ExportRooms End.,0秒
,,Nc3ExportBlog Start.,
,,Nc3ExportBlog End.,0秒
,,Nc3ExportBbs Start.,
,,Nc3ExportBbs End.,0秒
,,Nc3ExportMultidatabase Start.,
,,Nc3ExportMultidatabase End.,0秒 …
```
=> [移行ツール] 移行エクスポート＞NC3, 移行時間計測追加

app/Traits/Migration/MigrationTrait.php
移行コマンドの NC2 エクスポート時の時間計測メッセージを見やすく修正しました。
※ 移行データ少ないと0秒表示になります。
```shell
root@580f4f913c01:/var/www/html/connect-cms# php -d memory_limit=512M artisan command:ExportNc2 all redo
page_id,block_id,category,message
,,ExportNc2 Start.,
,,Nc2ExportBasic Start.,
,,Nc2ExportBasic End.,0秒
,,Nc2ExportUploads Start.,
,,Nc2ExportUploads End.,0秒
,,Nc2ExportUsers Start.,
,,Nc2ExportUsers End.,0秒
,,Nc2ExportRooms Start.,
,,「すべての会員をデフォルトで参加させる」ルームはグループ作成しない,ルーム名=ログインユーザ共通ルーム
,,Nc2ExportRooms End.,0秒
,,Nc2ExportJournal Start.,
,,Nc2ExportJournal End.,0秒
,,Nc2ExportBbs Start.,
,,Nc2ExportBbs End.,0秒
,,Nc2ExportMultidatabase Start.,
,,Nc2ExportMultidatabase End.,0秒
,,Nc2ExportRegistration Start.,
,,Nc2ExportRegistration End.,0秒
,,Nc2ExportLinklist Start.,
,,Nc2ExportLinklist End.,0秒
,,Nc2ExportWhatsnew …
```
=> [移行ツール] 移行エクスポート＞NC2, 移行時間計測の出力文字修正

public/robots.txt
NC3から移行後に、bot系からくるNC3系のアクセスをrobots.txtで除外する設定をさらに追加しました。
なし
* https://github.com/opensource-workshop/connect-cms/pull/2176
* https://github.com/opensource-workshop/connect-cms/pull/1788
なし
なし
=> [robots.txt] 他システムから移行後に不要な検索botのクロールを除外2

database/migrations/2023_09_04_153112_add_full_text_search_to_databases.php
* https://github.com/opensource-workshop/connect-cms/pull/2191
* 上記2ブランチのLaravel9を10へアップデート時に気付きましたので、修正しました。動作は同じです。
* Laravel8(Connect 1.x系 masterブランチ)でも動作する事を目検しました。
* https://github.com/opensource-workshop/connect-cms/actions/runs/14871820848
なし
概要に記載
なし
無し
=> [マイグレーション] DB::raw("select version() as version")の修正

.env.example, tests/DuskTestCase.php
件名通りです。
なし
* https://github.com/opensource-workshop/connect-cms/pull/2191
なし
なし
=> [ブラウザテスト] .envからDUSK_DRIVER_URLを取得できるよう修正

config/version.php
バージョンのファイルを忘れていたので、バージョンアップだけです。
https://github.com/opensource-workshop/connect-cms/pull/2214
無し
=> #2214 のバージョンアップです。

.github/workflows/create-release-v1-v2.yml, .github/workflows/test-v2.yml
開発効率化を目的として、GitHub Actionsによるリリース作成の自動化とテスト実行の安定性向上を実現しました。
**背景・目的**:
- 手動でのリリース作業の負担軽減
- v1/v2リリースの一貫性確保
- テスト実行時の偶発的失敗への対応
**追加内容**:
1. **create-release-v1-v2.yml**: PRラベルに基づくv1/v2自動リリース
2. **test-v2.yml**: リトライ機能付きv2テストワークフロー
なし
なし
- GitHub Actions workflow_dispatch（手動実行）
- semverライブラリによる自動バージョンアップ
- Laravel Duskテストのリトライ機能
なし
=> [GitHub Actions] リリース作成自動化とテストリトライ機能を追加しました
